---
sidebar: sidebar 
permalink: hu-aix-70.html 
keywords: host utilities, aix, powervm, vios, 3.1, 7.0, netapp, ontap 
summary: Die AIX Host Utilities unterstützen Sie beim Management von ONTAP-Speicher mit Anbindung an einen AIX-Host. 
---
= Installieren Sie AIX Host Utilities 7.0
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die AIX Host Utilities unterstützen Sie beim Management von ONTAP-Speicher mit Anbindung an einen AIX-Host.

AIX Host Utilities unterstützen die folgenden Protokolle:

* FC
* FCoE
* ISCSI


AIX Host Utilities unterstützen die folgenden Umgebungen:

* AIX Microsoft Multipath I/O (MPIO) (natives Betriebssystem)
* PowerVM
+
Weitere Informationen zu PowerVM finden Sie im IBM PowerVM Live Partition Mobility Red Book.



.Bevor Sie beginnen
* Stellen Sie für einen zuverlässigen Betrieb sicher, dass Ihre gesamte iSCSI-, FC- oder FCoE-Konfiguration unterstützt wird.
+
Sie können die verwenden https://imt.netapp.com/matrix/#welcome["Interoperabilitäts-Matrix-Tool"^], um Ihre Konfiguration zu überprüfen.

* Das dynamische Tracking muss für alle FC- und FCoE-Initiatoren aktiviert sein.



NOTE: Das Softwarepaket NetApp AIX Host Utilities ist auf dem  in einem komprimierten `tar.gz file` verfügbarlink:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.0["NetApp Support Website"^]. Sie müssen das AIX Host Utilities Kit installieren, während Sie AIX MPIO mit ONTAP-Speicher verwenden.

.Schritte
. Melden Sie sich bei Ihrem Host an.
+
** Melden Sie sich auf einem AIX-Host als *root* an.
** Melden Sie sich auf einem PowerVM-Host als *padmin* an, und geben Sie dann den `oem_setup_env` Befehl ein, um ein Root-Benutzer zu werden.


. Rufen Sie die https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.0["NetApp Support Website"^] auf, und laden Sie die komprimierte Datei mit den Host Utilities in ein Verzeichnis auf Ihrem Host herunter.
. Gehen Sie zu dem Verzeichnis, in dem der Download enthalten ist.
. Dekomprimieren Sie die Datei und extrahieren Sie das SAN Toolkit-Softwarepaket:
+
`# tar -xvf ntap_aix_host_utilities_7.0.tar.gz`

+
Beim Dekomprimieren der Datei wird folgendes Verzeichnis erstellt: `ntap_aix_host_utilities_7.0`. Dieses Verzeichnis enthält eines der folgenden Unterverzeichnisse: MPIO, NON_MPIO oder SAN_Tool_Kit.

. Installieren Sie AIX MPIO:
+
`# installp -aXYd /var/tmp/ntap_aix_host_utilities_7.0/MPIO NetApp.MPIO_Host_Utilities_Kit`

. Installieren Sie das SAN Toolkit:
+
`# installp -aXYd /var/tmp/ntap_aix_host_utilities_7.0/SAN_Tool_Kit/NetApp.SAN_toolkit`

. Starten Sie den Host neu.
. Überprüfen Sie die Installation:
+
`# lslpp -l |grep -i netapp`

+
[listing]
----
NetApp.MPIO_Host_Utilities_Kit.config
                             7.0.0.0  COMMITTED  NetApp MPIO PCM Host Utilities
  NetApp.MPIO_Host_Utilities_Kit.fcp
                             7.0.0.0  COMMITTED  NetApp MPIO PCM Host Utilities
  NetApp.MPIO_Host_Utilities_Kit.iscsi
                             7.0.0.0  COMMITTED  NetApp MPIO PCM Host Utilities
  NetApp.MPIO_Host_Utilities_Kit.pcmodm
                             7.0.0.0  COMMITTED  NetApp MPIO PCM Host Utilities
NetApp.SAN_toolkit.sanlun  7.0.0.0  COMMITTED  NetApp SAN Toolkit sanlun
----
. Bestätigen Sie die Softwareversion:
+
`# sanlun version`

+
[listing]
----
7.0.725.3521
----
. Überprüfen Sie, ob der SCSI-UNMAP- `lbp_enabled`Parameter zum ODM hinzugefügt wurde, indem Sie die folgenden Befehle ausführen:
+
`# odmget -q "uniquetype=disk/fcp/NetAppMPIO" PdAt |grep  "lbp_enabled"`

+
[listing]
----
attribute = "lbp_enabled"
----
+
`# odmget -q "uniquetype=disk/fcp/NetAppMPIO and attribute=lbp_enabled" PdAt`

+
[listing]
----
PdAt:
        uniquetype = "disk/fcp/NetAppMPIO"
        attribute = "lbp_enabled"
        deflt = "true"
        values = "true,false"
        width = ""
        type = "R"
        generic = ""
        rep = "s"
        nls_index = 18
----




== SAN Toolkit

AIX Host Utilities ist eine NetApp-Host-Software, die ein Kommandozeilen-Toolkit auf Ihrem IBM AIX-Host bereitstellt. Das Toolkit wird bei der Installation des NetApp Host Utilities-Pakets installiert. Dieses Kit enthält die `sanlun` Dienstprogramm zum Managen von LUNs und Host Bus Adaptern (HBAs). Der `sanlun` Befehl gibt Informationen über die LUNs zurück, die Ihrem Host zugeordnet sind, Multipathing und Informationen zurück, die zum Erstellen von Initiatorgruppen erforderlich sind.

*Beispiel*

Im folgenden Beispiel wird der verwendet `sanlun lun show` Mit dem Befehl werden die LUN-Informationen zurückgegeben.

[listing]
----
# sanlun lun show all
----
*Beispielausgabe*

[listing]
----
controller(7mode)/ device host lun

vserver(Cmode) lun-pathname filename adapter protocol size mode
----------------------------------------------------------------
data_vserver   /vol/vol1/lun1 hdisk0 fcs0    FCP      60g C
data_vserver   /vol/vol2/lun2 hdisk0 fcs0    FCP      20g C
data_vserver   /vol/vol3/lun3 hdisk11 fcs0   FCP      20g C
data_vserver   /vol/vol4/lun4 hdisk14 fcs0   FCP      20g C
----

NOTE: Dieses Toolkit ist für alle Host Utilities-Konfigurationen und -Protokolle üblich. Daher gelten nicht alle Komponenten für jede Konfiguration. Nicht verwendete Komponenten beeinträchtigen nicht die Systemleistung. Das SAN Toolkit wird auf AIX- und PowerVM/VIOS-Versionen unterstützt
