---
sidebar: sidebar 
permalink: hu-aix-san-toolkit.html 
keywords: san, toolkit, command, line, AIX, hot, utilities 
summary: Die Hostsoftware AIX Host Utilities stellt ein Befehlszeilen-Toolkit auf Ihrem IBM AIX-Host bereit. 
---
= Erfahren Sie mehr über das AIX SAN Toolkit für ONTAP -Speicher
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
AIX Host Utilities ist eine NetApp Hostsoftware, die ein Befehlszeilen-Toolkit auf Ihrem IBM AIX-Host bereitstellt.  Das SAN-Toolkit wird installiert, wenn Sie das NetApp Host Utilities-Paket installieren.  Das Toolkit bietet die `sanlun` Dienstprogramm, das Sie bei der Verwaltung von ONTAP LUNs und Host Bus Adaptern (HBAs) unterstützt.  Der `sanlun` Der Befehl gibt Informationen zu Ihrem Host zugeordneten ONTAP -LUNs, Multipathing und Informationen zurück, die zum Erstellen von Initiatorgruppen erforderlich sind.

Die folgende Beispielausgabe zeigt die ONTAP LUN-Informationen, die für das `sanlun lun show` Befehl:

[listing]
----
controller(7mode)/ device host lun

vserver(Cmode) lun-pathname filename adapter protocol size mode
----------------------------------------------------------------
data_vserver   /vol/vol1/lun1 hdisk0 fcs0    FCP      60g C
data_vserver   /vol/vol2/lun2 hdisk0 fcs0    FCP      20g C
data_vserver   /vol/vol3/lun3 hdisk11 fcs0   FCP      20g C
data_vserver   /vol/vol4/lun4 hdisk14 fcs0   FCP      20g C
----

NOTE: Das SAN Toolkit ist für alle AIX-Hostkonfigurationen und Transportprotokolle gleich.  Daher sind nicht alle Komponenten für jede Konfiguration gültig.  Nicht verwendete Komponenten beeinträchtigen die Leistung Ihres Systems nicht.  Das SAN Toolkit wird auf den Betriebssystemversionen AIX und PowerVM/VIOS unterstützt.



== Was kommt als Nächstes?

link:hu-aix-command-reference.html["Erfahren Sie mehr über die Verwendung des AIX Host Utilities-Tools"] .
