---
sidebar: sidebar 
permalink: hu-ol-810.html 
keywords: host utilities, oracle, linux, 8.10, netapp, ontap 
summary: Beschreibt die Verwendung von Oracle Linux 8.10 mit ONTAP 
---
= Verwenden Sie Oracle Linux 8.10 mit ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können die Konfigurationseinstellungen des ONTAP-SAN-Hosts verwenden, um Oracle Linux 8.10 mit ONTAP als Ziel zu konfigurieren.



== Installieren Sie die Linux Host Utilities

Sie können das Softwarepaket NetApp Linux Host Utilities als 64-bit.rpm-Datei aus der herunterladenlink:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["NetApp Support Website"^].

NetApp empfiehlt ausdrücklich die Installation der Linux Host Utilities, dies ist jedoch nicht zwingend erforderlich. Die Dienstprogramme ändern keine Einstellungen auf Ihrem Linux-Host. Die Versorgungseinrichtungen verbessern das Management und unterstützen den NetApp Kunden-Support bei der Erfassung von Informationen zu Ihrer Konfiguration.

.Schritte
. Laden Sie das 64-Bit-Linux Host Utilities-Softwarepaket vom auf Ihren Host herunter https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["NetApp Support Website"^].
. Installieren des Softwarepakets:
+
`rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_64`





== SAN-Toolkit

Das Toolkit wird automatisch installiert, wenn Sie das NetApp Host Utilities-Paket installieren. Dieses Kit enthält die `sanlun` Dienstprogramm zum Managen von LUNs und Host Bus Adaptern (HBAs). Der `sanlun` Befehl gibt Informationen über die LUNs zurück, die Ihrem Host zugeordnet sind, Multipathing und Informationen zurück, die zum Erstellen von Initiatorgruppen erforderlich sind.

Im folgenden Beispiel wird der verwendet `sanlun lun show` Befehl gibt LUN-Informationen zurück.

[listing]
----
# sanlun lun show all
----
.Beispielausgabe:
[listing]
----
controller(7mode/E-Series)/              device     host               lun
vserver(cDOT/FlashRay)  lun-pathname     filename   adapter  protocol  size   Product
-------------------------------------------------------------------------------------
data_vserver            /vol/vol1/lun1   /dev/sdb   host16   FCP       80.0g  cDOT
data_vserver            /vol/vol1/lun1   /dev/sdc   host15   FCP       80.0g  cDOT
data_vserver            /vol/vol2/lun2   /dev/sdd   host16   FCP       80.0g  cDOT
data_vserver            /vol/vol2/lun2   /dev/sde   host15   FCP       80.0g  cDOT
----


== Aktivieren Sie das Booten über SAN

Wenn Sie sich für das Booten über SAN entscheiden, muss es von Ihrer Konfiguration unterstützt werden.

.Bevor Sie beginnen
Überprüfen Sie mithilfe deslink:https://imt.netapp.com/matrix/#welcome["Interoperabilitäts-Matrix-Tool"^], ob Betriebssystem, HBA, HBA-Firmware, HBA-Boot-BIOS und ONTAP-Version unterstützt werden.

.Schritte
. Ordnen Sie die SAN-Boot-LUN dem Host zu.
. Vergewissern Sie sich, dass mehrere Pfade verfügbar sind.
+

NOTE: Mehrere Pfade sind verfügbar, nachdem das Host-Betriebssystem auf den Pfaden ausgeführt wurde.

. Aktivieren Sie das SAN-Booten im Server-BIOS für die Ports, denen die SAN-Boot-LUN zugeordnet ist.
+
Informationen zum Aktivieren des HBA-BIOS finden Sie in der anbieterspezifischen Dokumentation.

. Starten Sie den Host neu, um zu überprüfen, ob der Startvorgang erfolgreich war.




== Multipathing

Für Oracle Linux 8.10 muss die `/etc/multipath.conf` Datei vorhanden sein. Sie müssen keine Änderungen an dieser Datei vornehmen, da Oracle Linux 8.10 mit den Einstellungen kompiliert wird, die zum Erkennen und korrekten Verwalten von ONTAP-LUNs erforderlich sind.

Für Konfigurationen mit All-SAN-Arrays (ASA) und ohne ASA können Sie mit dem `multipath -ll` Befehl die Einstellungen für eine ONTAP-LUN überprüfen, wie in den folgenden Beispielen gezeigt.


NOTE: Eine einzelne LUN sollte nicht mehr als vier Pfade benötigen. Mehr als acht Pfade können bei Storage-Ausfällen zu Pfadproblemen führen.



=== ASA-Konfigurationen

In ASA Konfigurationen sind alle Pfade zu einer bestimmten LUN aktiv und optimiert. Dies verbessert die Performance, da I/O-Operationen über alle Pfade gleichzeitig ausgeführt werden können.

Im folgenden Beispiel wird die richtige Ausgabe für eine ONTAP-LUN angezeigt, die einer ASA-Persona zugeordnet ist:

[listing]
----
# multipath -ll
3600a098038314d79492b58306a727a6a dm-0 NETAPP,LUN C-Mode
size=180G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
  |- 11:0:7:6  sdbz 68:208  active ready running
  |- 11:0:11:6 sddn 71:80   active ready running
  |- 11:0:15:6 sdfb 129:208 active ready running
  |- 12:0:1:6  sdgp 132:80  active ready running
----


=== Konfigurationen ohne ASA

Für Konfigurationen ohne ASA sollten zwei Gruppen von Pfaden mit unterschiedlichen Prioritäten vorhanden sein. Die Pfade mit höheren Prioritäten sind aktiv/optimiert, d. h. sie werden vom Controller gewartet, in dem sich das Aggregat befindet. Die Pfade mit niedrigeren Prioritäten sind aktiv, aber nicht optimiert, da sie von einem anderen Controller bedient werden. Die nicht optimierten Pfade werden nur verwendet, wenn keine optimierten Pfade verfügbar sind.

Im folgenden Beispiel wird die richtige Ausgabe für eine ONTAP-LUN mit zwei aktiven/optimierten Pfaden und zwei aktiv/nicht optimierten Pfaden angezeigt, die einer nicht-ASA-Persona zugeordnet sind:

[listing]
----
# multipath -ll
3600a0980383036347ffb4d59646c4436 dm-28 NETAPP,LUN C-Mode
size=10G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 16:0:6:35 sdwb	69:624	active ready running
| |- 16:0:5:35 sdun	66:752	active ready running
`-+- policy='service-time 0' prio=10 status=enabled
|- 15:0:0:35 sdaj	66:48	active ready running
|- 15:0:1:35 sdbx	68:176	active ready running
----


== Empfohlene Einstellungen

Das Betriebssystem Oracle Linux 8.10 wird so kompiliert, dass es ONTAP-LUNs erkennt und automatisch die richtigen Konfigurationsparameter für ASA- und nicht-ASA-Konfigurationen festlegt. Außerdem können Sie anhand der folgenden Empfehlungen die Performance Ihrer Host-Konfiguration weiter optimieren:

Die `multipath.conf` Datei muss vorhanden sein, damit der Multipath-Daemon gestartet werden kann. Wenn diese Datei nicht vorhanden ist, können Sie eine leere, Null-Byte-Datei mit dem Befehl erstellen `touch /etc/multipath.conf`.

Wenn Sie die `multipath.conf` Datei zum ersten Mal erstellen, müssen Sie möglicherweise die Multipath-Services mithilfe der folgenden Befehle aktivieren und starten:

[listing]
----
chkconfig multipathd on
/etc/init.d/multipathd start
----
Sie müssen der Datei nichts direkt hinzufügen `multipath.conf`, es sei denn, Sie verfügen über Geräte, die nicht von Multipath verwaltet werden sollen, oder Sie haben bereits vorhandene Einstellungen, die die Standardeinstellungen außer Kraft setzen. Um unerwünschte Geräte auszuschließen, fügen Sie der Datei die folgende Syntax hinzu `multipath.conf` und ersetzen <DevId> durch die Zeichenfolge Worldwide Identifier (WWID) des Geräts, das Sie ausschließen möchten:

[listing]
----
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----
Das folgende Beispiel bestimmt die WWID eines Geräts und fügt sie der Datei hinzu `multipath.conf`.

.Schritte
. Bestimmen Sie die WWID:
+
[listing]
----
/lib/udev/scsi_id -gud /dev/sda
----
+
[listing]
----
3600a098038314c4a433f5774717a3046
----
+
`sda` Ist das lokale SCSI-Laufwerk, das Sie der Blacklist hinzufügen möchten.

. Fügen Sie die hinzu `WWID` Zur schwarzen Liste stanza in `/etc/multipath.conf`:
+
[source, cli]
----
blacklist {
     wwid   3600a098038314c4a433f5774717a3046
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----


Überprüfen Sie Ihre Datei, insbesondere im Abschnitt „Standardeinstellungen“, immer `/etc/multipath.conf` auf ältere Einstellungen, die die Standardeinstellungen überschreiben könnten.

In der folgenden Tabelle sind die kritischen `multipathd` Parameter für ONTAP-LUNs und die erforderlichen Werte aufgeführt. Wenn ein Host mit LUNs anderer Hersteller verbunden ist und diese Parameter überschrieben werden, müssen sie durch spätere Strophen in der `multipath.conf` Datei korrigiert werden, die speziell für ONTAP-LUNs gelten. Ohne diese Korrektur funktionieren die ONTAP-LUNs möglicherweise nicht wie erwartet. Sie sollten diese Standardeinstellungen nur in Absprache mit NetApp, dem OS-Anbieter oder beiden außer Kraft setzen, und zwar nur dann, wenn die Auswirkungen vollständig verstanden sind.

[cols="2*"]
|===
| Parameter | Einstellung 


| Erkennen_Prio | ja 


| Dev_Loss_tmo | Unendlich 


| Failback | Sofort 


| Fast_io_fail_tmo | 5 


| Funktionen | 2 pg_init_retries 50 


| Flush_on_Last_del | ja 


| Hardware_Handler | 0 


| Kein_PATH_retry | Warteschlange 


| PATH_Checker | tur 


| Path_Grouping_Policy | Group_by_prio 


| Pfad_Auswahl | Servicezeit 0 


| Polling_Interval | 5 


| prio | ONTAP 


| Produkt | LUN.* 


| Beibehalten_Attached_hw_Handler | ja 


| rr_weight | Einheitlich 


| User_friendly_names | Nein 


| Anbieter | NETAPP 
|===
Das folgende Beispiel zeigt, wie eine übergebene Standardeinstellung korrigiert wird. In diesem Fall definiert die `multipath.conf` Datei Werte für `path_checker` und `no_path_retry`, die nicht mit ONTAP LUNs kompatibel sind. Wenn sie nicht entfernt werden können, da noch andere SAN-Arrays an den Host angeschlossen sind, können diese Parameter speziell für ONTAP-LUNs mit einem Device stanza korrigiert werden.

[listing]
----
defaults {
 path_checker readsector0
 no_path_retry fail
 }
devices {
 device {
 vendor "NETAPP "
 product "LUN.*"
 no_path_retry queue
 path_checker tur
 }
}
----

NOTE: Um Oracle Linux 8.10 Red hat Compatible Kernel (RHCK) zu konfigurieren, verwenden Sie den link:hu_rhel_810.html#recommended-settings["Empfohlene Einstellungen"] für Red hat Enterprise Linux (RHEL) 8.10.



== Konfigurieren Sie die KVM-Einstellungen

Sie müssen keine Einstellungen für eine Kernel-basierte virtuelle Maschine konfigurieren, da die LUN dem Hypervisor zugeordnet ist.



== ASM Spiegelung

Bei der ASM-Spiegelung (Automatic Storage Management) sind möglicherweise Änderungen an den Linux Multipath-Einstellungen erforderlich, damit ASM ein Problem erkennen und zu einer alternativen Fehlergruppe wechseln kann. Die meisten ASM-Konfigurationen auf ONTAP verwenden externe Redundanz, was bedeutet, dass Datenschutz vom externen Array bereitgestellt wird und ASM keine Daten spiegelt. Einige Standorte verwenden ASM mit normaler Redundanz, um normalerweise zwei-Wege-Spiegelung über verschiedene Standorte hinweg bereitzustellen. Weitere Informationen finden Sie unterlink:https://docs.netapp.com/us-en/ontap-apps-dbs/oracle/oracle-overview.html["Oracle-Datenbanken auf ONTAP"^].



== Bekannte Probleme

Es gibt keine bekannten Probleme für die Oracle Linux 8.10 mit ONTAP-Version.
