---
sidebar: sidebar 
permalink: hu-proxmox-ve-8x.html 
keywords: host utilities, proxmox, linux, 8.x, netapp, ontap 
summary: Installieren Sie die Linux Host Utilities auf einem Proxmox VE 8.x Host, um FCP- und iSCSI-Protokolloperationen mit ONTAP LUNs zu verwalten. 
---
= Konfigurieren Sie Proxmox VE 8.x für FCP und iSCSI mit ONTAP -Speicher
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Konfigurieren Sie Proxmox VE 8.x für Multipathing und mit spezifischen Parametern und Einstellungen für FCP- und iSCSI-Protokolloperationen mit ONTAP -Speicher.

FCP und iSCSI mit Proxmox VE 8.x weisen folgende bekannte Einschränkungen auf:

* Die Linux Host Utilities unterstützen keine Proxmox VE 8.x Betriebssysteme.
* Die SAN-Bootkonfiguration wird nicht unterstützt.




== Schritt 1: Bestätigen Sie die Multipath-Konfiguration für Ihren Host

Mit Proxmox VE 8.x können Sie Multipathing zur Verwaltung von ONTAP LUNs nutzen.

Um sicherzustellen, dass Multipathing für Ihren Host korrekt konfiguriert ist, überprüfen Sie, ob die `/etc/multipath.conf` Datei definiert ist und ob die von NetApp empfohlenen Einstellungen für Ihre ONTAP LUNs konfiguriert sind.

.Schritte
. Überprüfen Sie, ob die `/etc/multipath.conf` Datei beendet wird. Wenn die Datei nicht vorhanden ist, erstellen Sie eine leere, Null-Byte-Datei:
+
[source, cli]
----
touch /etc/multipath.conf
----
. Beim ersten Erstellen der `multipath.conf` Datei müssen Sie möglicherweise die Multipath-Services aktivieren und starten, um die empfohlenen Einstellungen zu laden:
+
[source, cli]
----
systemctl enable multipathd
----
+
[source, cli]
----
systemctl start multipathd
----
. Jedes Mal, wenn Sie den Host starten, lädt die leere `/etc/multipath.conf` Zero-Byte-Datei automatisch die von NetApp empfohlenen Multipath-Parameter als Standardeinstellungen. Sie sollten keine Änderungen an der Datei für Ihren Host vornehmen `/etc/multipath.conf` müssen, da das Betriebssystem mit den Multipath-Parametern kompiliert wird, die ONTAP-LUNs korrekt erkennen und verwalten.
+
In der folgenden Tabelle sind die nativen kompilierten Multipath-Parametereinstellungen für ONTAP LUNs unter Linux aufgeführt.

+
.Parametereinstellungen anzeigen
[%collapsible]
====
[cols="2"]
|===
| Parameter | Einstellung 


| Erkennen_Prio | ja 


| Dev_Loss_tmo | „Unendlich“ 


| Failback | Sofort 


| Fast_io_fail_tmo | 5 


| Funktionen | „2 pg_init_retries 50“ 


| Flush_on_Last_del | "stets" 


| Hardware_Handler | "1" 


| Kein_PATH_retry | Warteschlange 


| PATH_Checker | „nur“ 


| Path_Grouping_Policy | „Group_by_prio“ 


| Pfad_Auswahl | „Servicezeit 0“ 


| Polling_Interval | 5 


| prio | ONTAP 


| Produkt | LUN 


| Beibehalten_Attached_hw_Handler | ja 


| rr_weight | „Einheitlich“ 


| User_friendly_names | Nein 


| Anbieter | NETAPP 
|===
====
. Optional kann der Standardwert für die `find_multipaths` Parameter, um sicherzustellen, dass ONTAP LUNs von multipathd korrekt erkannt und verwaltet werden:
+
--
.. Satz `find_multipaths` im Abschnitt „Standardeinstellungen“ auf „Nein“ setzen `/etc/multipath.conf` :
+
[source, cli]
----
defaults {
    find_multipaths "no"
}
----
.. Laden Sie den Multipath-Dienst neu:
+
[source, cli]
----
systemctl reload multipathd
----


--
+

NOTE: Standardmäßig setzt die Proxmox OS-native Multipath-Konfiguration `find_multipaths` zu "*strict*" mit dem leeren Nullbyte `/etc/multipath.conf` Die Konfigurationsdatei wird bei jedem Neustart des Hosts neu erstellt.  Dies kann verhindern, dass der Host neu präsentierte ONTAP LUNs als Multipath-Geräte erkennt, was bedeutet, dass sie nicht automatisch unter Multipath-Steuerung erscheinen.  Vorhandene ONTAP -LUNs bleiben nach jedem Neustart erkannt und unter Multipath-Steuerung.

. Überprüfen Sie die Parametereinstellungen und den Pfadstatus für Ihre ONTAP LUNs:
+
[source, cli]
----
multipath -ll
----
+
Die standardmäßigen Multipath-Parameter unterstützen ASA-, AFF- und FAS-Konfigurationen. In diesen Konfigurationen sollte eine einzelne ONTAP-LUN nicht mehr als vier Pfade benötigen. Wenn mehr als vier Pfade vorhanden sind, kann dies bei einem Storage-Ausfall zu Problemen mit den Pfaden führen.

+
Die Ausgaben im folgenden Beispiel zeigen die korrekten Parametereinstellungen und den Pfadstatus für ONTAP LUNs in einer ASA-, AFF- oder FAS-Konfiguration.

+
[role="tabbed-block"]
====
.ASA-Konfiguration
--
Eine ASA Konfiguration optimiert alle Pfade zu einer bestimmten LUN und hält sie aktiv. Dies verbessert die Performance, da I/O-Operationen über alle Pfade gleichzeitig ausgeführt werden können.

.Beispiel anzeigen
[%collapsible]
=====
[listing]
----
multipath -ll
3600a098038315071592b59713261566d dm-38 NETAPP,LUN C-Mode
size=100G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 8:0:0:7 sdbv 68:144 active ready running
  |- 9:0:0:7 sdbx 68:176 active ready running
  |- 6:0:0:7 sdbr 68:80  active ready running
  `- 7:0:0:7 sdbt 68:112 active ready running

----
=====
--
.AFF- oder FAS-Konfiguration
--
Eine AFF- oder FAS-Konfiguration sollte zwei Pfadgruppen mit höheren und niedrigeren Prioritäten aufweisen. Aktiv/optimierte Pfade mit höherer Priorität werden vom Controller bedient, wo sich das Aggregat befindet. Pfade mit niedriger Priorität sind aktiv, jedoch nicht optimiert, da sie von einem anderen Controller bedient werden. Nicht optimierte Pfade werden nur verwendet, wenn keine optimierten Pfade verfügbar sind.

Das folgende Beispiel zeigt die Ausgabe für eine ONTAP LUN mit zwei aktiven/optimierten Pfaden und zwei aktiven/nicht optimierten Pfaden:

.Beispiel anzeigen
[%collapsible]
=====
[listing]
----
multipath -ll
3600a0980383149764b5d567257516273 dm-0 NETAPP,LUN C-Mode
size=150G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 16:0:3:0  sdcg 69:64  active ready running
| `- 10:0:0:0  sdb  8:16   active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 10:0:1:0  sdc  8:32   active ready running
  `- 16:0:2:0  sdcf 69:48  active ready running
----
=====
--
====




== Schritt 2: Bestätigen Sie die iSCSI-Konfiguration für Ihren Host

Stellen Sie sicher, dass iSCSI für Ihren Host korrekt konfiguriert ist.

.Über diese Aufgabe
Sie führen die folgenden Schritte auf dem iSCSI-Host durch.

.Schritte
. Überprüfen Sie, ob das iSCSI-Initiator-Paket (open-iscsi) installiert ist:
+
[source, cli]
----
$apt list |grep open-iscsi
----
+
Sie sollten eine Ausgabe ähnlich dem folgenden Beispiel sehen:

+
[listing]
----
open-iscsi/noble-updates,noble-updates,now 2.1.9-3ubuntu5.4 amd64
----
. Überprüfen Sie den iSCSI-Initiator-Node-Name, der sich in der  `/etc/iscsi/initiatorname.iscsi` Datei befindet:
+
[source, cli]
----
InitiatorName=iqn.YYYY-MM.com.<vendor>:<host_name>
----
. Konfigurieren Sie den iSCSI-Session-Zeitüberschreitungsparameter in der  `/etc/iscsi/iscsid.conf` Datei:
+
[source, cli]
----
node.session.timeo.replacement_timeout = 5
----
+
Der iSCSI `replacement_timeout` Parameter steuert, wie lange die iSCSI-Schicht warten soll, bis sich ein Pfad oder eine Sitzung mit Zeitüberschreitung wieder selbst herstellt, bevor Befehle darauf fehlschlagen. Sie sollten den Wert von `replacement_timeout` in der iSCSI-Konfigurationsdatei auf 5 setzen.

. Aktivieren Sie den iSCSI-Service:
+
[source, cli]
----
$systemctl enable iscsid
----
. Starten Sie den iSCSI-Service:
+
[source, cli]
----
$systemctl start iscsid
----
. Überprüfen Sie, ob der iSCSI-Service ausgeführt wird:
+
[source, cli]
----
$systemctl status iscsid
----
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
●iscsid.service - iSCSI initiator daemon (iscsid)
     Loaded: loaded (/usr/lib/systemd/system/iscsid.service; enabled; preset: disabled)
     Active: active (running) since Mon 2026-01-12 12:53:18 IST; 2 days ago
TriggeredBy: ● iscsid.socket
       Docs: man:iscsid(8)
   Main PID: 1127419 (iscsid)
      Tasks: 2 (limit: 76557)
     Memory: 4.3M (peak: 8.8M)
        CPU: 1.657s
     CGroup: /system.slice/iscsid.service
             ├─1127418 /usr/sbin/iscsid
             └─1127419 /usr/sbin/iscsid
----
====
. Ermitteln Sie die iSCSI-Ziele:
+
[source, cli]
----
$iscsiadm --mode discovery --op update --type sendtargets --portal <target_IP>
----
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
iscsiadm --mode discovery --op update --type sendtargets --portal  192.168.100.197
192.168.100.197:3260,1046 iqn.1992-08.com.netapp:sn.7cd154a7d35411f0a25ed039eaa95f59:vs.8
192.168.200.199:3260,1049 iqn.1992-08.com.netapp:sn.7cd154a7d35411f0a25ed039eaa95f59:vs.8
192.168.100.199:3260,1048 iqn.1992-08.com.netapp:sn.7cd154a7d35411f0a25ed039eaa95f59:vs.8
192.168.200.197:3260,1047 iqn.1992-08.com.netapp:sn.7cd154a7d35411f0a25ed039eaa95f59:vs.8
----
====
. Melden Sie sich bei den Targets an:
+
[source, cli]
----
$iscsiadm --mode node -l all
----
. Stellen Sie iSCSI so ein, dass es sich beim Hochfahren des Hosts automatisch anmeldet:
+
[source, cli]
----
$iscsiadm --mode node -T <target_name> -p <ip:port> -o update -n node.startup -v automatic
----
+
Sie sollten eine Ausgabe ähnlich dem folgenden Beispiel sehen:

+
[listing]
----
iscsiadm --mode node -T iqn.1992-08.com.netapp:sn.7cd154a7d35411f0a25ed039eaa95f59:vs.8 -p 192.168.100.197:3260 -o update -n node.startup -v automatic
----
. Überprüfen Sie die iSCSI-Sitzungen:
+
[source, cli]
----
$iscsiadm --mode session
----
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
iscsiadm --mode session
tcp: [1] 192.168.200.197:3260,1047 iqn.1992-08.com.netapp:sn.7cd154a7d35411f0a25ed039eaa95f59:vs.8 (non-flash)
tcp: [2] 192.168.100.197:3260,1046 iqn.1992-08.com.netapp:sn.7cd154a7d35411f0a25ed039eaa95f59:vs.8 (non-flash)
tcp: [3] 192.168.100.199:3260,1048 iqn.1992-08.com.netapp:sn.7cd154a7d35411f0a25ed039eaa95f59:vs.8 (non-flash)
tcp: [4] 192.168.200.199:3260,1049 iqn.1992-08.com.netapp:sn.7cd154a7d35411f0a25ed039eaa95f59:vs.8 (non-flash)
----
====




== Schritt 3: Optionales Ausschließen eines Geräts vom Multipathing

Bei Bedarf können Sie ein Gerät vom Multipathing ausschließen, indem Sie die WWID für das unerwünschte Gerät der „Blacklist“-Strophe für die Datei hinzufügen `multipath.conf`.

.Schritte
. Bestimmen Sie die WWID:
+
[source, cli]
----
/lib/udev/scsi_id -gud /dev/sda
----
+
„sda“ ist die lokale SCSI-Festplatte, die Sie der Blacklist hinzufügen möchten.

+
Ein Beispiel WWID ist `360030057024d0730239134810c0cb833`.

. Fügen Sie die WWID der schwarzen Liste hinzu:
+
[source, cli]
----
blacklist {
	     wwid   360030057024d0730239134810c0cb833
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----




== Schritt 4: Multipath-Parameter für ONTAP LUNs anpassen

Wenn Ihr Host mit LUNs anderer Hersteller verbunden ist und eine der Multipath-Parametereinstellungen überschrieben wird, müssen Sie diese korrigieren, indem Sie später Strophen in der Datei hinzufügen `multipath.conf`, die speziell für ONTAP-LUNs gelten. Wenn Sie dies nicht tun, funktionieren die ONTAP LUNs möglicherweise nicht wie erwartet.

Überprüfen Sie Ihre `/etc/multipath.conf` Datei, insbesondere im Abschnitt Standardeinstellungen, auf Einstellungen, die die überschreiben könnten<<multipath-parameter-settings,Standardeinstellungen für Multipath-Parameter>>.


CAUTION: Die empfohlenen Parametereinstellungen für ONTAP LUNs sollten Sie nicht außer Kraft setzen. Diese Einstellungen sind für eine optimale Performance Ihrer Hostkonfiguration erforderlich. Weitere Informationen erhalten Sie vom NetApp-Support, vom Hersteller Ihres Betriebssystems oder von beiden.

Das folgende Beispiel zeigt, wie eine überhielte Standardeinstellung korrigiert wird. In diesem Beispiel definiert die `multipath.conf` Datei Werte für `path_checker` und `no_path_retry`, die nicht mit ONTAP-LUNs kompatibel sind. Sie können diese Parameter nicht entfernen, da ONTAP-Speicher-Arrays noch mit dem Host verbunden sind. Stattdessen korrigieren Sie die Werte für `path_checker` und `no_path_retry`, indem Sie der Datei, die speziell auf die ONTAP-LUNs zutrifft, eine Gerätestanze hinzufügen `multipath.conf`.

.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
defaults {
   path_checker      *readsector0*
   no_path_retry     *fail*
}

devices {
   device {
      vendor          "NETAPP"
      product         "LUN"
      no_path_retry   *queue*
      path_checker    *tur*
   }
}
----
====


== Schritt 5: Überprüfen der bekannten Probleme

Es sind keine Probleme bekannt.
