---
sidebar: sidebar 
permalink: hu-rhel-8x.html 
keywords: host utilities, red hat, rhel, linux, 8.10, 8.9, 8.8, 8.7, 8.6, 8.5, 8.4, 8.3, 8.2, 8.1, 8.0, netapp, ontap, rhel 
summary: Installieren Sie Linux Host Utilities auf einem RHEL 8.x-Host, um FCP- und iSCSI-Protokolloperationen mit ONTAP LUNs zu verwalten. 
---
= Konfigurieren Sie RHEL 8.x für FCP und iSCSI mit ONTAP -Speicher
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die Linux Host Utilities-Software bietet Verwaltungs- und Diagnosetools für Linux-Hosts, die mit ONTAP Speicher verbunden sind. Wenn Sie die Linux Host Utilities auf einem Red Hat Enterprise Linux (RHEL) 8.x-Host installieren, können Sie die Host Utilities verwenden, um FCP- und iSCSI-Protokolloperationen mit ONTAP LUNs zu verwalten.



== Schritt 1: Aktivieren Sie optional den SAN-Bootvorgang

Sie können Ihren Host so konfigurieren, dass er SAN-Booting verwendet, um die Bereitstellung zu vereinfachen und die Skalierbarkeit zu verbessern.

.Bevor Sie beginnen
Überprüfen Sie mithilfe deslink:https://mysupport.netapp.com/matrix/#welcome["Interoperabilitäts-Matrix-Tool"^], ob Ihr Linux-Betriebssystem, Ihr Host Bus Adapter (HBA), die HBA-Firmware, das HBA-Boot-BIOS und die ONTAP-Version das Booten über das SAN unterstützen.

.Schritte
. link:https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["Erstellen Sie eine SAN-Boot-LUN und ordnen Sie sie dem Host zu"^].
. Aktivieren Sie das SAN-Booten im Server-BIOS für die Ports, denen die SAN-Boot-LUN zugeordnet ist.
+
Informationen zum Aktivieren des HBA-BIOS finden Sie in der anbieterspezifischen Dokumentation.

. Überprüfen Sie, ob die Konfiguration erfolgreich war, indem Sie den Host neu starten und überprüfen, ob das Betriebssystem ausgeführt wird.




== Schritt 2: Installieren Sie die Linux Host Utilities

NetApp empfiehlt dringend die Installation der Linux Host Utilities, um die ONTAP LUN-Verwaltung zu unterstützen, und den technischen Support beim Sammeln von Konfigurationsdaten zu unterstützen.

link:hu-luhu-80.html["Installieren Sie Linux Host Utilities 8.0"] .


NOTE: Durch die Installation der Linux Host Utilities werden keine Host-Timeout-Einstellungen auf Ihrem Linux-Host geändert.



== Schritt 3: Bestätigen Sie die Multipath-Konfiguration für Ihren Host

Mit RHEL 8.x können Sie Multipathing zur Verwaltung von ONTAP LUNs nutzen.

Um sicherzustellen, dass Multipathing für Ihren Host korrekt konfiguriert ist, überprüfen Sie, ob die `/etc/multipath.conf` Datei definiert ist und ob die von NetApp empfohlenen Einstellungen für Ihre ONTAP LUNs konfiguriert sind.

.Schritte
. Überprüfen Sie, ob die `/etc/multipath.conf` Datei beendet wird. Wenn die Datei nicht vorhanden ist, erstellen Sie eine leere, Null-Byte-Datei:
+
[source, cli]
----
touch /etc/multipath.conf
----
. Beim ersten Erstellen der `multipath.conf` Datei müssen Sie möglicherweise die Multipath-Services aktivieren und starten, um die empfohlenen Einstellungen zu laden:
+
[source, cli]
----
systemctl enable multipathd
----
+
[source, cli]
----
systemctl start multipathd
----
. Jedes Mal, wenn Sie den Host starten, lädt die leere `/etc/multipath.conf` Zero-Byte-Datei automatisch die von NetApp empfohlenen Multipath-Parameter als Standardeinstellungen. Sie sollten keine Änderungen an der Datei für Ihren Host vornehmen `/etc/multipath.conf` müssen, da das Betriebssystem mit den Multipath-Parametern kompiliert wird, die ONTAP-LUNs korrekt erkennen und verwalten.
+
In der folgenden Tabelle sind die nativen kompilierten Multipath-Parametereinstellungen für ONTAP LUNs unter Linux aufgeführt.

+
.Parametereinstellungen anzeigen
[%collapsible]
====
[cols="2"]
|===
| Parameter | Einstellung 


| Erkennen_Prio | ja 


| Dev_Loss_tmo | „Unendlich“ 


| Failback | Sofort 


| Fast_io_fail_tmo | 5 


| Funktionen | „2 pg_init_retries 50“ 


| Flush_on_Last_del | „ja“ 


| Hardware_Handler | „0“ 


| Kein_PATH_retry | Warteschlange 


| PATH_Checker | „nur“ 


| Path_Grouping_Policy | „Group_by_prio“ 


| Pfad_Auswahl | „Servicezeit 0“ 


| Polling_Interval | 5 


| prio | ONTAP 


| Produkt | LUN 


| Beibehalten_Attached_hw_Handler | ja 


| rr_weight | „Einheitlich“ 


| User_friendly_names | Nein 


| Anbieter | NETAPP 
|===
====
. Überprüfen Sie die Parametereinstellungen und den Pfadstatus für Ihre ONTAP LUNs:
+
[source, cli]
----
multipath -ll
----
+
Die standardmäßigen Multipath-Parameter unterstützen ASA, AFF und FAS Konfigurationen. In diesen Konfigurationen sollte eine einzelne ONTAP LUN nicht mehr als vier Pfade benötigen. Mehr als vier Pfade können bei einem Speicherausfall Probleme verursachen.

+
Die Ausgaben im folgenden Beispiel zeigen die korrekten Parametereinstellungen und den Pfadstatus für ONTAP LUNs in einer ASA-, AFF- oder FAS-Konfiguration.

+
[role="tabbed-block"]
====
.ASA-Konfiguration
--
Eine ASA Konfiguration optimiert alle Pfade zu einer bestimmten LUN und hält sie aktiv. Dies verbessert die Performance, da I/O-Operationen über alle Pfade gleichzeitig ausgeführt werden können.

.Beispiel anzeigen
[%collapsible]
=====
[listing]
----
multipath -ll
3600a098038314c4a433f577471797958 dm-2 NETAPP,LUN C-Mode
size=180G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 14:0:0:0  sdc  8:32   active ready running
  |- 17:0:0:0  sdas 66:192 active ready running
  |- 14:0:3:0  sdar 66:176 active ready running
  `- 17:0:3:0  sdch 69:80  active ready running
----
=====
--
.AFF- oder FAS-Konfiguration
--
Eine AFF- oder FAS-Konfiguration sollte zwei Pfadgruppen mit höheren und niedrigeren Prioritäten aufweisen. Aktiv/optimierte Pfade mit höherer Priorität werden vom Controller bedient, wo sich das Aggregat befindet. Pfade mit niedriger Priorität sind aktiv, jedoch nicht optimiert, da sie von einem anderen Controller bedient werden. Nicht optimierte Pfade werden nur verwendet, wenn keine optimierten Pfade verfügbar sind.

Im folgenden Beispiel wird die Ausgabe für eine ONTAP-LUN mit zwei aktiv/optimiert-Pfaden und zwei aktiv/nicht-optimierten Pfaden angezeigt:

.Beispiel anzeigen
[%collapsible]
=====
[listing]
----
multipath -ll
3600a0980383149764b5d567257516273 dm-0 NETAPP,LUN C-Mode
size=150G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 16:0:3:0  sdcg 69:64  active ready running
| `- 10:0:0:0  sdb  8:16   active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 10:0:1:0  sdc  8:32   active ready running
  `- 16:0:2:0  sdcf 69:48  active ready running
----
=====
--
====




== Schritt 4: Bestätigen Sie die iSCSI-Konfiguration für Ihren Host

Um sicherzustellen, dass Multipathing für Ihren Host korrekt konfiguriert ist, setzen Sie den  `timeout` Parameter auf Ihrem Host und bestätigen Sie, dass der iSCSI-Service läuft und eine Verbindung zu den iSCSI-Zielen herstellt.

.Schritte
. Überprüfen Sie, ob das iSCSI-Initiator-Paket (iscsi-initiator-utils) installiert ist:
+
[source, cli]
----
rpm -qa | grep iscsi-initiator-utils
----
+
Sie sollten eine Ausgabe ähnlich dem folgenden Beispiel sehen:

+
[listing]
----
iscsi-initiator-utils-6.2.1.11-0.git4b3e853.el9.x86_64
----
. Überprüfen Sie den iSCSI-Initiator-Node-Name, der sich in der  `/etc/iscsi/initiatorname.iscsi` Datei befindet:
+
[source, cli]
----
InitiatorName=iqn.YYYY-MM.com.<vendor>:<host_name>
----
. Konfigurieren Sie den iSCSI-Session-Zeitüberschreitungsparameter in der  `/etc/iscsi/iscsid.conf` Datei:
+
[source, cli]
----
node.session.timeo.replacement_timeout = 5
----
+
Der iSCSI `replacement_timeout` Parameter steuert, wie lange die iSCSI-Schicht warten soll, bis sich ein Pfad oder eine Sitzung mit Zeitüberschreitung wieder selbst herstellt, bevor Befehle darauf fehlschlagen. Sie sollten den Wert von `replacement_timeout` in der iSCSI-Konfigurationsdatei auf 5 setzen.

. Aktivieren Sie den iSCSI-Service:
+
[source, cli]
----
$systemctl enable iscsid
----
. Starten Sie den iSCSI-Service:
+
[source, cli]
----
$systemctl start iscsid
----
. Überprüfen Sie, ob der iSCSI-Service ausgeführt wird:
+
[source, cli]
----
$systemctl status iscsid
----
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
● iscsid.service - Open-iSCSI
     Loaded: loaded (/usr/lib/systemd/system/iscsid.service; enabled; preset: disabled)
     Active: active (running) since Tue 2025-12-02 11:36:21 EST; 2 weeks 1 day ago
TriggeredBy: ● iscsid.socket
       Docs: man:iscsid(8)
             man:iscsiuio(8)
             man:iscsiadm(8)
   Main PID: 2263 (iscsid)
     Status: "Ready to process requests"
      Tasks: 1 (limit: 816061)
     Memory: 18.5M
        CPU: 14.480s
     CGroup: /system.slice/iscsid.service
             └─2263 /usr/sbin/iscsid -f -d2
----
====
. Ermitteln Sie die iSCSI-Ziele:
+
[source, cli]
----
$iscsiadm --mode discovery --op update --type sendtargets --portal <target_IP>
----
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
iscsiadm --mode discovery --op update --type sendtargets --portal  192.168.30.87
192.168.30.87:3260,1139 iqn.1992-08.com.netapp:sn.064a9b19b3ee11f09dcad039eabac370:vs.23
192.168.31.97:3260,1142 iqn.1992-08.com.netapp:sn.064a9b19b3ee11f09dcad039eabac370:vs.23
192.168.31.87:3260,1141 iqn.1992-08.com.netapp:sn.064a9b19b3ee11f09dcad039eabac370:vs.23
192.168.30.97:3260,1140 iqn.1992-08.com.netapp:sn.064a9b19b3ee11f09dcad039eabac370:vs.23
----
====
. Melden Sie sich bei den Targets an:
+
[source, cli]
----
$iscsiadm --mode node -l all
----
. Stellen Sie iSCSI so ein, dass es sich beim Hochfahren des Hosts automatisch anmeldet:
+
[source, cli]
----
$iscsiadm --mode node -T <target_name> -p <ip:port> -o update -n node.startup -v automatic
----
+
Sie sollten eine Ausgabe ähnlich dem folgenden Beispiel sehen:

+
[listing]
----
iscsiadm --mode node -T iqn.1992-08.com.netapp:sn.064a9b19b3ee11f09dcad039eabac370:vs.23 -p 192.168.30.87:3260 -o update -n node.startup -v automatic
----
. Überprüfen Sie die iSCSI-Sitzungen:
+
[source, cli]
----
$iscsiadm --mode session
----
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
iscsiadm --mode session
tcp: [1] 192.168.30.87:3260,1139 iqn.1992-08.com.netapp:sn.064a9b19b3ee11f09dcad039eabac370:vs.23 (non-flash)
tcp: [2] 192.168.31.97:3260,1142 iqn.1992-08.com.netapp:sn.064a9b19b3ee11f09dcad039eabac370:vs.23 (non-flash)
tcp: [3] 192.168.31.87:3260,1141 iqn.1992-08.com.netapp:sn.064a9b19b3ee11f09dcad039eabac370:vs.23 (non-flash)
tcp: [4] 192.168.30.97:3260,1140 iqn.1992-08.com.netapp:sn.064a9b19b3ee11f09dcad039eabac370:vs.23 (non-flash)
----
====




== Schritt 5: Optional ein Gerät von der Multipathing-Funktion ausschließen

Bei Bedarf können Sie ein Gerät vom Multipathing ausschließen, indem Sie die WWID für das unerwünschte Gerät der „Blacklist“-Strophe für die Datei hinzufügen `multipath.conf`.

.Schritte
. Bestimmen Sie die WWID:
+
[source, cli]
----
/lib/udev/scsi_id -gud /dev/sda
----
+
„sda“ ist die lokale SCSI-Festplatte, die Sie der Blacklist hinzufügen möchten.

+
Ein Beispiel WWID ist `360030057024d0730239134810c0cb833`.

. Fügen Sie die WWID der schwarzen Liste hinzu:
+
[source, cli]
----
blacklist {
	     wwid   360030057024d0730239134810c0cb833
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----




== Schritt 6: Multipath-Parameter für ONTAP LUNs anpassen

Wenn Ihr Host mit LUNs anderer Hersteller verbunden ist und eine der Multipath-Parametereinstellungen überschrieben wird, müssen Sie diese korrigieren, indem Sie später Strophen in der Datei hinzufügen `multipath.conf`, die speziell für ONTAP-LUNs gelten. Wenn Sie dies nicht tun, funktionieren die ONTAP LUNs möglicherweise nicht wie erwartet.

Überprüfen Sie Ihre `/etc/multipath.conf` Datei, insbesondere im Abschnitt Standardeinstellungen, auf Einstellungen, die die überschreiben könnten<<multipath-parameter-settings,Standardeinstellungen für Multipath-Parameter>>.


CAUTION: Die empfohlenen Parametereinstellungen für ONTAP LUNs sollten Sie nicht außer Kraft setzen. Diese Einstellungen sind für eine optimale Performance Ihrer Hostkonfiguration erforderlich. Weitere Informationen erhalten Sie vom NetApp-Support, vom Hersteller Ihres Betriebssystems oder von beiden.

Das folgende Beispiel zeigt, wie eine überhielte Standardeinstellung korrigiert wird. In diesem Beispiel definiert die `multipath.conf` Datei Werte für `path_checker` und `no_path_retry`, die nicht mit ONTAP-LUNs kompatibel sind. Sie können diese Parameter nicht entfernen, da ONTAP-Speicher-Arrays noch mit dem Host verbunden sind. Stattdessen korrigieren Sie die Werte für `path_checker` und `no_path_retry`, indem Sie der Datei, die speziell auf die ONTAP-LUNs zutrifft, eine Gerätestanze hinzufügen `multipath.conf`.

.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
defaults {
   path_checker      *readsector0*
   no_path_retry     *fail*
}

devices {
   device {
      vendor          "NETAPP"
      product         "LUN"
      no_path_retry   *queue*
      path_checker    *tur*
   }
}
----
====


== Schritt 7: Überprüfen Sie die bekannten Probleme

Bei RHEL 8.x mit ONTAP -Speicher gibt es folgende bekannte Probleme.

[role="tabbed-block"]
====
.8.1
--
[cols="3*"]
|===
| NetApp Bug ID | Titel | Beschreibung 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1275843["1275843"^] | Bei Red hat Enterprise Linux 8.1 mit QLogic QLE2672 16 Gbit FC HBA tritt möglicherweise eine Kernel-Störung auf | Bei einem Storage Failover auf dem Red hat Enterprise Linux 8.1 Kernel mit einem QLogic QLE2672 Fibre Channel (FC) Host Bus Adapter (HBA) kann es zu Kernel-Störungen kommen. Die Kernel-Störung bewirkt, dass Red hat Enterprise Linux 8.1 neu gestartet wird, was zu Applikationsunterbrechungen führt. Wenn der kdump-Mechanismus aktiviert ist, generiert die Kernel-Störung eine vmcore-Datei im Verzeichnis/var/Crash/Verzeichnis. Sie können die vmcore-Datei überprüfen, um die Ursache der Störung festzustellen.Ein Storage-Failover mit dem QLogic QLE2672 HBA-Ereignis wirkt sich auf das Modul „kmem_Cache_alloc+131“ aus. Sie können das Ereignis in der vmcore-Datei finden, indem Sie folgende Zeichenfolge suchen: „ [Ausnahme-RIP: Kmem_Cache_alloc+131]“nach der Kernel-Störung, starten Sie das Host-Betriebssystem neu und stellen Sie das Betriebssystem wieder her. Starten Sie dann die Applikationen neu 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1275838["1275838"^] | Bei einem Storage Failover-Betrieb tritt bei Red hat Enterprise Linux 8.1 mit QLogic QLE2742 32 GB FC HBA eine Störung des Kernels auf | Kernel-Störung tritt bei Storage Failover-Vorgängen auf dem Red hat Enterprise Linux 8.1 Kernel mit einem QLogic QLE2742 Fibre Channel (FC) Host Bus Adapter (HBA) auf. Die Kernel-Störung bewirkt, dass Red hat Enterprise Linux 8.1 neu gestartet wird, was zu Applikationsunterbrechungen führt. Wenn der kdump-Mechanismus aktiviert ist, generiert die Kernel-Störung eine vmcore-Datei im Verzeichnis/var/Crash/Verzeichnis. Sie können die vmcore-Datei überprüfen, um die Ursache der Störung festzustellen. Ein Storage Failover mit dem QLogic QLE2742 HBA-Ereignis wirkt sich auf das „kmem_Cache_alloc+131“-Modul aus. Sie können das Ereignis in der vmcore-Datei finden, indem Sie folgende Zeichenfolge suchen: „ [Ausnahme-RIP: Kmem_Cache_alloc+131]“nach der Kernel-Störung, starten Sie das Host-Betriebssystem neu und stellen Sie das Betriebssystem wieder her. Starten Sie dann die Applikationen neu. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1266250["1266250"^] | Die Anmeldung bei mehreren Pfaden ist während der Installation von Red hat Enterprise Linux 8.1 auf iSCSI SAN LUN fehlgeschlagen | Während der Installation von Red hat Enterprise Linux 8.1 auf iSCSI SAN LUN Multipath-Geräten können Sie sich nicht mit mehreren Pfaden anmelden. Die Installation ist auf Multipath iSCSI-Geräten nicht möglich und der Multipath-Dienst ist auf dem SAN-Boot-Gerät nicht aktiviert. 
|===
--
.8.0
--
[cols="3*"]
|===
| NetApp Bug ID | Titel | Beschreibung 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1238719["1238719"^] | Kernel-Störung auf RHEL8 mit QLogic QLE2672 16GB FC während des Storage Failover-Betriebs | Bei Storage Failover-Vorgängen auf einem Red hat Enterprise Linux (RHEL) 8 Kernel mit einem QLogic QLE2672 Host Bus Adapter (HBA) kann es zu Kernel-Störungen kommen. Die Kernel-Störung bewirkt, dass das Betriebssystem neu gestartet wird. Das Neubooten bewirkt eine Applikationsunterbrechung und generiert die vmcore-Datei unter dem Verzeichnis /var/crash/Directory, wenn kdump konfiguriert ist. Verwenden Sie die vmcore-Datei, um die Ursache des Fehlers zu identifizieren. In diesem Fall befindet sich die Störung im Modul „kmem_Cache_alloc+160“. Sie wird in der vmcore-Datei mit der folgenden Zeichenfolge protokolliert: „[Ausnahme-RIP: Kmem_Cache_alloc+160]“. Starten Sie das Host-Betriebssystem neu, um das Betriebssystem wiederherzustellen, und starten Sie dann die Anwendung neu. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1226783["1226783"^] | RHEL8 OS startet bis zum „Notfallmodus“, wenn mehr als 204 SCSI-Geräte auf allen Fibre Channel (FC) Host Bus Adaptern (HBA) abgebildet sind | Wenn ein Host während eines laufenden Systemneustarts mehr als 204 SCSI-Geräte zugeordnet ist, kann das RHEL8-Betriebssystem nicht in den „normalen Modus“ gestartet werden und wechselt in den „Notfallmodus“. Dies führt dazu, dass der Großteil der Host Services nicht mehr verfügbar ist. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1230882["1230882"^] | Das Erstellen einer Partition auf einem iSCSI Multipath-Gerät während der RHEL8-Installation ist nicht möglich. | ISCSI SAN LUN Multipath-Geräte werden während der RHEL 8-Installation nicht in der Festplattenauswahl aufgeführt. Folglich ist der Multipath-Service auf dem SAN Boot-Gerät nicht aktiviert. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1235998["1235998"^] | Der Befehl „rescan-scsi-bus.sh -a“ scannt nicht mehr als 328 Geräte | Wenn ein Red hat Enterprise Linux 8-Host mit mehr als 328 SCSI-Geräten zuordnet, scannt der Host-Betriebssystem-Befehl „rescan-scsi-bus.sh -A“ nur 328 Geräte. Der Host entdeckt keine verbleibenden zugeordneten Geräte. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1231087["1231087"^] | Remote-Ports werden beim Storage Failover-Betrieb in einen blockierten Status auf RHEL8 mit Emulex LPe16002 16 GB FC überführt | Remote-Ports werden beim Storage Failover in einen blockierten Status auf RHEL8 mit Emulex LPe16002 16 GB Fibre Channel (FC) überführt. Wenn der Storage Node wieder in einen optimalen Zustand versetzt wird, kommen die LIFs ebenfalls hinzu und der Remote-Port-Status sollte „online“ lesen. Gelegentlich wird der Status des Remote-Ports möglicherweise weiterhin als „gesperrt“ oder „nicht vorhanden“ gelesen. Dieser Status kann zu einem „fehlerhaften“ Pfad zu LUNs in der Multipath-Schicht führen 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1231098["1231098"^] | Remote-Ports werden während des Storage Failover-Betriebs auf RHEL8 mit Emulex LPe32002 32 GB FC in blockierten Status versetzt | Remote-Ports werden beim Storage Failover in einen blockierten Status auf RHEL8 mit Emulex LPe32002 32 GBFibre Channel (FC) überführt. Wenn der Storage Node wieder in einen optimalen Zustand versetzt wird, kommen die LIFs ebenfalls hinzu und der Remote-Port-Status sollte „online“ lesen. Gelegentlich wird der Status des Remote-Ports möglicherweise weiterhin als „gesperrt“ oder „nicht vorhanden“ gelesen. Dieser Status kann zu einem „fehlerhaften“ Pfad zu LUNs in der Multipath-Schicht führen. 
|===
--
====


== Was kommt als Nächstes?

* link:hu-luhu-command-reference.html["Erfahren Sie mehr über die Verwendung des Linux Host Utilities-Tools"] .
* Erfahren Sie mehr über ASM-Spiegelung.
+
Bei der ASM-Spiegelung (Automatic Storage Management) sind möglicherweise Änderungen an den Linux Multipath-Einstellungen erforderlich, damit ASM ein Problem erkennen und zu einer alternativen Fehlergruppe wechseln kann. Die meisten ASM-Konfigurationen auf ONTAP verwenden externe Redundanz, was bedeutet, dass Datenschutz vom externen Array bereitgestellt wird und ASM keine Daten spiegelt. Einige Standorte verwenden ASM mit normaler Redundanz, um normalerweise zwei-Wege-Spiegelung über verschiedene Standorte hinweg bereitzustellen. Weitere Informationen finden Sie unterlink:https://docs.netapp.com/us-en/ontap-apps-dbs/oracle/oracle-overview.html["Oracle-Datenbanken auf ONTAP"^].

* Erfahren Sie mehr über Red Hat Linux Virtualisierung (KVM).
+
Red Hat Linux kann als KVM-Host dienen. Dies ermöglicht es Ihnen, mehrere virtuelle Maschinen auf einem einzigen physischen Server mithilfe der Linux Kernel-based Virtual Machine (KVM)-Technologie auszuführen. Der KVM-Host benötigt keine expliziten Hostkonfigurationseinstellungen für ONTAP LUNs.


