---
sidebar: sidebar 
permalink: hu-wuhu-80.html 
keywords: windows, 7.2, host utilities, SAN, windows 
summary: Windows Host Utilities enthält ein Installationsprogramm, das die erforderlichen Windows-Registrierungs- und HBA-Parameter festlegt, sodass der Windows-Host das Speichersystemverhalten für ONTAP -Plattformen korrekt handhabt. 
---
= Installieren Sie Windows Host Utilities 8.0 für ONTAP -Speicher
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Mithilfe der Windows Host Utilities können Sie einen Windows Host-Computer mit NetApp Storage-Systemen verbinden.

Die Windows Host Utilities unterstützen die folgenden Versionen von Windows:

* Windows 2025
* Windows 2022
* Windows 2019
* Windows 2016


Windows Host Utilities enthält ein Installationsprogramm, das die erforderlichen Windows-Registrierungs- und Host Bus Adapter (HBA)-Parameter festlegt, sodass ein Windows-Host das Speichersystemverhalten für ONTAP -Plattformen korrekt verarbeiten kann.

Wenn Sie die Host Utilities-Software installieren, legt das Installationsprogramm die erforderlichen Windows Registry- und HBA-Parameter fest.

Die folgenden Programme und Dateien werden auf dem Windows-Hostcomputer installiert. Das Standardverzeichnis ist `C:\Program Files\NetApp\Windows Host Utilities`.

|===
| Programm | Zweck 


| `\NetAppQCLI\fcconfig.exe` | Wird vom Installationsprogramm zum Einstellen der HBA-Parameter verwendet. 


| `\NetAppQCLI\fcconfig.ini` | Wird vom Installationsprogramm zum Einstellen der HBA-Parameter verwendet. 


| `san_version.exe` | Zeigt die Version der Host Utilities und FC HBAs an. 
|===
Die Host Utilities unterstützen verschiedene Windows Host-Konfigurationen, Protokolle und Multipathing-Optionen. Weitere Informationen finden Sie im https://mysupport.netapp.com/matrix/["Interoperabilitäts-Matrix-Tool"^].



== Schritt 1: Überprüfen Sie die Konfiguration Ihres Hosts und Speichersystems

Überprüfen Sie, ob Ihre Host- und Speichersystemkonfiguration unterstützt wird, bevor Sie Windows Host Utilities für die<<supported-windows-versions-80,Unterstützte Windows-Version>> .

.Schritte
. Überprüfen Sie die unterstützte Konfiguration im http://mysupport.netapp.com/matrix["Interoperabilitäts-Matrix-Tool"^].
. Überprüfen Sie die für Ihre Windows Server-Hostversion erforderlichen Hotfixes imlink:https://docs.netapp.com/us-en/ontap-sanhost/index.html["SAN-Host, Windows-Dokumentation"] .
+
Zum Beispiel dielink:https://docs.netapp.com/us-en/ontap-sanhost/hu-windows-2025.html["Konfigurieren Sie Windows Server 2025 für ONTAP-Speicher"] Die Dokumentation enthält Anweisungen zum Installieren von Windows-Hotfixes für Windows Server 2025.

. link:https://docs.netapp.com/us-en/ontap/san-admin/verify-license-fc-iscsi-task.html["Fügen Sie die iSCSI- oder FCP-Lizenz hinzu"^] .
. Starten Sie den Zieldienst.
. Überprüfen Sie die Verkabelung.
+
Weitere Informationen finden Sie im https://docs.netapp.com/us-en/ontap/san-config/index.html["Referenz zur SAN-Konfiguration"^] für detaillierte Informationen zur Verkabelung und Konfiguration.





== Schritt 2: FC-HBAs und Switches konfigurieren

Installieren und konfigurieren Sie einen oder mehrere unterstützte FC-Hostbusadapter (HBAs) für FC-Verbindungen zum Speichersystem.

Das Windows Host Utilities-Installationsprogramm legt die erforderlichen FC HBA-Einstellungen fest.


CAUTION: Sie sollten nur zulassen, dass das Installationsprogramm von Windows Host Utilities die HBA-Parameter einstellt.  Dadurch wird sichergestellt, dass der Windows-Host das Speichersystemverhalten für ONTAP -Plattformen korrekt verarbeiten kann.

.Schritte
. Installieren Sie einen oder mehrere unterstützte FC-HBAs gemäß den Anweisungen des HBA-Anbieters.
. Beziehen Sie die unterstützten HBA-Treiber und Verwaltungsprogrammen ein, und installieren Sie diese gemäß den Anweisungen des HBA-Anbieters.
. https://docs.netapp.com/us-en/ontap/san-management/index.html["Verbinden Sie die HBAs mit Ihren FC-Switches oder direkt mit dem Speichersystem"^] .
. https://docs.netapp.com/us-en/ontap/san-config/fibre-channel-fcoe-zoning-concept.html["Erstellen Sie Zonen auf dem FC-Switch gemäß Ihrer FC-Switch-Dokumentation"^] .
. Bei ONTAP zonieren Sie den Switch nach dem WWPN.  Achten Sie darauf, die WWPN der logischen Schnittstellen (LIFs) und nicht die WWPN der physischen Ports auf den Speichercontrollern zu verwenden. Weitere Informationen finden Sie im  https://docs.netapp.com/us-en/ontap/san-config/index.html["Referenz zur SAN-Konfiguration"^] für weitere Informationen.




== Schritt 3: Installieren Sie die Windows-Host-Dienstprogramme

Das Installationsprogramm installiert das Windows Host Utilities-Paket und legt die Windows-Registrierung und die HBA-Einstellungen fest.

.Über diese Aufgabe
Optional können Sie Multipathing-Unterstützung einschließen, wenn Sie das Softwarepaket „Windows Host Utilities“ installieren.  Das Installationsprogramm fordert Sie zur Eingabe der folgenden Optionen auf:

* Wählen `MPIO` Wenn Sie mehr als einen Pfad vom Windows-Host oder der virtuellen Maschine zum Speichersystem haben.
* Wählen `no MPIO` nur, wenn Sie einen einzelnen Pfad zum Speichersystem verwenden.


Sie können die Multipathing-Unterstützung auch über eine Windows-Eingabeaufforderung auswählen.

Bei Hyper-V-Gästen werden Raw-Datenträger (Pass-Through) nicht im Gastbetriebssystem angezeigt, wenn Sie die Multipathing-Unterstützung wählen.  Sie können entweder Raw-Festplatten oder MPIO verwenden, aber nicht beides im Gastbetriebssystem.


CAUTION: Wenn Sie die MPIO-Software nicht installieren, sieht das Windows-Betriebssystem jeden Pfad möglicherweise als separate Festplatte. Dies kann zu Datenbeschädigungen führen.


NOTE: Windows XP oder Windows Vista, die auf einer virtuellen Hyper-V-Maschine ausgeführt werden, unterstützt MPIO nicht.

.Schritte
Sie können die Host-Dienstprogramme interaktiv oder über die Windows-Befehlszeile installieren.  Das neue Host Utilities-Installationspaket muss sich in einem Pfad befinden, auf den der Windows-Host zugreifen kann.

[role="tabbed-block"]
====
.Interaktiv installieren
--
Installieren Sie das Softwarepaket „Windows Host Utilities“ interaktiv, indem Sie das Installationsprogramm ausführen und den Anweisungen folgen.

. Laden Sie die ausführbare Datei von der https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/8.0/downloads["NetApp Support Website"^] .
. Wechseln Sie in das Verzeichnis, in dem Sie die ausführbare Datei heruntergeladen haben.
. Führen Sie den `netapp_windows_host_utilities_8.0.0_x64` Datei und folgen Sie den Anweisungen auf dem Bildschirm.
. Starten Sie den Windows-Host neu, wenn Sie dazu aufgefordert werden.


--
.Nicht-interaktiv installieren
--
Führen Sie eine nicht interaktive Installation der Host-Dienstprogramme mithilfe der Windows-Befehlszeile durch.  Das System wird nach Abschluss der Installation automatisch neu gestartet.

. Geben Sie den folgenden Befehl an der Windows-Eingabeaufforderung ein:
+
[source, cli]
----
msiexec /i installer.msi /quiet MULTIPATHING= {0 | 1} [INSTALLDIR=inst_path]
----
+
** `installer` Ist der Name des `.msi` Datei für Ihre CPU-Architektur.
** MULTIPATHING gibt an, ob MPIO-Unterstützung installiert ist. Die zulässigen Werte sind „0“ für „Nein“ und „1“ für „Ja“.
** `inst_path` Ist der Pfad, in dem die Host Utilities-Dateien installiert werden. Der Standardpfad lautet `C:\Program Files\NetApp\Windows Host Utilities\`.





NOTE: Um die standardmäßigen Microsoft Installer-Optionen (MSI) für die Protokollierung und andere Funktionen anzuzeigen, geben Sie ein `msiexec /help` An der Windows-Eingabeaufforderung. Beispiel: Der `msiexec /i install.msi /quiet /l*v <install.log> LOGVERBOSE=1` Befehl zeigt Protokollinformationen an.

--
====


== Was kommt als Nächstes?

link:hu_wuhu_hba_settings.html["Konfigurieren der Registrierungseinstellungen für Windows Host Utilities"] .
