---
sidebar: sidebar 
permalink: hu_aix_61.html 
keywords: host utilities, aix, powervm, vios, 3.1, 7.2 netapp, ontap 
summary: Beschreibt die Verwendung von IBM AIX 7.2 und/oder PowerVM VIOS 3.1 mit ONTAP 
---
= Installieren Sie AIX Host Utilities 6.1 für ONTAP-Speicher
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die AIX Host Utilities unterstützen Sie bei der Verwaltung des an einen AIX-Host angeschlossenen ONTAP Speichers.  NetApp empfiehlt dringend die Installation der AIX Host Utilities, um die ONTAP Speicherverwaltung zu verbessern und den NetApp -Support beim Sammeln von Informationen zu Ihrer Konfiguration zu unterstützen.

AIX Host Utilities 6.1 unterstützt die folgenden Transportprotokolle und AIX-Umgebungen:

* FC, FCoE und iSCSI
* AIX Microsoft Multipath I/O (MPIO)
* PowerVM
+
Weitere Informationen zu PowerVM finden Sie im IBM PowerVM Live Partition Mobility Red Book.



.Über diese Aufgabe
* Sie müssen das AIX Host Utilities SAN Toolkit mit AIX MPIO installieren, um den an einen AIX-Host angeschlossenen ONTAP -Speicher zu verwalten.
* Wenn Sie AIX Host Utilities installieren, werden keine Einstellungen auf Ihrem AIX-Host geändert.


.Bevor Sie beginnen
* Verwenden Sie dielink:https://mysupport.netapp.com/matrix/#welcome["Interoperabilitäts-Matrix-Tool"^] um zu überprüfen, ob Ihr AIX-Betriebssystem, Ihr Protokoll und ONTAP Version das SAN-Booten unterstützen.
* Aktivieren Sie die dynamische Verfolgung für alle FC- und FCoE-Initiatoren, indem Sie den `chdev -l <fscsi_device> -a dyntrk=ye` Befehl auf dem AIX-Host.


.Schritte
. Melden Sie sich bei Ihrem Host an.
+
[role="tabbed-block"]
====
.AIX
--
Melden Sie sich auf einem AIX-Host als *root* an.

--
.PowerVM
--
Auf einem PowerVM-Host:

.. Melden Sie sich als *padmin* an.
.. Werden Sie Root-Benutzer:
+
[source, cli]
----
oem_setup_env
----


--
====
. Wechseln Sie zum https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/6.1/downloads["NetApp Support Website"^] Und laden Sie die komprimierte Datei mit den Host Utilities in ein Verzeichnis auf Ihrem Host herunter.
. Gehen Sie zu dem Verzeichnis, in dem der Download enthalten ist.
. Dekomprimieren Sie die Datei und extrahieren Sie das SAN Toolkit Softwarepaket.
+
[source, cli]
----
tar -xvf ntap_aix_host_utilities_6.1.tar.gz
----
+
Das folgende Verzeichnis wird beim Dekomprimieren der Datei erstellt: `ntap_aix_host_utilities_6.1`. Dieses Verzeichnis verfügt über eines der folgenden Unterverzeichnisse: MPIO, NON_MPIO oder SAN_Tool_Kit.

. Installieren Sie AIX MPIO:
+
[source, cli]
----
installp -aXYd /var/tmp/ntap_aix_host_utilities_6.1/MPIO NetApp.MPIO_Host_Utilities_Kit
----
. Installieren Sie das SAN Toolkit:
+
[source, cli]
----
installp -aXYd /var/tmp/ntap_aix_host_utilities_6.1/SAN_Tool_Kit NetApp.SAN_toolkit
----
. Starten Sie den Host neu.
. Überprüfen Sie die Installation:
+
[source, cli]
----
sanlun version
----




== Was kommt als Nächstes?

link:hu-aix-san-toolkit.html["Erfahren Sie mehr über das AIX SAN Toolkit"] .
