---
sidebar: sidebar 
permalink: hu_aix_61_rn.html 
keywords: host utilities, aix, 6.1 netapp, ontap, powervm 
summary: Versionshinweise zu AIX Host Utilities 6.1 
---
= AIX Host Utilities 6.1 – Versionshinweise
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Diese Versionshinweise enthalten die neuesten Informationen zur Version von AIX Host Utilities 6.1 sowie Updates zu bekannten Problemen, Einschränkungen sowie die Konfiguration und Verwaltung des ONTAP Storage-Systems.

Das Release Notes-Dokument wird aktualisiert, wenn neue Informationen zur Verwendung der AIX Host Utilities verfügbar sind.



== Informationen über die AIX Host Utilities 6.1 Version

Mit den AIX Host Utilities können Sie einen AIX Host mit NetApp Storage verbinden. Die AIX Host Utilities unterstützen mehrere Umgebungen sowie die Protokolle FC, FCoE und iSCSI. Bei den unterstützten Umgebungen handelt es sich um AIX MPIO (Native OS) und PowerVM.

[NOTE]
====
Informationen zu den von Host Utilities unterstützten Betriebssystemversionen und Updates finden Sie im link:https://mysupport.netapp.com/matrix/imt.jsp?components=85803;&solution=1&isHWU&src=IMT["NetApp Interoperabilitäts-Matrix-Tool"^].

Weitere Informationen zur PowerVM-Funktion finden Sie im IBM PowerVM Live Partition Mobility Red Book.

====
Die Host Utilities-Software wird als einzelne, komprimierte Datei verpackt. Sie können die komprimierte Datei und die Dokumentation vom herunterladen link:https://mysupport.netapp.com/site/["NetApp Support Website"^]. Die ONTAP-SAN-Host-Konfiguration enthält Anweisungen zur Installation und Einrichtung der Host Utilities für die Verwendung mit Ihrer Umgebung und Ihrem Protokoll.


NOTE: Sie müssen das dynamische Tracking für alle FC- und FCoE-Initiatoren für Clustered Data ONTAP-Implementierungen aktivieren.



== VERBESSERUNGEN VON AIX Host Utilities 6.1

* AIX Host Utilities 6.1 bietet zusätzliche Unterstützung für das Problem mit Speicherfehler, das in früheren Versionen von AIX Host OS aufgetreten ist. Mit AIX Host Utilities 6.1 hat sich nur die sanlun-Binärdatei geändert. Die MPIO- und die zugehörige ODM bleiben unverändert.




== Problem Behoben

[cols="3"]
|===
| BUGID | Titel | Beschreibung 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/872113["872113"^] | `sanlun lun show –p` Befehl kann bei einigen Versionen des AIX Host OS einen Speicherfehler verursachen | Intermittierende Instanzen von AIX coredump werden während der Ausführung des gemeldet `sanlun lun show -p` Befehl. Sanlun’s `lun show -p` Option bietet Multipathing-Informationen für alle LUNs, die auf einem Host ermittelt wurden. Er ordnet die Informationen an, welches SCSI-Gerät von welcher LUN, dem Pfadstatus (primäres oder sekundäres) sowie weiteren Details stammt. Auf einigen AIX Hosts jedoch läuft die `sanlun lun show -p` Befehl kann einen Speicherfehler verursachen. Dieses Problem wird nur beobachtet, wenn Sie den Befehl sanlun mit dem ausführen `-p` Option. 
|===


== Bekannte Probleme und Einschränkungen

Um die Host Utilities effizient zu nutzen, sollten Sie beachten, dass die Performance durch bekannte Probleme bei einer bestimmten Funktion, wie z. B. einem Netzwerk, oder durch Funktionen beeinträchtigt werden kann, die die Host Utilities nicht unterstützen, z. B. eine bestimmte Version eines Betriebssystems.

[cols="3"]
|===
| Fehler-ID | Titel | Beschreibung 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1069147["1069147"^] | AIX HU Sanlun meldet eine falsche HBA-Geschwindigkeit | Instanzen von Sanlun mit falschen HBA-Geschwindigkeiten werden während der Ausführung von gemeldet `sanlun fcp show adapter –v` Befehl. Der `sanlun fcp show adapter –v` Mit dem Befehl werden die HBA-Karten-Informationen angezeigt, z. B. die unterstützten und vereinbarten Geschwindigkeiten für die Adapter. Dies scheint nur ein Problem der Berichterstattung zu sein. Um die tatsächliche Geschwindigkeit zu bestimmen, verwenden Sie den `fcstat fcsx` Befehl. 
|===
link:https://mysupport.netapp.com/site/["NetApp Bugs Online"] Bietet vollständige Informationen für die meisten bekannten Probleme, einschließlich Lösungsvorschläge, falls möglich. Einige Schlüsselwortkombinationen und Fehlertypen, die Sie möglicherweise verwenden möchten, sind:

* FCP Allgemein: Zeigt FC- und HBA-Fehler an, die nicht mit einem bestimmten Host verknüpft sind.
* FCP – AIX




== Über die Dokumentation der SAN-Host-Konfiguration

Die Dokumentation für SAN Host Utilities ist im enthalten link:https://docs.netapp.com/us-en/ontap-sanhost/index.html["ONTAP SAN-Host-Konfiguration"] Dokumentation. Die Dokumentation der ONTAP SAN-HOST-Konfiguration ist kumulativ und deckt alle aktuellen SAN-HOST-Versionen ab. Funktionsunterschiede zwischen Releases werden im Kontext festgehalten.



== Hier finden Sie Produktdokumentation und andere Informationen

Sie können auf die Dokumentation für alle NetApp Produkte zugreifen und weitere Ressourcen zu Produktinformationen, wie z. B. technische Berichte und Whitepaper, auf der Seite mit der Produktdokumentation auf der NetApp Website zugreifen.

.Verwandte Informationen
*Konfigurieren und Verwalten Ihres ONTAP Storage-Systems*

* Der link:https://docs.netapp.com/us-en/ontap/setup-upgrade/index.html["ONTAP Software-Setup-Leitfaden"^] Für Ihre Version von ONTAP
* Der link:https://docs.netapp.com/us-en/ontap/san-management/index.html["ONTAP – San-Administration Guide"^] Für Ihre Version von ONTAP
* Der link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["Versionshinweise zu ONTAP"^] Für Ihre Version von ONTAP
* link:https://imt.netapp.com/matrix/#welcome["NetApp Interoperabilitätsmatrix"^]
* link:https://hwu.netapp.com/["Hardware Universe"^] (Ehemals System Configuration Guide)
* link:https://docs.netapp.com/us-en/ontap-sanhost/index.html["Unterstützte Fibre Channel-SAN-Topologien"^]
* link:https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61343["Konfigurieren des Hosts für Host Utilities"^]

