---
sidebar: sidebar 
permalink: hu_aix_72_sanbooting_aix.html 
keywords: host utilities, aix, netapp, ontap, configure, discover, configuring, discovering 
summary: Beschreibt, wie LUNS mit AIX gefunden und konfiguriert werden können 
---
= (AIX MPIO ohne PowerVM) ermitteln und konfigurieren Sie LUNs mit AIX
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn Sie AIX ohne PowerVM verwenden, können Sie den Befehl ausführen `cfgmgr`, damit der Host die LUNs erkennen kann. Sie müssen den Host nicht neu starten, um die LUNs zu ermitteln. Um zu bestätigen, dass der Host die LUNS erkannt hat, können Sie das Dienstprogramm sanlun verwenden.


NOTE: Die folgenden Schritte gelten nicht für einen Host, auf dem eine PowerVM-Umgebung ausgeführt wird.

.Schritte
. Melden Sie sich als Root auf dem Host an.
. Ermitteln Sie auf dem AIX-Host die neu erstellten LUNs:
+
[source, cli]
----
cfgmgr
----
+
Der `cfgmgr` Befehl unterstützt folgende Bereiche:

+
** Die Initiatoren, die sich bei der Fabric anmelden sollen.
** Das System, das auf neue Geräte überprüft werden soll.
** Das System zum Erstellen neuer Geräteeinträge.


. Alle AIX-Laufwerke anzeigen, einschließlich der NetApp-LUNs:
+
[source, cli]
----
lsdev -Cc disk
----
+
Die LUNs werden auf dem Host als Festplatten angezeigt. Sie können diese Festplatten auf die gleiche Weise verwenden, wie Sie lokale Festplatten auf dem Host. Die ODM-Datei mit den Host-Einstellungen, die im Rahmen der Host Utilities installiert ist, führt dazu, dass die LUNs als NetApp FCP-Festplatten angezeigt werden.

+
Notieren Sie sich die hdisk-Instanznummern. Sie verwenden sie, wenn Sie die Pfadkonfiguration durchführen.

+
Im folgenden Beispiel wird die Befehlsausgabe in einer FC-Umgebung angezeigt `lsdev -Cc disk`.

+
.Beispielausgabe anzeigen
[%collapsible]
====
[listing]
----
# lsdev -Cc disk
hdisk0 Available 08-08-00-5,0 16 Bit LVD SCSI Disk Drive
hdisk1 Available 08-08-00-8,0 16 Bit LVD SCSI Disk Drive
hdisk2 Available 04-08-02  MPIO NetApp FCP Default PCM Disk
hdisk3 Available 04-08-02  MPIO NetApp FCP Default PCM Disk
hdisk4 Available 04-08-02  MPIO NetApp FCP Default PCM Disk
hdisk5 Available 04-08-02  MPIO NetApp FCP Default PCM Disk
----
====
. Informationen zu Ihrem Setup abrufen:
+
[source, cli]
----
lsattr -El hdisk_name
----
+
.Beispielausgabe anzeigen
[%collapsible]
====
[listing]
----
# lsattr -El hdisk65
PCM   PCM/friend/NetApp   PCM Path Control Module          False
PR_key_value    none                             Persistant Reserve Key Value            True
algorithm       round_robin                      Algorithm                               True
clr_q           no                               Device CLEARS its Queue on error        True
dist_err_pcnt   0                                Distributed Error Sample Time           True
dist_tw_width   50                               Distributed Error Sample Time           True
hcheck_cmd      inquiry                          Health Check Command                    True
hcheck_interval 30                               Health Check Interval                   True
hcheck_mode     nonactive                        Health Check Mode                       True
location                                         Location Label                          True
lun_id          0x2000000000000                  Logical Unit Number ID                  False
lun_reset_spt   yes                              LUN Level Reset                         True
max_transfer    0x100000                         Maximum TRANSFER Size                   True
node_name       0x500a0980894ae0e0               FC Node Name                            False
pvid            00067fbad453a1da0000000000000000 Physical volume identifier              False
q_err           yes                              Use QERR bit                            True
q_type          simple                           Queuing TYPE                            True
qfull_dly       2                                Delay in seconds for SCSI TASK SET FULL True
queue_depth     64                               Queue DEPTH                             True
reassign_to     120                              REASSIGN time out value                 True
reserve_policy  no_reserve                       Reserve Policy                          True
rw_timeout      30                               READ/WRITE time out value               True
scsi_id         0xd10001                         SCSI ID                                 False
start_timeout   60                               START unit time out value               True
ww_name         0x500a0984994ae0e0               FC World Wide Name                      False
----
====
. Falls Ihre Konfiguration ALUA unterstützt, können Sie damit die Pfadpriorität festlegen. Vergewissern Sie sich, dass ALUA aktiviert ist:
+
[source, cli]
----
lun igroup show -instance igroup_name
----
+
.. Wenn ALUA nicht aktiviert ist, aktivieren Sie es:
+
[source, cli]
----
igroup set igroup_name alua yes
----


. Wenn Ihre Konfiguration ALUA nicht unterstützt, müssen Sie das Dienstprogramm dotpaths verwenden, um die Pfadprioritäten festzulegen. Das dotpaths-Dienstprogramm wird installiert, wenn Sie die Host Utilities installieren. Verwenden Sie das Dienstprogramm dotpaths nicht, wenn ALUA aktiviert ist.
+
.. Legen Sie die Priorität für alle ONTAP LUNs fest:
+
[source, cli]
----
dotpaths
----
.. Legen Sie die Priorität für einen bestimmten Festplattensatz fest:
+
[source, cli]
----
dotpaths [-hqv] [hdiskN ...]
----
+
Verwenden Sie die `-v` Option, um den ausführlichen Modus zu aktivieren und alle Prioritäten anzuzeigen. Verwenden Sie die `-q` Option, um alle oder einzelne Festplattenprioritäten abzufragen.



. Überprüfen Sie, ob der Host die LUNs erkannt hat:
+
[source, cli]
----
sanlun lun show
----
+
Im folgenden Beispiel wird die typische Ausgabe des Befehls in einer Microsoft Multipath I/O (MPIO) Multipathing-Umgebung gezeigt `sanlun lun show`:

+
.Beispielausgabe anzeigen
[%collapsible]
====
[listing]
----
sanlun lun show -p

                    ONTAP Path: fas3170-aix03:/vol/ibmbc_aix01b14_fcp_vol8/ibmbc-aix01b14_fcp_lun0
                           LUN: 8
                      LUN Size: 3g
           Controller CF State: Cluster Enabled
            Controller Partner: fas3170-aix04
                   Host Device: hdisk9
                          Mode: 7
            Multipath Provider: AIX Native
        Multipathing Algorithm: round_robin
--------- ----------- ------ ------- ---------------------------------------------- ----------
host      controller  AIX            controller                                     AIX MPIO
path      path        MPIO   host    target                                         path
state     type        path   adapter port                                           priority
--------- ----------- ------ ------- ---------------------------------------------- ----------
up        secondary   path0  fcs0    3b                                             1
up        primary     path1  fcs0    3a                                             1
up        secondary   path2  fcs0    3a                                             1
up        primary     path3  fcs0    3b                                             1
up        secondary   path4  fcs0    4b                                             1
up        secondary   path5  fcs0    4a                                             1
up        primary     path6  fcs0    4b                                             1
up        primary     path7  fcs0    4a                                             1
up        secondary   path8  fcs1    3b                                             1
up        primary     path9  fcs1    3a                                             1
up        secondary   path10 fcs1    3a                                             1
up        primary     path11 fcs1    3b                                             1
up        secondary   path12 fcs1    4b                                             1
up        secondary   path13 fcs1    4a                                             1
up        primary     path14 fcs1    4b                                             1
up        primary     path15 fcs1    4a                                             1
----
====

