---
sidebar: sidebar 
permalink: hu_aix_61.html 
keywords: host utilities, aix, powervm, vios, 3.1, 7.2 netapp, ontap 
summary: Beschreibt die Verwendung von IBM AIX 7.2 und/oder PowerVM VIOS 3.1 mit ONTAP 
---
= AIX Host Utilitys 6.1
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Die AIX Unified Host Utilities unterstützen Sie beim Management von NetApp ONTAP-Speicher mit Anbindung an einen AIX-Host.



== SAN Toolkit

AIX Host Utilities ist eine NetApp Host Software, die ein Befehlszeilen-Tool Kit auf Ihrem IBM AIX Host bereitstellt. Das Toolkit wird bei der Installation des NetApp Host Utilities-Pakets installiert. Dieses Kit enthält die `sanlun` Dienstprogramm: Unterstützt Sie beim Management von LUNs und HBAs. Der `sanlun` Befehl gibt Informationen über die LUNs zurück, die Ihrem Host zugeordnet sind, Multipathing und Informationen zurück, die zum Erstellen von Initiatorgruppen erforderlich sind.

*Beispiel*

Im folgenden Beispiel wird der verwendet `sanlun lun show` Mit dem Befehl werden die LUN-Informationen zurückgegeben.

[listing]
----
#sanlun lun show all

controller(7mode)/ device host lun

vserver(Cmode) lun-pathname filename adapter protocol size mode
----------------------------------------------------------------
data_vserver   /vol/vol1/lun1 hdisk0 fcs0    FCP      60g C
data_vserver   /vol/vol2/lun2 hdisk0 fcs0    FCP      20g C
data_vserver   /vol/vol3/lun3 hdisk11 fcs0   FCP      20g C
data_vserver   /vol/vol4/lun4 hdisk14 fcs0   FCP      20g C
----

NOTE: Dieses Toolkit ist für alle Konfigurationen und Protokolle der Host Utilities üblich. Als Ergebnis gelten einige ihrer Inhalte auf eine Konfiguration, jedoch nicht auf eine andere. Ungenutzte Komponenten haben keine Auswirkungen auf die Systemleistung.


NOTE: Das SAN Toolkit wird auf den Versionen AIX und PowerVM/VIOS unterstützt.



== Installieren Sie AIX Host Utilities

Das Software-Paket NetApp AIX Host Utilities finden Sie auf der https://mysupport.netapp.com/NOW/cgi-bin/software/?product=Host%2BUtilities%2B-%2BSAN&platform=Linux["NetApp Support Website"^] In einer komprimierten Datei von tar.gz.

Sie müssen das AIX ONTAP Utilities Kit bei der Verwendung von AIX MPIO mit NetApp Storage installieren.

Sie können die komprimierte Datei mit den Host Utilities Softwarepaketen von der NetApp Support-Website herunterladen. Nachdem Sie die Datei heruntergeladen haben, müssen Sie sie dekomprimieren, um die beiden Softwarepakete zu erhalten, die Sie benötigen, um die Host Utilities zu installieren.

*Schritte*

. Melden Sie sich bei Ihrem Host an.
+
** Melden Sie sich auf einem AIX-Host als *root* an.
** Melden Sie sich auf einem PowerVM-Host als *padmin* an, und geben Sie dann den oem_Setup_env-Befehl ein, um Root zu werden.


. Laden Sie eine Kopie der komprimierten Datei mit den Host Utilities von der NetApp Support Site in ein Verzeichnis auf Ihrem Host herunter.
. Gehen Sie zu dem Verzeichnis, in dem der Download enthalten ist.
. Dekomprimieren Sie die Datei und extrahieren Sie das SAN Toolkit Softwarepaket.
+
`tar -xvf ntap_aix_host_utilities_6.1.tar.gz`

+
Das folgende Verzeichnis wird beim Dekomprimieren der Datei erstellt: `ntap_aix_host_utilities_6.1`. Dieses Verzeichnis verfügt über eines der folgenden Unterverzeichnisse: MPIO, NON_MPIO oder SAN_Tool_Kit.

. Installieren Sie AIX MPIO:
+
`installp -aXYd /var/tmp/ntap_aix_host_utilities_6.1/MPIO NetApp.MPIO_Host_Utilities_Kit`

. Installieren Sie das SAN Toolkit:
+
`installp -aXYd /var/tmp/ntap_aix_host_utilities_6.1/SAN_Tool_Kit NetApp.SAN_toolkit`

. Starten Sie den Host neu.
. Überprüfen Sie die Installation:
+
`sanlun version`


