---
sidebar: sidebar 
permalink: hu_aix_72_sanbooting_powervm_vscsi.html 
keywords: host utilities, aix, powervm, 7.2 netapp, ontap, luns, configure, discover, configuring, discovering 
summary: Beschreibt die Verwendung von Discover and Configure LUNs mit PowerVM vSCSI 
---
= (PowerVM vSCSI) Erkennen und Konfigurieren von LUNs
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn Sie PowerVM vSCSI- und VIO-Server verwenden, müssen Sie zum Konfigurieren und Erkennen von LUNs die padmin-Anmeldung und die entsprechenden Befehle verwenden.

.Schritte
. Melden Sie sich als padmin beim Host an.
. Geben Sie auf dem AIX-Host den folgenden Befehl ein, um die neu erstellten LUNs zu ermitteln:
+
`cfgdev`

+
Der Befehl cfgdev führt zu folgenden Ursachen:

+
** Die Initiatoren, die sich bei der Fabric anmelden sollen.
** Das System, das auf neue Geräte überprüft werden soll.
** Das System erstellt neue Geräteeinträge, bei denen die neuen LUNs über das Standard-PCM als MPIO-Geräte zugeordnet werden.


. Geben Sie den folgenden Befehl ein, um zu überprüfen, ob die hdisk MPIO-Geräte erstellt wurden:
+
`lsdev -type disk`

+
Die LUNs werden auf dem Host als Festplatten angezeigt. Sie können diese Festplatten auf die gleiche Weise verwenden, wie Sie lokale Festplatten auf dem Host.

+
Notieren Sie sich die hdisk-Instanznummern. Sie verwenden sie, wenn Sie die Pfadkonfiguration durchführen.

+
Der `lsdev -type disk` Befehl gibt den folgenden Ausgabetyp aus. Die Ausgabe im folgenden Beispiel ist abgeschnitten.

+
[listing]
----
vioserver$ lsdev -type disk NetApp
name     status      description
hdisk0   Available   16 Bit LVD SCSI Disk Drive
hdisk1   Available   16 Bit LVD SCSI Disk Drive
hdisk2   Available   MPIO NetApp FCP Default PCM Disk
hdisk3   Available   MPIO NetApp FCP Default PCM Disk
hdisk4   Available   MPIO NetApp FCP Default PCM Disk
hdisk5   Available   MPIO NetApp FCP Default PCM Disk
hdisk6   Available   MPIO NetApp FCP Default PCM Disk
----
. Geben Sie den folgenden Befehl ein, um Informationen über das Setup zu erhalten:
+
`lsdev -dev hdisk_name -attr`

+
Der `lsdev -dev hdisk_name -attr` Der Befehl erzeugt die folgende Ausgabe:

+
[listing]
----
vioserver$ lsdev -dev hdisk2 -attr
attribute value                   description                user-settable
PCM   PCM/friend/NetApp   PCM Path Control Module          False
PR_key_value    none                             Persistent Reserve Key Value            True
algorithm       round_robin                      Algorithm                               True
clr_q           no                               Device CLEARS its Queue on error        True
dist_err_pcnt   0                                Distributed Error Sample Time           True
dist_tw_width   50                               Distributed Error Sample Time           True
hcheck_cmd      inquiry                          Health Check Command                    True
hcheck_interval 30                               Health Check Interval                   True
hcheck_mode     nonactive                        Health Check Mode                       True
location                                         Location Label                          True
lun_id          0x2000000000000                  Logical Unit Number ID                  False
lun_reset_spt   yes                              LUN Level Reset                         True
max_transfer    0x100000                         Maximum TRANSFER Size                   True
node_name       0x500a0980894ae0e0               FC Node Name                            False
pvid            00067fbad453a1da0000000000000000 Physical volume identifier              False
q_err           yes                              Use QERR bit                            True
q_type          simple                           Queuing TYPE                            True
qfull_dly       2                                Delay in seconds for SCSI TASK SET FULL True
queue_depth     64                               Queue DEPTH                             True
reassign_to     120                              REASSIGN time out value                 True
reserve_policy  no_reserve                       Reserve Policy                          True
rw_timeout      30                               READ/WRITE time out value               True
scsi_id         0xd10001                         SCSI ID                                 False
start_timeout   60                               START unit time out value               True
ww_name         0x500a0984994ae0e0               FC World Wide Name                      False
----
. Wenn Ihre Konfiguration ALUA nicht unterstützt, müssen Sie das Dienstprogramm dotphs ausführen, um die Pfadprioritäten festzulegen. Das dotpaths-Dienstprogramm wird installiert, wenn Sie die Host Utilities installieren. Verwenden Sie das dotpaths-Dienstprogramm nicht, wenn ALUA aktiviert ist. Wechseln Sie zum `oem_setup_env` Modus zum Ausführen der Dotpathhs durch Eingabe des folgenden Befehls:
+
`oem_setup_env`

+
Wenn Sie das eingeben `oem_setup_env` Im Modus ändert sich die Eingabeaufforderung der Befehlszeile von einem Dollar-Zeichen zu einem Pfund-Zeichen, und Sie bleiben in `oem_setup_env` Modus bis zum Anhalten des Befehls geben Sie einen Befehl wie exit ein.

+
.Beispiel
``# vioserver$ oem_setup_env`

. Falls Ihre Konfiguration ALUA unterstützt, können Sie damit die Pfadpriorität festlegen. Vergewissern Sie sich, dass ALUA aktiviert ist:
+
`lun igroup show -instance igroup_name`

+
.. Wenn ALUA nicht aktiviert ist, aktivieren Sie es:
+
`igroup set igroup_name alua yes`



. Wenn Ihre Konfiguration ALUA nicht unterstützt, müssen Sie das Dienstprogramm dotphs ausführen, um die Pfadprioritäten festzulegen. Das dotpaths-Dienstprogramm wird installiert, wenn Sie die Host Utilities installieren. Verwenden Sie das dotpaths-Dienstprogramm nicht, wenn ALUA aktiviert ist.
+
.. Um die Priorität für alle Data ONTAP LUNs festzulegen, geben Sie Folgendes ein:
+
`dotpaths`

.. So legen Sie die Priorität für einen bestimmten Festplattensatz fest:
+
`dotpaths [-hqv] [hdiskN ...]`

+
Verwenden Sie die `-v` Option zum Aktivieren des ausführlichen Modus und zur Anzeige aller Prioritäten. Verwenden Sie die `-q` Option, um alle oder einzelne Festplattenprioritäten abzufragen.

+
Das folgende Beispiel zeigt die Verwendung des Dienstprogramms dotpaths:

+
[listing]
----
vioserver# dotpaths -v
hdisk2 (path 0): Optimized path - Setting priority to 255
hdisk2 (path 1): Optimized path - Setting priority to 255
hdisk2 (path 2): Unoptimized path - Current priority of 1 is correct
hdisk2 (path 3): Unoptimized path - Current priority of 1 is correct
...
Path priority set and/or verified for 22 disks, 86 total paths.
vioserver#
----


. Geben Sie den folgenden Befehl ein, um zu überprüfen, ob der Host die LUNs erkannt hat:
+
`# sanlun lun show -p`

+
.Beispiel
Dieses Beispiel zeigt die typische Ausgabe des `sanlun lun show -p` Befehl für eine Direct-Attached-Konfiguration. Es schließt auch die ein `sanlun lun show -d hdisk9 -v` Befehl zum Anzeigen von Informationen über hdisk9. Die Ausgabe dieses Befehls wurde abgeschnitten.

+
[listing]
----
sanlun lun show -p

                    ONTAP Path: fas3170-aix03:/vol/ibmbc_aix01b14_fcp_vol8/ibmbc-aix01b14_fcp_lun0
                           LUN: 8
                      LUN Size: 3g
           Controller CF State: Cluster Enabled
            Controller Partner: fas3170-aix04
                   Host Device: hdisk9
                          Mode: 7
            Multipath Provider: AIX Native
        Multipathing Algorithm: round_robin
--------- ----------- ------ ------- ------------- ----------
host      controller  AIX            controller    AIX MPIO
path      path        MPIO   host    target        path
state     type        path   adapter port          priority
--------- ----------- ------ ------- ------------- ----------
up        secondary   path0  fcs0    3b              1
up        primary     path1  fcs0    3a              1
up        secondary   path2  fcs0    3a              1
up        primary     path3  fcs0    3b              1
up        secondary   path4  fcs0    4b              1
up        secondary   path5  fcs0    4a              1
up        primary     path6  fcs0    4b              1
up        primary     path7  fcs0    4a              1
up        secondary   path8  fcs1    3b              1
up        primary     path9  fcs1    3a              1
up        secondary   path10 fcs1    3a              1
up        primary     path11 fcs1    3b              1
up        secondary   path12 fcs1    4b              1
up        secondary   path13 fcs1    4a              1
up        primary     path14 fcs1    4b              1
up        primary     path15 fcs1    4a              1
----
+
[listing]
----
sanlun lun show -vd hdisk10
                                                                      device          host                  lun
vserver              lun-pathname                                     filename        adapter    protocol   size    mode
------------------------------------------------------------------------------------------------------------------------
GPFS_p520_FC         /vol/GPFS_p520_FC_FlexVol_2/GPFS_p520_FC_LUN_2_4 hdisk10         fcs3       FCP        100g    C
             LUN Serial number: 1k/yM$-ia5HC
         Controller Model Name: N5600
          Vserver FCP nodename: 200200a0980c892f
          Vserver FCP portname: 200a00a0980c892f
              Vserver LIF name: GPFS_p520_FC_2
            Vserver IP address: 10.225.121.100
           Vserver volume name: GPFS_p520_FC_FlexVol_2  MSID::0x00000000000000000000000080000420
         Vserver snapshot name:
----

