---
sidebar: sidebar 
permalink: hu_citrix_8x.html 
keywords: host utilities, citrix, hypervisor, 8.0, 8.1, 8.2, netapp, ontap, sanhost 
summary: Beschreibung der Verwendung von Citrix Hypervisor 8.x mit ONTAP 
---
= Verwenden Sie Citrix Hypervisor mit ONTAP
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content




== Einführung

Dieses Dokument enthält eine Anleitung zu den Host-Konfigurationseinstellungen des ONTAP-SAN für die Betriebssystemversionen der Citrix Hypervisor 8 Serie mit FC-, FCoE- und iSCSI-Protokollen.



== SAN wird gebootet

.Was Sie benötigen
Wenn Sie sich für das Booten über SAN entscheiden, muss es von Ihrer Konfiguration unterstützt werden. Sie können das verwenden link:https://mysupport.netapp.com/matrix/imt.jsp?components=91241;&solution=236&isHWU&src=IMT["NetApp Interoperabilitäts-Matrix-Tool"^] Um zu überprüfen, ob Ihr Betriebssystem, HBA, die HBA-Firmware und das HBA-Boot-BIOS sowie die ONTAP-Version unterstützt werden.

.Schritte
. Ordnen Sie die SAN-Boot-LUN dem Host zu.
. Vergewissern Sie sich, dass mehrere Pfade verfügbar sind.
+

NOTE: Mehrere Pfade sind verfügbar, nachdem das Host-Betriebssystem auf den Pfaden ausgeführt wurde.

. Aktivieren Sie das SAN-Booten im Server-BIOS für die Ports, denen die SAN-Boot-LUN zugeordnet ist.
+
Informationen zum Aktivieren des HBA-BIOS finden Sie in der anbieterspezifischen Dokumentation.

. Starten Sie den Host neu, um zu überprüfen, ob der Startvorgang erfolgreich war.




== Multipathing

Für Citrix Hypervisor (CH) 8.x der `/etc/multipath.conf` Die Datei muss vorhanden sein, Sie müssen jedoch keine spezifischen Änderungen an der Datei vornehmen. CH 8.x wird mit allen Einstellungen zusammengestellt, die zum Erkennen und korrekten Managen von ONTAP LUNs erforderlich sind. Sie können das verwenden `/sbin/mpathutil` Status Befehl zum Überprüfen der Einstellungen für Ihre ONTAP-LUNs. Die folgenden Abschnitte enthalten ein Beispiel für eine Multipath-Ausgabe für eine LUN, die ASA-Personas zugeordnet ist.



=== Konfiguration von All-SAN-Arrays (ASA

Für die gesamte SAN Array-(ASA-)Konfiguration sollte eine Gruppe von Pfaden mit einzelnen Prioritäten vorhanden sein. Alle Pfade sind aktiv/optimiert, was bedeutet, dass sie vom Controller gewartet werden und I/O wird an alle aktiven Pfade gesendet.

.Beispiel
Im folgenden Beispiel wird die richtige Ausgabe für eine ONTAP-LUN mit vier aktiv/optimierten Pfaden angezeigt:

....
# mpathutil status
3600a09803830344674244a357579386a dm-13 NETAPP  ,LUN C-Mode
size=30G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
policy='service-time 0' prio=50 status=active
  |- 11:0:7:1    sdfi   130:64   active ready running
  |- 11:0:9:1    sdiy  8:288     active ready running
  |- 11:0:10:1  sdml 69:464   active ready running
  |- 11:0:11:1  sdpt  131:304  active ready running
....

NOTE: Verwenden Sie keine unverhältnismäßig hohe Anzahl von Pfaden zu einer einzelnen LUN. Es sollten nicht mehr als 4 Pfade erforderlich sein. Mehr als 8 Pfade können bei Storage-Ausfällen zu Pfadproblemen führen.



=== Nicht-ASA-Konfiguration

Für eine nicht-ASA-Konfiguration sollte es zwei Gruppen von Pfaden mit unterschiedlichen Prioritäten geben. Die Pfade mit den höheren Prioritäten sind aktiv/optimiert, was bedeutet, dass sie vom Controller gewartet werden, wo sich das Aggregat befindet. Die Pfade mit den niedrigeren Prioritäten sind aktiv, werden aber nicht optimiert, da sie von einem anderen Controller bereitgestellt werden. Die nicht optimierten Pfade werden nur verwendet, wenn keine optimierten Pfade verfügbar sind.

.Beispiel
Im folgenden Beispiel wird die richtige Ausgabe für eine ONTAP-LUN mit zwei aktiv/optimierten Pfaden und zwei aktiv/nicht optimierten Pfaden angezeigt:

....
# mpathutil status
3600a09803830344674244a357579386a dm-13 NETAPP  ,LUN C-Mode
size=30G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
 |- 1:0:0:11   sde   8:64    active ready running
`- 12:0:8:11  sdua  66:544  active ready running
`-+- policy='service-time 0' prio=10 status=enabled
   |- 1:0:9:11   sddo  71:96   active ready running
   `- 12:0:26:11 sdyt  129:720 active ready running
....

NOTE: Verwenden Sie keine unverhältnismäßig hohe Anzahl von Pfaden zu einer einzelnen LUN. Es sollten nicht mehr als vier Pfade erforderlich sein. Mehr als acht Pfade können bei Storage-Ausfällen zu Pfadproblemen führen.



== Empfohlene Einstellungen

Das Betriebssystem Citrix Hypervisor 8.x wird mit allen Einstellungen kompiliert, die erforderlich sind, um ONTAP-LUNs zu erkennen und richtig zu verwalten. Für Citrix Hypervisor 8.x, eine leere Nullen `/etc/multipath.conf` Die Datei muss vorhanden sein, Sie müssen jedoch keine spezifischen Änderungen an der Datei vornehmen.

Aktivieren Sie den Host Multipath Service über das *XenCenter Management Portal* und überprüfen Sie, ob der Multipath-Dienst aktiviert ist und ausgeführt wird.

[listing]
----
# systemct1 status multipathd
multipathd.service - Device-Mapper Multipath Device Controller
  Loaded:  load (/usr/lib/systemd/system/multipathd.service; enabled; vendor preset: enabled)
 Drop-In:  /etc/systemd/system/multipathd.service.d
             slice.config
  Active:  active (running) since Fri YYYY-MM-DD 00:00:26 IST; 1 month 9 days ago
Main PID:  3789 (multipathd)
  CGroup:  /control.slice/multipathd.service
            3789  /sbin/multipathd
----
Es besteht keine Anforderung, dem Inhalt hinzuzufügen `/etc/multipath.conf` Datei, es sei denn, Sie haben Geräte, die Sie nicht von Multipath verwalten möchten, oder Sie haben bereits vorhandene Einstellungen, die die Standardeinstellungen überschreiben. Sie können der Multipath.conf-Datei die folgende Syntax hinzufügen, um unerwünschte Geräte auszuschließen.

[listing]
----
# cat /etc/multipath.conf
blacklist {
     wwid    <DevId>
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----

NOTE: Ersetzen Sie *<Devid>* durch die WWID-Zeichenfolge des Geräts, das Sie ausschließen möchten.

.Beispiel
In diesem Beispiel für Citrix Hypervisor 8.x, `sda` Ist die lokale SCSI Festplatte, die wir zur Blacklist hinzufügen müssen.

. Führen Sie den folgenden Befehl aus, um die WWID zu bestimmen:
+
[listing]
----
# lib/udev/scsi_id -gud /dev/sda
3600a098038303458772450714535317a
----
. Fügen Sie diese WWID der schwarzen Liste Stanza im hinzu `/etc/multipath.conf`:
+
[listing]
----
#cat /etc/multipath.conf
blacklist {
  wwid    3600a098038303458772450714535317a
  devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9*]"
  devnode "^hd[a-z]"
  devnode "^cciss.*"
}
----


Beachten Sie die Laufzeitkonfiguration des Multipath-Parameters mithilfe des `$multipathd show config` Befehl. Sie sollten die ausgeführte Konfiguration immer auf ältere Einstellungen überprüfen, die möglicherweise die Standardeinstellungen überschreiben, insbesondere im Abschnitt „Standardeinstellungen“.

Die folgende Tabelle zeigt die kritischen *multipathd* Parameter für ONTAP LUNs und die erforderlichen Werte. Wenn ein Host mit LUNs von anderen Anbietern verbunden ist und einer dieser Parameter außer Kraft gesetzt wird, müssen sie später in *Multipath.conf* korrigiert werden, die sich speziell auf ONTAP LUNs beziehen. Wenn dies nicht ausgeführt wird, funktionieren die ONTAP LUNs möglicherweise nicht wie erwartet. Die folgenden Standardeinstellungen sollten nur in Absprache mit NetApp und/oder dem OS-Anbieter außer Kraft gesetzt werden und nur dann, wenn die Auswirkungen vollständig verstanden wurden.

[cols="2*"]
|===
| Parameter | Einstellung 


| `detect_prio` | ja 


| `dev_loss_tmo` | „Unendlich“ 


| `failback` | Sofort 


| `fast_io_fail_tmo` | 5 


| `features` | „3 queue_if_no_Pg_init_retries 50“ 


| `flush_on_last_del` | „ja“ 


| `hardware_handler` | „0“ 


| `path_checker` | „nur“ 


| `path_grouping_policy` | „Group_by_prio“ 


| `path_selector` | „Servicezeit 0“ 


| `polling_interval` | 5 


| `prio` | ONTAP 


| `product` | LUN.* 


| `retain_attached_hw_handler` | ja 


| `rr_weight` | „Einheitlich“ 


| `user_friendly_names` | Nein 


| `vendor` | NETAPP 
|===
.Beispiel
Das folgende Beispiel zeigt, wie eine überhielte Standardeinstellung korrigiert wird. In diesem Fall definiert die Datei *Multipath.conf* Werte für *path_Checker* und *detect_prio*, die nicht mit ONTAP LUNs kompatibel sind. Wenn sie nicht entfernt werden können, weil andere SAN-Arrays an den Host angeschlossen sind, können diese Parameter speziell für ONTAP-LUNs mit einem Gerätstanza korrigiert werden.

[listing]
----
# cat /etc/multipath.conf
defaults {
  path_checker readsector0
  detect_prio no
}
devices{
        device{
                vendor "NETAPP "
                product "LUN.*"
                path_checker tur
                detect_prio yes
        }
}
----

NOTE: Der Citrix Hypervisor empfiehlt die Nutzung von Citrix VM Tools für alle Gast-VMs unter Linux und Windows, um eine unterstützte Konfiguration zu erhalten.



== Bekannte Probleme und Einschränkungen

[cols="4*"]
|===
| NetApp Bug ID | Titel | Beschreibung | Citrix Tracker-ID 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1242343["1242343"^] | Kernel-Unterbrechung auf Citrix Hypervisor 8.0 mit QLogic QLE2742 32 GB FC während eines Storage Failover-Betriebs | Kernel-Störungen können bei Storage Failover-Vorgängen auf Citrix Hypervisor 8.0 Kernel (4.19.0+1) mit QLogic QLE2742 32 GB HBA auftreten. Dieses Problem fordert einen Neustart des Betriebssystems auf und verursacht Anwendungsunterbrechungen. Wenn kdump konfiguriert ist, generiert die Kernel-Störung eine vmcore-Datei im Verzeichnis /var/crash/. Sie können die Ursache des Fehlers in der vmcore-Datei ermitteln. Nach einer Störung des Kernels können Sie das Betriebssystem wiederherstellen, indem Sie das Host-Betriebssystem neu starten und die Anwendung neu starten. | link:https://tracker.citrix.com/browse/NETAPP-98["NETAPP-98"^] 
|===