---
sidebar: sidebar 
permalink: hu_hpux_60.html 
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap 
summary: Beschreibt die Verwendung der HP-UX Host Utilities 6.0 mit ONTAP-Speicher 
---
= Installieren Sie HP-UX Host Utilities 6.0 für ONTAP-Speicher
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die HP-UX Host Utilities unterstützen Sie bei der Verwaltung des an einen HP-UX-Host angeschlossenen ONTAP Speichers.  NetApp empfiehlt dringend die Installation der HP-UX Host Utilities, dies ist jedoch nicht zwingend erforderlich.  Die Dienstprogramme verbessern die Verwaltung und unterstützen den NetApp Kundensupport beim Sammeln von Informationen zu Ihrer Konfiguration.

Die HP-UX Host Utilities unterstützen die folgenden Umgebungen:

* Native Microsoft Multipath-I/O (MPIO)
* Veritas Dynamic Multipathing (DMP)


.Bevor Sie beginnen
Für einen zuverlässigen Betrieb verwenden Sie die https://imt.netapp.com/matrix/#welcome["Interoperabilitäts-Matrix-Tool"^] um zu überprüfen, ob Ihre iSCSI-, FC- oder FCoE-Konfiguration unterstützt wird.

.Schritte
. Melden Sie sich bei Ihrem HP-UX-Host an.
. Laden Sie die Datei HP-UX Host Utilities herunter `netapp_hpux_host_utilities_6.0_ia_pa.depot.gz` Von link:https://mysupport.netapp.com/site/["NetApp Support Website"^] Auf Ihren HP-UX-Host.
. Dekomprimieren Sie die `netapp_hpux_host_utilities_6.0_ia_pa.depot.gz` Datei:
+
[source, cli]
----
gunzip netapp_hpux_host_utilities_6.0_ia_pa.depot.gz
----
+
Das System legt die extrahierte Software in das Verzeichnis, in dem Sie die Depotdatei unkomprimiert haben.

. Installieren der Software:
+
[source, cli]
----
swinstall -s /depot_path
----
+
`depot_path` Gibt den Pfad und den Namen der Depotdatei an.

+
Der `swinstall` Mit dem Befehl wird ein Installationsskript ausgeführt, das den Status des HP-UX-Setups überprüft. Wenn Ihr System die Anforderungen erfüllt, installiert dieses Skript das `sanlun` Dienstprogramme und Diagnoseskripte im `/opt/NetApp/santools/bin` Verzeichnis.

. Überprüfen Sie die Installation:
+
[source, cli]
----
sanlun version
----




== Was kommt als Nächstes?

link:hu-hpux-sanlun-toolkit.html["Erfahren Sie mehr über das SAN Toolkit"] .
