---
sidebar: sidebar 
permalink: hu_hpux_60.html 
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap 
summary: Beschreibt die Verwendung von Linux Unified Host Utilities 7.1 mit ONTAP 
---
= HP-UX Host Utilitys 6.0
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


.Was Sie und#8217;ll benötigen
* Für einen zuverlässigen Betrieb müssen Sie sicherstellen, dass Ihre gesamte iSCSI-, FC- oder FCoE-Konfiguration unterstützt wird.


Sie können das verwenden link:https://mysupport.netapp.com/matrix/imt.jsp?components=71102;&solution=1&isHWU&src=IMT["NetApp Interoperabilitäts-Matrix-Tool"^] Um Ihre Konfiguration zu überprüfen.



== SAN Toolkit

HP-UX Host Utilities ist eine NetApp Host Software, die auf Ihrem HP-UX Host ein Befehlszeilen-Tool Kit enthält. Das Toolkit wird bei der Installation des NetApp Host Utilities-Pakets installiert. Dieses Kit enthält die `sanlun` Dienstprogramm, das Sie beim Management der LUNs und HBAs unterstützt. Der `sanlun` Befehl gibt Informationen über die LUNs zurück, die Ihrem Host zugeordnet sind, Multipathing und Informationen zurück, die zum Erstellen von Initiatorgruppen erforderlich sind.

Im folgenden Beispiel wird der verwendet `sanlun lun show` Mit dem Befehl werden die LUN-Informationen zurückgegeben.

[listing]
----
# sanlun lun show all

controller(7mode)/ device host lun
vserver(Cmode)           lun-pathname                   filename          adapter    protocol   size   mode
------------------------------------------------------------------------------------------------------------
sanboot_unix         /vol/hpux_boot/boot_hpux_lun      /dev/rdsk/c34t0d0  fclp1      FCP        150g    C
sanboot_unix         /vol/hpux_boot/boot_hpux_lun      /dev/rdsk/c23t0d0  fclp1      FCP        150g    C
sanboot_unix         /vol/hpux_boot/boot_hpux_lun      /dev/rdsk/c12t0d0  fclp0      FCP        150g    C
sanboot_unix         /vol/hpux_boot/boot_hpux_lun      /dev/rdsk/c81t0d0  fclp0      FCP        150g    C

----

NOTE: Dieses Toolkit ist für alle Konfigurationen und Protokolle der Host Utilities üblich. Als Ergebnis gelten einige ihrer Inhalte auf eine Konfiguration, jedoch nicht auf eine andere. Ungenutzte Komponenten haben keine Auswirkungen auf die Systemleistung.



== Installieren von HP-UX Host Utilities

Das NetApp HP-UX Host Utilities-Softwarepaket ist auf der erhältlich link:https://mysupport.netapp.com/site/["NetApp Support Website"^] In einer komprimierten Datei.

Sie können die komprimierte Datei mit den Host Utilities Softwarepaketen von herunterladen link:https://mysupport.netapp.com/site/["NetApp Support Website"^]. Nachdem Sie die Datei heruntergeladen haben, müssen Sie sie vor der Installation dekomprimieren.

.Schritte
. Melden Sie sich bei Ihrem Host an.
. Laden Sie die Datei HP-UX Host Utilities herunter `netapp_hpux_host_utilities_6.0_ia_pa.depot.gz` Von link:https://mysupport.netapp.com/site/["NetApp Support Website"^] Auf Ihren HP-UX-Host.
. Dekomprimieren Sie die `netapp_hpux_host_utilities_6.0_ia_pa.depot.gz` Datei durch Eingabe des folgenden Befehls:
+
`# gunzip netapp_hpux_host_utilities_6.0_ia_pa.depot.gz`

+
Das System legt die extrahierte Software in das Verzeichnis, in dem Sie die Depotdatei unkomprimiert haben.

. Installieren Sie die Software mit folgendem Befehl:
+
`# swinstall -s /depot_path`

+
`depot_path` Gibt den Pfad und den Namen der Depotdatei an.

+
Der `swinstall` Mit dem Befehl wird ein Installationsskript ausgeführt, das den Status des HP-UX-Setups überprüft. Wenn Ihr System die Anforderungen erfüllt, installiert dieses Skript das `sanlun` Dienstprogramme und Diagnoseskripte im `/opt/NetApp/santools/bin` Verzeichnis.

. Überprüfen Sie die Installation:
+
`sanlun version`





== Beispielbefehlsverweis



=== Führen Sie alle Host-Initiatoren auf, die dem Host zugeordnet sind

[listing]
----
# sanlun fcp show adapter -v
adapter name:      fclp2
WWPN:              10000000c985ef92
WWNN:              20000000c985ef92
driver name:       fclp
model:             AJ763-63001
model description: HP 8Gb Dual Channel PCI-e 2.0 FC HBA
serial number:     MY19034N9U
hardware version:  3
driver version:    @(#) FCLP: PCIe Fibre Channel driver (FibrChanl-02), B.11.31.1805, Feb  5 2018, FCLP_IFC (3,2)
firmware version:  2.02X2 SLI-3 (U3D2.02X2)
Number of ports:   1 of 2
port type:         Unknown
port state:        Link Down
supported speed:   8 GBit/sec
negotiated speed:  Speed not established
OS device name:    /dev/fclp2

adapter name:      fclp3
WWPN:              10000000c985ef93
WWNN:              20000000c985ef93
driver name:       fclp
model:             AJ763-63001
model description: HP 8Gb Dual Channel PCI-e 2.0 FC HBA
serial number:     MY19034N9U
hardware version:  3
driver version:    @(#) FCLP: PCIe Fibre Channel driver (FibrChanl-02), B.11.31.1805, Feb  5 2018, FCLP_IFC (3,2)
firmware version:  2.02X2 SLI-3 (U3D2.02X2)
Number of ports:   2 of 2
port type:         Unknown
port state:        Link Down
supported speed:   8 GBit/sec
negotiated speed:  Speed not established
OS device name:    /dev/fclp3
----


=== Listen Sie alle LUNs auf, die dem Host zugeordnet sind

[listing]
----
# sanlun lun show -p -v all
\
                    ONTAP Path: vs_hp_cluster:/vol/chathpux_217_vol_en_1_10/hp_en_217_lun
                           LUN: 55
                      LUN Size: 15g
                   Host Device: /dev/rdisk/disk718
                          Mode: C
                            VG: /dev/vg_data
              Multipath Policy: A/A
            Multipath Provider: Native
-------- ---------- -------------------- ------- ---------------------------------------------- -------------
host     vserver    /dev/dsk                                                                    HP A/A
path     path       filename             host    vserver                                        path failover
state    type       or hardware path     adapter LIF                                            priority
-------- ---------- -------------------- ------- ---------------------------------------------- -------------
up       primary    /dev/dsk/c37t6d7     fclp0   hpux_7                                         0
up       primary    /dev/dsk/c22t6d7     fclp1   hpux_8                                         0
up       secondary  /dev/dsk/c36t6d7     fclp0   hpux_5                                         1
up       secondary  /dev/dsk/c44t6d7     fclp1   hpux_6                                         1

----


=== Listen Sie alle LUNs auf, die einem Host von einer bestimmten SVM zugeordnet sind

[listing]
----
# sanlun lun show -p -v vs_hp_cluster
                    ONTAP Path: vs_hp_cluster:/vol/chathpux_217_vol_en_1_10/hp_en_217_lun
                           LUN: 55
                      LUN Size: 15g
                   Host Device: /dev/rdisk/disk718
                          Mode: C
                            VG: /dev/vg_data
              Multipath Policy: A/A
            Multipath Provider: Native
-------- ---------- -------------------- ------- ---------------------------------------------- -------------
host     vserver    /dev/dsk                                                                    HP A/A
path     path       filename             host    vserver                                        path failover
state    type       or hardware path     adapter LIF                                            priority
-------- ---------- -------------------- ------- ---------------------------------------------- -------------
up       primary    /dev/dsk/c37t6d7     fclp0   hpux_7                                         0
up       primary    /dev/dsk/c22t6d7     fclp1   hpux_8                                         0
up       secondary  /dev/dsk/c36t6d7     fclp0   hpux_5                                         1
up       secondary  /dev/dsk/c44t6d7     fclp1   hpux_6                                         1

----


=== Listen Sie alle Attribute einer bestimmten LUN auf, die dem Host zugeordnet sind

[listing]
----

# sanlun lun show -p -v vs_hp_cluster:/vol/chathpux_217_vol_en_1_5/hp_en_217_lun

                    ONTAP Path: vs_hp_cluster:/vol/chathpux_217_vol_en_1_5/hp_en_217_lun
                           LUN: 49
                      LUN Size: 15g
                   Host Device: /dev/rdisk/disk712
                          Mode: C
                            VG: /dev/vg_data
              Multipath Policy: A/A
            Multipath Provider: Native
-------- ---------- -------------------- ------- ---------------------------------------------- -------------
host     vserver    /dev/dsk                                                                    HP A/A
path     path       filename             host    vserver                                        path failover
state    type       or hardware path     adapter LIF                                            priority
-------- ---------- -------------------- ------- ---------------------------------------------- -------------
up       primary    /dev/dsk/c37t6d1     fclp0   hpux_7                                         0
up       primary    /dev/dsk/c22t6d1     fclp1   hpux_8                                         0
up       secondary  /dev/dsk/c36t6d1     fclp0   hpux_5                                         1
up       secondary  /dev/dsk/c44t6d1     fclp1   hpux_6                                         1

----


=== Listen Sie die ONTAP-LUN-Attribute nach Host-Gerätedateiname auf

[listing]
----
#sanlun lun show -dv /dev/rdisk/disk716
                                                                 device             host                  lun
vserver              lun-pathname                                filename           adapter    protocol   size    mode
----------------------------------------------------------------------------------------------------------------------
vs_hp_cluster        /vol/chathpux_217_vol_en_1_14/hp_en_217_lun /dev/rdisk/disk716 0          FCP        15g     C
             LUN Serial number: 80D7l?NiNP5U
         Controller Model Name: AFF-A800
          Vserver FCP nodename: 208400a098ba7afe
          Vserver FCP portname: 207e00a098ba7afe
              Vserver LIF name: hpux_5
            Vserver IP address: 10.141.54.30
                                10.141.54.35
                                10.141.54.37
                                10.141.54.33
                                10.141.54.31
           Vserver volume name: chathpux_217_vol_en_1_14        MSID::0x00000000000000000000000080915935
         Vserver snapshot name:
----


=== Führen Sie alle dem Host angeschlossenen SVM-Ziel-LIF-WWPNs auf

[listing]
----
# sanlun lun show -wwpn

controller(7mode)/
vserver(Cmode)       target wwpn        lun-pathname                                  device filename
--------------------------------------------------------------------------------------------------------
vs_hp_cluster        208300a098ba7afe   /vol/chathpux_217_vol_en_1_10/hp_en_217_lun   /dev/rdsk/c22t6d7
vs_hp_cluster        208100a098ba7afe   /vol/chathpux_217_vol_en_1_10/hp_en_217_lun   /dev/rdsk/c44t6d7
vs_hp_cluster        208200a098ba7afe   /vol/chathpux_217_vol_en_1_10/hp_en_217_lun   /dev/rdsk/c37t6d7
vs_hp_cluster        207e00a098ba7afe   /vol/chathpux_217_vol_en_1_10/hp_en_217_lun   /dev/rdsk/c36t6d7
vs_hp_cluster        207d00a098ba7afe   /vol/chathpux_217_os/hp_217_os                /dev/rdsk/c18t7d4
vs_hp_cluster        207f00a098ba7afe   /vol/chathpux_217_os/hp_217_os                /dev/rdsk/c42t7d4

host adapter    lun size    mode
---------------------------------
fclp1           15g         C
fclp1           15g         C
fclp0           15g         C
fclp0           15g         C
fclp1           30g         C
fclp0           30g         C
----