---
sidebar: sidebar 
permalink: hu_hpux_60_rn.html 
keywords: host utilities, hpux, 6.0, netapp, ontap, release, notes 
summary: Versionshinweise zu HPUX Host Utilities 6.0 
---
= HP-UX Host Utilities 6.0 – Versionshinweise
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


Diese Versionshinweise enthalten die neuesten Informationen zur Version HP-UX Host Utilities 6.0, einschließlich Updates zu bekannten Problemen, Einschränkungen sowie Konfiguration und Management des ONTAP Storage-Systems. Das Release Notes-Dokument wird aktualisiert, wenn neue Informationen zur Verwendung der HP-UX Host Utilities verfügbar sind.



== Informationen über die Version HP-UX Host Utilities 6.0

Die HP-UX Host Utilities unterstützen mehrere HP-UX Umgebungen und verschiedene Protokolle. Die HP-UX Host Utilities unterstützen die folgenden Umgebungen:

* Native MPIO
* Veritas Dynamic Multipathing (DMP)



NOTE: Um sofort klar zu machen, welche Umgebung genutzt wird, gibt dieses Dokument manchmal „DMP“ für die Veritas DMP-Umgebung und „MPIO“ für die native HP-UX-Umgebung an. In einigen Fällen können die von Ihnen verwendeten Befehle von den Treibern abweichen. In diesen Fällen werden sowohl die Umgebung als auch die Treibertypen angegeben.



== Verbesserungen für HP-UX Host Utilities 6.0

Die Versionshinweise werden zwischen Produktversionen aktualisiert, sobald neue Informationen verfügbar sind. HP-UX Host Utilities 6.0 unterstützt weiterhin Versionen der folgenden Komponenten:

* HP-UX 11iv2
* HP-UX 11iv3




== Bekannte Probleme und Einschränkungen

Für die HP-UX 6.0-Version sind keine Probleme bekannt.



== Über die Dokumentation der SAN-Host-Konfiguration

Die Dokumentation für SAN Host Utilities ist im enthalten link:https://docs.netapp.com/us-en/ontap-sanhost/index.html["Dokumentation der ONTAP-SAN-Host-Konfiguration"] Die Dokumentation für die ONTAP-SAN-Host-Konfiguration ist kumulativ und deckt alle aktuellen SAN-Host-Versionen ab. Funktionsunterschiede zwischen Releases werden im Kontext festgehalten.



== Hier finden Sie Produktdokumentation und andere Informationen

Sie können auf die Dokumentation für alle NetApp Produkte zugreifen und weitere Ressourcen zu Produktinformationen, wie z. B. technische Berichte und Whitepaper, auf der Seite mit der Produktdokumentation auf der NetApp Website zugreifen.

*Konfigurieren und Verwalten Ihres ONTAP Storage-Systems*

* Der link:https://docs.netapp.com/us-en/ontap/setup-upgrade/index.html["ONTAP Software Setup Guide für Ihre Version von ONTAP"^]
* Der link:https://docs.netapp.com/us-en/ontap/san-management/index.html["ONTAP San Administration Guide für Ihre Version von ONTAP"^]
* Der link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["ONTAP Versionshinweise für Ihre Version von ONTAP"^]
* link:https://imt.netapp.com/matrix/#welcome["NetApp Interoperabilitätsmatrix"^]
* link:https://hwu.netapp.com/["Hardware Universe"^] (Ehemals System Configuration Guide)
* link:https://docs.netapp.com/us-en/ontap-sanhost/index.html["Unterstützte Fibre Channel-SAN-Topologien"]
* link:https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61343["Konfigurieren des Hosts für Host Utilities"^]

