---
sidebar: sidebar 
permalink: hu_hpux_11iv3.html 
keywords: host utilities, hp_ux, 11iv3, netapp, ontap 
summary: Beschreibt die Verwendung von IBM AIX 7.2 und/oder PowerVM VIOS 3.1 mit ONTAP 
---
= Konfigurieren Sie HP-UX 11i v3 für FCP und iSCSI mit ONTAP Speicher
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können die Konfigurationseinstellungen des ONTAP-SAN-Hosts verwenden, um HP-UX 11i v3 mit ONTAP als Ziel zu konfigurieren.

Die HP-UX Host Utilities-Software bietet Verwaltungs- und Diagnosetools für HP-UX-Hosts, die mit ONTAP Speicher verbunden sind.  Wenn Sie die HP-UX Host Utilities auf einem HP-UX 11i v3-Host installieren, können Sie die Host Utilities zur Verwaltung von FCP- und iSCSI-Protokollvorgängen mit ONTAP LUNs verwenden.



== Schritt 1: Aktivieren Sie optional den SAN-Bootvorgang

Konfigurieren Sie Ihren Host für die Verwendung von SAN-Boot, um die Bereitstellung zu vereinfachen und die Skalierbarkeit zu verbessern.  Beim SAN-Booten handelt es sich um den Vorgang, bei dem eine an ein SAN angeschlossene Festplatte (eine LUN) als Bootgerät für einen HP-UX-Host eingerichtet wird.  Die Host Utilities unterstützen das SAN-Booten mit FC- und FCoE-Protokollen in HP-UX-Umgebungen.

.Schritte
. Überprüfen Sie mithilfe deslink:https://mysupport.netapp.com/matrix/#welcome["Interoperabilitäts-Matrix-Tool"^], ob Ihr Linux-Betriebssystem, Ihr Host Bus Adapter (HBA), die HBA-Firmware, das HBA-Boot-BIOS und die ONTAP-Version das Booten über das SAN unterstützen.
. Befolgen Sie die Best Practices zum Einrichten eines SAN-Boots in der HP-UX-Anbieterdokumentation.




== Schritt 2: Installieren Sie die HP-UX Host Utilities

NetApp empfiehlt dringend die Installation der HP-UX Host Utilities, um die ONTAP LUN-Verwaltung zu unterstützen und den technischen Support beim Erfassen von Konfigurationsdaten zu unterstützen.

link:hu_hpux_60.html["Installieren Sie HP-UX Host Utilities 6.0"]



== Schritt 3: Bestätigen Sie die Multipath-Konfiguration für Ihren Host

Verwenden Sie Multipathing mit HP-UX 11i v3, um ONTAP LUNs zu verwalten.  Mit Multipathing können Sie mehrere Netzwerkpfade zwischen dem Host und dem Speichersystem konfigurieren.  Wenn ein Pfad ausfällt, wird der Verkehr auf den verbleibenden Pfaden fortgesetzt.

Überprüfen Sie nach der Installation der HP-UX Host Utilities, ob Sie die von NetApp empfohlenen Einstellungen für Ihre ONTAP LUNs konfiguriert haben.

.Über diese Aufgabe
Die HP-UX Host Utilities unterstützen Native Microsoft Multipath I/O (MPIO) und Veritas Dynamic Multipathing.  Die folgenden Schritte gelten für die native MPIO-Lösung.

.Schritte
. Wenn Sie die HP-UX Host Utilities installieren, werden die folgenden empfohlenen Standardeinstellungen für ONTAP LUNs automatisch geladen.


.Parametereinstellungen anzeigen
[%collapsible]
====
[cols="2*"]
|===
| Parameter | Verwendet Den Standardwert 


| Transiente_Sek. | 120 


| Leg_mpath_enable | RICHTIG 


| max_q_Tiefe | 8 


| Pfad_FAIL_s | 120 


| Load_BAL_Policy | Round_Robin 


| lua_Enabled | RICHTIG 


| esd_Sek. | 30 
|===
====
. Überprüfen Sie die Parametereinstellungen und den Pfadstatus für Ihre ONTAP LUNs:
+
[source, cli]
----
sanlun lun show
----
+
Die standardmäßigen Multipath-Parameter unterstützen ASA, AFF und FAS Konfigurationen.  Die folgenden Beispielausgaben zeigen die richtigen Parametereinstellungen und den Pfadstatus für ONTAP LUNs in einer ASA, AFF oder FAS Konfiguration.

+
[role="tabbed-block"]
====
.ASA-Konfiguration
--
Eine ASA Konfiguration optimiert alle Pfade zu einer bestimmten LUN und hält sie aktiv. Dies verbessert die Performance, da I/O-Operationen über alle Pfade gleichzeitig ausgeführt werden können.

[listing]
----
# sanlun lun show -p vs39:/vol/hpux_vol_1_1/hpux_lun

                    ONTAP Path: vs39:/vol/hpux_vol_1_1/hpux_lun
                           LUN: 2
                      LUN Size: 30g
                   Host Device: /dev/rdisk/disk25
                          Mode: C
            Multipath Provider: None
-------- ---------- -------------------- ------- --------------
host     vserver    /dev/dsk
path     path       filename             host    vserver
state    type       or hardware path     adapter LIF
-------- ---------- -------------------- ------- --------------
up       primary    /dev/dsk/c4t0d2      fcd0    248_1c_hp
up       primary    /dev/dsk/c6t0d2      fcd0    246_1c_hp
up       primary    /dev/dsk/c10t0d2     fcd1    246_1d_hp
up       primary    /dev/dsk/c8t0d2      fcd1    248_1d_hp
----
--
.AFF- oder FAS-Konfiguration
--
Eine AFF- oder FAS-Konfiguration sollte zwei Pfadgruppen mit höheren und niedrigeren Prioritäten aufweisen. Aktiv/optimierte Pfade mit höherer Priorität werden vom Controller bedient, wo sich das Aggregat befindet. Pfade mit niedriger Priorität sind aktiv, jedoch nicht optimiert, da sie von einem anderen Controller bedient werden. Nicht optimierte Pfade werden nur verwendet, wenn keine optimierten Pfade verfügbar sind.

Im folgenden Beispiel wird die Ausgabe für eine ONTAP-LUN mit zwei aktiv/optimiert-Pfaden und zwei aktiv/nicht-optimierten Pfaden angezeigt:

[listing]
----
# sanlun lun show -p vs39:/vol/vol24_3_0/lun24_0
                    ONTAP Path: vs39:/vol/vol24_3_0/lun24_0
                           LUN: 37
                      LUN Size: 15g
                   Host Device: /dev/rdisk/disk942
                          Mode: C
              Multipath Policy: A/A
            Multipath Provider: Native
------- ---------- ------ ------- ---------- ---------- --------------
host    vserver     /dev/dsk                            HP A/A
path    path        filename          host    vserver   path failover
state   type        or hardware path adapter    LIF     priority
------- ---------- ------ ------- ---------- ---------- --------------
up       primary    /dev/dsk/c39t4d5   fcd0    hpux_3     0
up       primary    /dev/dsk/c41t4d5   fcd1    hpux_4     0
up       secondary  /dev/dsk/c40t4d5   fcd0    hpux_3     1
up       secondary  /dev/dsk/c42t4d5   fcd1    hpux_4     1
----
--
====




== Schritt 4: Überprüfen der bekannten Probleme

Bei der Version HP-UX 11i v3 mit ONTAP Speicher treten die folgenden bekannten Probleme auf:

[cols="4*"]
|===
| NetApp Bug ID | Titel | Beschreibung | Partner-ID 


| 1447287 | Das AUFO-Ereignis auf dem isolierten Master-Cluster in der Active Sync-Konfiguration von SnapMirror verursacht eine vorübergehende Unterbrechung auf dem HP-UX-Host | Dieses Problem tritt auf, wenn auf dem isolierten Master-Cluster in der Active Sync-Konfiguration von SnapMirror ein Ereignis mit einem automatischen ungeplanten Failover (AUFO) auftritt. Es kann mehr als 120 Sekunden dauern, bis die I/O-Vorgänge auf dem HP-UX-Host fortgesetzt werden. Dies kann jedoch zu keinen I/O-Unterbrechungen oder Fehlermeldungen führen. Dieses Problem verursacht bei doppeltem Ereignis einen Ausfall, da die Verbindung zwischen dem primären und dem sekundären Cluster verloren geht und die Verbindung zwischen dem primären Cluster und dem Mediator verloren geht. Dies gilt im Gegensatz zu anderen AUFO-Ereignissen als ein seltenes Ereignis. | NA 


| 1344935 | HP-UX 11.31-Host meldet gelegentlich den Pfadstatus beim ASA-Setup falsch. | Probleme bei der Pfadberichterstellung bei der ASA-Konfiguration | NA 


| 1306354 | Bei der LVM-Erstellung von HP-UX wird I/O von Blockgrößen über 1 MB gesendet | Die maximale SCSI-Übertragungslänge von 1 MB wird in ONTAP All SAN Array durchgesetzt. Um die maximale Übertragungslänge von HP-UX-Hosts einzuschränken, wenn eine Verbindung zu ONTAP All SAN Array besteht, müssen Sie die maximale E/A-Größe festlegen, die vom HP-UX SCSI-Subsystem zulässig ist, auf 1 MB. Weitere Informationen finden Sie in der Dokumentation des HP-UX-Anbieters. | NA 
|===


== Was kommt als nächstes

link:hu_hpux_60_cmd.html["Erfahren Sie mehr über die Verwendung des HP-UX Host Utilities-Tools"] .
