---
sidebar: sidebar 
permalink: hu_hpux_60.html 
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap 
summary: Beschreibt die Verwendung von Linux Unified Host Utilities 7.1 mit ONTAP 
---
= HP-UX Host Utilitys 6.0
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Die HP-UX Unified Host Utilities unterstützen Sie beim Management von NetApp ONTAP-Speicher mit Anbindung an einen HP-UX-Host.



== SAN Toolkit

HP-UX Host Utilities ist eine NetApp Host Software, die auf Ihrem HP-UX Host ein Befehlszeilen-Tool Kit enthält. Das Toolkit wird bei der Installation des NetApp Host Utilities-Pakets installiert. Dieses Kit enthält die `sanlun` Dienstprogramm, das Sie beim Management der LUNs und HBAs unterstützt. Der `sanlun` Befehl gibt Informationen über die LUNs zurück, die Ihrem Host zugeordnet sind, Multipathing und Informationen zurück, die zum Erstellen von Initiatorgruppen erforderlich sind.

.Beispiel
Im folgenden Beispiel wird der verwendet `sanlun lun show` Mit dem Befehl werden die LUN-Informationen zurückgegeben.

[listing]
----
# sanlun lun show all

controller(7mode)/ device host lun
vserver(Cmode)           lun-pathname                   filename          adapter    protocol   size   mode
------------------------------------------------------------------------------------------------------------
sanboot_unix         /vol/hpux_boot/boot_hpux_lun      /dev/rdsk/c34t0d0  fclp1      FCP        150g    C
sanboot_unix         /vol/hpux_boot/boot_hpux_lun      /dev/rdsk/c23t0d0  fclp1      FCP        150g    C
sanboot_unix         /vol/hpux_boot/boot_hpux_lun      /dev/rdsk/c12t0d0  fclp0      FCP        150g    C
sanboot_unix         /vol/hpux_boot/boot_hpux_lun      /dev/rdsk/c81t0d0  fclp0      FCP        150g    C

----

NOTE: Dieses Toolkit ist für alle Konfigurationen und Protokolle der Host Utilities üblich. Als Ergebnis gelten einige ihrer Inhalte auf eine Konfiguration, jedoch nicht auf eine andere. Ungenutzte Komponenten haben keine Auswirkungen auf die Systemleistung.



== Installieren von HP-UX Host Utilities

Das NetApp HP-UX Host Utilities-Softwarepaket ist auf der erhältlich link:https://mysupport.netapp.com/site/["NetApp Support Website"^] In einer komprimierten Datei.

Sie können die komprimierte Datei mit den Host Utilities Softwarepaketen von herunterladen link:https://mysupport.netapp.com/site/["NetApp Support Website"^]. Nachdem Sie die Datei heruntergeladen haben, müssen Sie sie vor der Installation dekomprimieren.

.Schritte
. Melden Sie sich bei Ihrem Host an.
. Laden Sie die Datei HP-UX Host Utilities herunter `netapp_hpux_host_utilities_6.0_ia_pa.depot.gz` Von link:https://mysupport.netapp.com/site/["NetApp Support Website"^] Auf Ihren HP-UX-Host.
. Dekomprimieren Sie die `netapp_hpux_host_utilities_6.0_ia_pa.depot.gz` Datei durch Eingabe des folgenden Befehls:
+
`# gunzip netapp_hpux_host_utilities_6.0_ia_pa.depot.gz`

+
Das System legt die extrahierte Software in das Verzeichnis, in dem Sie die Depotdatei unkomprimiert haben.

. Installieren Sie die Software mit folgendem Befehl:
+
`# swinstall -s /depot_path`

+
`depot_path` Gibt den Pfad und den Namen der Depotdatei an.

+
Der `swinstall` Mit dem Befehl wird ein Installationsskript ausgeführt, das den Status des HP-UX-Setups überprüft. Wenn Ihr System die Anforderungen erfüllt, installiert dieses Skript das `sanlun` Dienstprogramme und Diagnoseskripte im `/opt/NetApp/santools/bin` Verzeichnis.

. Überprüfen Sie die Installation:
+
`sanlun version`


