---
sidebar: sidebar 
permalink: hu_luhu_71_rn.html 
keywords: host utilities, linux, 7.1, netapp, ontap, release, notes 
summary: Versionshinweise zu Linux Unified Host Utilities 7.1 
---
= Linux Unified Host Utilities 7.1 – Versionshinweise
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
In den Versionshinweisen werden neue Funktionen und Verbesserungen, bekannte Probleme und Einschränkungen sowie wichtige Hinweise zur Konfiguration und Verwaltung Ihres spezifischen Hosts mit Ihrem ONTAP-Speichersystem beschrieben.

Informationen zu den von Host Utilities unterstützten Betriebssystemversionen und Updates finden Sie im link:https://mysupport.netapp.com/matrix/imt.jsp?components=65623;64703;&solution=1&isHWU&src=IMT["NetApp Interoperabilitäts-Matrix-Tool"^].



== Was ist neu

Die Version Linux Host Utilities 7.1 enthält die folgenden neuen Funktionen und Verbesserungen:

* Linux Host Utilities heißt jetzt _Linux Unified Host Utilities_, da sie NetApp E-Series Storage-Systeme mit SANtricity sowie AFF, FAS und ASA Systeme mit ONTAP unterstützen.
+

NOTE: Jede Nennung der Host Utilities oder Linux Host Utilities in diesem Dokument bezieht sich auf Linux Unified Host Utilities.

* Folgende Betriebssysteme werden jetzt unterstützt:
+
** SUSE Linux Enterprise Server 15-Serie
** Oracle VM 3.2-Serie
** Oracle Linux 6 und 7 Serien
** Red hat Enterprise Linux 6 und 7 Series
** SUSE Linux Enterprise Server 11 SP4
** KVM und XEN, RHEV 6.4 und 6.5
** Citrix XenServer


* Auf Red hat Enterprise Linux (RHEL) 6- und RHEL 7-Hosts wird nun ein abgestimmtes Paket zur Festlegung von Serverprofilen unterstützt. Sie können das verwenden `tuned-adm` Befehl zum Festlegen verschiedener Profile, je nach Umgebung.  Sie können beispielsweise das virtuelle Gastprofil auch als virtuelle Gastmaschine verwenden und das Unternehmensspeicherprofil für Konfigurationen verwenden, bei denen LUNs aus Enterprise-Speicherarrays verwendet werden.  Mithilfe dieser optimierten Pakete können Sie den Durchsatz und die Latenz in ONTAP verbessern.
* Unterstützt 32-GB-Fibre-Channel-Adapter von Broadcom Emulex und Marvell Qlogic.



NOTE: NetApp arbeitet weiterhin mit den Host Utilities zusammen, um nach der ersten Version Unterstützung für Funktionen hinzuzufügen. Aktuelle Informationen über unterstützte Funktionen und die neuen Funktionen finden Sie im link:https://mysupport.netapp.com/matrix/imt.jsp?components=65623;64703;&solution=1&isHWU&src=IMT["NetApp Interoperabilitäts-Matrix-Tool"^].



== In dieser Version behoben

Das zeitweise auftretende Problem mit dem Host-Betriebssystem, das beim Ausführen des auftritt `sanlun lun show -p` Der Befehl in SLES12SP1, OL7.2, RHEL7.2 und RHEL 6.8 ist in dieser Version behoben.



== Bekannte Probleme und Einschränkungen

Die Linux Host Utilities 7.1-Version weist die folgenden bekannten Probleme und Einschränkungen auf.

[cols="10, 30, 30"]
|===
| NetApp Bug ID | Titel | Beschreibung 


| 1457017 |  `sanlun` Installationsprobleme mit Warnmeldungen im Zusammenhang mit `libdevmapper.so` Und `libnl.so` Bibliotheken. Diese Warnungen wirken sich nicht auf die Funktionalität von aus `sanlun` Kit. | Wenn Sie den Linux Unified Host Utilities CLI-Befehl „sanlun fcp show Adapter -V“ auf einem SAN-Host ausführen, schlägt der Befehl mit der Fehlermeldung fehl, die anzeigt, dass die für die Erkennung eines Host Bus Adapters (HBA) erforderlichen Bibliotheksabhängigkeiten nicht sein können
Standort:

[Root@hostname ~]# sanlun fcp show Adapter -V
Die Bibliothek /usr/lib64/libHBAAPI.so konnte nicht gefunden werden
Stellen Sie sicher, dass das Paket, das die Bibliothek installiert und geladen ist, installiert ist
Siehe öffentlichen Bericht 1508554. 
|===
link:https://mysupport.netapp.com/site/bugs-online/product["NetApp Bugs Online"^] Bietet vollständige Informationen für die meisten bekannten Probleme, einschließlich Lösungsvorschläge, falls möglich.
