---
sidebar: sidebar 
permalink: hu_luhu_71.html 
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap 
summary: Hier wird die Verwendung der Linux Host Utilities 7.1 mit ONTAP beschrieben 
---
= Installieren Sie Linux Host Utilities 7.1
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die Linux Host Utilities unterstützen Sie beim Management von mit einem Linux-Host verbundenen ONTAP-Speicher. NetApp empfiehlt ausdrücklich die Installation der Linux Host Utilities, dies ist jedoch nicht zwingend erforderlich. Die Dienstprogramme ändern keine Einstellungen auf Ihrem Linux-Host. Die Versorgungseinrichtungen verbessern das Management und unterstützen den NetApp Kunden-Support bei der Erfassung von Informationen zu Ihrer Konfiguration.

Die folgenden Linux-Distributionen werden unterstützt:

* Red Hat Enterprise Linux
* SUSE Linux Enterprise Server
* Oracle Linux
* Oracle VM
* Citrix XenServer


.Bevor Sie beginnen
Das NetApp Linux-Hostdienstprogramme-Softwarepaket ist auf dem  in einer 32-Bit- oder 64-Bit-.rpm-Datei verfügbarlink:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["NetApp Support Website"^].

* Für einen zuverlässigen Betrieb müssen Sie sicherstellen, dass Ihre gesamte iSCSI-, FC- oder FCoE-Konfiguration unterstützt wird.
+
Sie können die verwendenlink:https://imt.netapp.com/matrix/#welcome["Interoperabilitäts-Matrix-Tool"^], um Ihre Konfiguration zu überprüfen.

* Sie müssen die auf der Support-Website des Anbieters verfügbaren Verwaltungspakete für den Host Bus Adapter (HBA) installieren.
+
Die Managementsoftware aktiviert die SAN-Toolkit-Befehle, um Informationen über FC-HBAs, z. B. deren WWPNs, zu sammeln. Überprüfen Sie, ob die folgenden Pakete korrekt installiert sind, damit `sanlun fcp show adapter` der Befehl funktioniert:

+
** Marvell QLogic HBA – QConvergeConsole CLI
** Broadcom Emulex HBA – OneCommand Manager-CLI für die Kernanwendung
** Marvell Brocade HBA – Brocade Command Utility CLI


* RPM Pakete "libhbaapi" und "libhbalinux", die für jede Linux-Distribution zur Verfügung stehen, sollten auf dem Host-Betriebssystem installiert werden.



NOTE: Die Linux Host Utilities Software unterstützt keine NVMe over Fibre Channel (NVMe/FC)- und NVMe over TCP (NVMe/TCP)-Host-Protokolle.

.Schritte
. Wenn Sie derzeit eine Version von Linux Host Utilities installiert haben, entfernen Sie diese mit dem folgenden Befehl:
+
[source, cli]
----
rpm -e netapp_linux_unified_host_utilities-7-1
----
+
Bei früheren Versionen von Linux Host Utilities wechseln Sie zum Verzeichnis, in dem die Host Utility-Software installiert ist, und geben den Deinstallationsbefehl ein, um das installierte Paket zu entfernen.

. Laden Sie das 32-Bit- oder 64-Bit-Linux Host Utilities-Softwarepaket vom auf Ihren Host herunterlink:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["NetApp Support Website"^].
. Rufen Sie das Verzeichnis auf, in dem Sie das Softwarepaket heruntergeladen haben, und installieren Sie es mit dem folgenden Befehl:
+
[source, cli]
----
rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_xx.rpm
----
+
[listing]
----
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:netapp_linux_unified_host_utiliti################################# [100%]
----
. Überprüfen Sie die Installation:
+
[source, cli]
----
sanlun version
----
+
[listing]
----
sanlun version 7.1.386.1644
----




== Empfohlene Treibereinstellungen mit Linux-Kernel

Wenn Sie eine FC-Umgebung konfigurieren, die native Inbox-Treiber verwendet, die mit dem Linux-Kernel gebündelt sind, können Sie die Standardwerte für die Treiber verwenden.



== SAN Toolkit

Linux Host Utilities ist eine NetApp Host-Software, die ein Befehlszeilen-Toolkit auf Ihrem Linux-Host bereitstellt.

Das Toolkit wird automatisch installiert, wenn Sie das NetApp Host Utilities-Paket installieren. Dieses Kit enthält die `sanlun` Dienstprogramm: Unterstützt Sie beim Management von LUNs und HBAs. Der `sanlun` Befehl gibt Informationen über die LUNs zurück, die Ihrem Host zugeordnet sind, Multipathing und Informationen zurück, die zum Erstellen von Initiatorgruppen erforderlich sind.

.Beispiel
Im folgenden Beispiel wird der verwendet `sanlun lun show` Befehl gibt LUN-Informationen zurück.

[source, cli]
----
# sanlun lun show all
----
Beispielausgabe:

[listing]
----
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
------------------------------------------------------------------------------------
data_vserver          /vol/vol1/lun1   /dev/sdb   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol1/lun1   /dev/sdc   host15   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sdd   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sde   host15   FCP       120.0g  cDOT
----
[NOTE]
====
* Dieses Toolkit ist für alle Konfigurationen und Protokolle der Host Utilities üblich. Als Ergebnis gelten einige ihrer Inhalte auf eine Konfiguration, jedoch nicht auf eine andere. Ungenutzte Komponenten haben keine Auswirkungen auf die Systemleistung.
* Das SAN Toolkit wird auf Citrix XenServer, Oracle VM und Red hat Enterprise Virtualization Hypervisor nicht unterstützt.


====