---
sidebar: sidebar 
permalink: hu_ol_76.html 
keywords: host utilities, oracle, linux, 7.6, netapp, ontap 
summary: Beschreibt die Verwendung von Oracle Linux 7.6 mit ONTAP 
---
= Verwenden Sie Oracle Linux 7.6 mit ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können die Konfigurationseinstellungen des ONTAP-SAN-Hosts verwenden, um Oracle Linux 7.6 mit ONTAP als Ziel zu konfigurieren.



== Installieren Sie die Linux Unified Host Utilities

Das NetApp Linux Unified Host Utilities-Softwarepaket ist auf dem  in einer 32-Bit- und 64-Bit-RPM-Datei verfügbarlink:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["NetApp Support Website"^]. Wenn Sie nicht wissen, welche Datei für Ihre Konfiguration geeignet ist, überprüfen Sie mithilfe der, welche Datei link:https://mysupport.netapp.com/matrix/#welcome["NetApp Interoperabilitäts-Matrix-Tool"^]Sie benötigen.

NetApp empfiehlt ausdrücklich die Installation der Linux Unified Host Utilities, dies ist jedoch nicht zwingend erforderlich. Die Dienstprogramme ändern keine Einstellungen auf Ihrem Linux-Host. Die Versorgungseinrichtungen verbessern das Management und unterstützen den NetApp Kunden-Support bei der Erfassung von Informationen zu Ihrer Konfiguration.

Wenn Sie Linux Unified Host Utilities derzeit installiert haben, sollten Sie entweder ein Upgrade auf die neueste Version durchführen oder diese entfernen und die aktuelle Version wie folgt installieren.

.Schritte
. Laden Sie das Softwarepaket für 32 Bit oder 64 Bit Linux Unified Host Utilities von herunter link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["NetApp Support Website"^] Auf Ihren Host.
. Installieren des Softwarepakets:
+
`rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_64`




NOTE: Sie können die in diesem Dokument angegebenen Konfigurationseinstellungen verwenden, um die mit verbundenen Cloud-Clients zu konfigurieren link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] Und link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["Amazon FSX für ONTAP"^].



== SAN Toolkit

Das Toolkit wird automatisch installiert, wenn Sie das NetApp Host Utilities-Paket installieren. Dieses Kit enthält die `sanlun` Dienstprogramm: Unterstützt Sie beim Management von LUNs und HBAs. Der `sanlun` Befehl gibt Informationen über die LUNs zurück, die Ihrem Host zugeordnet sind, Multipathing und Informationen zurück, die zum Erstellen von Initiatorgruppen erforderlich sind.

.Beispiel
Im folgenden Beispiel wird der verwendet `sanlun lun show` Befehl gibt LUN-Informationen zurück.

[source, cli]
----
# sanlun lun show all
----
Beispielausgabe:

[listing]
----
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
------------------------------------------------------------------------------------
data_vserver          /vol/vol1/lun1   /dev/sdb   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol1/lun1   /dev/sdc   host15   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sdd   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sde   host15   FCP       120.0g  cDOT
----


== SAN wird gebootet

.Was Sie benötigen
Wenn Sie sich für das Booten über SAN entscheiden, muss es von Ihrer Konfiguration unterstützt werden. Sie können das verwenden link:https://mysupport.netapp.com/matrix/imt.jsp?components=86309;&solution=1&isHWU&src=IMT["NetApp Interoperabilitäts-Matrix-Tool"^] Um zu überprüfen, ob Ihr Betriebssystem, HBA, die HBA-Firmware und das HBA-Boot-BIOS sowie die ONTAP-Version unterstützt werden.

.Schritte
. Ordnen Sie die SAN-Boot-LUN dem Host zu.
. Vergewissern Sie sich, dass mehrere Pfade verfügbar sind.
+

NOTE: Mehrere Pfade sind verfügbar, nachdem das Host-Betriebssystem auf den Pfaden ausgeführt wurde.

. Aktivieren Sie das SAN-Booten im Server-BIOS für die Ports, denen die SAN-Boot-LUN zugeordnet ist.
+
Informationen zum Aktivieren des HBA-BIOS finden Sie in der anbieterspezifischen Dokumentation.

. Starten Sie den Host neu, um zu überprüfen, ob der Startvorgang erfolgreich war.




== Multipathing

Für Oracle Linux 7.6 muss die Datei /etc/Multipath.conf vorhanden sein, Sie müssen jedoch keine spezifischen Änderungen an der Datei vornehmen. Oracle Linux 7.6 wird mit allen Einstellungen zusammengestellt, die zum Erkennen und korrekten Managen von ONTAP LUNs erforderlich sind.

Sie können mit dem `multipath -ll` Befehl die Einstellungen für Ihre ONTAP LUNs überprüfen. Es sollte zwei Gruppen von Pfaden mit unterschiedlichen Prioritäten geben. Die Pfade mit höheren Prioritäten sind aktiv/optimiert, d. h. sie werden vom Controller gewartet, in dem sich das Aggregat befindet. Die Pfade mit niedrigeren Prioritäten sind aktiv, aber nicht optimiert, da sie von einem anderen Controller bedient werden. Die nicht optimierten Pfade werden nur verwendet, wenn optimierte Pfade nicht verfügbar sind.

.Beispiel
Im folgenden Beispiel wird die richtige Ausgabe für eine ONTAP-LUN mit zwei aktiv/optimierten Pfaden und zwei aktiv/nicht optimierten Pfaden angezeigt:

[listing]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 11:0:1:0 sdj 8:144 active ready running
| |- 11:0:2:0 sdr 65:16 active ready running
|-+- policy='service-time 0' prio=10 status=enabled
|- 11:0:0:0 sdb 8:i6 active ready running
|- 12:0:0:0 sdz 65:144 active ready running
----

NOTE: Eine einzelne LUN sollte nicht mehr als vier Pfade benötigen. Eine Verfügbarkeit von mehr als vier Pfaden kann bei Storage-Ausfällen zu Pfadproblemen führen.



== Empfohlene Einstellungen

Das Oracle Linux 7.6-Betriebssystem wird kompiliert, um ONTAP-LUNs zu erkennen und automatisch alle Konfigurationsparameter korrekt einzustellen. Die `multipath.conf` Datei muss vorhanden sein, damit der Multipath-Daemon gestartet werden kann. Wenn diese Datei nicht vorhanden ist, können Sie eine leere, Null-Byte-Datei mit dem Befehl erstellen `touch /etc/multipath.conf`.

Wenn Sie die `multipath.conf` Datei zum ersten Mal erstellen, müssen Sie möglicherweise die Multipath-Services mithilfe der folgenden Befehle aktivieren und starten:

`# chkconfig multipathd on`
`# /etc/init.d/multipathd start`

Sie müssen der Datei nichts direkt hinzufügen `multipath.conf`, es sei denn, Sie verfügen über Geräte, die nicht von Multipath verwaltet werden sollen, oder Sie haben bereits vorhandene Einstellungen, die die Standardeinstellungen außer Kraft setzen. Um unerwünschte Geräte auszuschließen, fügen Sie der `multipath.conf` Datei die folgende Syntax hinzu und ersetzen <DevId> durch die WWID-Zeichenfolge des Geräts, das Sie ausschließen möchten:

[listing]
----
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----
Das folgende Beispiel bestimmt die WWID eines Geräts und fügt sie der Datei hinzu `multipath.conf`.

.Schritte
. Bestimmen Sie die WWID:
+
[listing]
----
# /lib/udev/scsi_id -gud /dev/sda
360030057024d0730239134810c0cb833
----
+
`sda` Ist das lokale SCSI-Laufwerk, das Sie der Blacklist hinzufügen möchten.

. Fügen Sie die hinzu `WWID` Zur schwarzen Liste stanza in `/etc/multipath.conf`:
+
[listing]
----
blacklist {
     wwid   360030057024d0730239134810c0cb833
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----


Überprüfen Sie Ihre Datei immer `/etc/multipath.conf`, insbesondere im Abschnitt „Standardeinstellungen“, auf ältere Einstellungen, die die Standardeinstellungen überschreiben könnten.

In der folgenden Tabelle sind die kritischen `multipathd` Parameter für ONTAP-LUNs und die erforderlichen Werte aufgeführt. Wenn ein Host mit LUNs anderer Hersteller verbunden ist und diese Parameter überschrieben werden, müssen sie durch spätere Strophen in der `multipath.conf` Datei korrigiert werden, die speziell für ONTAP-LUNs gelten. Ohne diese Korrektur funktionieren die ONTAP-LUNs möglicherweise nicht wie erwartet. Sie sollten diese Standardeinstellungen nur in Absprache mit NetApp, dem OS-Anbieter oder beiden außer Kraft setzen, und zwar nur dann, wenn die Auswirkungen vollständig verstanden sind.

[cols="2*"]
|===
| Parameter | Einstellung 


| Erkennen_Prio | ja 


| Dev_Loss_tmo | „Unendlich“ 


| Failback | Sofort 


| Fast_io_fail_tmo | 5 


| Funktionen | „3 queue_if_no_Pg_init_retries 50“ 


| Flush_on_Last_del | „ja“ 


| Hardware_Handler | „0“ 


| PATH_Checker | „nur“ 


| Path_Grouping_Policy | „Group_by_prio“ 


| Pfad_Auswahl | „Servicezeit 0“ 


| Polling_Interval | 5 


| prio | ONTAP 


| Produkt | LUN.* 


| Beibehalten_Attached_hw_Handler | ja 


| rr_weight | „Einheitlich“ 


| User_friendly_names | Nein 


| Anbieter | NETAPP 
|===
.Beispiel
Das folgende Beispiel zeigt, wie eine überhielte Standardeinstellung korrigiert wird. In diesem Fall die `multipath.conf` Datei definiert Werte für `path_checker` Und `detect_prio` Die nicht mit ONTAP LUNs kompatibel sind. Wenn sie nicht entfernt werden können, weil andere SAN-Arrays noch an den Host angeschlossen sind, können diese Parameter speziell für ONTAP-LUNs mit einem Device stanza korrigiert werden.

[listing]
----
defaults {
 path_checker readsector0
 detect_prio no
 }
devices {
 device {
 vendor "NETAPP "
 product "LUN.*"
 path_checker tur
 detect_prio yes
 }
}
----

NOTE: Um Oracle Linux 7.6 Red hat Enterprise Kernel (RHCK) zu konfigurieren, verwenden Sie den link:hu_rhel_76.html#recommended-settings["Empfohlene Einstellungen"] für Red hat Enterprise Linux (RHEL) 7.6.



== Bekannte Probleme

Die Oracle Linux 7.6 mit ONTAP-Version weist folgende bekannte Probleme auf:

[cols="3*"]
|===
| NetApp Bug ID | Titel | Beschreibung 


| 1440718 | Wenn Sie eine LUN ohne SCSI-erneute Zuordnung aufheben oder zuordnen, kann dies zu Datenbeschädigungen auf dem Host führen. | Wenn Sie den Multipath-Konfigurationsparameter 'disable_changed_wwids' auf YES setzen, wird der Zugriff auf das Pfadgerät bei einer WWID-Änderung deaktiviert. Multipath deaktiviert den Zugriff auf das Pfadgerät, bis die WWID des Pfads auf die WWID des Multipath-Geräts wiederhergestellt ist. Weitere Informationen finden Sie unter link:https://kb.netapp.com/Advice_and_Troubleshooting/Flash_Storage/AFF_Series/The_filesystem_corruption_on_iSCSI_LUN_on_the_Oracle_Linux_7["NetApp Knowledge Base: Beschädigung des Dateisystems auf iSCSI LUN auf Oracle Linux 7"^]. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1202736["1202736"^] | LUNs sind während der Host-Erkennung möglicherweise nicht verfügbar, da Remote-Ports auf einem OL7U6-Host mit QLogic QLE2742 Adapter „nicht vorhanden“ sind | Während der Host-Erkennung kann der Status der Fibre Channel (FC) Remote-Ports auf einem OL7U6 Host mit einem QLogic QLE2742 Adapter in den Status „nicht vorhanden“ eintreten. Remote-Ports mit Status „nicht vorhanden“ können dazu führen, dass Pfade zu LUNs nicht mehr verfügbar sind. Während des Storage Failover kann die Pfadredundanz reduziert werden und zu einem I/O-Ausfall führen. Sie können den Status des Remote-Ports überprüfen, indem Sie den folgenden Befehl eingeben: # CAT /sys/class/fc_Remote_Ports/rport-*/Port_State: Das folgende Beispiel zeigt die Ausgabe an: Online Online nicht vorhanden Online Online 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1204078["1204078"^] | Kernel-Störung tritt auf Oracle Linux 7.6 mit Qlogic(QLE2672) 16-GB-FC-HBA während eines Storage-Failover-Betriebs auf | Während Speicher-Failover-Vorgänge auf dem Oracle Linux 7.6 mit einem Qlogic QLE2672 Fibre Channel (FC) Host Bus Adapter (HBA), tritt eine Kernel-Störung aufgrund einer Panik im Kernel auf. Die Kernel-Panic bewirkt einen Neustart von Oracle Linux 7.6, was zu einer Applikationsunterbrechung führt. Wenn der kdump-Mechanismus aktiviert ist, generiert die Kernel Panic eine vmcore-Datei im Verzeichnis /var/crash/. Sie können die vmcore-Datei analysieren, um die Ursache der Panik zu ermitteln. Nach einer Störung des Kernels können Sie das Host-Betriebssystem neu starten und das Betriebssystem wiederherstellen. Anschließend können Sie alle Anwendungen nach Bedarf neu starten. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1204351["1204351"^] | Bei Oracle Linux 7.6 mit Qlogic (QLE2742) 32-GB-FC-HBA während eines Storage-Failover-Betriebs kann es zu Kernel-Störungen kommen | Während Storage Failover-Vorgänge auf dem Oracle Linux 7.6 mit einem Qlogic QLE2742 Fibre Channel (FC) Host Bus Adapter (HBA) können eine Kernel-Störung aufgrund einer Panic im Kernel auftreten. Die Kernel-Panic bewirkt einen Neustart von Oracle Linux 7.6, was zu einer Applikationsunterbrechung führt. Wenn der kdump-Mechanismus aktiviert ist, generiert die Kernel Panic eine vmcore-Datei im Verzeichnis /var/crash/. Sie können die vmcore-Datei analysieren, um die Ursache der Panik zu ermitteln. Nach einer Störung des Kernels können Sie das Host-Betriebssystem neu starten und das Betriebssystem wiederherstellen. Anschließend können Sie alle Anwendungen nach Bedarf neu starten. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1204352["1204352"^] | Bei Oracle Linux 7.6 mit Emulex (LPe32002-M2) 32 GB FC HBA tritt möglicherweise eine Störung des Kernels auf | Während Storage Failover-Vorgänge auf dem Oracle Linux 7.6 mit einem Emulex LPe32002-M2 Fibre Channel (FC) Host Bus Adapter (HBA) auftreten können, kann es zu einer Kernel-Störung kommen, da eine Panik im Kernel auftritt. Die Kernel-Panic bewirkt einen Neustart von Oracle Linux 7.6, was zu einer Applikationsunterbrechung führt. Wenn der kdump-Mechanismus aktiviert ist, generiert die Kernel Panic eine vmcore-Datei im Verzeichnis /var/crash/. Sie können die vmcore-Datei analysieren, um die Ursache der Panik zu ermitteln. Nach einer Störung des Kernels können Sie das Host-Betriebssystem neu starten und das Betriebssystem wiederherstellen. Anschließend können Sie alle Anwendungen nach Bedarf neu starten. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1246134["11246134"^] | Keine I/O-Fortschritte bei Oracle Linux 7.6 mit UEK5U2 Kernel, der mit einem Emulex LPe16002B-M6 16G FC HBA während Storage Failover-Vorgängen ausgeführt wird | Während Speicher-Failover-Vorgänge auf Oracle Linux 7.6 bei laufendem UEK5U2-Kernel mit einem Emulex LPe16002B-M6 16G Fibre Channel (FC) Host Bus Adapter (HBA), kann der I/O-Fortschritt aufgrund blockierter Berichte gestoppt werden. Der Storage Failover-Vorgang meldet, dass sich der Status „Online“ in einen „blockierten“ Zustand ändert und zu einer Verzögerung bei Lese- und Schreibvorgängen führt. Nach erfolgreichem Abschluss des Vorgangs können die Berichte nicht wieder in einen „Online“-Zustand zurückverschoben werden und bleiben weiterhin in einem „blockierten“ Zustand. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1246327["1246327"^] | Der Remote-Port-Status auf QLogic QLE2672 16G Host wurde während eines Storage-Failover-Betriebs blockiert | Fibre-Channel-Remote-Ports (FC) können bei Red hat Enterprise Linux (RHEL) 7.6 mit dem QLogic QLE2672 16G-Host während Storage-Failover-Vorgängen blockiert werden. Da bei einem Ausfall eines Storage-Node die logischen Schnittstellen ausfallen, setzen die Remote-Ports den Status des Storage-Node auf „gesperrt“. Der I/O-Fortschritt wird möglicherweise aufgrund der blockierten Ports gestoppt, wenn Sie sowohl einen QLogic QLE2672 16G Host als auch einen QLE2742 32 GB Fibre Channel (FC) Host Bus Adapter (HBA) ausführen. Wenn der Storage-Node wieder in seinen optimalen Status wechselt, werden auch die logischen Schnittstellen angezeigt, und die Remote-Ports sollten online sein. Die Remote-Ports sind jedoch möglicherweise immer noch blockiert. Dieser blockierte Status wird als fehlerhaft für LUNS auf der Multipath-Ebene registriert. Sie können den Status der Remote-Ports mit folgendem Befehl überprüfen: # CAT /sys/class/fc_Remote_Ports/rport-*/Port_stat Sie sollten folgende Ausgabe sehen: Blocked Blocked Blocked Online 
|===