---
sidebar: sidebar 
permalink: hu_ol_77.html 
keywords: host utilities, oracle, linux, 7.7, netapp, ontap 
summary: Installieren Sie Linux Host Utilities auf einem Oracle Linux 7.7-Host, um FCP- und iSCSI-Protokollvorgänge mit ONTAP LUNs zu verwalten. 
---
= Konfigurieren Sie Oracle Linux 7.7 für FCP und iSCSI mit ONTAP-Speicher
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die Linux Host Utilities-Software enthält Management- und Diagnose-Tools für Linux-Hosts, die mit dem ONTAP-Storage verbunden sind. Wenn Sie die Linux Host Utilities auf einem Oracle Linux 7.7-Host installieren, können Sie die Host Utilities zur Verwaltung von FCP- und iSCSI-Protokollvorgängen mit ONTAP LUNs verwenden.


NOTE: Sie müssen die Einstellungen der Kernel-basierten virtuellen Maschine (KVM) nicht manuell konfigurieren, da ONTAP LUNs automatisch dem Hypervisor zugeordnet werden.



== Schritt 1: Aktivieren Sie optional den SAN-Bootvorgang

Sie können Ihren Host so konfigurieren, dass er SAN-Booting verwendet, um die Bereitstellung zu vereinfachen und die Skalierbarkeit zu verbessern.

.Bevor Sie beginnen
Überprüfen Sie mithilfe deslink:https://mysupport.netapp.com/matrix/#welcome["Interoperabilitäts-Matrix-Tool"^], ob Ihr Linux-Betriebssystem, Ihr Host Bus Adapter (HBA), die HBA-Firmware, das HBA-Boot-BIOS und die ONTAP-Version das Booten über das SAN unterstützen.

.Schritte
. link:https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["Erstellen Sie eine SAN-Boot-LUN und ordnen Sie sie dem Host zu"^].
. Aktivieren Sie das SAN-Booten im Server-BIOS für die Ports, denen die SAN-Boot-LUN zugeordnet ist.
+
Informationen zum Aktivieren des HBA-BIOS finden Sie in der anbieterspezifischen Dokumentation.

. Überprüfen Sie, ob die Konfiguration erfolgreich war, indem Sie den Host neu starten und überprüfen, ob das Betriebssystem ausgeführt wird.




== Schritt 2: Installieren Sie die Linux Host Utilities

NetApp empfiehlt dringend die Installation der Linux Host Utilities, um die ONTAP LUN-Verwaltung zu unterstützen, und den technischen Support beim Sammeln von Konfigurationsdaten zu unterstützen.

link:hu_luhu_71.html["Installieren Sie Linux Host Utilities 7.1"].


NOTE: Durch die Installation der Linux Host Utilities werden keine Host-Timeout-Einstellungen auf Ihrem Linux-Host geändert.



== Schritt 3: Bestätigen Sie die Multipath-Konfiguration für Ihren Host

Sie können Multipathing mit Oracle Linux 7.7 verwenden, um ONTAP-LUNs zu verwalten.


NOTE: Sie können die link:hu_rhel_77.html#rhel-rhck["empfohlene Einstellungen für Red Hat Enterprise Linux (RHEL) 7.7"] um den Red Hat Compatible Kernel für Oracle Linux 7.7 zu konfigurieren.

Um sicherzustellen, dass Multipathing für Ihren Host korrekt konfiguriert ist, überprüfen Sie, ob die `/etc/multipath.conf` Datei definiert ist und ob die von NetApp empfohlenen Einstellungen für Ihre ONTAP LUNs konfiguriert sind.

.Schritte
. Überprüfen Sie, ob die `/etc/multipath.conf` Datei beendet wird. Wenn die Datei nicht vorhanden ist, erstellen Sie eine leere, Null-Byte-Datei:
+
[source, cli]
----
touch /etc/multipath.conf
----
. Beim ersten Erstellen der `multipath.conf` Datei müssen Sie möglicherweise die Multipath-Services aktivieren und starten, um die empfohlenen Einstellungen zu laden:
+
[source, cli]
----
chkconfig multipathd on
----
+
[source, cli]
----
/etc/init.d/multipathd start
----
. Jedes Mal, wenn Sie den Host starten, lädt die leere `/etc/multipath.conf` Zero-Byte-Datei automatisch die von NetApp empfohlenen Multipath-Parameter als Standardeinstellungen. Sie sollten keine Änderungen an der Datei für Ihren Host vornehmen `/etc/multipath.conf` müssen, da das Betriebssystem mit den Multipath-Parametern kompiliert wird, die ONTAP-LUNs korrekt erkennen und verwalten.
+
In der folgenden Tabelle sind die nativen kompilierten Multipath-Parametereinstellungen für ONTAP LUNs unter Linux aufgeführt.

+
.Parametereinstellungen anzeigen
[%collapsible]
====
[cols="2"]
|===
| Parameter | Einstellung 


| Erkennen_Prio | ja 


| Dev_Loss_tmo | „Unendlich“ 


| Failback | Sofort 


| Fast_io_fail_tmo | 5 


| Funktionen | „2 pg_init_retries 50“ 


| Flush_on_Last_del | „ja“ 


| Hardware_Handler | „0“ 


| Kein_PATH_retry | Warteschlange 


| PATH_Checker | „nur“ 


| Path_Grouping_Policy | „Group_by_prio“ 


| Pfad_Auswahl | „Servicezeit 0“ 


| Polling_Interval | 5 


| prio | ONTAP 


| Produkt | LUN 


| Beibehalten_Attached_hw_Handler | ja 


| rr_weight | „Einheitlich“ 


| User_friendly_names | Nein 


| Anbieter | NETAPP 
|===
====
. Überprüfen Sie die Parametereinstellungen und den Pfadstatus für Ihre ONTAP LUNs:
+
[source, cli]
----
multipath -ll
----
+
Die Standard-Multipath-Parameter unterstützen AFF und FAS Konfigurationen. In diesen Konfigurationen sollte eine einzelne ONTAP LUN nicht mehr als vier Pfade benötigen. Mehr als vier Pfade können bei einem Speicherausfall Probleme verursachen.

+
Eine AFF- oder FAS-Konfiguration sollte zwei Pfadgruppen mit höheren und niedrigeren Prioritäten aufweisen. Aktiv/optimierte Pfade mit höherer Priorität werden vom Controller bedient, wo sich das Aggregat befindet. Pfade mit niedriger Priorität sind aktiv, jedoch nicht optimiert, da sie von einem anderen Controller bedient werden. Nicht optimierte Pfade werden nur verwendet, wenn keine optimierten Pfade verfügbar sind.

+
Die folgenden Beispielausgaben zeigen die richtigen Parametereinstellungen und den Pfadstatus für ONTAP LUNs in einer AFF- oder FAS-Konfiguration mit zwei aktiven/optimierten Pfaden und zwei aktiven/nicht optimierten Pfaden:

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
multipath -ll
3600a0980383036347ffb4d59646c4436 dm-28 NETAPP,LUN C-Mode
size=10G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 16:0:6:35 sdwb  69:624  active ready running
| |- 16:0:5:35 sdun  66:752  active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 15:0:0:35 sdaj  66:48   active ready running
  |- 15:0:1:35 sdbx  68:176  active ready running
----
====




== Schritt 4: Optional: Schließen Sie ein Gerät vom Multipathing aus

Bei Bedarf können Sie ein Gerät vom Multipathing ausschließen, indem Sie die WWID für das unerwünschte Gerät der „Blacklist“-Strophe für die Datei hinzufügen `multipath.conf`.

.Schritte
. Bestimmen Sie die WWID:
+
[source, cli]
----
/lib/udev/scsi_id -gud /dev/sda
----
+
„sda“ ist die lokale SCSI-Festplatte, die Sie der Blacklist hinzufügen möchten.

+
Ein Beispiel WWID ist `360030057024d0730239134810c0cb833`.

. Fügen Sie die WWID der schwarzen Liste hinzu:
+
[source, cli]
----
blacklist {
	     wwid   360030057024d0730239134810c0cb833
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----




== Schritt 5: Passen Sie Multipath-Parameter für ONTAP LUNs an

Wenn Ihr Host mit LUNs anderer Hersteller verbunden ist und eine der Multipath-Parametereinstellungen überschrieben wird, müssen Sie diese korrigieren, indem Sie später Strophen in der Datei hinzufügen `multipath.conf`, die speziell für ONTAP-LUNs gelten. Wenn Sie dies nicht tun, funktionieren die ONTAP LUNs möglicherweise nicht wie erwartet.

Überprüfen Sie Ihre `/etc/multipath.conf` Datei, insbesondere im Abschnitt Standardeinstellungen, auf Einstellungen, die die überschreiben könnten<<multipath-parameter-settings,Standardeinstellungen für Multipath-Parameter>>.


CAUTION: Die empfohlenen Parametereinstellungen für ONTAP LUNs sollten Sie nicht außer Kraft setzen. Diese Einstellungen sind für eine optimale Performance Ihrer Hostkonfiguration erforderlich. Weitere Informationen erhalten Sie vom NetApp-Support, vom Hersteller Ihres Betriebssystems oder von beiden.

Das folgende Beispiel zeigt, wie eine überhielte Standardeinstellung korrigiert wird. In diesem Beispiel definiert die `multipath.conf` Datei Werte für `path_checker` und `no_path_retry`, die nicht mit ONTAP-LUNs kompatibel sind. Sie können diese Parameter nicht entfernen, da ONTAP-Speicher-Arrays noch mit dem Host verbunden sind. Stattdessen korrigieren Sie die Werte für `path_checker` und `no_path_retry`, indem Sie der Datei, die speziell auf die ONTAP-LUNs zutrifft, eine Gerätestanze hinzufügen `multipath.conf`.

.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
defaults {
   path_checker      *readsector0*
   no_path_retry     *fail*
}

devices {
   device {
      vendor          "NETAPP"
      product         "LUN"
      no_path_retry   *queue*
      path_checker    *tur*
   }
}
----
====


== Schritt 6: Überprüfen Sie die bekannten Probleme

Beim Oracle Linux 7.7-Host mit ONTAP-Speicher sind die folgenden Probleme bekannt:

[cols="3*"]
|===
| NetApp Bug ID | Titel | Beschreibung 


| 1440718 | Wenn Sie eine LUN ohne SCSI-erneute Zuordnung aufheben oder zuordnen, kann dies zu Datenbeschädigungen auf dem Host führen. | Wenn Sie den Multipath-Konfigurationsparameter 'disable_changed_wwids' auf YES setzen, wird der Zugriff auf das Pfadgerät bei einer WWID-Änderung deaktiviert. Multipath deaktiviert den Zugriff auf das Pfadgerät, bis die WWID des Pfads auf die WWID des Multipath-Geräts wiederhergestellt ist. Weitere Informationen finden Sie unter link:https://kb.netapp.com/Advice_and_Troubleshooting/Flash_Storage/AFF_Series/The_filesystem_corruption_on_iSCSI_LUN_on_the_Oracle_Linux_7["NetApp Knowledge Base: Beschädigung des Dateisystems auf iSCSI LUN auf Oracle Linux 7"^]. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1311575["1311575"^] | I/O-Verzögerungen, die aufgrund von Lese-/Schreibvorgängen beobachtet wurden, konnten während des Speicher-Failovers mit Qlogic QLE2672 (16G) nicht durch sekundäre Pfade umgeschaltet werden | I/O-Vorgänge können bei einem Storage Failover-Vorgang auf dem Oracle Linux 7.7 Kernel (5.4.17-2011.0.7.el7uek.x86_6) mit QLogic QLE2672 16G HBA nicht fortgesetzt werden. Wenn der I/O-Fortschritt aufgrund von blockierten primären Pfaden während des Storage Failovers unterbrochen wird, kann der I/O-Vorgang möglicherweise nicht über sekundäre Pfade fortgesetzt werden, was zu einer Verzögerung des I/O-Vorgangs führt. Der I/O-Vorgang wird erst fortgesetzt, nachdem die primären Pfade nach Abschluss des Storage-Failover-Giveback online geschaltet wurden. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1311576["1311576"^] | I/O-Verzögerungen, die während des Storage Failover durch Emulex LPe16002(16G) auftreten, wenn der Lese-/Schreibvorgang nicht durch sekundäre Pfade umgeschaltet wird | I/O-Vorgänge können bei einem Storage Failover-Vorgang auf dem Oracle Linux 7.7 Kernel (5.4.17-2011.0.7.el7uek.x86_6) mit Emulex LPe16002 16G HBA nicht fortgesetzt werden. Wenn der I/O-Fortschritt aufgrund von blockierten primären Pfaden während des Storage Failovers unterbrochen wird, kann der I/O-Vorgang möglicherweise nicht über sekundäre Pfade fortgesetzt werden, was zu einer Verzögerung des I/O-Vorgangs führt. Der I/O-Vorgang wird erst fortgesetzt, nachdem die primären Pfade nach Abschluss des Storage-Failover-Giveback online geschaltet wurden. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1246134["1246134"^] | Beobachtete I/O-Verzögerungen und Berichte befinden sich während des Storage Failover in den Status „gesperrt“, „NICHT VORHANDEN“ mit Emulex LPe16002 (16G). | Während Speicher-Failover-Vorgänge auf Oracle Linux 7.6 bei laufendem UEK5U2-Kernel mit einem Emulex LPe16002B-M6 16G Fibre Channel (FC) Host Bus Adapter (HBA), kann der I/O-Fortschritt aufgrund blockierter Berichte gestoppt werden. Der Storage Failover-Vorgang meldet, dass sich der Status „Online“ in den Status „gesperrt“ ändert, was zu einer Verzögerung bei Lese- und Schreibvorgängen führt. Nach erfolgreichem Abschluss des Vorgangs können die Berichte nicht wieder in den Status „Online“ zurückverschoben werden und bleiben weiterhin im Status „gesperrt“. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1246327["1246327"^] | Beobachtete I/O-Verzögerungen und Rports werden während des Speicher-Failovers mit Qlogic QLE2672(16G) und QLE2742(32G) in den Status „gesperrt“, „NICHT VORHANDEN“ verschoben. | Fibre-Channel-Remote-Ports (FC) können bei Red hat Enterprise Linux (RHEL) 7.6 mit dem QLogic QLE2672 16G-Host während Storage-Failover-Vorgängen blockiert werden. Da bei einem Ausfall eines Storage-Node die logischen Schnittstellen ausfallen, setzen die Remote-Ports den Status des Storage-Node auf „gesperrt“. Der I/O-Fortschritt wird aufgrund der blockierten Ports möglicherweise angehalten, wenn sowohl ein QLogic QLE2672 16G-Host als auch ein QLE2742 32-GB-FC-Host-Bus-Adapter (HBA) ausgeführt werden. Wenn der Storage-Node wieder in seinen optimalen Status wechselt, werden auch die logischen Schnittstellen angezeigt, und die Remote-Ports sollten online sein. Die Remote-Ports sind jedoch möglicherweise immer noch blockiert. Dieser blockierte Status wird als fehlerhaft für LUNS auf der Multipath-Ebene registriert. Sie können den Status der Remote-Ports mit folgendem Befehl überprüfen: # CAT /sys/class/fc_Remote_Ports/rport-*/Port_stat Sie sollten folgende Ausgabe sehen: Blocked Blocked Blocked Online 
|===


== Was kommt als Nächstes?

* link:hu-luhu-command-reference.html["Erfahren Sie mehr über die Verwendung des Linux Host Utilities-Tools"] .
* Erfahren Sie mehr über ASM Mirroring.
+
Bei der ASM-Spiegelung (Automatic Storage Management) sind möglicherweise Änderungen an den Linux Multipath-Einstellungen erforderlich, damit ASM ein Problem erkennen und zu einer alternativen Fehlergruppe wechseln kann. Die meisten ASM-Konfigurationen auf ONTAP verwenden externe Redundanz, was bedeutet, dass Datenschutz vom externen Array bereitgestellt wird und ASM keine Daten spiegelt. Einige Standorte verwenden ASM mit normaler Redundanz, um normalerweise zwei-Wege-Spiegelung über verschiedene Standorte hinweg bereitzustellen. Weitere Informationen finden Sie unterlink:https://docs.netapp.com/us-en/ontap-apps-dbs/oracle/oracle-overview.html["Oracle-Datenbanken auf ONTAP"^].


