---
sidebar: sidebar 
permalink: hu_rhel_75.html 
keywords: host utilities, red hat, rhel, linux, 7.5, netapp, ontap 
summary: Beschreibt die Verwendung von Red hat Enterprise Linux 7.5 mit ONTAP 
---
= Einsatz von Red hat Enterprise Linux 7.5 mit NetApp ONTAP
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content




== Installieren der Linux Unified Host Utilities

Das NetApp Linux Unified Host Utilities-Softwarepaket ist auf der erhältlich link:https://mysupport.netapp.com/NOW/cgi-bin/software/?product=Host+Utilities+-+SAN&platform=Linux["NetApp Support Website"^] In einer 32-Bit- und 64-Bit-.rpm-Datei. Wenn Sie nicht wissen, welche Datei für Ihre Konfiguration geeignet ist, verwenden Sie den link:https://mysupport.netapp.com/matrix/#welcome["NetApp Interoperabilitäts-Matrix-Tool"^] Um zu überprüfen, welches Sie benötigen.

Es wird dringend empfohlen, Linux Unified Host Utilities zu installieren, jedoch nicht zwingend. Die Dienstprogramme ändern keine Einstellungen auf Ihrem Linux-Host. Die Versorgungseinrichtungen verbessern das Management und unterstützen den NetApp Kunden-Support bei der Erfassung von Informationen zu Ihrer Konfiguration.

Wenn Sie derzeit eine Version von Linux Unified Host Utilities installiert haben, sollten Sie sie aktualisieren oder Sie sollten sie entfernen und die folgenden Schritte verwenden, um die neueste Version zu installieren.

. Laden Sie das Softwarepaket für 32 Bit oder 64 Bit Linux Unified Host Utilities von herunter link:https://mysupport.netapp.com/NOW/cgi-bin/software/?product=Host+Utilities+-+SAN&platform=Linux["NetApp Support Website"^] Standort zu Ihrem Host.
. Verwenden Sie den folgenden Befehl, um das Softwarepaket zu installieren:
+
`rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_64`




NOTE: Sie können die in diesem Inhalt angegebenen Konfigurationseinstellungen verwenden, um die mit verbundenen Cloud-Clients zu konfigurieren link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] Und link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["Amazon FSX für ONTAP"^].



== SAN Toolkit

Das Toolkit wird automatisch installiert, wenn Sie das NetApp Host Utilities-Paket installieren. Dieses Kit enthält die `sanlun` Dienstprogramm: Unterstützt Sie beim Management von LUNs und HBAs. Der `sanlun` Befehl gibt Informationen über die LUNs zurück, die Ihrem Host zugeordnet sind, Multipathing und Informationen zurück, die zum Erstellen von Initiatorgruppen erforderlich sind.

Im folgenden Beispiel wird der verwendet `sanlun lun show` Befehl gibt LUN-Informationen zurück.

[listing]
----
# sanlun lun show all
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
-------------------------------------------------------------------------
data_vserver          /vol/vol1/lun1   /dev/sdb   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol1/lun1   /dev/sdc   host15   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sdd   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sde   host15   FCP       120.0g  cDOT
----


== SAN wird gebootet

Wenn Sie sich für das Booten über SAN entscheiden, muss es von Ihrer Konfiguration unterstützt werden. Sie können das verwenden link:https://mysupport.netapp.com/matrix/imt.jsp?components=82985;&solution=1&isHWU&src=IMT["NetApp Interoperabilitäts-Matrix-Tool"^] Um zu überprüfen, ob Ihr Betriebssystem, HBA, die HBA-Firmware und das HBA-Boot-BIOS sowie die ONTAP-Version unterstützt werden.

.Schritte
. Ordnen Sie die SAN-Boot-LUN dem Host zu.
. Vergewissern Sie sich, dass mehrere Pfade verfügbar sind.
+
Denken Sie daran, dass mehrere Pfade nur verfügbar sind, wenn das Host-Betriebssystem betriebsbereit ist und auf den Pfaden ausgeführt wird.

. Aktivieren Sie das SAN-Booten im Server-BIOS für die Ports, denen die SAN-Boot-LUN zugeordnet ist.
+
Informationen zum Aktivieren des HBA-BIOS finden Sie in der anbieterspezifischen Dokumentation.

. Starten Sie den Host neu, um sicherzustellen, dass der Startvorgang erfolgreich ist.




== Multipathing

Für Red hat Enterprise Linux (RHEL) 7.5 muss die Datei /etc/Multipath.conf vorhanden sein, Sie müssen jedoch keine spezifischen Änderungen an der Datei vornehmen. RHEL 7.5 wird mit allen Einstellungen zusammengestellt, die zum Erkennen und korrekten Managen von ONTAP-LUNs erforderlich sind.

Sie können das verwenden `multipath -ll` Überprüfen Sie mit dem Befehl die Einstellungen für Ihre ONTAP LUNs. Die folgenden Abschnitte enthalten ein Beispiel für eine Multipath-Ausgabe für eine LUN, die ASA- und nicht-ASA-Personas zugeordnet ist.



=== Konfiguration einer All-SAN-Array-Lösung

In allen ASA-Konfigurationen (SAN Array) sind alle Pfade zu einer bestimmten logischen Einheit (LUN) aktiv und optimiert. Das bedeutet, dass I/O gleichzeitig über alle Pfade bedient werden kann, was zu einer besseren Performance führt.

Im folgenden Beispiel wird die richtige Ausgabe für eine ONTAP LUN angezeigt:

[listing]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G  features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 11:0:7:1    sdfi   130:64   active ready running
  |- 11:0:9:1    sdiy  8:288     active ready running
  |- 11:0:10:1  sdml 69:464   active ready running
  |- 11:0:11:1  sdpt  131:304  active ready running
----

NOTE: Verwenden Sie keine unverhältnismäßig hohe Anzahl von Pfaden zu einer einzelnen LUN. Es sollten nicht mehr als 4 Pfade erforderlich sein. Mehr als 8 Pfade können bei Storage-Ausfällen zu Pfadproblemen führen.



=== Nicht-ASA-Konfiguration

Für eine nicht-ASA-Konfiguration sollte es zwei Gruppen von Pfaden mit unterschiedlichen Prioritäten geben. Die Pfade mit den höheren Prioritäten sind aktiv/optimiert, was bedeutet, dass sie vom Controller gewartet werden, wo sich das Aggregat befindet. Die Pfade mit den niedrigeren Prioritäten sind aktiv, werden aber nicht optimiert, da sie von einem anderen Controller bereitgestellt werden. Die nicht optimierten Pfade werden nur verwendet, wenn keine optimierten Pfade verfügbar sind.

Im folgenden Beispiel wird die richtige Ausgabe für eine ONTAP-LUN mit zwei aktiv/optimierten Pfaden und zwei aktiv/nicht optimierten Pfaden angezeigt:

[listing]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle’ hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 11:0:1:0 sdj  8:144  active ready running
| |- 11:0:2:0 sdr  65:16  active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 11:0:0:0 sdb  8:i6   active ready running
  |- 12:0:0:0 sdz  65:144 active ready running
----

NOTE: Verwenden Sie keine unverhältnismäßig hohe Anzahl von Pfaden zu einer einzelnen LUN. Es sollten nicht mehr als 4 Pfade erforderlich sein. Mehr als 8 Pfade können bei Storage-Ausfällen zu Pfadproblemen führen.



== Empfohlene Einstellungen

Das RHEL 7.5 Betriebssystem wird kompiliert, um ONTAP-LUNs zu erkennen und automatisch alle Konfigurationsparameter für ASA- und nicht-ASA-Konfigurationen korrekt festzulegen.

Der `multipath.conf` Datei muss vorhanden sein, damit der Multipath-Daemon gestartet werden kann. Sie können jedoch mit dem Befehl eine leere Zero-Byte-Datei erstellen:
`touch /etc/multipath.conf`

Wenn Sie diese Datei zum ersten Mal erstellen, müssen Sie die Multipath-Services unter Umständen aktivieren und starten.

[listing]
----
# systemctl enable multipathd
# systemctl start multipathd
----
Es sind keine Anforderungen, direkt etwas hinzuzufügen `multipath.conf` Datei, es sei denn, Sie haben Geräte, die Sie nicht von Multipath verwalten möchten, oder Sie haben bereits vorhandene Einstellungen, die die Standardeinstellungen überschreiben.

Sie können die folgende Syntax dem hinzufügen `multipath.conf` Datei zum Ausschließen unerwünschter Geräte.

Ersetzen Sie den `<DevId>` Mit der WWID-Zeichenfolge des Geräts, das Sie ausschließen möchten. Verwenden Sie den folgenden Befehl, um die WWID zu bestimmen:

....
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
....
In diesem Beispiel `sda` Ist die lokale SCSI Festplatte, die wir Blacklist benötigen.

.Schritte
. Führen Sie den folgenden Befehl aus, um die WWID zu bestimmen:
+
....
# /lib/udev/scsi_id -gud /dev/sda
360030057024d0730239134810c0cb833
....
. Fügen Sie diese WWID der schwarzen Liste Stanza im hinzu `/etc/multipath.conf`:
+
....
blacklist {
     wwid   360030057024d0730239134810c0cb833
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
....


Sie sollten immer Ihre überprüfen `/etc/multipath.conf` Datei für ältere Einstellungen, insbesondere im Abschnitt Standardeinstellungen, die möglicherweise die Standardeinstellungen überschreiben.

Die folgende Tabelle zeigt den entscheidenden `multipathd` Parameter für ONTAP-LUNs und die erforderlichen Werte. Wenn ein Host mit LUNs anderer Anbieter verbunden ist und einer dieser Parameter außer Kraft gesetzt wird, müssen sie später in korrigiert werden `multipath.conf` Die speziell für ONTAP LUNs gelten. Wenn dies nicht erfolgt, funktionieren die ONTAP LUNs möglicherweise nicht wie erwartet. Diese Standardeinstellungen sollten nur in Absprache mit NetApp und/oder dem Anbieter des Betriebssystems außer Kraft gesetzt werden und nur dann, wenn die Auswirkungen vollständig verstanden wurden.

[cols="2*"]
|===
| Parameter | Einstellung 


| Erkennen_Prio | ja 


| Dev_Loss_tmo | „Unendlich“ 


| Failback | Sofort 


| Fast_io_fail_tmo | 5 


| Funktionen | „3 queue_if_no_Pg_init_retries 50“ 


| Flush_on_Last_del | „ja“ 


| Hardware_Handler | „0“ 


| Kein_PATH_retry | Warteschlange 


| PATH_Checker | „nur“ 


| Path_Grouping_Policy | „Group_by_prio“ 


| Pfad_Auswahl | „Servicezeit 0“ 


| Polling_Interval | 5 


| prio | ONTAP 


| Produkt | LUN.* 


| Beibehalten_Attached_hw_Handler | ja 


| rr_weight | „Einheitlich“ 


| User_friendly_names | Nein 


| Anbieter | NETAPP 
|===
Das folgende Beispiel zeigt, wie eine überhielte Standardeinstellung korrigiert wird. In diesem Fall die `multipath.conf` Datei definiert Werte für `path_checker` Und `no_path_retry` Die nicht mit ONTAP LUNs kompatibel sind. Wenn sie nicht entfernt werden können, weil andere SAN-Arrays noch an den Host angeschlossen sind, können diese Parameter speziell für ONTAP-LUNs mit einem Device stanza korrigiert werden.

[listing]
----
defaults {
   path_checker      readsector0
   no_path_retry      fail
}

devices {
   device {
      vendor         "NETAPP  "
      product         "LUN.*"
      no_path_retry     queue
      path_checker      tur
   }
}
----


=== KVM-Einstellungen

Sie können die empfohlenen Einstellungen verwenden, um Kernel-Based Virtual Machine (KVM) ebenfalls zu konfigurieren. Es sind keine Änderungen erforderlich, um KVM zu konfigurieren, da die LUN dem Hypervisor zugeordnet ist.



== Bekannte Probleme und Einschränkungen

[cols="4*"]
|===
| NetApp Bug ID | Titel | Beschreibung | Bugzilla-ID 


| 1440718 | Wenn Sie eine LUN ohne SCSI-erneute Zuordnung aufheben oder zuordnen, kann dies zu Datenbeschädigungen auf dem Host führen. | Wenn Sie den Multipath-Konfigurationsparameter 'disable_changed_wwids' auf YES setzen, wird der Zugriff auf das Pfadgerät bei einer WWID-Änderung deaktiviert. Multipath deaktiviert den Zugriff auf das Pfadgerät, bis die WWID des Pfads auf die WWID des Multipath-Geräts wiederhergestellt ist. Weitere Informationen finden Sie unter link:https://kb.netapp.com/Advice_and_Troubleshooting/Flash_Storage/AFF_Series/The_filesystem_corruption_on_iSCSI_LUN_on_the_Oracle_Linux_7["NetApp Knowledge Base: Beschädigung des Dateisystems auf iSCSI LUN auf Oracle Linux 7"^]. | K. A. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1139053["1139053"^] | Kernel-Störung tritt bei RHEL7.5 mit QLogic QLE2672 16 GB FC beim Storage Failover-Betrieb auf | Während Storage Failover-Vorgänge auf dem RHEL7U5 Kernel mit QLogic QLE2672 16 GB Fibre Channel Host Bus Adapter, tritt die Kernel-Störung aufgrund einer Panic im Kernel auf. Die Kernel-Panic bewirkt einen Neustart von RHEL 7.5, was zu einer Applikationsunterbrechung führt. Wenn kdump konfiguriert ist, generiert die Kernel-Panic die vmcore-Datei unter dem Verzeichnis /var/crash/Directory. Die vmcore-Datei wird verwendet, um die Ursache des Fehlers zu verstehen. In diesem Fall wurde die Panik im Modul „get_next_timer_Interrupt+440“ beobachtet, das in der vmcore-Datei mit der folgenden Zeichenfolge angemeldet ist: " [Ausnahme RIP: Get_next_timer_Interrupt+440]" nach der Kernel-Störung können Sie das Betriebssystem wiederherstellen, indem Sie das Host-Betriebssystem neu starten und die Anwendung nach Bedarf neu starten. | link:https://bugzilla.redhat.com/show_bug.cgi?id=1542564["1542564"^] 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1138536["1138536"^] | Kernel-Störung tritt bei RHEL7U5 mit QLogic QLE2742 32 GB FC während eines Storage Failover-Betriebs auf | Während Storage Failover-Vorgänge auf dem Red hat Enterprise Linux (RHEL) RHEL7U5 Kernel mit QLogic QLE2742 HBA treten Kernel-Unterbrechungen aufgrund einer Panikmache im Kernel auf. Die Kernel-Panic führt zu einem Neustart des Betriebssystems, was zu einer Anwendungsunterbrechung führt. Wenn kdump konfiguriert ist, generiert die Kernel-Panic die vmcore-Datei unter dem Verzeichnis /var/crash/. Wenn der Kernel eine Panik gibt, können Sie die vmcore-Datei verwenden, um den Grund für den Ausfall zu ermitteln. Das folgende Beispiel zeigt eine Panik im bget_next_timer_Interrupt+440b Modul. Die Panik wird in der vmcore-Datei mit der folgenden Zeichenfolge protokolliert: " [Ausnahme-RIP: Get_next_Timer_Interrupt+440]" Sie können das Betriebssystem wiederherstellen, indem Sie das Host-Betriebssystem neu starten und die Anwendung nach Bedarf neu starten. | link:https://bugzilla.redhat.com/show_bug.cgi?id=1541972["1541972"^] 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1148090["1148090"^] | Kernel-Störung tritt bei RHEL 7.5 mit QLogic QLE2742 32 GB FC HBA bei Storage Failover-Vorgängen auf | Bei Storage Failover-Vorgängen auf dem Red hat Enterprise Linux (RHEL) 7.5 Kernel mit einem QLogic QLE2742 Fibre Channel (FC) Host Bus Adapter (HBA) tritt eine Kernel-Störung auf, da eine Panik im Kernel auftritt. Die Kernel-Panic bewirkt einen Neustart von RHEL 7.5, was zu einer Applikationsunterbrechung führt. Wenn der kdump-Mechanismus aktiviert ist, generiert die Kernel Panic eine vmcore-Datei im Verzeichnis /var/crash/. Sie können die vmcore-Datei analysieren, um die Ursache der Panik zu ermitteln. Wenn in dieser Instanz ein Storage Failover mit dem QLogic QLE2742 HBA-Ereignis auftritt, ist das Modul „native_warteschlange_spin_lock_langsampath+464“ betroffen. Sie können das Ereignis in der vmcore-Datei finden, indem Sie die folgende Zeichenfolge finden: „ [Ausnahme-RIP: Native_quined_Spin_Lock_langsampath+464]“ nach der Kernel-Störung können Sie das Host-Betriebssystem neu starten und das Betriebssystem wiederherstellen. Anschließend können Sie die Anwendungen nach Bedarf neu starten. | link:https://bugzilla.redhat.com/show_bug.cgi?id=1559050["1559050"^] 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1146898["1146898"^] | Bei einem Storage Failover tritt bei RHEL 7.5 mit Emulex HBAs eine Kernelunterbrechung auf | Bei Storage Failover-Vorgängen auf einem Red hat Enterprise Linux (RHEL) 7.5 System mit Emulex LPe32002-M2 32-GB FC-Host-Bus-Adaptern (HBAs) tritt eine Störung des Kernels auf. Die Kernel-Störung verursacht einen Neustart des Betriebssystems, was wiederum zu einer Anwendungsunterbrechung führt. Wenn Sie kdump konfigurieren, generiert die Kernel-Störung die vmcore-Datei im Verzeichnis /var/crash/. Sie können die Ursache des Fehlers in der vmcore-Datei ermitteln. Im folgenden Beispiel sehen Sie die Störung im Modul „lpfc_hba_clean_txcmplq+368“. Diese Störung wird in der vmcore-Datei mit der folgenden Zeichenfolge protokolliert: „ [Ausnahme-RIP: Lpfc_hba_clean_txcmplq+368]“ nach der Kernel-Störung, starten Sie das Host-Betriebssystem neu, um das Betriebssystem wiederherzustellen. Applikation nach Bedarf neu starten. | link:https://bugzilla.redhat.com/show_bug.cgi?id=1554777["1554777"^] 
|===


== Versionshinweise



=== ASM Mirroring

ASM Spiegelung erfordert möglicherweise Änderungen an den Linux Multipath-Einstellungen, damit ASM ein Problem erkennt und auf eine andere Fehlergruppe umschaltet. Die meisten ASM-Konfigurationen auf ONTAP verwenden externe Redundanz. Das bedeutet, dass Datensicherung durch das externe Array bereitgestellt wird und ASM keine Daten spiegelt. Einige Standorte verwenden ASM mit normaler Redundanz, um normalerweise zwei-Wege-Spiegelung über verschiedene Standorte hinweg bereitzustellen. Siehe link:https://www.netapp.com/us/media/tr-3633.pdf["Oracle-Datenbanken auf ONTAP"^] Für weitere Informationen.
