---
sidebar: sidebar 
permalink: hu_rhel_65.html 
keywords: host utilities, red hat, rhel, linux, 6.5, netapp, ontap 
summary: Beschreibt die Verwendung von Red hat Enterprise Linux 6.5 mit ONTAP 
---
= Verwenden Sie Red hat Enterprise Linux 6.5 mit ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können die Konfigurationseinstellungen des ONTAP-SAN-Hosts verwenden, um Red hat Enterprise Linux 6.5 mit ONTAP als Ziel zu konfigurieren.



== Installieren Sie die Linux Unified Host Utilities

Das NetApp Linux Unified Host Utilities-Softwarepaket ist auf dem  in einer 32-Bit- und 64-Bit-RPM-Datei verfügbarlink:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["NetApp Support Website"^]. Wenn Sie nicht wissen, welche Datei für Ihre Konfiguration geeignet ist, überprüfen Sie mithilfe der, welche Datei link:https://mysupport.netapp.com/matrix/#welcome["NetApp Interoperabilitäts-Matrix-Tool"^]Sie benötigen.

NetApp empfiehlt ausdrücklich die Installation der Linux Unified Host Utilities, dies ist jedoch nicht zwingend erforderlich. Die Dienstprogramme ändern keine Einstellungen auf Ihrem Linux-Host. Die Versorgungseinrichtungen verbessern das Management und unterstützen den NetApp Kunden-Support bei der Erfassung von Informationen zu Ihrer Konfiguration.

Wenn Sie Linux Unified Host Utilities derzeit installiert haben, sollten Sie entweder ein Upgrade auf die neueste Version durchführen oder diese entfernen und die aktuelle Version wie folgt installieren.

.Schritte
. Laden Sie das Softwarepaket für 32 Bit oder 64 Bit Linux Unified Host Utilities von herunter link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["NetApp Support Website"^] Auf Ihren Host.
. Installieren des Softwarepakets:
+
`rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_64`




NOTE: Sie können die in diesem Dokument angegebenen Konfigurationseinstellungen verwenden, um die mit verbundenen Cloud-Clients zu konfigurieren link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] Und link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["Amazon FSX für ONTAP"^].



== SAN Toolkit

Das Toolkit wird automatisch installiert, wenn Sie das NetApp Host Utilities-Paket installieren. Dieses Kit enthält die `sanlun` Dienstprogramm: Unterstützt Sie beim Management von LUNs und HBAs. Der `sanlun` Befehl gibt Informationen über die LUNs zurück, die Ihrem Host zugeordnet sind, Multipathing und Informationen zurück, die zum Erstellen von Initiatorgruppen erforderlich sind.

.Beispiel
Im folgenden Beispiel wird der verwendet `sanlun lun show` Befehl gibt LUN-Informationen zurück.

[source, cli]
----
# sanlun lun show all
----
Beispielausgabe:

[listing]
----
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
------------------------------------------------------------------------------------
data_vserver          /vol/vol1/lun1   /dev/sdb   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol1/lun1   /dev/sdc   host15   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sdd   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sde   host15   FCP       120.0g  cDOT
----


== SAN wird gebootet

.Was Sie benötigen
Wenn Sie sich für das Booten über SAN entscheiden, muss es von Ihrer Konfiguration unterstützt werden. Sie können das verwenden link:https://mysupport.netapp.com/matrix/imt.jsp?components=67197;&solution=1&isHWU&src=IMT["NetApp Interoperabilitäts-Matrix-Tool"^] Um zu überprüfen, ob Ihr Betriebssystem, HBA, die HBA-Firmware und das HBA-Boot-BIOS sowie die ONTAP-Version unterstützt werden.

.Schritte
. Ordnen Sie die SAN-Boot-LUN dem Host zu.
. Vergewissern Sie sich, dass mehrere Pfade verfügbar sind.
+

NOTE: Mehrere Pfade sind verfügbar, nachdem das Host-Betriebssystem auf den Pfaden ausgeführt wurde.

. Aktivieren Sie das SAN-Booten im Server-BIOS für die Ports, denen die SAN-Boot-LUN zugeordnet ist.
+
Informationen zum Aktivieren des HBA-BIOS finden Sie in der anbieterspezifischen Dokumentation.

. Starten Sie den Host neu, um zu überprüfen, ob der Startvorgang erfolgreich war.




== Multipathing

Für Red hat Enterprise Linux (RHEL) 6.5 muss die Datei /etc/Multipath.conf vorhanden sein, Sie müssen jedoch keine spezifischen Änderungen an der Datei vornehmen. RHEL 6.5 wird mit allen Einstellungen zusammengestellt, die zum Erkennen und korrekten Managen von ONTAP-LUNs erforderlich sind. So aktivieren Sie ALUA Handler:

.Schritte
. Erstellen Sie ein Backup des initrd-Images.
. Hängen Sie den folgenden Parameterwert an den Kernel an, damit ALUA und Non-ALUA funktionieren:
`rdloaddriver=scsi_dh_alua`
+
....
kernel /vmlinuz-2.6.32-358.6.1.el6.x86_64 ro root=/dev/mapper/ vg_ibmx355021082-lv_root rd_NO_LUKS rd_LVM_LV=vg_ibmx355021082/ lv_root LANG=en_US.UTF-8 rd_LVM_LV=vg_ibmx355021082/lv_swap rd_NO_MD SYSFONT=latarcyrheb-sun16 crashkernel=auto KEYBOARDTYPE=pc KEYTABLE=us rd_NO_DM rhgb quiet rdloaddriver=scsi_dh_alua
....
. Verwenden Sie die `mkinitrd` Befehl zum Neuerstellen des initrd-Image. RHEL 6x und neuere Versionen verwenden entweder: Den Befehl: `mkinitrd -f /boot/ initrd-"uname -r".img uname -r`Oder den Befehl: `dracut -f`
. Starten Sie den Host neu.
. Überprüfen Sie die Ausgabe des `cat /proc/cmdline` Befehl, um sicherzustellen, dass die Einstellung abgeschlossen ist.


Sie können das verwenden `multipath -ll` Überprüfen Sie mit dem Befehl die Einstellungen für Ihre ONTAP LUNs.

Die folgenden Abschnitte bieten Beispiel-Multipath-Ausgaben für eine LUN, die ASA-Gruppen und nicht-ASA-Personas zugeordnet ist.



=== Alle SAN-Array-Konfigurationen

In Konfigurationen mit allen SAN-Arrays (ASA) sind alle Pfade zu einer bestimmten LUN aktiv und optimiert. Dies verbessert die Performance, da I/O-Operationen über alle Pfade gleichzeitig ausgeführt werden können.

.Beispiel
Im folgenden Beispiel wird die richtige Ausgabe für eine ONTAP LUN angezeigt:

[listing]
----
# multipath -ll
3600a0980383034466b2b4a3775474859 dm-3 NETAPP,LUN C-Mode
size=20G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='round-robin 0' prio=50 status=active
|- 1:0:8:1  sdb 8:16 active ready running
|- 2:0:8:1  sdd 8:48 active ready running
|- 1:0:9:1  sdc 8:32 active ready running
|- 2:0:9:1  sde 8:64 active ready running
----

NOTE: Eine einzelne LUN sollte nicht mehr als vier Pfade benötigen. Eine Verfügbarkeit von mehr als vier Pfaden kann bei Storage-Ausfällen zu Pfadproblemen führen.



=== Konfigurationen ohne ASA

Für Konfigurationen ohne ASA sollten zwei Gruppen von Pfaden mit unterschiedlichen Prioritäten vorhanden sein. Die Pfade mit höheren Prioritäten sind aktiv/optimiert, d. h. sie werden vom Controller gewartet, in dem sich das Aggregat befindet. Die Pfade mit niedrigeren Prioritäten sind aktiv, aber nicht optimiert, da sie von einem anderen Controller bedient werden. Die nicht optimierten Pfade werden nur verwendet, wenn optimierte Pfade nicht verfügbar sind.

.Beispiel
Im folgenden Beispiel wird die richtige Ausgabe für eine ONTAP-LUN mit zwei aktiv/optimierten Pfaden und zwei aktiv/nicht optimierten Pfaden angezeigt:

[listing]
----
# multipath -ll
3600a0980383034466b2b4a3775474859 dm-3 NETAPP,LUN C-Mode
size=20G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='round-robin 0' prio=50 status=active
| |- 1:0:8:1  sdb 8:16 active ready running
| `- 2:0:8:1  sdd 8:48 active ready running
`-+- policy='round-robin 0' prio=10 status=enabled
  |- 1:0:9:1  sdc 8:32 active ready running
  `- 2:0:9:1  sde 8:64 active ready running
----

NOTE: Eine einzelne LUN sollte nicht mehr als vier Pfade benötigen. Eine Verfügbarkeit von mehr als vier Pfaden kann bei Storage-Ausfällen zu Pfadproblemen führen.



== Empfohlene Einstellungen

Das RHEL 6.5 Betriebssystem wird kompiliert, um ONTAP-LUNs zu erkennen und automatisch alle Konfigurationsparameter für ASA- und nicht-ASA-Konfigurationen korrekt festzulegen.

Die `multipath.conf` Datei muss vorhanden sein, damit der Multipath-Daemon gestartet werden kann. Wenn diese Datei nicht vorhanden ist, können Sie eine leere, Null-Byte-Datei mit dem Befehl erstellen `touch /etc/multipath.conf`.

Wenn Sie die `multipath.conf` Datei zum ersten Mal erstellen, müssen Sie möglicherweise die Multipath-Services mithilfe der folgenden Befehle aktivieren und starten:

`# chkconfig multipathd on`
`# /etc/init.d/multipathd start`

Sie müssen der Datei nichts direkt hinzufügen `multipath.conf`, es sei denn, Sie verfügen über Geräte, die nicht von Multipath verwaltet werden sollen, oder Sie haben bereits vorhandene Einstellungen, die die Standardeinstellungen außer Kraft setzen. Um unerwünschte Geräte auszuschließen, fügen Sie der `multipath.conf` Datei die folgende Syntax hinzu und ersetzen <DevId> durch die WWID-Zeichenfolge des Geräts, das Sie ausschließen möchten:

[listing]
----
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----
Das folgende Beispiel bestimmt die WWID eines Geräts und fügt sie der Datei hinzu `multipath.conf`.

.Schritte
. Bestimmen Sie die WWID:
+
[listing]
----
# /lib/udev/scsi_id -gud /dev/sda
360030057024d0730239134810c0cb833
----
+
`sda` Ist das lokale SCSI-Laufwerk, das Sie der Blacklist hinzufügen möchten.

. Fügen Sie die hinzu `WWID` Zur schwarzen Liste stanza in `/etc/multipath.conf`:
+
[listing]
----
blacklist {
     wwid   360030057024d0730239134810c0cb833
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----


Überprüfen Sie Ihre Datei immer `/etc/multipath.conf`, insbesondere im Abschnitt „Standardeinstellungen“, auf ältere Einstellungen, die die Standardeinstellungen überschreiben könnten.

In der folgenden Tabelle sind die kritischen `multipathd` Parameter für ONTAP-LUNs und die erforderlichen Werte aufgeführt. Wenn ein Host mit LUNs anderer Hersteller verbunden ist und diese Parameter überschrieben werden, müssen sie durch spätere Strophen in der `multipath.conf` Datei korrigiert werden, die speziell für ONTAP-LUNs gelten. Ohne diese Korrektur funktionieren die ONTAP-LUNs möglicherweise nicht wie erwartet. Sie sollten diese Standardeinstellungen nur in Absprache mit NetApp, dem OS-Anbieter oder beiden außer Kraft setzen, und zwar nur dann, wenn die Auswirkungen vollständig verstanden sind.

[cols="2*"]
|===
| Parameter | Einstellung 


| Erkennen_Prio | ja 


| Dev_Loss_tmo | „Unendlich“ 


| Failback | Sofort 


| Fast_io_fail_tmo | 5 


| Funktionen | „3 queue_if_no_Pg_init_retries 50“ 


| Flush_on_Last_del | „ja“ 


| Hardware_Handler | „0“ 


| Kein_PATH_retry | Warteschlange 


| PATH_Checker | „nur“ 


| Path_Grouping_Policy | „Group_by_prio“ 


| Pfad_Auswahl | „Round Robin 0“ 


| Polling_Interval | 5 


| prio | ONTAP 


| Produkt | LUN.* 


| Beibehalten_Attached_hw_Handler | ja 


| rr_weight | „Einheitlich“ 


| User_friendly_names | Nein 


| Anbieter | NETAPP 
|===
.Beispiel
Das folgende Beispiel zeigt, wie eine überhielte Standardeinstellung korrigiert wird. In diesem Fall die `multipath.conf` Datei definiert Werte für `path_checker` Und `no_path_retry` Die nicht mit ONTAP LUNs kompatibel sind. Wenn sie nicht entfernt werden können, weil andere SAN-Arrays noch an den Host angeschlossen sind, können diese Parameter speziell für ONTAP-LUNs mit einem Device stanza korrigiert werden.

[listing]
----
defaults {
   path_checker      readsector0
   no_path_retry      fail
}

devices {
   device {
      vendor         "NETAPP  "
      product         "LUN.*"
      no_path_retry     queue
      path_checker      tur
   }
}
----


=== KVM-Einstellungen

Sie können die empfohlenen Einstellungen verwenden, um Kernel-Based Virtual Machine (KVM) ebenfalls zu konfigurieren. Es sind keine Änderungen erforderlich, um KVM zu konfigurieren, da die LUN dem Hypervisor zugeordnet ist.



== Bekannte Probleme

Die RHEL 6.5 mit ONTAP-Version weist folgende bekannte Probleme auf:

[cols="3*"]
|===
| NetApp Bug ID | Titel | Beschreibung 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=760515["760515"^] | Bei einem RHEL 6.5 8G Qlogic FC SAN-Host wurden Pfadausfälle oder Host-hängt während eines Storage-Failover-Betriebs beobachtet | Bei einem RHEL 6.5 8G Qlogic FC SAN-Host wurden Pfadausfälle oder Host-hängt während eines Storage-Failover-Betriebs beobachtet. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=758271["758271"^] | Bnx2-Firmware wird beim Booten mit Custom initrd nicht geladen (dracut -f) | Broadcom NetXtreme II Gigabit-Controller-Ports pingen nicht aufgrund bnx2-Firmware wird während des Starts mit benutzerdefinierter Initrd nicht geladen. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=799394["799394"^] | RHEL 6U5: Host-Absturz durch Emulex 16G FC (LPe16002B-M6) wird bei I/O-Vorgängen bei Storage Failover beobachtet | Emulex (LPe16002B-M6) Host-Absturz wird während der I/O bei Storage Failover-Vorgängen beobachtet. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=786571["786571"^] | QLogic FCoE-Host-Hänger-/Pfadausfälle, die bei einem Storage-Failover in RHEL 6.5 bei I/O-Vorgängen beobachtet wurden | QLogic FCoE (QLE8242) -Host-Ausfälle und -Pfade werden bei RHEL 6.5 während I/O-Vorgängen bei Storage-Failover beobachtet. In solchen Szenarien sehen Sie die folgende Meldung: "Mailbox cmd timeout aufgetreten, cmd=0x54, mb[0]=0x54. ISP-Planung abbrechen“-Nachrichten, die zu Host-Hung/Pfad-Fehler führen. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=801580["801580"^] | QLogic 16G FC-Host-Hänger oder Pfadausfälle, die bei RHEL 6.5 bei I/O-Vorgängen bei Storage-Failover beobachtet werden | Die I/O-Verzögerungen von mehr als 600 Sekunden werden bei QLogic 16G FC-Host (QLE2672) bei Storage Failover-Vorgängen beobachtet. In solchen Szenarien wird die folgende Meldung angezeigt: „Failed mbx[0]=54, mb[1]=0, mb[2]=76b9, mb[3]=5200, cmd=54“ 
|===