---
sidebar: sidebar 
permalink: hu_rhel_75.html 
keywords: host utilities, red hat, rhel, linux, 7.5, netapp, ontap 
summary: Beschreibt die Verwendung von Red hat Enterprise Linux 7.5 mit ONTAP 
---
= Verwenden Sie Red hat Enterprise Linux 7.5 mit ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können die Konfigurationseinstellungen des ONTAP-SAN-Hosts verwenden, um Red hat Enterprise Linux 7.5 mit ONTAP als Ziel zu konfigurieren.



== Installieren Sie die Linux Unified Host Utilities

Das NetApp Linux Unified Host Utilities-Softwarepaket ist auf der erhältlich link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["NetApp Support Website"^] In einer 32-Bit- und 64-Bit-.rpm-Datei. Wenn Sie nicht wissen, welche Datei für Ihre Konfiguration geeignet ist, verwenden Sie den link:https://mysupport.netapp.com/matrix/#welcome["NetApp Interoperabilitäts-Matrix-Tool"^] Um zu überprüfen, welches Sie benötigen.

NetApp empfiehlt ausdrücklich die Installation der Linux Unified Host Utilities, dies ist jedoch nicht zwingend erforderlich. Die Dienstprogramme ändern keine Einstellungen auf Ihrem Linux-Host. Die Versorgungseinrichtungen verbessern das Management und unterstützen den NetApp Kunden-Support bei der Erfassung von Informationen zu Ihrer Konfiguration.

Wenn Sie derzeit eine Version von Linux Unified Host Utilities installiert haben, sollten Sie diese entweder aktualisieren oder entfernen und die aktuelle Version wie folgt installieren.

.Schritte
. Laden Sie das Softwarepaket für 32 Bit oder 64 Bit Linux Unified Host Utilities von herunter link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["NetApp Support Website"^] Standort zu Ihrem Host.
. Verwenden Sie den folgenden Befehl, um das Softwarepaket zu installieren:
+
`rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_64`




NOTE: Sie können die in diesem Dokument angegebenen Konfigurationseinstellungen verwenden, um die mit verbundenen Cloud-Clients zu konfigurieren link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] Und link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["Amazon FSX für ONTAP"^].



== SAN Toolkit

Das Toolkit wird automatisch installiert, wenn Sie das NetApp Host Utilities-Paket installieren. Dieses Kit enthält die `sanlun` Dienstprogramm: Unterstützt Sie beim Management von LUNs und HBAs. Der `sanlun` Befehl gibt Informationen über die LUNs zurück, die Ihrem Host zugeordnet sind, Multipathing und Informationen zurück, die zum Erstellen von Initiatorgruppen erforderlich sind.

.Beispiel
Im folgenden Beispiel wird der verwendet `sanlun lun show` Befehl gibt LUN-Informationen zurück.

[source, cli]
----
# sanlun lun show all
----
Beispielausgabe:

[listing]
----
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
------------------------------------------------------------------------------------
data_vserver          /vol/vol1/lun1   /dev/sdb   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol1/lun1   /dev/sdc   host15   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sdd   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sde   host15   FCP       120.0g  cDOT
----


== SAN wird gebootet

.Was Sie benötigen
Wenn Sie sich für das Booten über SAN entscheiden, muss es von Ihrer Konfiguration unterstützt werden. Sie können das verwenden link:https://mysupport.netapp.com/matrix/imt.jsp?components=82985;&solution=1&isHWU&src=IMT["NetApp Interoperabilitäts-Matrix-Tool"^] Um zu überprüfen, ob Ihr Betriebssystem, HBA, die HBA-Firmware und das HBA-Boot-BIOS sowie die ONTAP-Version unterstützt werden.

.Schritte
. Ordnen Sie die SAN-Boot-LUN dem Host zu.
. Vergewissern Sie sich, dass mehrere Pfade verfügbar sind.
+

NOTE: Mehrere Pfade sind verfügbar, nachdem das Host-Betriebssystem auf den Pfaden ausgeführt wurde.

. Aktivieren Sie das SAN-Booten im Server-BIOS für die Ports, denen die SAN-Boot-LUN zugeordnet ist.
+
Informationen zum Aktivieren des HBA-BIOS finden Sie in der anbieterspezifischen Dokumentation.

. Starten Sie den Host neu, um zu überprüfen, ob der Startvorgang erfolgreich war.




== Multipathing

Für Red hat Enterprise Linux (RHEL) 7.5 muss die Datei /etc/Multipath.conf vorhanden sein, Sie müssen jedoch keine spezifischen Änderungen an der Datei vornehmen. RHEL 7.5 wird mit allen Einstellungen zusammengestellt, die zum Erkennen und korrekten Managen von ONTAP-LUNs erforderlich sind.

Sie können das verwenden `multipath -ll` Überprüfen Sie mit dem Befehl die Einstellungen für Ihre ONTAP LUNs.

Die folgenden Abschnitte bieten Beispiel-Multipath-Ausgaben für eine LUN, die ASA-Gruppen und nicht-ASA-Personas zugeordnet ist.



=== Alle SAN-Array-Konfigurationen

In Konfigurationen mit allen SAN-Arrays (ASA) sind alle Pfade zu einer bestimmten LUN aktiv und optimiert. Dies verbessert die Performance, da I/O-Operationen über alle Pfade gleichzeitig ausgeführt werden können.

.Beispiel
Im folgenden Beispiel wird die richtige Ausgabe für eine ONTAP LUN angezeigt:

[listing]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G  features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 11:0:7:1    sdfi   130:64   active ready running
  |- 11:0:9:1    sdiy  8:288     active ready running
  |- 11:0:10:1  sdml 69:464   active ready running
  |- 11:0:11:1  sdpt  131:304  active ready running
----

NOTE: Eine einzelne LUN sollte nicht mehr als vier Pfade benötigen. Eine Verfügbarkeit von mehr als vier Pfaden kann bei Storage-Ausfällen zu Pfadproblemen führen.



=== Konfigurationen ohne ASA

Für Konfigurationen ohne ASA sollten zwei Gruppen von Pfaden mit unterschiedlichen Prioritäten vorhanden sein. Die Pfade mit höheren Prioritäten sind aktiv/optimiert, d. h. sie werden vom Controller gewartet, in dem sich das Aggregat befindet. Die Pfade mit niedrigeren Prioritäten sind aktiv, aber nicht optimiert, da sie von einem anderen Controller bedient werden. Die nicht optimierten Pfade werden nur verwendet, wenn optimierte Pfade nicht verfügbar sind.

.Beispiel
Im folgenden Beispiel wird die richtige Ausgabe für eine ONTAP-LUN mit zwei aktiv/optimierten Pfaden und zwei aktiv/nicht optimierten Pfaden angezeigt:

[listing]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle’ hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 11:0:1:0 sdj  8:144  active ready running
| |- 11:0:2:0 sdr  65:16  active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 11:0:0:0 sdb  8:i6   active ready running
  |- 12:0:0:0 sdz  65:144 active ready running
----

NOTE: Eine einzelne LUN sollte nicht mehr als vier Pfade benötigen. Eine Verfügbarkeit von mehr als vier Pfaden kann bei Storage-Ausfällen zu Pfadproblemen führen.



== Empfohlene Einstellungen

Das RHEL 7.5 Betriebssystem wird kompiliert, um ONTAP-LUNs zu erkennen und automatisch alle Konfigurationsparameter für ASA- und nicht-ASA-Konfigurationen korrekt festzulegen.

Die `multipath.conf` Datei muss vorhanden sein, damit der Multipath-Daemon gestartet werden kann. Wenn diese Datei nicht vorhanden ist, können Sie mit dem Befehl eine leere, Null-Byte-Datei erstellen `touch /etc/multipath.conf`

Wenn Sie die `multipath.conf` Datei zum ersten Mal erstellen, müssen Sie möglicherweise die Multipath-Services mithilfe der folgenden Befehle aktivieren und starten:

`# chkconfig multipathd on`
`# /etc/init.d/multipathd start`

Sie müssen der Datei nichts direkt hinzufügen `multipath.conf`, es sei denn, Sie verfügen über Geräte, die nicht von Multipath verwaltet werden sollen, oder Sie haben bereits vorhandene Einstellungen, die die Standardeinstellungen außer Kraft setzen. Um unerwünschte Geräte auszuschließen, fügen Sie der `multipath.conf` Datei die folgende Syntax hinzu und ersetzen <DevId> durch die WWID-Zeichenfolge des Geräts, das Sie ausschließen möchten:

[listing]
----
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----
Das folgende Beispiel bestimmt die WWID eines Geräts und fügt sie der Datei hinzu `multipath.conf`.

.Schritte
. Bestimmen Sie die WWID:
+
[listing]
----
# /lib/udev/scsi_id -gud /dev/sda
360030057024d0730239134810c0cb833
----
+
`sda` Ist das lokale SCSI-Laufwerk, das Sie der Blacklist hinzufügen möchten.

. Fügen Sie die hinzu `WWID` Zur schwarzen Liste stanza in `/etc/multipath.conf`:
+
[listing]
----
blacklist {
     wwid   360030057024d0730239134810c0cb833
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----


Überprüfen Sie Ihre Datei immer `/etc/multipath.conf`, insbesondere im Abschnitt „Standardeinstellungen“, auf ältere Einstellungen, die die Standardeinstellungen überschreiben können.

In der folgenden Tabelle sind die kritischen `multipathd` Parameter für ONTAP-LUNs und die erforderliche Einstellung aufgeführt. Wenn ein Host mit LUNs anderer Hersteller verbunden ist und diese Parameter überschrieben werden, müssen sie durch spätere Strophen in der `multipath.conf` Datei korrigiert werden, die speziell für ONTAP-LUNs gelten. Ohne diese Korrektur funktionieren die ONTAP-LUNs möglicherweise nicht wie erwartet. Sie sollten diese Standardeinstellungen nur in Absprache mit NetApp, dem OS-Anbieter oder beiden außer Kraft setzen, und zwar nur dann, wenn die Auswirkungen vollständig verstanden sind.

[cols="2*"]
|===
| Parameter | Einstellung 


| Erkennen_Prio | ja 


| Dev_Loss_tmo | „Unendlich“ 


| Failback | Sofort 


| Fast_io_fail_tmo | 5 


| Funktionen | „3 queue_if_no_Pg_init_retries 50“ 


| Flush_on_Last_del | „ja“ 


| Hardware_Handler | „0“ 


| Kein_PATH_retry | Warteschlange 


| PATH_Checker | „nur“ 


| Path_Grouping_Policy | „Group_by_prio“ 


| Pfad_Auswahl | „Servicezeit 0“ 


| Polling_Interval | 5 


| prio | ONTAP 


| Produkt | LUN.* 


| Beibehalten_Attached_hw_Handler | ja 


| rr_weight | „Einheitlich“ 


| User_friendly_names | Nein 


| Anbieter | NETAPP 
|===
.Beispiel
Das folgende Beispiel zeigt, wie eine überhielte Standardeinstellung korrigiert wird. In diesem Fall die `multipath.conf` Datei definiert Werte für `path_checker` Und `no_path_retry` Die nicht mit ONTAP LUNs kompatibel sind. Wenn sie nicht entfernt werden können, weil andere SAN-Arrays noch an den Host angeschlossen sind, können diese Parameter speziell für ONTAP-LUNs mit einem Device stanza korrigiert werden.

[listing]
----
defaults {
   path_checker      readsector0
   no_path_retry      fail
}

devices {
   device {
      vendor         "NETAPP  "
      product         "LUN.*"
      no_path_retry     queue
      path_checker      tur
   }
}
----


=== KVM-Einstellungen

Sie können die empfohlenen Einstellungen verwenden, um Kernel-Based Virtual Machine (KVM) ebenfalls zu konfigurieren. Es sind keine Änderungen erforderlich, um KVM zu konfigurieren, da die LUN dem Hypervisor zugeordnet ist.



== Bekannte Probleme

Die RHEL 7.5 mit ONTAP-Version weist folgende bekannte Probleme auf:

[cols="3*"]
|===
| NetApp Bug ID | Titel | Beschreibung 


| 1440718 | Wenn Sie eine LUN ohne SCSI-erneute Zuordnung aufheben oder zuordnen, kann dies zu Datenbeschädigungen auf dem Host führen. | Wenn Sie den Multipath-Konfigurationsparameter 'disable_changed_wwids' auf YES setzen, wird der Zugriff auf das Pfadgerät bei einer WWID-Änderung deaktiviert. Multipath deaktiviert den Zugriff auf das Pfadgerät, bis die WWID des Pfads auf die WWID des Multipath-Geräts wiederhergestellt ist. Weitere Informationen finden Sie unter link:https://kb.netapp.com/Advice_and_Troubleshooting/Flash_Storage/AFF_Series/The_filesystem_corruption_on_iSCSI_LUN_on_the_Oracle_Linux_7["NetApp Knowledge Base: Beschädigung des Dateisystems auf iSCSI LUN auf Oracle Linux 7"^]. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1139053["1139053"^] | Kernel-Störung tritt bei RHEL7.5 mit QLogic QLE2672 16 GB FC beim Storage Failover-Betrieb auf | Während Storage Failover-Vorgänge auf dem RHEL7U5 Kernel mit QLogic QLE2672 16 GB Fibre Channel Host Bus Adapter, tritt die Kernel-Störung aufgrund einer Panic im Kernel auf. Die Kernel-Panic bewirkt einen Neustart von RHEL 7.5, was zu einer Applikationsunterbrechung führt. Wenn kdump konfiguriert ist, generiert die Kernel-Panic die vmcore-Datei unter dem Verzeichnis /var/crash/Directory. Die vmcore-Datei wird verwendet, um die Ursache des Fehlers zu verstehen. In diesem Fall wurde die Panik im Modul „get_next_timer_Interrupt+440“ beobachtet, das in der vmcore-Datei mit der folgenden Zeichenfolge angemeldet ist: " [Ausnahme RIP: Get_next_timer_Interrupt+440]" nach der Kernel-Störung können Sie das Betriebssystem wiederherstellen, indem Sie das Host-Betriebssystem neu starten und die Anwendung nach Bedarf neu starten. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1138536["1138536"^] | Kernel-Störung tritt bei RHEL7U5 mit QLogic QLE2742 32 GB FC während eines Storage Failover-Betriebs auf | Während Storage Failover-Vorgänge auf dem Red hat Enterprise Linux (RHEL) RHEL7U5 Kernel mit QLogic QLE2742 HBA treten Kernel-Unterbrechungen aufgrund einer Panikmache im Kernel auf. Die Kernel-Panic führt zu einem Neustart des Betriebssystems, was zu einer Anwendungsunterbrechung führt. Wenn kdump konfiguriert ist, generiert die Kernel-Panic die vmcore-Datei unter dem Verzeichnis /var/crash/. Wenn der Kernel eine Panik gibt, können Sie die vmcore-Datei verwenden, um den Grund für den Ausfall zu ermitteln. Das folgende Beispiel zeigt eine Panik im bget_next_timer_Interrupt+440b Modul. Die Panik wird in der vmcore-Datei mit der folgenden Zeichenfolge protokolliert: " [Ausnahme-RIP: Get_next_Timer_Interrupt+440]" Sie können das Betriebssystem wiederherstellen, indem Sie das Host-Betriebssystem neu starten und die Anwendung nach Bedarf neu starten. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1148090["1148090"^] | Kernel-Störung tritt bei RHEL 7.5 mit QLogic QLE2742 32 GB FC HBA bei Storage Failover-Vorgängen auf | Bei Storage Failover-Vorgängen auf dem Red hat Enterprise Linux (RHEL) 7.5 Kernel mit einem QLogic QLE2742 Fibre Channel (FC) Host Bus Adapter (HBA) tritt eine Kernel-Störung auf, da eine Panik im Kernel auftritt. Die Kernel-Panic bewirkt einen Neustart von RHEL 7.5, was zu einer Applikationsunterbrechung führt. Wenn der kdump-Mechanismus aktiviert ist, generiert die Kernel Panic eine vmcore-Datei im Verzeichnis /var/crash/. Sie können die vmcore-Datei analysieren, um die Ursache der Panik zu ermitteln. Wenn in dieser Instanz ein Storage Failover mit dem QLogic QLE2742 HBA-Ereignis auftritt, ist das Modul „native_warteschlange_spin_lock_langsampath+464“ betroffen. Sie können das Ereignis in der vmcore-Datei finden, indem Sie die folgende Zeichenfolge finden: „ [Ausnahme-RIP: Native_quined_Spin_Lock_langsampath+464]“ nach der Kernel-Störung können Sie das Host-Betriebssystem neu starten und das Betriebssystem wiederherstellen. Anschließend können Sie die Anwendungen nach Bedarf neu starten. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1146898["1146898"^] | Bei einem Storage Failover tritt bei RHEL 7.5 mit Emulex HBAs eine Kernelunterbrechung auf | Bei Storage Failover-Vorgängen auf einem Red hat Enterprise Linux (RHEL) 7.5 System mit Emulex LPe32002-M2 32-GB FC-Host-Bus-Adaptern (HBAs) tritt eine Störung des Kernels auf. Die Kernel-Störung verursacht einen Neustart des Betriebssystems, was wiederum zu einer Anwendungsunterbrechung führt. Wenn Sie kdump konfigurieren, generiert die Kernel-Störung die vmcore-Datei im Verzeichnis /var/crash/. Sie können die Ursache des Fehlers in der vmcore-Datei ermitteln. Im folgenden Beispiel sehen Sie die Störung im Modul „lpfc_hba_clean_txcmplq+368“. Diese Störung wird in der vmcore-Datei mit der folgenden Zeichenfolge protokolliert: „ [Ausnahme-RIP: Lpfc_hba_clean_txcmplq+368]“ nach der Kernel-Störung, starten Sie das Host-Betriebssystem neu, um das Betriebssystem wiederherzustellen. Applikation nach Bedarf neu starten. 
|===