---
sidebar: sidebar 
permalink: hu_solaris_114.html 
keywords: host utilities, solaris, 114, netapp, ontap 
summary: Beschreibt die Verwendung von IBM AIX 7.2 und/oder PowerVM VIOS 3.1 mit ONTAP 
---
= Verwenden von Solaris 11.4 mit NetApp ONTAP
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content




== Installieren der Solaris Host Utilities

Sie können die komprimierte Datei mit den Host Utilities Softwarepaketen von herunterladen link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab["NetApp Support Website"^]. Nachdem die Datei vorliegt, müssen Sie sie dekomprimieren, um die Softwarepakete zu erhalten, die Sie zur Installation der Host Utilities benötigen.

.Schritte
. Laden Sie eine Kopie der komprimierten Datei mit den Host Utilities von herunter link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab["NetApp Support Website"^] Zu einem Verzeichnis auf Ihrem Host.
. Gehen Sie zu dem Verzeichnis, in dem der Download enthalten ist.
. Dekomprimieren Sie die Datei.
+
Im folgenden Beispiel werden Dateien für ein SPARC System dekomprimiert. Verwenden Sie für x86-64-Plattformen den `x86/x64` Paket.

+
`gunzip netapp_solaris_host_utilities_6_2N20170913_0304_sparc.tar.gz`

. Verwenden Sie die `tar xvf` Befehl zum Enttar der Datei.
+
`tar xvf netapp_solaris_host_utilities_6_2N20170913_0304_sparc.tar`

. Fügen Sie die Pakete, die Sie aus der tar-Datei extrahiert haben, zu Ihrem Host hinzu.
+
`pkgadd -d NTAPSANTool.pkg`

+
Die Pakete werden dem hinzugefügt `/opt/NTAP/SANToolkit/bin` Verzeichnis.

+
Um die Installation abzuschließen, müssen Sie die Hostparameter für Ihre Umgebung (in diesem Fall MPxIO) mithilfe der konfigurieren `host_config` Befehl.

+
Der `host_config` Befehl weist das folgende Format auf:

+
`/opt/NTAP/SANToolkit/bin/host_config <-setup> <-protocol fcp|iscsi|mixed> <-multipath mpxio|dmp| non> [-noalua] [-mcc 60|90|120]`

+
Der `host_config` Befehl führt Folgendes aus:

+
** Ändert die Fibre-Channel- und SCSI-Treibereinstellungen für X86- und SPARC-Systeme
** Stellt SCSI-Timeout-Einstellungen für die MPxIO-Konfigurationen bereit
** Legt die VID-/PID-Informationen fest
** Aktiviert oder deaktiviert ALUA
** Konfiguration der von MPxIO und den SCSI-Treibern für X86- und SPARC-Systeme verwendeten ALUA-Einstellungen


. Starten Sie den Host neu.




== SAN-Toolkit

Das Toolkit wird automatisch installiert, wenn Sie das NetApp Host Utilities-Paket installieren. Dieses Kit enthält die `sanlun` Dienstprogramm: Unterstützt Sie beim Management von LUNs und HBAs. Der `sanlun` Befehl gibt Informationen über die LUNs zurück, die Ihrem Host zugeordnet sind, Multipathing und Informationen zurück, die zum Erstellen von Initiatorgruppen erforderlich sind.

.Beispiel
Im folgenden Beispiel wird der verwendet `sanlun lun show` Befehl gibt LUN-Informationen zurück.

[listing]
----
#sanlun lun show

controller(7mode)/                 device                                            host             lun
vserver(Cmode)     lun-pathname    filename                                         adapter protocol  size  mode
------------------------------------------------------------------------------------------------------
data_vserver       /vol/vol1/lun1  /dev/rdsk/c0t600A098038314362692451465A2F4F39d0s2  qlc1  FCP       60g   C
data_vserver       /vol/vol2/lun2  /dev/rdsk/c0t600A098038314362705D51465A626475d0s2  qlc1  FCP       20g   C
----


== SAN Booting

.Was Sie benötigen
Wenn Sie sich für das Booten über SAN entscheiden, muss es von Ihrer Konfiguration unterstützt werden. Sie können das verwenden link:https://mysupport.netapp.com/matrix/imt.jsp?components=71102;&solution=1&isHWU&src=IMT["NetApp Interoperabilitäts-Matrix-Tool"^] Um zu überprüfen, ob Ihr Betriebssystem, HBA, die HBA-Firmware und das HBA-Boot-BIOS sowie die ONTAP-Version unterstützt werden.

BEIM BOOTEN VON SAN wird ein SAN-Attached-Laufwerk (eine LUN) als Startgerät für einen Solaris-Host eingerichtet.

Sie können eine SAN-Boot-LUN einrichten, die in einer Solaris MPxIO-Umgebung mit dem FC-Protokoll und unter Verwendung der Solaris Host Utilities ausgeführt wird. Die Methode zur Einrichtung einer SAN-Boot-LUN kann je nach Volume-Manager und Dateisystem variieren. Siehe https://["Installieren Sie Solaris Host Utilities"] Für Details zum Booten von SAN-LUNs in einer Solaris MPIO-Umgebung.



== Multipathing

Multipathing ermöglicht Ihnen die Konfiguration mehrerer Netzwerkpfade zwischen dem Host und dem Storage-System. Falls ein Pfad ausfällt, wird der Verkehr auf den verbleibenden Pfaden fortgesetzt. Oracle Solaris I/O Multipathing (MPxIO) ist standardmäßig für Solaris 11.4 aktiviert. Die Standardeinstellung in `/kernel/drv/fp.conf` Änderungen in mpxio-disable=„no“.



=== Nicht-ASA-Konfiguration

Für eine nicht-ASA-Konfiguration sollte es zwei Gruppen von Pfaden mit unterschiedlichen Prioritäten geben. Die Pfade mit den höheren Prioritäten sind aktiv/optimiert, was bedeutet, dass sie vom Controller gewartet werden, wo sich das Aggregat befindet. Die Pfade mit den niedrigeren Prioritäten sind aktiv, werden aber nicht optimiert, da sie von einem anderen Controller bereitgestellt werden. Die nicht optimierten Pfade werden nur verwendet, wenn keine optimierten Pfade verfügbar sind.

.Beispiel
Im folgenden Beispiel wird die richtige Ausgabe für eine ONTAP-LUN mit zwei aktiv/optimierten Pfaden und zwei aktiv/nicht optimierten Pfaden angezeigt:

Die Pfadprioritäten werden für jede LUN im nativen Betriebssystem für den Abschnitt *Zugriffsstatus* angezeigt `mpathadm show lu <LUN>` Befehl.



=== Konfiguration einer All-SAN-Array-Lösung

In allen ASA-Konfigurationen (SAN Array) sind alle Pfade zu einer bestimmten logischen Einheit (LUN) aktiv und optimiert. Das bedeutet, dass I/O gleichzeitig über alle Pfade bedient werden kann, was zu einer besseren Performance führt.

.Beispiel
Im folgenden Beispiel wird die richtige Ausgabe für eine ONTAP LUN angezeigt:

Die Ausgabe für das `sanlun` Der Befehl ist für ASA- und nicht-ASA-Konfigurationen identisch.

Die Pfadprioritäten werden für jede LUN im nativen Betriebssystem für den Abschnitt *Zugriffsstatus* angezeigt `mpathadm show lu <LUN>` Befehl.

[listing]
----
#sanlun lun show -pv sparc-s7-16-49:/vol/solaris_vol_1_0/solaris_lun

                    ONTAP Path: sparc-s7-16-49:/vol/solaris_vol_1_0/solaris_lun
                           LUN: 0
                      LUN Size: 30g
                   Host Device: /dev/rdsk/c0t600A098038314362692451465A2F4F39d0s2
                          Mode: C
            Multipath Provider: Sun Microsystems
              Multipath Policy: Native
----

NOTE: Alle SAN-Arrays (ASA)-Konfigurationen werden ab ONTAP 9.8 für Solaris-Hosts unterstützt.



== Empfohlene Einstellungen

Im Folgenden finden Sie einige Parametereinstellungen, die für Solaris 11.4 SPARC und x86_64 mit NetApp ONTAP LUNs empfohlen werden. Diese Parameterwerte werden von Host Utilities festgelegt. Weitere Einstellungen für Solaris 11.4-Systeme finden Sie unter Oracle DOC-ID: 2595926.1

[cols="2*"]
|===
| Parameter | Wert 


| Drosselklappe_max | 8 


| Not_ready_Wiederholungen | 300 


| Busy_Wiederholungen | 30 


| Reset_Wiederholungen | 30 


| Drosselklappe_min | 2 


| Timeout_Wiederholungen | 10 


| Physische_Block_size | 4096 
|===


=== Empfohlene Einstellungen für MetroCluster

Standardmäßig schlägt das Betriebssystem Solaris nach 20 Sekunden I/OS fehl, wenn alle Pfade zu einer LUN verloren gehen. Dies wird von der gesteuert `fcp_offline_delay` Parameter. Der Standardwert für `fcp_offline_delay` Eignet sich für Standard-ONTAP-Cluster. In MetroCluster-Konfigurationen bietet sich jedoch der Nutzen von `fcp_offline_delay` Muss auf *120 s* erhöht werden, um sicherzustellen, dass I/O nicht zu einer frühzeitigen Auszeit während des Betriebs, einschließlich nicht ungeplanter Failover, erfolgt. Weitere Informationen und empfohlene Änderungen an den Standardeinstellungen finden Sie im Knowledge Base-Artikel https://["Überlegungen zum Support von Solaris Hosts in einer MetroCluster-Konfiguration"^].



== Oracle Solaris Virtualisierung

* Die Virtualisierungsoptionen von Solaris umfassen logische Solaris Domains (auch LDOMs oder Oracle VM Server für SPARC), Solaris Dynamic Domains, Solaris Zones und Solaris Container. Diese Technologien wurden im Allgemeinen als „Oracle Virtual Machines“ umbenannt, obwohl sie auf verschiedenen Architekturen basieren.
* In einigen Fällen können mehrere Optionen zusammen verwendet werden, z. B. ein Solaris Container in einer bestimmten logischen Solaris-Domäne.
* NetApp unterstützt die Nutzung dieser Virtualisierungstechnologien, bei denen die gesamte Konfiguration von Oracle unterstützt wird und jede Partition mit direktem Zugriff auf LUNs ist auf der aufgeführt link:https://mysupport.netapp.com/matrix/imt.jsp?components=95803;&solution=1&isHWU&src=IMT["NetApp Interoperabilitätsmatrix"^] In einer unterstützten Konfiguration. Dazu gehören Root-Container, LDOM IO-Domänen und LDOM, die NPIV für den Zugriff auf LUNs verwenden.
* Partitionen und/oder virtuelle Maschinen, die nur virtualisierte Speicherressourcen wie z. B. vdsk nutzen, benötigen keine spezielle Qualifizierung, da sie keinen direkten Zugriff auf NetApp LUNs haben. Nur die Partition/VM, die direkten Zugriff auf die zugrunde liegende LUN hat, wie beispielsweise eine LDOM IO-Domäne, muss in der gefunden werden link:https://mysupport.netapp.com/matrix/imt.jsp?components=95803;&solution=1&isHWU&src=IMT["NetApp Interoperabilitätsmatrix"^].




=== Empfohlene Einstellungen für Virtualisierung

Wenn LUNs als virtuelle Festplattengeräte innerhalb eines LDOM verwendet werden, wird die Quelle der LUN durch Virtualisierung maskiert. LDOM erkennt die Blockgrößen nicht richtig. Um dieses Problem zu vermeiden, muss das LDOM-Betriebssystem für _Oracle Bug 15824910_ und A gepatcht werden `vdc.conf` Datei muss erstellt werden, die die Blockgröße des virtuellen Laufwerks auf 4096 setzt. Weitere Informationen finden Sie im Oracle Doc 2157669.1.

So überprüfen Sie den Patch:

.Schritte
. Erstellen Sie ein zpool.
. Laufen `zdb -C` Gegen den zpool und überprüfen Sie, dass der Wert von *ashift* 12 ist.
+
Wenn der Wert von *ashift* nicht 12 ist, überprüfen Sie, ob der richtige Patch installiert wurde, und überprüfen Sie den Inhalt von `vdc.conf`.

+
Fahren Sie erst fort, wenn *ashift* einen Wert von 12 anzeigt.




NOTE: Patches sind verfügbar für Oracle Bug 15824910 auf verschiedenen Versionen von Solaris. Wenden Sie sich an Oracle, wenn Sie Hilfe beim ermitteln des besten Kernel-Patches benötigen.



== Empfohlene Einstellungen für SnapMirror Business Continuity

Um sicherzustellen, dass die Solaris Client-Applikationen bei einer ungeplanten Failover-Umschaltung in einer SnapMirror Business Continuity (SM-BC)-Umgebung unterbrechungsfrei laufen, müssen Sie die folgende Einstellung auf dem Solaris 11.4-Host konfigurieren. Diese Einstellung überschreibt das Failover-Modul `f_tpgs` Um die Ausführung des Codepfads zu verhindern, der den Widerspruch erkennt.


NOTE: Ab ONTAP 9.9 werden die SM-BC-Einstellungskonfigurationen auf dem Solaris 11.4 Host unterstützt.

Befolgen Sie die Anweisungen, um den Überschreibungsparameter zu konfigurieren:

. Erstellen Sie die Konfigurationsdatei `/etc/driver/drv/scsi_vhci.conf` Bei einem Eintrag, der dem folgenden ähnlich ist, für den NetApp-Speichertyp, der mit dem Host verbunden ist:
+
[listing]
----
scsi-vhci-failover-override =
"NETAPP  LUN","f_tpgs"
----
. Verwenden Sie die `devprop` Und `mdb` Befehle, um zu überprüfen, ob der Override-Parameter erfolgreich angewendet wurde:
+
`root@host-A:~# devprop -v -n /scsi_vhci scsi-vhci-failover-override      scsi-vhci-failover-override=NETAPP  LUN + f_tpgs
root@host-A:~# echo "*scsi_vhci_dip::print -x struct dev_info devi_child | ::list struct dev_info devi_sibling| ::print struct dev_info devi_mdi_client| ::print mdi_client_t ct_vprivate| ::print struct scsi_vhci_lun svl_lun_wwn svl_fops_name"| mdb -k`

+
[listing]
----
svl_lun_wwn = 0xa002a1c8960 "600a098038313477543f524539787938"
svl_fops_name = 0xa00298d69e0 "conf f_tpgs"
----



NOTE: Nachher `scsi-vhci-failover-override` Wurde angewendet, `conf` Wird hinzugefügt zu `svl_fops_name` . Weitere Informationen und empfohlene Änderungen an den Standardeinstellungen finden Sie im NetApp KB-Artikel https://["Solaris Host Support Empfohlene Einstellungen in SnapMirror Business Continuity (SM-BC)-Konfiguration"^].



== Bekannte Probleme und Einschränkungen

[cols="4*"]
|===
| NetApp Bug ID | Titel | Beschreibung | Oracle-ID 


| 1362435 | Änderungen an HUK 6.2- und Solaris_11.4-FC-Treibern verbindlich | Befolgen Sie die Empfehlungen von Solaris 11.4 und HUK. Die FC-Treiberbindung wird von ssd(4D) zu sd(4D) geändert. Verschieben Sie die Konfiguration in `ssd.conf` Bis `sd.conf` Wie in Oracle beschrieben (Doc ID 2595926.1). Das Verhalten variiert zwischen neu installiertem Solaris 11.4-System und einem Upgrade von 11.3 oder niedriger Versionen. | (DOC-ID 2595926.1) 


| 1366780 | Solaris LIF-Problem während GB mit Emulex 32G HBA auf x86 Arch | Gesehen mit Emulex-Firmware-Version 12.6.x und höher auf x86_64-Plattform | SR 3-24746803021 


| 1368957 | Solaris 11.x `cfgadm -c configure` Dies führt zu einem E/A-Fehler bei einer End-to-End-Emulex-Konfiguration | Wird Ausgeführt `cfgadm -c configure` Führen bei Emulex End-to-End-Konfigurationen zu einem I/O-Fehler. Dies ist in 9.5P17, 9.6P14 , 9.7P13 und 9.8P2 behoben | NA 


| 1345622 | Anormale Pfadberichte auf Solaris-Hosts mit ASA/PPorts unter Verwendung systemeigener Befehle | Probleme mit der Meldung von Pfaden auf Solaris 11.4 mit ASA | Keine Angabe 
|===