---
sidebar: sidebar 
permalink: hu_solaris_62.html 
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap 
summary: Beschreibt die Verwendung von Linux Unified Host Utilities 7.1 mit ONTAP 
---
= Installieren Sie Solaris Host Utilities 6.2
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die Solaris Unified Host Utilities unterstützen Sie bei der Verwaltung von NetApp ONTAP-Speicher, der mit einem Solaris-Host verbunden ist.

Solaris Host Utilities 6.2 unterstützt mehrere Solaris Umgebungen und Protokolle. Die primären Host-Utilities-Umgebungen sind:

* Natives Betriebssystem mit MPxIO mit Fibre Channel (FC) oder iSCSI-Protokoll auf einem System mit SPARC-Prozessor oder x86/64-Prozessor.
* Veritas Dynamic Multipathing (DMP) mit dem FC- oder iSCSI-Protokoll auf einem System mit SPARC Prozessor oder dem iSCSI-Protokoll auf einem System mit x86/64-Prozessor.


Solaris Unified Host Utilities 6.2 unterstützt weiterhin die folgenden Versionen von Solaris:

* Solaris 11.x-Serie
* Solaris 10.x-Serie


.Was Sie benötigen
* Stellen Sie für einen zuverlässigen Betrieb sicher, dass Ihre gesamte iSCSI-, FC- oder FCoE-Konfiguration unterstützt wird.


Sie können das verwenden link:https://mysupport.netapp.com/matrix/imt.jsp?components=71102;&solution=1&isHWU&src=IMT["NetApp Interoperabilitäts-Matrix-Tool"^] Um Ihre Konfiguration zu überprüfen.


NOTE: Das Software-Paket NetApp Solaris Host Utilities steht auf der zur Verfügung link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/6.2/downloads["NetApp Support Website"^] In einem komprimierten Dateiformat für Ihren Prozessor. Sie können das Host Utilities Software-Paket für Ihre Umgebung von der Support-Website herunterladen.

.Schritte
. Melden Sie sich bei Ihrem Host als Root an.
. Laden Sie eine Kopie der komprimierten Datei mit den Host Utilities von herunter link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/6.2/downloads["NetApp Support Website"^] Zu einem Verzeichnis auf Ihrem Host.
+
Zum Zeitpunkt der Erstellung dieser Dokumentation wurden die komprimierten Dateien aufgerufen:

+
** SPARC CPU: `netapp_solaris_host_utilities_6_2_sparc.tar.gz`
** X86/x64-CPU: `netapp_solaris_host_utilities_6_2_amd.tar.gz`


. Gehen Sie zu dem Verzeichnis, in dem der Download enthalten ist.
. Entpacken Sie die Datei mithilfe des `gunzip` Befehl:
+
`# gunzip netapp_solaris_host_utilities_6_2_sparc.tar.gz`

. Entpacken Sie die Datei. Sie können das verwenden `tar xvf` Befehl um dies zu tun.
+
`# tar xvf netapp_solaris_host_utilities_6_2_sparc.tar`

. Fügen Sie die Pakete, die Sie aus tar-Datei extrahiert haben, zu Ihrem Host hinzu. Sie können das verwenden `pkgadd` Befehl um dies zu tun.
+
Die Pakete werden dem hinzugefügt `/opt/NTAP/SANToolkit/bin` Verzeichnis. Im folgenden Beispiel wird das verwendet `pkgadd` Befehl zum Installieren des Solaris Installationspakets:

+
`# pkgadd -d ./NTAPSANTool.pkg`

. Bestätigen Sie, dass das Toolkit erfolgreich mit dem installiert wurde `pkginfo` Befehl oder das `ls - al` Befehl.
+
[listing]
----
# ls -alR /opt/NTAP/SANToolkit
/opt/NTAP/SANToolkit:
total 1038
drwxr-xr-x   3 root     sys            4 Jul 22  2019 .
drwxr-xr-x   3 root     sys            3 Jul 22  2019 ..
drwxr-xr-x   2 root     sys            6 Jul 22  2019 bin
-r-xr-xr-x   1 root     sys       432666 Sep 13  2017 NOTICES.PDF

/opt/NTAP/SANToolkit/bin:
total 7962
drwxr-xr-x   2 root     sys            6 Jul 22  2019 .
drwxr-xr-x   3 root     sys            4 Jul 22  2019 ..
-r-xr-xr-x   1 root     sys      2308252 Sep 13  2017 host_config
-r-xr-xr-x   1 root     sys          995 Sep 13  2017 san_version
-r-xr-xr-x   1 root     sys      1669204 Sep 13  2017 sanlun
-r-xr-xr-x   1 root     sys          677 Sep 13  2017 vidpid.dat

# (cd /usr/share/man/man1; ls -al host_config.1 sanlun.1)
-r-xr-xr-x   1 root     sys        12266 Sep 13  2017 host_config.1
-r-xr-xr-x   1 root     sys         9044 Sep 13  2017 sanlun.1
----
. Konfigurieren Sie anschließend die Host-Parameter für Ihre Umgebung mithilfe der `/opt/NTAP/SANToolkit/bin/host_config` Befehl:
+
** Mpxio
** Veritas DMP


. Überprüfen Sie die Installation:
+
`sanlun version`





== SAN Toolkit

Solaris Host Utilities ist eine NetApp Host Software, die auf Ihrem Oracle Solaris Host ein Befehlszeilen-Toolkit bietet. Das Toolkit wird bei der Installation des NetApp Host Utilities-Pakets installiert. Dieses Kit enthält die `sanlun` Dienstprogramm zum Verwalten von LUNs und Host Bus Adaptern (HBAs). Der `sanlun` Befehl gibt Informationen über die LUNs zurück, die Ihrem Host zugeordnet sind, Multipathing und Informationen zurück, die zum Erstellen von Initiatorgruppen erforderlich sind.

.Beispiel
Im folgenden Beispiel wird der verwendet `sanlun lun show` Mit dem Befehl werden die LUN-Informationen zurückgegeben.

[listing]
----
#sanlun lun show all
controller(7mode)/ device host lun
vserver(Cmode)                     lun-pathname       filename                                       adapter protocol size mode
-----------------------------------------------------------------------------------------------------------------------------------
data_vserver                     /vol/vol1/lun1     /dev/rdsk/c0t600A098038304437522B4E694E49792Dd0s2 qlc3   FCP       10g cDOT
data_vserver                     /vol/vol0/lun2     /dev/rdsk/c0t600A098038304437522B4E694E497938d0s2 qlc3   FCP       10g cDOT
data_vserver                     /vol/vol2/lun3     /dev/rdsk/c0t600A098038304437522B4E694E497939d0s2 qlc3   FCP       10g cDOT
data_vserver                     /vol/vol3/lun4     /dev/rdsk/c0t600A098038304437522B4E694E497941d0s2 qlc3   FCP       10g cDOT


----

NOTE: Dieses Toolkit ist für alle Host Utilities-Konfigurationen und -Protokolle üblich. Daher können einige Toolkit-Inhalte auf eine Konfiguration angewendet werden, aber nicht auf eine andere. Ungenutzte Komponenten haben keine Auswirkungen auf die Systemleistung.
