---
sidebar: sidebar 
permalink: hu_solaris_114.html 
keywords: host utilities, solaris, 114, netapp, ontap 
summary: Beschreibt die Verwendung von IBM AIX 7.2 und/oder PowerVM VIOS 3.1 mit ONTAP 
---
= Verwenden Sie Solaris 11.4 mit ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können die Konfigurationseinstellungen des ONTAP-SAN-Hosts verwenden, um Solaris 11.4 mit ONTAP als Ziel zu konfigurieren.



== Installieren Sie die Solaris Host Utilities

Sie können die komprimierte Datei mit den Host Utilities Softwarepaketen von herunterladen https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/6.2/downloads["NetApp Support Website"^]. Nachdem Sie die Datei heruntergeladen haben, müssen Sie die ZIP-Datei extrahieren, um die Softwarepakete zu erhalten, die Sie zur Installation der Host Utilities benötigen.

.Schritte
. Laden Sie eine Kopie der komprimierten Datei mit den Host Utilities von herunter https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/6.2/downloads["NetApp Support Website"^] Zu einem Verzeichnis auf Ihrem Host.
. Gehen Sie zu dem Verzeichnis, in dem der Download enthalten ist.
. Dekomprimieren Sie die Datei.
+
Im folgenden Beispiel werden Dateien für ein SPARC System dekomprimiert. Verwenden Sie für x86-64-Plattformen den `x86/x64` Paket.

+
`gunzip netapp_solaris_host_utilities_6_2N20170913_0304_sparc.tar.gz`

. Verwenden Sie die `tar xvf` Befehl, um die Datei zu extrahieren.
+
`tar xvf netapp_solaris_host_utilities_6_2N20170913_0304_sparc.tar`

. Fügen Sie die Pakete hinzu, die Sie aus der tar-Datei extrahiert haben, und fügen Sie sie Ihrem Host hinzu.
+
`pkgadd -d NTAPSANTool.pkg`

+
Die Pakete werden dem hinzugefügt `/opt/NTAP/SANToolkit/bin` Verzeichnis.

+
Um die Installation abzuschließen, müssen Sie die Hostparameter für Ihre Umgebung (in diesem Fall Oracle Solaris I/O Multipathing oder MPxIO) mithilfe des konfigurieren `host_config` Befehl.

+
Der `host_config` Befehl weist das folgende Format auf:

+
`/opt/NTAP/SANToolkit/bin/host_config <-setup> <-protocol fcp|iscsi|mixed> <-multipath mpxio|dmp| non> [-noalua] [-mcc 60|90|120]`

+
Der `host_config` Befehl führt Folgendes aus:

+
** Ändert die FC- und SCSI-Treibereinstellungen für x86- und SPARC-Systeme
** Bietet SCSI-Timeout-Einstellungen für beide MPxIO-Konfigurationen
** Legt die VID-/PID-Informationen fest
** Aktiviert oder deaktiviert ALUA
** Konfiguriert die ALUA-Einstellungen, die von MPxIO und den SCSI-Treibern für x86- und SPARC-Systeme verwendet werden


. Starten Sie den Host neu.




== SAN-Toolkit

Das Tool-Kit wird automatisch installiert, wenn Sie das NetApp Host Utilities-Paket installieren. Dieses Kit enthält die `sanlun` Dienstprogramm: Unterstützt Sie beim Management von LUNs und HBAs. Der `sanlun` Befehl gibt Informationen über die LUNs zurück, die Ihrem Host zugeordnet sind, Multipathing und Informationen zurück, die zum Erstellen von Initiatorgruppen erforderlich sind.

.Beispiel
Im folgenden Beispiel wird der verwendet `sanlun lun show` Befehl gibt LUN-Informationen zurück.

[listing]
----
#sanlun lun show

controller(7mode)/                 device                                            host             lun
vserver(Cmode)     lun-pathname    filename                                         adapter protocol  size  mode
------------------------------------------------------------------------------------------------------
data_vserver       /vol/vol1/lun1  /dev/rdsk/c0t600A098038314362692451465A2F4F39d0s2  qlc1  FCP       60g   C
data_vserver       /vol/vol2/lun2  /dev/rdsk/c0t600A098038314362705D51465A626475d0s2  qlc1  FCP       20g   C
----


== SAN Booting

.Was Sie benötigen
Wenn Sie sich für das Booten über SAN entscheiden, muss es von Ihrer Konfiguration unterstützt werden. Sie können das verwenden link:https://mysupport.netapp.com/matrix/imt.jsp?components=71102;&solution=1&isHWU&src=IMT["NetApp Interoperabilitäts-Matrix-Tool"^] Um zu überprüfen, ob Ihr Betriebssystem, HBA, die HBA-Firmware und das HBA-Boot-BIOS sowie die ONTAP-Version unterstützt werden.

BEIM BOOTEN VON SAN wird ein SAN-Attached-Laufwerk (eine LUN) als Startgerät für einen Solaris-Host eingerichtet.

Sie können eine SAN-Start-LUN einrichten, um in einer Solaris MPxIO-Umgebung mit dem FC-Protokoll und dem Ausführen von Solaris Host Utilities zu arbeiten. Die Methode zur Einrichtung einer SAN-Boot-LUN kann je nach Volume-Manager und Dateisystem variieren. Siehe link:hu_solaris_62.html["Installieren Sie Solaris Host Utilities"] Für Details zu SAN-Boot-LUNs in einer Solaris MPIO-Umgebung (Multipath I/O).



== Multipathing

Multipathing ermöglicht Ihnen, mehrere Netzwerkpfade zwischen dem Host und den Speichersystemen zu konfigurieren. Falls ein Pfad ausfällt, wird der Verkehr auf den verbleibenden Pfaden fortgesetzt. Oracle Solaris I/O Multipathing oder MPxIO ist standardmäßig für Solaris 11.4 aktiviert. Die Standardeinstellung in `/kernel/drv/fp.conf` Änderungen in mpxio-disable=„no“.



=== Konfigurationen ohne ASA

Für Konfigurationen ohne ASA sollten zwei Gruppen von Pfaden mit unterschiedlichen Prioritäten vorhanden sein. Die Pfade mit höheren Prioritäten sind aktiv/optimiert, d. h. sie werden vom Controller gewartet, in dem sich das Aggregat befindet. Die Pfade mit niedrigeren Prioritäten sind aktiv, aber nicht optimiert, da sie von einem anderen Controller bedient werden. Die nicht optimierten Pfade werden nur verwendet, wenn optimierte Pfade nicht verfügbar sind.

.Beispiel
Im folgenden Beispiel wird die richtige Ausgabe für eine ONTAP-LUN mit zwei aktiv/optimierten Pfaden und zwei aktiv/nicht optimierten Pfaden angezeigt:

Die Pfadprioritäten werden für jede LUN im nativen Betriebssystem für den Abschnitt *Zugriffsstatus* angezeigt `mpathadm show lu <LUN>` Befehl.



=== Alle SAN-Array-Konfigurationen

In Konfigurationen mit allen SAN-Arrays (ASA) sind alle Pfade zu einer bestimmten LUN aktiv und optimiert. Dies verbessert die Performance, da I/O-Operationen über alle Pfade gleichzeitig ausgeführt werden können.

.Beispiel
Im folgenden Beispiel wird die richtige Ausgabe für eine ONTAP LUN angezeigt:

Die Ausgabe für das `sanlun` Der Befehl ist für ASA- und nicht-ASA-Konfigurationen identisch.

Die Pfadprioritäten werden für jede LUN im nativen Betriebssystem für den Abschnitt *Zugriffsstatus* angezeigt `mpathadm show lu <LUN>` Befehl.

[listing]
----
#sanlun lun show -pv sparc-s7-16-49:/vol/solaris_vol_1_0/solaris_lun

                    ONTAP Path: sparc-s7-16-49:/vol/solaris_vol_1_0/solaris_lun
                           LUN: 0
                      LUN Size: 30g
                   Host Device: /dev/rdsk/c0t600A098038314362692451465A2F4F39d0s2
                          Mode: C
            Multipath Provider: Sun Microsystems
              Multipath Policy: Native
----

NOTE: Alle SAN-Arrays (ASA)-Konfigurationen werden ab ONTAP 9.8 für Solaris-Hosts unterstützt.



== Empfohlene Einstellungen

NetApp empfiehlt die Verwendung der folgenden Parametereinstellungen für Solaris 11.4 SPARC und x86_64 mit NetApp ONTAP-LUNs. Diese Parameterwerte werden von Host Utilities festgelegt. Weitere Systemeinstellungen für Solaris 11.4 finden Sie unter Oracle DOC-ID: 2595926.1.

[cols="2*"]
|===
| Parameter | Wert 


| Drosselklappe_max | 8 


| Not_ready_Wiederholungen | 300 


| Busy_Wiederholungen | 30 


| Reset_Wiederholungen | 30 


| Drosselklappe_min | 2 


| Timeout_Wiederholungen | 10 


| Physische_Block_size | 4096 
|===
Alle Solaris-Betriebssystemversionen (einschließlich Solaris 10.x und Solaris 11.x) unterstützen Solaris HUK 6.2.

* Bei Solaris 11.4 wird die FC-Treiberbindung von geändert `ssd` Bis `sd`. Die folgenden Konfigurationsdateien werden während der Installation von HUK 6.2 teilweise aktualisiert:
+
** `/kernel/drv/sd.conf`
** `/etc/driver/drv/scsi_vhci.conf`


* Für Solaris 11.3 verwendet die FC-Treiberbindung `ssd`. Die folgenden Konfigurationsdateien werden während der Installation von HUK 6.2 teilweise aktualisiert:
+
** `/kernel/drv/ssd.conf`
** `/etc/driver/drv/scsi_vhci.conf`


* Für Solaris 10.x werden die folgenden Konfigurationsdateien während der Installation von HUK 6.2 vollständig aktualisiert:
+
** `/kernel/drv/sd.conf`
** `/kernel/drv/ssd.conf`
** `/kernel/drv/scsi_vhci.conf`




Informationen zum Beheben von Konfigurationsproblemen finden Sie im Artikel der Knowledge Base link:https://kb.netapp.com/onprem/ontap/da/SAN/What_are_the_Solaris_Host_recommendations_for_Supporting_HUK_6.2["Was sind die Solaris Host-Empfehlungen für die Unterstützung von HUK 6.2"^].

NetApp empfiehlt für eine erfolgreiche 4-KB-ausgerichtete I/O mit zpools unter Verwendung von NetApp-LUNs Folgendes:

* Stellen Sie sicher, dass Sie ein Solaris-Betriebssystem verwenden, das in der letzten Zeit ausreicht, um sicherzustellen, dass alle Solaris-Funktionen verfügbar sind, die die 4-KB-I/O-Größenausrichtung unterstützen.
* Überprüfen Sie, ob Solaris 10 Update 11 mit den neuesten Kernel-Patches und Solaris 11.4 mit dem neuesten Support Repository Update (SRU) installiert ist.
* Die logische NetApp-Einheit muss über verfügen `lun/host-type` Als `Solaris` Unabhängig von der LUN-Größe.




=== Empfohlene Einstellungen für MetroCluster

Standardmäßig kann das Solaris-Betriebssystem die E/A-Vorgänge nach *20s* nicht ausführen, wenn alle Pfade zu einer LUN verloren gehen. Dies wird von der gesteuert `fcp_offline_delay` Parameter. Der Standardwert für `fcp_offline_delay` Eignet sich für Standard-ONTAP-Cluster. In MetroCluster-Konfigurationen bietet sich jedoch der Nutzen von `fcp_offline_delay` Muss auf *120s* erhöht werden, um sicherzustellen, dass die I/O-Vorgänge, einschließlich ungeplanter Failover, nicht vorzeitig ausfallen. Weitere Informationen und empfohlene Änderungen an den Standardeinstellungen finden Sie im Knowledge Base-Artikel https://kb.netapp.com/onprem/ontap/metrocluster/Solaris_host_support_considerations_in_a_MetroCluster_configuration["Überlegungen zum Support von Solaris Hosts in einer MetroCluster-Konfiguration"^].



== Virtualisierung mit Oracle Solaris

* Die Virtualisierungsoptionen von Solaris umfassen logische Solaris Domains (auch LDOMs oder Oracle VM Server für SPARC), Solaris Dynamic Domains, Solaris Zones und Solaris Container. Diese Technologien wurden allgemein als „Oracle Virtual Machines“ unter dem Markennamen „neu“ bezeichnet, obwohl sie auf verschiedenen Architekturen basieren.
* In einigen Fällen können mehrere Optionen zusammen verwendet werden, z. B. ein Solaris Container in einer bestimmten logischen Solaris-Domäne.
* NetApp unterstützt die Nutzung dieser Virtualisierungstechnologien, bei denen die gesamte Konfiguration von Oracle unterstützt wird und jede Partition mit direktem Zugriff auf LUNs ist auf der aufgeführt link:https://mysupport.netapp.com/matrix/imt.jsp?components=95803;&solution=1&isHWU&src=IMT["NetApp Interoperabilitätsmatrix"^] In einer unterstützten Konfiguration. Dazu gehören Root-Container, LDOM I/O-Domänen und LDOM mit NPIV für den Zugriff auf LUNs.
* Partitionen oder Virtual Machines, die nur virtualisierte Storage-Ressourcen verwenden, z. B. `vdsk`, Benötigen keine speziellen Qualifikationen, da sie keinen direkten Zugriff auf NetApp LUNs haben. Nur die Partition oder virtuelle Maschine, die direkten Zugriff auf die zugrunde liegende LUN hat, wie z. B. eine LDOM-I/O-Domäne, muss in gefunden werden link:https://mysupport.netapp.com/matrix/imt.jsp?components=95803;&solution=1&isHWU&src=IMT["NetApp Interoperabilitäts-Matrix-Tool"^].




=== Empfohlene Einstellungen für Virtualisierung

Wenn LUNs als virtuelle Festplattengeräte innerhalb eines LDOM verwendet werden, wird die Quelle der LUN durch Virtualisierung maskiert. LDOM erkennt die Blockgrößen nicht richtig. Um dieses Problem zu vermeiden, muss das LDOM-Betriebssystem für _Oracle Bug 15824910_ und A gepatcht werden `vdc.conf` Es muss eine Datei erstellt werden, die die Blockgröße des virtuellen Laufwerks auf festlegt `4096`. Weitere Informationen finden Sie unter Oracle DOC: 2157669.1.

So überprüfen Sie den Patch:

.Schritte
. Erstellen Sie ein zpool.
. Laufen `zdb -C` Gegen den zpool und überprüfen Sie, dass der Wert von *ashift* ist `12`.
+
Wenn der Wert von *ashift* nicht ist `12`Überprüfen Sie, ob der richtige Patch installiert wurde, und überprüfen Sie den Inhalt von erneut `vdc.conf`.

+
Fahren Sie erst fort, wenn *ashift* einen Wert von anzeigt `12`.




NOTE: Patches sind verfügbar für Oracle Bug 15824910 auf verschiedenen Versionen von Solaris. Wenden Sie sich an Oracle, wenn Sie Hilfe beim ermitteln des besten Kernel-Patches benötigen.



== Empfohlene Einstellungen für SnapMirror Active Sync

Um zu überprüfen, ob die Solaris Client-Anwendungen bei einer ungeplanten Standort-Failover-Umschaltung in einer SnapMirror Active Sync-Umgebung unterbrechungsfrei ausgeführt werden, müssen Sie die folgende Einstellung auf dem Solaris 11.4-Host konfigurieren. Diese Einstellung überschreibt das Failover-Modul `f_tpgs` Um die Ausführung des Codepfads zu verhindern, der den Widerspruch erkennt.


NOTE: Ab ONTAP 9.9 werden die Konfigurationen der aktiven Synchronisierungseinstellungen von SnapMirror auf dem Solaris 11.4 Host unterstützt.

Befolgen Sie die Anweisungen, um den Überschreibungsparameter zu konfigurieren:

.Schritte
. Erstellen Sie die Konfigurationsdatei `/etc/driver/drv/scsi_vhci.conf` Bei einem Eintrag, der dem folgenden ähnlich ist, für den NetApp-Speichertyp, der mit dem Host verbunden ist:
+
[listing]
----
scsi-vhci-failover-override =
"NETAPP  LUN","f_tpgs"
----
. Verwenden Sie die `devprop` Und `mdb` Befehle, um zu überprüfen, ob der Override-Parameter erfolgreich angewendet wurde:
+
`root@host-A:~# devprop -v -n /scsi_vhci scsi-vhci-failover-override      scsi-vhci-failover-override=NETAPP  LUN + f_tpgs
root@host-A:~# echo "*scsi_vhci_dip::print -x struct dev_info devi_child | ::list struct dev_info devi_sibling| ::print struct dev_info devi_mdi_client| ::print mdi_client_t ct_vprivate| ::print struct scsi_vhci_lun svl_lun_wwn svl_fops_name"| mdb -k`

+
[listing]
----
svl_lun_wwn = 0xa002a1c8960 "600a098038313477543f524539787938"
svl_fops_name = 0xa00298d69e0 "conf f_tpgs"
----



NOTE: Nachher `scsi-vhci-failover-override` Wurde angewendet, `conf` Wird hinzugefügt zu `svl_fops_name`. Weitere Informationen und empfohlene Änderungen an den Standardeinstellungen finden Sie in dem Artikel der NetApp Wissensdatenbank https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapMirror/Solaris_Host_support_recommended_settings_in_SnapMirror_Business_Continuity_(SM-BC)_configuration["Von Solaris Host unterstützte empfohlene Einstellungen in der SnapMirror Active Sync Konfiguration"^].



== Bekannte Probleme

Die Solaris 11.4 mit ONTAP-Version weist folgende bekannte Probleme auf:

[cols="4*"]
|===
| NetApp Bug ID | Titel | Beschreibung | Oracle-ID 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1362435["1362435"^] | Änderungen an HUK 6.2- und Solaris_11.4-FC-Treibern verbindlich | Siehe Empfehlungen für Solaris 11.4 und HUK. Die Bindung des FC-Treibers wird von geändert `ssd (4D)` Bis `sd (4D)`. Verschieben Sie die vorhandene Konfiguration aus `ssd.conf` Bis `sd.conf` Wie in Oracle DOC erwähnt: 2595926.1). Das Verhalten variiert je nach neu installierten Solaris 11.4-Systemen und Systemen, die von Solaris 11.3 oder früheren Versionen aktualisiert wurden. | (DOC-ID 2595926.1) 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1366780["1366780"^] | Beim Speicher-Failover (SFO)-Giveback-Vorgang mit Emulex 32G Host Bus Adapter (HBA) auf x86 Arch wurde das LIF-Problem von Solaris festgestellt | Auf der x86_64-Plattform wurde das Problem mit der Emulex-Firmware-Version 12.6.x und höher festgestellt. | SR 3-24746803021 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1368957["1368957"^] | Solaris 11.x `cfgadm -c configure` Dies führt zu einem E/A-Fehler bei einer End-to-End-Emulex-Konfiguration | Wird Ausgeführt `cfgadm -c configure` Bei der Emulex End-to-End-Konfiguration wird ein I/O-Fehler angezeigt. Diese ist in ONTAP 9.5P17, 9.6P14, 9.7P13 und 9.8P2 behoben | Keine Angabe 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1345622["1345622"^] | Abnormale Pfadberichte auf Solaris-Hosts mit ASA/PPorts unter Verwendung systemeigener Befehle | Unter Solaris 11.4 mit All-SAN-Array (ASA) werden zeitweise Probleme bei der Pfadmeldung festgestellt. | Keine Angabe 
|===