---
sidebar: sidebar 
permalink: hu_solaris_62.html 
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap 
summary: Beschreibt die Verwendung der Solaris Host Utilities 6.2 mit ONTAP 
---
= Installieren Sie Solaris Host Utilities 6.2 für ONTAP-Speicher
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die Solaris Host Utilities helfen Ihnen bei der Verwaltung des an einen Solaris-Host angeschlossenen ONTAP Speichers und unterstützen den technischen Support beim Erfassen von Konfigurationsdaten.

Die Solaris Host Utilities unterstützen mehrere Solaris-Umgebungen und mehrere Transportprotokolle.  Dies sind die primären Solaris Host Utilities-Umgebungen:

* Das native Betriebssystem mit MPxIO und entweder dem Fibre Channel (FC)- oder dem iSCSI-Protokoll auf einem System, das entweder einen SPARC-Prozessor oder einen x86/64-Prozessor verwendet.
* Veritas Dynamic Multipathing (DMP) mit dem FC- oder iSCSI-Protokoll auf einem System mit SPARC Prozessor oder dem iSCSI-Protokoll auf einem System mit x86/64-Prozessor.


Die Solaris Host Utilities 6.2 unterstützen die folgenden Solaris-Serien:

* Solaris 11.x
* Solaris 10.x


.Bevor Sie beginnen
Stellen Sie sicher, dass Ihre iSCSI-, FC- oder FCoE-Konfiguration unterstützt wird.  Sie können dielink:https://imt.netapp.com/matrix/#welcome["Interoperabilitäts-Matrix-Tool"^] um Ihre Konfiguration zu überprüfen.

.Schritte
. Melden Sie sich als Root bei Ihrem Host an.
. Laden Sie eine Kopie der komprimierten Datei mit den Host-Dienstprogrammen von derlink:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/6.2/downloads["NetApp Support Website"^] in ein Verzeichnis auf Ihrem Solaris-Host:
+
[role="tabbed-block"]
====
.SPARC-CPU
--
[source, cli]
----
netapp_solaris_host_utilities_6_2_sparc.tar.gz
----
--
.x86/x64-CPU
--
[source, cli]
----
netapp_solaris_host_utilities_6_2_amd.tar.gz
----
--
====
. Gehen Sie zu dem Verzeichnis auf Ihrem Solaris-Host, das den Download enthält.
. Entpacken Sie die Datei mithilfe des `gunzip` Befehl:
+
[source, cli]
----
gunzip netapp_solaris_host_utilities_6_2_sparc.tar.gz
----
. Extrahieren Sie die Datei mit dem `tar xvf` Befehl:
+
[source, cli]
----
tar xvf netapp_solaris_host_utilities_6_2_sparc.tar
----
. Fügen Sie die Pakete, die Sie aus der Tar-Datei extrahiert haben, zu Ihrem Host hinzu
+
[source, cli]
----
pkgadd
----
+
Die Pakete werden dem hinzugefügt `/opt/NTAP/SANToolkit/bin` Verzeichnis.

+
Im folgenden Beispiel wird der Befehl verwendet `pkgadd`, um das Solaris-Installationspaket zu installieren:

+
[source, cli]
----
pkgadd -d ./NTAPSANTool.pkg
----
. Bestätigen Sie mit einem der folgenden Befehle, dass das Toolkit erfolgreich installiert wurde:
+
[source, cli]
----
pkginfo
----
+
[source, cli]
----
ls - al
----
+
.Beispielausgaben anzeigen
[%collapsible]
====
[listing]
----
# ls -alR /opt/NTAP/SANToolkit
/opt/NTAP/SANToolkit:
total 1038
drwxr-xr-x   3 root     sys            4 Jul 22  2019 .
drwxr-xr-x   3 root     sys            3 Jul 22  2019 ..
drwxr-xr-x   2 root     sys            6 Jul 22  2019 bin
-r-xr-xr-x   1 root     sys       432666 Sep 13  2017 NOTICES.PDF

/opt/NTAP/SANToolkit/bin:
total 7962
drwxr-xr-x   2 root     sys            6 Jul 22  2019 .
drwxr-xr-x   3 root     sys            4 Jul 22  2019 ..
-r-xr-xr-x   1 root     sys      2308252 Sep 13  2017 host_config
-r-xr-xr-x   1 root     sys          995 Sep 13  2017 san_version
-r-xr-xr-x   1 root     sys      1669204 Sep 13  2017 sanlun
-r-xr-xr-x   1 root     sys          677 Sep 13  2017 vidpid.dat

# (cd /usr/share/man/man1; ls -al host_config.1 sanlun.1)
-r-xr-xr-x   1 root     sys        12266 Sep 13  2017 host_config.1
-r-xr-xr-x   1 root     sys         9044 Sep 13  2017 sanlun.1
----
====
. Konfigurieren Sie die Hostparameter für Ihre MPxIO- oder Veritas DMP-Umgebung:
+
[source, cli]
----
/opt/NTAP/SANToolkit/bin/host_config
----
. Überprüfen Sie die Installation:
+
[source, cli]
----
sanlun version
----




== Was kommt als Nächstes?

link:hu-solaris-san-toolkit.html["Erfahren Sie mehr über das SAN Toolkit"] .
