---
sidebar: sidebar 
permalink: hu_solaris_62_rn.html 
keywords: Host Utilities, solaris, 6.2 netapp, ontap 
summary: Versionshinweise zu Solaris Host Utilities 6.2 
---
= Solaris Host Utilities 6.2 – Versionshinweise
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
In den Versionshinweisen werden neue Funktionen und Verbesserungen, in der aktuellen Version behobene Probleme, bekannte Probleme und Einschränkungen sowie wichtige Hinweise zur Konfiguration und Verwaltung Ihres spezifischen Solaris-Hosts mit Ihrem ONTAP-Speichersystem beschrieben.

Spezifische Informationen zu den von den Host Utilities unterstützten Betriebssystemversionen und link:https://imt.netapp.com/matrix/#welcome["Interoperabilitäts-Matrix-Tool"^]-Updates finden Sie im .



== Bekannte Probleme und Einschränkungen

Sie sollten sich der folgenden bekannten Probleme und Einschränkungen bewusst sein, die die Performance auf Ihrem spezifischen Host beeinträchtigen könnten.

[cols="3"]
|===
| Fehler-ID | Titel | Beschreibung 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1385189["1385189"^] | Solaris 11.4 FC-Treiberverbindungsänderungen sind in HUK 6.2 erforderlich | Empfehlungen für Solaris 11.4 und HUK:
Die Bindung des FC-Treibers wird von geändert `ssd(4D)` Bis `sd(4D)`. Verschieben Sie die Konfiguration in `ssd.conf` Bis `sd.conf` Wie bereits in Oracle erwähnt (Doc-ID 2595926.1). Das Verhalten variiert je nach neu installierten Solaris 11.4-Systemen und Systemen, die von 11.3 oder älteren Versionen aktualisiert wurden. 
|===
link:https://mysupport.netapp.com/site/["NetApp Bugs Online"^] Bietet vollständige Informationen für die meisten bekannten Probleme, einschließlich Lösungsvorschläge, falls möglich. Einige Schlüsselwortkombinationen und Fehlertypen, die Sie möglicherweise verwenden möchten, sind:

* FCP Allgemein: Zeigt FC- und HBA-Fehler (Host Bus Adapter) an, die keinem bestimmten Host zugeordnet sind.
* FCP – Solaris

