---
sidebar: sidebar 
permalink: hu_sles_12SP3.html 
keywords: host utilities, suse linux enterprise server 12 SP3, suse, linux, 12 SP3, netapp, ontap 
summary: Beschreibt die Verwendung von SUSE Linux Enterprise Server 12 SP3 mit ONTAP 
---
= Verwendung von SUSE Linux Enterprise Server 12 SP3 mit NetApp ONTAP
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content




== Installieren der Linux Unified Host Utilities

Das NetApp Linux Unified Host Utilities-Softwarepaket ist auf der erhältlich link:https://mysupport.netapp.com/NOW/cgi-bin/software/?product=Host+Utilities+-+SAN&platform=Linux["NetApp Support Website"^] In einer 32-Bit- und 64-Bit-.rpm-Datei. Wenn Sie nicht wissen, welche Datei für Ihre Konfiguration geeignet ist, verwenden Sie den link:https://mysupport.netapp.com/matrix/#welcome["NetApp Interoperabilitäts-Matrix-Tool"^] Um zu überprüfen, welches Sie benötigen.

Es wird dringend empfohlen, Linux Unified Host Utilities zu installieren, jedoch nicht zwingend. Die Dienstprogramme ändern keine Einstellungen auf Ihrem Linux-Host. Die Versorgungseinrichtungen verbessern das Management und unterstützen den NetApp Kunden-Support bei der Erfassung von Informationen zu Ihrer Konfiguration.

.Was Sie benötigen
Wenn Sie derzeit eine Version von Linux Unified Host Utilities installiert haben, sollten Sie sie aktualisieren oder Sie sollten sie entfernen und die folgenden Schritte verwenden, um die neueste Version zu installieren.

. Laden Sie das Softwarepaket für 32 Bit oder 64 Bit Linux Unified Host Utilities von herunter link:https://mysupport.netapp.com/NOW/cgi-bin/software/?product=Host+Utilities+-+SAN&platform=Linux["NetApp Support Website"^] Standort zu Ihrem Host.
. Verwenden Sie den folgenden Befehl, um das Softwarepaket zu installieren:
+
`rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_64`




NOTE: Sie können die in diesem Inhalt angegebenen Konfigurationseinstellungen verwenden, um die mit verbundenen Cloud-Clients zu konfigurieren link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] Und link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["Amazon FSX für ONTAP"^].



== SAN Toolkit

Das Toolkit wird automatisch installiert, wenn Sie das NetApp Host Utilities-Paket installieren. Dieses Kit enthält die `sanlun` Dienstprogramm: Unterstützt Sie beim Management von LUNs und HBAs. Der `sanlun` Befehl gibt Informationen über die LUNs zurück, die Ihrem Host zugeordnet sind, Multipathing und Informationen zurück, die zum Erstellen von Initiatorgruppen erforderlich sind.

.Beispiel
Im folgenden Beispiel wird der verwendet `sanlun lun show` Befehl gibt LUN-Informationen zurück.

[listing]
----
# sanlun lun show all
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
-------------------------------------------------------------------------
data_vserver          /vol/vol1/lun1   /dev/sdb   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol1/lun1   /dev/sdc   host15   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sdd   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sde   host15   FCP       120.0g  cDOT
----


== SAN wird gebootet

.Was Sie benötigen
Wenn Sie sich für das Booten über SAN entscheiden, muss es von Ihrer Konfiguration unterstützt werden. Sie können das verwenden link:https://mysupport.netapp.com/matrix/imt.jsp?components=80043;&solution=1&isHWU&src=IMT["NetApp Interoperabilitäts-Matrix-Tool"^] Um zu überprüfen, ob Ihr Betriebssystem, HBA, die HBA-Firmware und das HBA-Boot-BIOS sowie die ONTAP-Version unterstützt werden.

.Schritte
. Ordnen Sie die SAN-Boot-LUN dem Host zu.
. Vergewissern Sie sich, dass mehrere Pfade verfügbar sind.
+
Denken Sie daran, dass mehrere Pfade nur verfügbar sind, wenn das Host-Betriebssystem betriebsbereit ist und auf den Pfaden ausgeführt wird.

. Aktivieren Sie das SAN-Booten im Server-BIOS für die Ports, denen die SAN-Boot-LUN zugeordnet ist.
+
Informationen zum Aktivieren des HBA-BIOS finden Sie in der anbieterspezifischen Dokumentation.

. Starten Sie den Host neu, um sicherzustellen, dass der Startvorgang erfolgreich ist.




== Multipathing

Für SUSE Linux Enterprise Server 12 SP3 muss die Datei /etc/Multipath.conf vorhanden sein, Sie müssen jedoch keine spezifischen Änderungen an der Datei vornehmen. SUSE Linux Enterprise Server 12 SP3 ist mit allen Einstellungen zusammengestellt, die zum Erkennen und korrekten Verwalten von ONTAP-LUNs erforderlich sind.

Sie können das verwenden `multipath -ll` Überprüfen Sie mit dem Befehl die Einstellungen für Ihre ONTAP LUNs. Die folgenden Abschnitte enthalten ein Beispiel für eine Multipath-Ausgabe für eine LUN, die ASA- und nicht-ASA-Personas zugeordnet ist.



=== Konfiguration einer All-SAN-Array-Lösung

In allen ASA-Konfigurationen (SAN Array) sind alle Pfade zu einer bestimmten logischen Einheit (LUN) aktiv und optimiert. Das bedeutet, dass I/O gleichzeitig über alle Pfade bedient werden kann, was zu einer besseren Performance führt.

.Beispiel
Im folgenden Beispiel wird die richtige Ausgabe für eine ONTAP LUN angezeigt:

[listing]
----
# multipath -ll
3600a0980383034466b2b4a3775474859 dm-3 NETAPP,LUN C-Mode
size=20G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='round-robin 0' prio=50 status=active
| |- 1:0:8:1  sdb 8:16 active ready running
| `- 2:0:8:1  sdd 8:48 active ready running
`-+- policy='round-robin 0' prio=10 status=enabled
  |- 1:0:9:1  sdc 8:32 active ready running
  `- 2:0:9:1  sde 8:64 active ready running
----

NOTE: Verwenden Sie keine unverhältnismäßig hohe Anzahl von Pfaden zu einer einzelnen LUN. Es sollten nicht mehr als 4 Pfade erforderlich sein. Mehr als 8 Pfade können bei Storage-Ausfällen zu Pfadproblemen führen.



=== Nicht-ASA-Konfiguration

Für eine nicht-ASA-Konfiguration sollte es zwei Gruppen von Pfaden mit unterschiedlichen Prioritäten geben. Die Pfade mit den höheren Prioritäten sind aktiv/optimiert, was bedeutet, dass sie vom Controller gewartet werden, wo sich das Aggregat befindet. Die Pfade mit den niedrigeren Prioritäten sind aktiv, werden aber nicht optimiert, da sie von einem anderen Controller bereitgestellt werden. Die nicht optimierten Pfade werden nur verwendet, wenn keine optimierten Pfade verfügbar sind.

.Beispiel
Im folgenden Beispiel wird die richtige Ausgabe für eine ONTAP-LUN mit zwei aktiv/optimierten Pfaden und zwei aktiv/nicht optimierten Pfaden angezeigt:

[listing]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handler' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 11:0:1:0 sdj 8:144 active ready running
| |- 11:0:2:0 sdr 65:16 active ready running
`-+- policy='service-time 0' prio=10 status=enabled
|- 11:0:0:0 sdb 8:i6 active ready running
|- 12:0:0:0 sdz 65:144 active ready running
----

NOTE: Verwenden Sie keine unverhältnismäßig hohe Anzahl von Pfaden zu einer einzelnen LUN. Es sollten nicht mehr als 4 Pfade erforderlich sein. Mehr als 8 Pfade können bei Storage-Ausfällen zu Pfadproblemen führen.



== Empfohlene Einstellungen

Das Betriebssystem SUSE Linux Enterprise Server 12 SP3 wird kompiliert, um ONTAP-LUNs zu erkennen und automatisch alle Konfigurationsparameter richtig einzustellen. Der `multipath.conf` Datei muss vorhanden sein, damit der Multipath-Daemon gestartet werden kann. Sie können jedoch mit dem Befehl eine leere Zero-Byte-Datei erstellen:
`touch /etc/multipath.conf`

Wenn Sie diese Datei zum ersten Mal erstellen, müssen Sie die Multipath-Services unter Umständen aktivieren und starten.

[listing]
----
# systemctl enable multipathd
# systemctl start multipathd
----
Es sind keine Anforderungen, direkt etwas hinzuzufügen `multipath.conf` Datei, es sei denn, Sie haben Geräte, die Sie nicht von Multipath verwalten möchten, oder Sie haben bereits vorhandene Einstellungen, die die Standardeinstellungen überschreiben.

Sie können die folgende Syntax dem hinzufügen `multipath.conf` Datei zum Ausschließen unerwünschter Geräte.

Ersetzen Sie den `<DevId>` Mit der WWID-Zeichenfolge des Geräts, das Sie ausschließen möchten. Verwenden Sie den folgenden Befehl, um die WWID zu bestimmen:

....
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
....
.Beispiel
In diesem Beispiel `sda` Ist die lokale SCSI Festplatte, die wir zur Blacklist hinzufügen müssen.

.Schritte
. Führen Sie den folgenden Befehl aus, um die WWID zu bestimmen:
+
....
# /lib/udev/scsi_id -gud /dev/sda
360030057024d0730239134810c0cb833
....
. Fügen Sie diese WWID der schwarzen Liste Stanza im hinzu `/etc/multipath.conf`:
+
....
blacklist {
     wwid   360030057024d0730239134810c0cb833
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
....


Sie sollten immer Ihre überprüfen `/etc/multipath.conf` Datei für ältere Einstellungen, insbesondere im Abschnitt Standardeinstellungen, die möglicherweise die Standardeinstellungen überschreiben.

Die folgende Tabelle zeigt den entscheidenden `multipathd` Parameter für ONTAP-LUNs und die erforderlichen Werte. Wenn ein Host mit LUNs anderer Anbieter verbunden ist und einer dieser Parameter außer Kraft gesetzt wird, müssen sie später in korrigiert werden `multipath.conf` Die speziell für ONTAP LUNs gelten. Wenn dies nicht erfolgt, funktionieren die ONTAP LUNs möglicherweise nicht wie erwartet. Diese Standardeinstellungen sollten nur in Absprache mit NetApp und/oder dem Anbieter des Betriebssystems außer Kraft gesetzt werden und nur dann, wenn die Auswirkungen vollständig verstanden wurden.

[cols="2*"]
|===
| Parameter | Einstellung 


| Erkennen_Prio | ja 


| Dev_Loss_tmo | „Unendlich“ 


| Failback | Sofort 


| Fast_io_fail_tmo | 5 


| Funktionen | „2 pg_init_retries 50“ 


| Flush_on_Last_del | „ja“ 


| Hardware_Handler | „0“ 


| Kein_PATH_retry | Warteschlange 


| PATH_Checker | „nur“ 


| Path_Grouping_Policy | „Group_by_prio“ 


| Pfad_Auswahl | „Servicezeit 0“ 


| Polling_Interval | 5 


| prio | ONTAP 


| Produkt | LUN.* 


| Beibehalten_Attached_hw_Handler | ja 


| rr_weight | „Einheitlich“ 


| User_friendly_names | Nein 


| Anbieter | NETAPP 
|===
.Beispiel
Das folgende Beispiel zeigt, wie eine überhielte Standardeinstellung korrigiert wird. In diesem Fall die `multipath.conf` Datei definiert Werte für `path_checker` Und `no_path_retry` Die nicht mit ONTAP LUNs kompatibel sind. Wenn sie nicht entfernt werden können, weil andere SAN-Arrays noch an den Host angeschlossen sind, können diese Parameter speziell für ONTAP-LUNs mit einem Device stanza korrigiert werden.

[listing]
----
defaults {
 path_checker readsector0
 no_path_retry fail
}
devices {
 device {
 vendor "NETAPP "
 product "LUN.*"
 no_path_retry queue
 path_checker tur
 }
}
----


== Bekannte Probleme und Einschränkungen

[cols="4*"]
|===
| NetApp Bug ID | Titel | Beschreibung | Bugzilla-ID 


| link:https://https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1089555["1089555"^] | Kernel-Störung auf Kernel-Version SLES12 SP3 mit Emulex LPe16002 16 GB FC während Speicher-Failover-Betrieb beobachtet | Bei Storage Failover-Vorgängen auf Kernel-Version SLES12 SP3 mit Emulex LPe16002 HBA kann es zu einer Kernel-Störung kommen. Die Kernel-Störung fordert einen Neustart des Betriebssystems auf, was wiederum zu einer Anwendungsunterbrechung führt. Wenn kdump konfiguriert ist, generiert die Kernel-Störung eine vmcore-Datei unter /var/crash/Directory. Sie können die Ursache des Fehlers in der vmcore-Datei untersuchen. Beispiel: Im beobachteten Fall wurde die Kernel-Störung im Modul „lpfc_sli_ringtxcmpl_Put+51“ beobachtet und in der vmcore-Datei – Ausnahme-RIP: Lpfc_sli_ringtxcmpl_Put+51 protokolliert. Stellen Sie das Betriebssystem nach der Kernel-Störung wieder her, indem Sie das Host-Betriebssystem neu starten und die Anwendung neu starten. | link:http://bugzilla.suse.com/show_bug.cgi?id=1042847["1042847"^] 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1089561["1089561"^] | Kernel-Störung auf Kernel-Version SLES12 SP3 mit Emulex LPe32002 32 GB FC während Storage Failover-Vorgänge beobachtet | Bei Storage Failover-Vorgängen auf Kernel-Version SLES12 SP3 mit Emulex LPe32002 HBA kann es zu einer Kernel-Störung kommen. Die Kernel-Störung fordert einen Neustart des Betriebssystems auf, was wiederum zu einer Anwendungsunterbrechung führt. Wenn kdump konfiguriert ist, generiert die Kernel-Störung eine vmcore-Datei unter /var/crash/Directory. Sie können die Ursache des Fehlers in der vmcore-Datei untersuchen. Beispiel: Im beobachteten Fall wurde die Kernel-Störung im Modul „lpfc_sli_free_hbq+76“ beobachtet und in der vmcore-Datei – Ausnahme-RIP: Lpfc_sli_free_hbq+76 protokolliert. Stellen Sie das Betriebssystem nach der Kernel-Störung wieder her, indem Sie das Host-Betriebssystem neu starten und die Anwendung neu starten. | link:http://bugzilla.suse.com/show_bug.cgi?id=1042807["1042807"^] 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1117248["1117248"^] | Kernel-Störungen bei SLES12SP3 mit QLogic QLE2562 8 GB FC während eines Storage Failover-Betriebs | Bei Speicher-Failover-Operationen auf dem Sles12sp3 Kernel (Kernel-default-4.4.82-6.3.1) mit QLogic QLE2562 HBA wurde die Kernel-Störung aufgrund einer Panik im Kernel beobachtet. Die Kernel-Panic führt zu einem Neustart des Betriebssystems, was zu einer Anwendungsunterbrechung führt. Wenn kdump konfiguriert ist, generiert die Kernel-Panic die vmcore-Datei unter dem Verzeichnis /var/crash/. Nach einem Panikzustand des Kernels kann die vmcore-Datei verwendet werden, um die Ursache des Fehlers zu verstehen. Beispiel: In diesem Fall wurde die Panik im Modul „blk_Finish_request+289“ beobachtet. Es wird in der vmcore-Datei mit der folgenden Zeichenfolge protokolliert: „Ausnahme RIP: blk_Finish_Request+289“ nach der Kernel-Störung können Sie das Betriebssystem wiederherstellen, indem Sie das Host-Betriebssystem neu starten. Sie können die Anwendung bei Bedarf neu starten. | link:http://bugzilla.suse.com/show_bug.cgi?id=1062496["1062496"^] 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1117261["1117261"^] | Kernel-Störung auf SLES12SP3 mit Qlogic QLE2662 16 GB FC während Speicher-Failover-Operationen beobachtet | Während Speicher-Failover-Operationen auf Sles12sp3 Kernel (Kernel-default-4.4.82-6.3.1) mit Qlogic QLE2662 HBA, können Sie Kernel-Störungen beobachten. Dadurch wird ein Neustart des Betriebssystems angezeigt, der eine Anwendungsunterbrechung verursacht. Die Kernel-Störung generiert eine vmcore-Datei unter dem Verzeichnis /var/crash/, wenn kdump konfiguriert ist. Die vmcore-Datei kann verwendet werden, um die Ursache des Fehlers zu verstehen. Beispiel: In diesem Fall wurde die Kernel-Störung im Modul "unbekannte oder ungültige Adresse" beobachtet und in der vmcore-Datei mit der folgenden Zeichenfolge - Ausnahme RIP: Unbekannte oder ungültige Adresse protokolliert. Nach einer Störung des Kernels kann das Betriebssystem wiederhergestellt werden, indem das Host-Betriebssystem neu gestartet und die Anwendung nach Bedarf neu gestartet wird. | link:http://bugzilla.suse.com/show_bug.cgi?id=1062508["1062508"^] 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1117274["1117274"^] | Kernel-Störung auf SLES12SP3 mit Emulex LPe16002 16 GB FC bei Storage Failover-Operationen | Bei Storage Failover-Vorgängen auf dem Sles12sp3 Kernel (Kernel-default-4.4.87-3.1) mit Emulex LPe16002 HBA können Sie möglicherweise eine Kernel-Störung beobachten. Dadurch wird ein Neustart des Betriebssystems angezeigt, der eine Anwendungsunterbrechung verursacht. Wenn kdump konfiguriert ist, generiert die Kernel-Störung eine vmcore-Datei im Verzeichnis /var/crash/. Die vmcore-Datei kann verwendet werden, um die Ursache des Fehlers zu verstehen. Beispiel: In diesem Fall wurde die Kernel-Störung im Modul „RAW_spin_Lock_irqsave+30“ beobachtet und in der vmcore-Datei mit der folgenden Zeichenfolge protokolliert: – Ausnahme RIP: _RAW_spin_Lock_irqsave+30. Nach einer Störung des Kernels kann das Betriebssystem wiederhergestellt werden, indem das Host-Betriebssystem neu gestartet und die Anwendung nach Bedarf neu gestartet wird. | link:http://bugzilla.suse.com/show_bug.cgi?id=1062514["1062514"^] 
|===


== Versionshinweise



=== ASM Mirroring

ASM Spiegelung erfordert möglicherweise Änderungen an den Linux Multipath-Einstellungen, damit ASM ein Problem erkennt und auf eine andere Fehlergruppe umschaltet. Die meisten ASM-Konfigurationen auf ONTAP verwenden externe Redundanz. Das bedeutet, dass Datensicherung durch das externe Array bereitgestellt wird und ASM keine Daten spiegelt. Einige Standorte verwenden ASM mit normaler Redundanz, um normalerweise zwei-Wege-Spiegelung über verschiedene Standorte hinweg bereitzustellen. Siehe link:https://www.netapp.com/us/media/tr-3633.pdf["Oracle-Datenbanken auf ONTAP"^] Für weitere Informationen.
