---
sidebar: sidebar 
permalink: hu_sles_12SP3.html 
keywords: host utilities, suse linux enterprise server 12 SP3, suse, linux, 12 SP3, netapp, ontap 
summary: Installieren Sie Linux Host Utilities auf einem SUSE Linux Enterprise Server 12 SP3, um FCP- und iSCSI-Protokollvorgänge mit ONTAP LUNs zu verwalten. 
---
= Konfigurieren Sie SUSE Linux Enterprise Server 12 SP3 für FCP und iSCSI mit ONTAP-Speicher
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die Linux Host Utilities-Software enthält Management- und Diagnose-Tools für Linux-Hosts, die mit dem ONTAP-Storage verbunden sind. Wenn Sie die Linux Host Utilities auf einem SUSE Linux Enterprise Server 12 SP3-Host installieren, können Sie mithilfe der Host Utilities FCP- und iSCSI-Protokollvorgänge mit ONTAP-LUNs verwalten.


NOTE: Sie müssen die Einstellungen der Kernel-basierten virtuellen Maschine (KVM) nicht manuell konfigurieren, da ONTAP LUNs automatisch dem Hypervisor zugeordnet werden.



== Schritt 1: Aktivieren Sie optional den SAN-Bootvorgang

Sie können Ihren Host so konfigurieren, dass er SAN-Booting verwendet, um die Bereitstellung zu vereinfachen und die Skalierbarkeit zu verbessern.

.Bevor Sie beginnen
Überprüfen Sie mithilfe deslink:https://mysupport.netapp.com/matrix/#welcome["Interoperabilitäts-Matrix-Tool"^], ob Ihr Linux-Betriebssystem, Ihr Host Bus Adapter (HBA), die HBA-Firmware, das HBA-Boot-BIOS und die ONTAP-Version das Booten über das SAN unterstützen.

.Schritte
. link:https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["Erstellen Sie eine SAN-Boot-LUN und ordnen Sie sie dem Host zu"^].
. Aktivieren Sie das SAN-Booten im Server-BIOS für die Ports, denen die SAN-Boot-LUN zugeordnet ist.
+
Informationen zum Aktivieren des HBA-BIOS finden Sie in der anbieterspezifischen Dokumentation.

. Überprüfen Sie, ob die Konfiguration erfolgreich war, indem Sie den Host neu starten und überprüfen, ob das Betriebssystem ausgeführt wird.




== Schritt 2: Installieren Sie die Linux Host Utilities

NetApp empfiehlt dringend die Installation der Linux Host Utilities, um die ONTAP LUN-Verwaltung zu unterstützen, und den technischen Support beim Sammeln von Konfigurationsdaten zu unterstützen.

link:hu_luhu_71.html["Installieren Sie Linux Host Utilities 7.1"].


NOTE: Durch die Installation der Linux Host Utilities werden keine Host-Timeout-Einstellungen auf Ihrem Linux-Host geändert.



== Schritt 3: Bestätigen Sie die Multipath-Konfiguration für Ihren Host

Sie können Multipathing mit SUSE Linux Enterprise Server 12 SP3 zur Verwaltung von ONTAP-LUNs verwenden.

Um sicherzustellen, dass Multipathing für Ihren Host korrekt konfiguriert ist, überprüfen Sie, ob die `/etc/multipath.conf` Datei definiert ist und ob die von NetApp empfohlenen Einstellungen für Ihre ONTAP LUNs konfiguriert sind.

.Schritte
. Überprüfen Sie, ob die `/etc/multipath.conf` Datei vorhanden ist:
+
[source, cli]
----
ls /etc/multipath.conf
----
+
Wenn die Datei nicht vorhanden ist, erstellen Sie eine leere, Null-Byte-Datei:

+
[source, cli]
----
touch /etc/multipath.conf
----
. Beim ersten Erstellen der `multipath.conf` Datei müssen Sie möglicherweise die Multipath-Services aktivieren und starten, um die empfohlenen Einstellungen zu laden:
+
[source, cli]
----
systemctl enable multipathd
----
+
[source, cli]
----
systemctl start multipathd
----
. Jedes Mal, wenn Sie den Host starten, lädt die leere `/etc/multipath.conf` Zero-Byte-Datei automatisch die von NetApp empfohlenen Multipath-Parameter als Standardeinstellungen. Sie sollten keine Änderungen an der Datei für Ihren Host vornehmen `/etc/multipath.conf` müssen, da das Host-Betriebssystem mit den Multipath-Parametern kompiliert ist, die ONTAP LUNs korrekt erkennen und verwalten.
+
In der folgenden Tabelle sind die nativen vom Linux OS kompilierten Multipath-Parametereinstellungen für ONTAP LUNs aufgeführt.

+
.Parametereinstellungen anzeigen
[%collapsible]
====
[cols="2"]
|===
| Parameter | Einstellung 


| Erkennen_Prio | ja 


| Dev_Loss_tmo | „Unendlich“ 


| Failback | Sofort 


| Fast_io_fail_tmo | 5 


| Funktionen | „2 pg_init_retries 50“ 


| Flush_on_Last_del | „ja“ 


| Hardware_Handler | „0“ 


| Kein_PATH_retry | Warteschlange 


| PATH_Checker | „nur“ 


| Path_Grouping_Policy | „Group_by_prio“ 


| Pfad_Auswahl | „Servicezeit 0“ 


| Polling_Interval | 5 


| prio | ONTAP 


| Produkt | LUN 


| Beibehalten_Attached_hw_Handler | ja 


| rr_weight | „Einheitlich“ 


| User_friendly_names | Nein 


| Anbieter | NETAPP 
|===
====
. Überprüfen Sie die Parametereinstellungen und den Pfadstatus für Ihre ONTAP LUNs:
+
[source, cli]
----
multipath -ll
----
+
Die standardmäßigen Multipath-Parameter unterstützen ASA-, AFF- und FAS-Konfigurationen. In diesen Konfigurationen sollte eine einzelne ONTAP-LUN nicht mehr als vier Pfade benötigen. Wenn mehr als vier Pfade vorhanden sind, kann dies bei einem Storage-Ausfall zu Problemen mit den Pfaden führen.

+
Die Ausgaben im folgenden Beispiel zeigen die korrekten Parametereinstellungen und den Pfadstatus für ONTAP LUNs in einer ASA-, AFF- oder FAS-Konfiguration.

+
[role="tabbed-block"]
====
.ASA-Konfiguration
--
Eine ASA Konfiguration optimiert alle Pfade zu einer bestimmten LUN und hält sie aktiv. Dies verbessert die Performance, da I/O-Operationen über alle Pfade gleichzeitig ausgeführt werden können.

[listing]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 3:0:7:9    sdco 69:192  active ready running
  |- 3:0:8:9    sddi 71:0    active ready running
  |- 14:0:8:9   sdjq 65:320  active ready running
  `- 14:0:7:9   sdiw 8:256   active ready running
----
--
.AFF- oder FAS-Konfiguration
--
Eine AFF- oder FAS-Konfiguration sollte zwei Pfadgruppen mit höheren und niedrigeren Prioritäten aufweisen. Aktiv/optimierte Pfade mit höherer Priorität werden vom Controller bedient, wo sich das Aggregat befindet. Pfade mit niedriger Priorität sind aktiv, jedoch nicht optimiert, da sie von einem anderen Controller bedient werden. Nicht optimierte Pfade werden nur verwendet, wenn keine optimierten Pfade verfügbar sind.

Im folgenden Beispiel wird die Ausgabe für eine ONTAP-LUN mit zwei aktiv/optimiert-Pfaden und zwei aktiv/nicht-optimierten Pfaden angezeigt:

[listing]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 3:0:3:0    sdd  8:48    active ready running
| |- 3:0:4:0    sdx  65:112  active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 14:0:2:0   sdfk 130:96  active ready running
  `- 14:0:5:0   sdgz 132:240 active ready running
----
--
====




== Schritt 4: Optional: Schließen Sie ein Gerät vom Multipathing aus

Bei Bedarf können Sie ein Gerät vom Multipathing ausschließen, indem Sie die WWID für das unerwünschte Gerät der „Blacklist“-Strophe für die Datei hinzufügen `multipath.conf`.

.Schritte
. Bestimmen Sie die WWID:
+
[source, cli]
----
/lib/udev/scsi_id -gud /dev/sda
----
+
„sda“ ist die lokale SCSI-Festplatte, die Sie der Blacklist hinzufügen möchten.

+
Ein Beispiel WWID ist `360030057024d0730239134810c0cb833`.

. Fügen Sie die WWID der schwarzen Liste hinzu:
+
[source, cli]
----
blacklist {
	     wwid   360030057024d0730239134810c0cb833
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----




== Schritt 5: Passen Sie Multipath-Parameter für ONTAP LUNs an

Wenn Ihr Host mit LUNs anderer Hersteller verbunden ist und eine der Multipath-Parametereinstellungen überschrieben wird, müssen Sie diese korrigieren, indem Sie später Strophen in der Datei hinzufügen `multipath.conf`, die speziell für ONTAP-LUNs gelten. Wenn Sie dies nicht tun, funktionieren die ONTAP LUNs möglicherweise nicht wie erwartet.

Überprüfen Sie Ihre `/etc/multipath.conf` Datei, insbesondere im Abschnitt Standardeinstellungen, auf Einstellungen, die die überschreiben könnten<<multipath-parameter-settings,Standardeinstellungen für Multipath-Parameter>>.


CAUTION: Die empfohlenen Parametereinstellungen für ONTAP LUNs sollten Sie nicht außer Kraft setzen. Diese Einstellungen sind für eine optimale Performance Ihrer Hostkonfiguration erforderlich. Weitere Informationen erhalten Sie vom NetApp-Support, vom Hersteller Ihres Betriebssystems oder von beiden.

Das folgende Beispiel zeigt, wie eine überhielte Standardeinstellung korrigiert wird. In diesem Beispiel definiert die `multipath.conf` Datei Werte für `path_checker` und `no_path_retry`, die nicht mit ONTAP-LUNs kompatibel sind. Sie können diese Parameter nicht entfernen, da ONTAP-Speicher-Arrays noch mit dem Host verbunden sind. Stattdessen korrigieren Sie die Werte für `path_checker` und `no_path_retry`, indem Sie der Datei, die speziell auf die ONTAP-LUNs zutrifft, eine Gerätestanze hinzufügen `multipath.conf`.

.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
defaults {
   path_checker      *readsector0*
   no_path_retry     *fail*
}

devices {
   device {
      vendor          "NETAPP"
      product         "LUN"
      no_path_retry   *queue*
      path_checker    *tur*
   }
}
----
====


== Schritt 6: Überprüfen Sie die bekannten Probleme

Die Version SUSE Linux Enterprise Server 12 SP3 mit ONTAP Storage weist folgende bekannte Probleme auf:

[cols="3*"]
|===
| NetApp Bug ID | Titel | Beschreibung 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1089555["1089555"^] | Kernel-Störung auf Kernel-Version SLES12 SP3 mit Emulex LPe16002 16 GB FC während Speicher-Failover-Betrieb beobachtet | Bei Storage Failover-Vorgängen auf Kernel-Version SLES12 SP3 mit Emulex LPe16002 HBA kann es zu einer Kernel-Störung kommen. Die Kernel-Störung fordert einen Neustart des Betriebssystems auf, was wiederum zu einer Anwendungsunterbrechung führt. Wenn kdump konfiguriert ist, generiert die Kernel-Störung eine vmcore-Datei unter /var/crash/Directory. Sie können die Ursache des Fehlers in der vmcore-Datei untersuchen. Beispiel: Im beobachteten Fall wurde die Kernel-Störung im Modul „lpfc_sli_ringtxcmpl_Put+51“ beobachtet und in der vmcore-Datei – Ausnahme-RIP: Lpfc_sli_ringtxcmpl_Put+51 protokolliert. Stellen Sie das Betriebssystem nach der Kernel-Störung wieder her, indem Sie das Host-Betriebssystem neu starten und die Anwendung neu starten. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1089561["1089561"^] | Kernel-Störung auf Kernel-Version SLES12 SP3 mit Emulex LPe32002 32 GB FC während Storage Failover-Vorgänge beobachtet | Bei Storage Failover-Vorgängen auf Kernel-Version SLES12 SP3 mit Emulex LPe32002 HBA kann es zu einer Kernel-Störung kommen. Die Kernel-Störung fordert einen Neustart des Betriebssystems auf, was wiederum zu einer Anwendungsunterbrechung führt. Wenn kdump konfiguriert ist, generiert die Kernel-Störung eine vmcore-Datei unter /var/crash/Directory. Sie können die Ursache des Fehlers in der vmcore-Datei untersuchen. Beispiel: Im beobachteten Fall wurde die Kernel-Störung im Modul „lpfc_sli_free_hbq+76“ beobachtet und in der vmcore-Datei – Ausnahme-RIP: Lpfc_sli_free_hbq+76 protokolliert. Stellen Sie das Betriebssystem nach der Kernel-Störung wieder her, indem Sie das Host-Betriebssystem neu starten und die Anwendung neu starten. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1117248["1117248"^] | Kernel-Störungen bei SLES12SP3 mit QLogic QLE2562 8 GB FC während eines Storage Failover-Betriebs | Bei Speicher-Failover-Operationen auf dem Sles12sp3 Kernel (Kernel-default-4.4.82-6.3.1) mit QLogic QLE2562 HBA wurde die Kernel-Störung aufgrund einer Panik im Kernel beobachtet. Die Kernel-Panic führt zu einem Neustart des Betriebssystems, was zu einer Anwendungsunterbrechung führt. Wenn kdump konfiguriert ist, generiert die Kernel-Panic die vmcore-Datei unter dem Verzeichnis /var/crash/. Nach einem Panikzustand des Kernels kann die vmcore-Datei verwendet werden, um die Ursache des Fehlers zu verstehen. Beispiel: In diesem Fall wurde die Panik im Modul „blk_Finish_request+289“ beobachtet. Es wird in der vmcore-Datei mit der folgenden Zeichenfolge protokolliert: „Ausnahme RIP: blk_Finish_Request+289“ nach der Kernel-Störung können Sie das Betriebssystem wiederherstellen, indem Sie das Host-Betriebssystem neu starten. Sie können die Anwendung bei Bedarf neu starten. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1117261["1117261"^] | Kernel-Störung auf SLES12SP3 mit Qlogic QLE2662 16 GB FC während Speicher-Failover-Operationen beobachtet | Während Speicher-Failover-Operationen auf Sles12sp3 Kernel (Kernel-default-4.4.82-6.3.1) mit Qlogic QLE2662 HBA, können Sie Kernel-Störungen beobachten. Dadurch wird ein Neustart des Betriebssystems angezeigt, der eine Anwendungsunterbrechung verursacht. Die Kernel-Störung generiert eine vmcore-Datei unter dem Verzeichnis /var/crash/, wenn kdump konfiguriert ist. Die vmcore-Datei kann verwendet werden, um die Ursache des Fehlers zu verstehen. Beispiel: In diesem Fall wurde die Kernel-Störung im Modul "unbekannte oder ungültige Adresse" beobachtet und in der vmcore-Datei mit der folgenden Zeichenfolge - Ausnahme RIP: Unbekannte oder ungültige Adresse protokolliert. Nach einer Störung des Kernels kann das Betriebssystem wiederhergestellt werden, indem das Host-Betriebssystem neu gestartet und die Anwendung nach Bedarf neu gestartet wird. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1117274["1117274"^] | Kernel-Störung auf SLES12SP3 mit Emulex LPe16002 16 GB FC bei Storage Failover-Operationen | Bei Storage Failover-Vorgängen auf dem Sles12sp3 Kernel (Kernel-default-4.4.87-3.1) mit Emulex LPe16002 HBA können Sie möglicherweise eine Kernel-Störung beobachten. Dadurch wird ein Neustart des Betriebssystems angezeigt, der eine Anwendungsunterbrechung verursacht. Wenn kdump konfiguriert ist, generiert die Kernel-Störung eine vmcore-Datei im Verzeichnis /var/crash/. Die vmcore-Datei kann verwendet werden, um die Ursache des Fehlers zu verstehen. Beispiel: In diesem Fall wurde die Kernel-Störung im Modul „RAW_spin_Lock_irqsave+30“ beobachtet und in der vmcore-Datei mit der folgenden Zeichenfolge protokolliert: – Ausnahme RIP: _RAW_spin_Lock_irqsave+30. Nach einer Störung des Kernels kann das Betriebssystem wiederhergestellt werden, indem das Host-Betriebssystem neu gestartet und die Anwendung nach Bedarf neu gestartet wird. 
|===


== Was kommt als Nächstes?

* link:hu-luhu-command-reference.html["Erfahren Sie mehr über die Verwendung des Linux Host Utilities-Tools"] .
* Erfahren Sie mehr über ASM Mirroring.
+
Bei der ASM-Spiegelung (Automatic Storage Management) sind möglicherweise Änderungen an den Linux Multipath-Einstellungen erforderlich, damit ASM ein Problem erkennen und zu einer alternativen Fehlergruppe wechseln kann. Die meisten ASM-Konfigurationen auf ONTAP verwenden externe Redundanz, was bedeutet, dass Datenschutz vom externen Array bereitgestellt wird und ASM keine Daten spiegelt. Einige Standorte verwenden ASM mit normaler Redundanz, um normalerweise zwei-Wege-Spiegelung über verschiedene Standorte hinweg bereitzustellen. Weitere Informationen finden Sie unterlink:https://docs.netapp.com/us-en/ontap-apps-dbs/oracle/oracle-overview.html["Oracle-Datenbanken auf ONTAP"^].


