---
sidebar: sidebar 
permalink: hu_vsphere_6.html 
keywords: host utilities, veritas, infoscale, 6.5. 6.7, netapp, ontap 
summary: Beschreibt die Verwendung von Veritas Infoscale 6.5 und 6.7 für Linux mit ONTAP 
---
= Verwenden Sie VMware vSphere 6.5 und 6.7 mit ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können ONTAP SAN-Hostkonfigurationseinstellungen für die vSphere 6.5.x- und 6.7.x-Versionen mit FC-, FCoE- und iSCSI-Protokollen verwenden.



== Booten des Hypervisor-SAN

.Bevor Sie beginnen
Wenn Sie sich für das Booten über SAN entscheiden, muss es von Ihrer Konfiguration unterstützt werden. Sie können mit dem link:https://imt.netapp.com/matrix/#welcome["Interoperabilitäts-Matrix-Tool"^]überprüfen, ob Ihr Betriebssystem, HBA, die HBA-Firmware und das HBA-StartBIOS sowie die ONTAP-Version unterstützt werden.

.Schritte
. Ordnen Sie die SAN-Boot-LUN dem Host zu.
. Vergewissern Sie sich, dass mehrere Pfade verfügbar sind.
+

NOTE: Mehrere Pfade sind verfügbar, nachdem das Host-Betriebssystem auf den Pfaden ausgeführt wurde.

. Aktivieren Sie das SAN-Booten im Server-BIOS für die Ports, denen die SAN-Boot-LUN zugeordnet ist.
+
Informationen zum Aktivieren des HBA-BIOS finden Sie in der anbieterspezifischen Dokumentation.

. Starten Sie den Host neu, um zu überprüfen, ob der Startvorgang erfolgreich war.




== Multipathing

ESXi bietet ein erweiterbares Multipathing-Modul namens Native Multipathing Plug-in (NMP), das die Sub-Plugins, Storage Array Type Plugins (SATPs) und Path Selection Plugins (PSPs) verwaltet. Diese SATP-Regeln sind standardmäßig in ESXi verfügbar.

Für ONTAP-Speicher wird standardmäßig das „VMW_SATP_ALUA“-Plugin mit „VMW_PSP_RR“ als Pfadauswahlrichtlinie (PSP) verwendet. Du kannst den folgenden Befehl ausführen, um das PSP-System zu bestätigen:

*`esxcli storage nmp satp rule list -s VMW_SATP_ALUA`*

[listing]
----
Name           Device  Vendor    Model     Driver  Transport  Options
-------------  ------  ------    -------   ------  ---------  -------
VMW_SATP_ALUA           LSI      INF-01-00                reset_on_attempted_reserve
VMW_SATP_ALUA           NETAPP                            reset_on_attempted_reserve

Rule Group  Claim Options  Default PSP  PSP Options  Description
----------  -------------  -----------  -----------  ------------
system        tpgs_on         VMW_PSP_MRU       NetApp E-Series arrays with ALUA support
system        tpgs_on          MW_PSP_RR 	      NetApp arrays with ALUA support

----


=== Alle SAN-Array-Konfigurationen

Alle SAN-Array-(ASA-)Konfigurationen optimieren alle Pfade zu einer bestimmten LUN und halten sie aktiv. Dies verbessert die Performance, da I/O-Operationen über alle Pfade gleichzeitig ausgeführt werden können.

.Beispiel
Im folgenden Beispiel wird die richtige Ausgabe für eine ONTAP-LUN angezeigt.

*`esxcli storage nmp device list -d naa.600a098038304759563f4e7837574453`*

[listing]
----
fc.20000024ff171d37:21000024ff171d37-fc.202300a098ea5e27:204a00a098ea5e27-naa.600a098038304759563f4e7837574453
   Runtime Name: vmhba4:C0:T0:L9
   Device: naa.600a098038304759563f4e7837574453
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038304759563f4e7837574453)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1000,TPG_state=AO,RTP_id=6,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.20000024ff171d36:21000024ff171d36-fc.202300a098ea5e27:201d00a098ea5e27-naa.600a098038304759563f4e7837574453
   Runtime Name: vmhba3:C0:T1:L9
   Device: naa.600a098038304759563f4e7837574453
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038304759563f4e7837574453)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1001,TPG_state=AO,RTP_id=3,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.20000024ff171d36:21000024ff171d36-fc.202300a098ea5e27:201b00a098ea5e27-naa.600a098038304759563f4e7837574453
   Runtime Name: vmhba3:C0:T0:L9
   Device: naa.600a098038304759563f4e7837574453
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038304759563f4e7837574453)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1000,TPG_state=AO,RTP_id=1,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.20000024ff171d37:21000024ff171d37-fc.202300a098ea5e27:201e00a098ea5e27-naa.600a098038304759563f4e7837574453
   Runtime Name: vmhba4:C0:T1:L9
   Device: naa.600a098038304759563f4e7837574453
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038304759563f4e7837574453)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1001,TPG_state=AO,RTP_id=4,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.
----
In dem obigen Beispiel wurde die LUN aus NetApp Storage mit 4 Pfaden zugeordnet (4 aktiv-optimiert).



=== Konfigurationen ohne ASA

Für Konfigurationen ohne ASA sollten zwei Gruppen von Pfaden mit unterschiedlichen Prioritäten vorhanden sein. Die Pfade mit höheren Prioritäten sind aktiv/optimiert. Das heißt, sie werden vom Controller gewartet, wo sich das Aggregat befindet. Die Pfade mit niedrigeren Prioritäten sind aktiv, aber nicht optimiert, da sie von einem anderen Controller bedient werden. Die nicht optimierten Pfade werden nur verwendet, wenn optimierte Pfade nicht verfügbar sind.

.Beispiel
Das folgende Beispiel zeigt die richtige Ausgabe für eine ONTAP-LUN mit zwei aktiv/optimierten Pfaden und zwei aktiv/nicht optimierten Pfaden.

*`esxcli storage nmp path list -d naa.600a098038313530772b4d673979372f`*

[listing]
----
fc.20000090fae0ec8e:10000090fae0ec8e-fc.201000a098dfe3d1:200b00a098dfe3d1-naa.600a098038313530772b4d673979372f
   Runtime Name: vmhba3:C0:T2:L21
   Device: naa.600a098038313530772b4d673979372f
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038313530772b4d673979372f)
   Group State: active unoptimized
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1001,TPG_state=ANO,RTP_id=29,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.20000090fae0ec8e:10000090fae0ec8e-fc.201000a098dfe3d1:200700a098dfe3d1-naa.600a098038313530772b4d673979372f
   Runtime Name: vmhba3:C0:T3:L21
   Device: naa.600a098038313530772b4d673979372f
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038313530772b4d673979372f)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1000,TPG_state=AO,RTP_id=25,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.20000090fae0ec8f:10000090fae0ec8f-fc.201000a098dfe3d1:200800a098dfe3d1-naa.600a098038313530772b4d673979372f
   Runtime Name: vmhba4:C0:T2:L21
   Device: naa.600a098038313530772b4d673979372f
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038313530772b4d673979372f)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1000,TPG_state=AO,RTP_id=26,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.20000090fae0ec8f:10000090fae0ec8f-fc.201000a098dfe3d1:200c00a098dfe3d1-naa.600a098038313530772b4d673979372f
   Runtime Name: vmhba4:C0:T3:L21
   Device: naa.600a098038313530772b4d673979372f
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038313530772b4d673979372f)
   Group State: active unoptimized
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1001,TPG_state=ANO,RTP_id=30,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.
----
In dem obigen Beispiel wurde die LUN von NetApp Storage mit 4 Pfaden zugeordnet (2 aktiv-optimiert und 2 aktiv-nicht optimiert).



== VVol

Virtual Volumes (VVols) sind ein VMware Objekttyp, der einer VM-Festplatte (Virtual Machine) entspricht, mit Snapshots und schnellen Klonen.

Die ONTAP Tools für VMware vSphere umfassen den VASA Provider für ONTAP, der den Integrationspunkt für VMware vCenter zur Nutzung von VVols-basiertem Storage bietet. Bei der Implementierung der ONTAP Tools OVA wird sie automatisch beim vCenter Server registriert und aktiviert den VASA Provider.

Wenn Sie einen VVols-Datastore über die vCenter-Benutzeroberfläche erstellen, werden FlexVols als Backup-Storage für den Datastore erstellt. Auf VVols in einem VVols-Datastore wird von ESXi-Hosts über einen Protokollendpunkt (PE) zugegriffen. In SAN-Umgebungen wird eine 4-MB-LUN auf jedem FlexVol volume-Volume im Datenspeicher erstellt, um sie als PE zu verwenden. Ein SAN PE ist eine administrative logische Einheit (Alu); VVols sind untergeordnete logische Einheiten (SLUs).

Bei der Verwendung von VVols gelten Standardanforderungen und Best Practices für SAN-Umgebungen, darunter (aber nicht beschränkt auf) die folgenden:

. Erstellen Sie mindestens eine SAN-LIF auf jedem Node pro SVM, die Sie verwenden möchten. Als Best Practice empfiehlt es sich, mindestens zwei pro Node zu erstellen, aber nicht mehr als nötig.
. Keine Single Points of Failure mehr Nutzung mehrerer VMkernel Netzwerkschnittstellen für verschiedene Subnetze, in denen bei Verwendung mehrerer virtueller Switches NIC-Teaming zum Einsatz kommt oder mehrere physische NICs zum Einsatz kommen, die mit mehreren physischen Switches verbunden sind, um Hochverfügbarkeit und einen höheren Durchsatz bereitzustellen.
. Konfiguration des Zoning und/oder VLANs entsprechend den Anforderungen der Host-Konnektivität
. Stellen Sie sicher, dass alle erforderlichen Initiatoren in den Ziel-LIFs auf der gewünschten SVM protokolliert werden.



NOTE: Um den VASA Provider zu aktivieren, müssen Sie ONTAP Tools für VMware vSphere implementieren. Vasa Provider verwaltet alle igroup-Einstellungen für Sie, sodass das Erstellen und Managen von iGroups in einer VVols-Umgebung nicht erforderlich ist.

NetApp empfiehlt derzeit nicht, die Standardeinstellungen für VVols zu ändern.

Spezifische Versionen von ONTAP Tools finden Sie im. Weitere Informationen finden Sie im https://imt.netapp.com/matrix/#welcome["Interoperabilitäts-Matrix-Tool"^] alten VASA Provider für Ihre spezifischen Versionen von vSphere und ONTAP.

Ausführliche Informationen zum Bereitstellen und Managen von VVols finden Sie in der Dokumentation zu ONTAP Tools für VMware vSphere sowie https://docs.netapp.com/us-en/ontap-apps-dbs/vmware/vmware-vsphere-overview.html["VMware vSphere mit ONTAP –"^] zu und link:https://docs.netapp.com/us-en/ontap-apps-dbs/vmware/vmware-vvols-overview.html["Virtual Volumes (VVols) mit ONTAP Tools 10"^].



== Empfohlene Einstellungen



=== ATS-Verriegelung

ATS-Sperrung ist *obligatorisch* für VAAI-kompatiblen Speicher und aktualisierte VMFS5 und ist erforderlich für ordnungsgemäße Interoperabilität und optimale VMFS Shared Storage I/O-Performance mit ONTAP LUNs. Weitere Informationen zum Aktivieren der ATS-Sperrung finden Sie in der VMware-Dokumentation.

[cols="4*"]
|===
| Einstellungen | Standard | ONTAP empfohlen | Beschreibung 


| HardwareBeschleunigungsverriegelung | 1 | 1 | Ermöglicht die Verwendung von ATS-Verriegelung (Atomic Test and Set) 


| Festplatten-IOPS | 1000 | 1 | IOPS-Limit: Das Round Robin PSP-System erreicht standardmäßig ein IOPS-Limit von 1000. In diesem Standardfall wird ein neuer Pfad verwendet, nachdem 1000 I/O-Vorgänge ausgegeben wurden. 


| Disk/QFullSampleSize | 0 | 32 | Die Anzahl der „QUEUE FULL“- oder „BUSY“-Bedingungen, die es dauert, bevor ESXi beginnt, zu drosseln. 
|===

NOTE: Aktivieren Sie die Space-Alloc-Einstellung für alle LUNs, die VMware vSphere zugeordnet sind, damit UNMAP funktioniert. Weitere Informationen finden Sie unter https://docs.netapp.com/ontap-9/index.jsp["ONTAP-Dokumentation"^].



=== Timeouts für Gastbetriebssysteme

Sie können die virtuellen Maschinen manuell mit den empfohlenen Einstellungen für das Gastbetriebssystem konfigurieren. Nach den Tuning-Updates müssen Sie den Gast neu starten, damit die Updates wirksam werden.

*GOS Timeout Werte:*

[cols="2*"]
|===
| Gastbetriebssystem-Typ | Zeitüberschreitungen 


| Linux-Varianten | Zeitüberschreitung bei Festplatte = 60 


| Windows | Zeitüberschreitung bei Festplatte = 60 


| Solaris | Disk-Timeout = 60 Taced Retry = 300 Not Ready retry = 300 RESET-Retry = 30 max.drossel = 32 min.drossel = 8 
|===


=== Validieren der abstimmbaren vSphere-Lösung

Verwenden Sie den folgenden Befehl, um die zu überprüfen `HardwareAcceleratedLocking` Einstellung:

*`esxcli system settings  advanced list --option /VMFS3/HardwareAcceleratedLocking`*

[listing]
----
   Path: /VMFS3/HardwareAcceleratedLocking
   Type: integer
   Int Value: 1
   Default Int Value: 1
   Min Value: 0
   Max Value: 1
   String Value:
   Default String Value:
   Valid Characters:
   Description: Enable hardware accelerated VMFS locking (requires compliant hardware). Please see http://kb.vmware.com/kb/2094604 before disabling this option.
----


=== Überprüfen Sie die Festplatten-IOPS-Einstellung

Überprüfen Sie die IOPS-Einstellung mit dem folgenden Befehl:

*`esxcli storage nmp device list -d naa.600a098038304731783f506670553355`*

[listing]
----
naa.600a098038304731783f506670553355
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038304731783f506670553355)
   Storage Array Type: VMW_SATP_ALUA
   Storage Array Type Device Config: {implicit_support=on; explicit_support=off; explicit_allow=on; alua_followover=on; action_OnRetryErrors=off; {TPG_id=1000,TPG_state=ANO}{TPG_id=1001,TPG_state=AO}}
   Path Selection Policy: VMW_PSP_RR
   Path Selection Policy Device Config: {policy=rr,iops=1,bytes=10485760,useANO=0; lastPathIndex=0: NumIOsPending=0,numBytesPending=0}
   Path Selection Policy Device Custom Config:
   Working Paths: vmhba4:C0:T0:L82, vmhba3:C0:T0:L82
   Is USB: false
----


=== Überprüfen Sie die QFullSampleSize

Überprüfen Sie mit dem folgenden Befehl die QFullSampleSize:

*`esxcli system settings  advanced list --option /Disk/QFullSampleSize`*

[listing]
----
   Path: /Disk/QFullSampleSize
   Type: integer
   Int Value: 32
   Default Int Value: 0
   Min Value: 0
   Max Value: 64
   String Value:
   Default String Value:
   Valid Characters:
   Description: Default I/O samples to monitor for detecting non-transient queue full condition. Should be nonzero to enable queue depth throttling. Device specific QFull options will take precedence over this value if set.
----


== Bekannte Probleme

VMware vSphere 6.5 und 6.7 mit ONTAP Version weist folgende bekannte Probleme auf:

[cols="21%,20%,14%,27%"]
|===
| *Betriebssystemversion* | *NetApp Bug ID* | *Titel* | *Beschreibung* 


| ESXi 6.5 und ESXi 6.7.x | 1413424 | Die WFC RDM luns schlägt während des Tests fehl | Windows Failover Clustering der RAW Device Mapping zwischen Windows Virtual Machines wie Windows 2019 7, Windows 2016 und Windows 2012 über den VMware ESXi Host ist beim Storage Failover-Test auf allen C-Mode Cluster Controllern fehlgeschlagen. 


| ESXi 6.5.x und ESXi 6.7.x | 1256473 | PLOGI-Problem während der Tests auf Emulex-Adaptern gesehen |  
|===
.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap-apps-dbs/vmware/vmware-vsphere-overview.html["VMware vSphere mit ONTAP –"^]
* link:https://kb.vmware.com/s/article/2031038["Unterstützung von VMware vSphere 5.x, 6.x und 7.x mit NetApp MetroCluster (2031038)"^]
* link:https://kb.vmware.com/s/article/83370["NetApp ONTAP mit NetApp SnapMirror Active Sync mit VMware vSphere Metro Storage Cluster (vMSC)"^]

