---
sidebar: sidebar 
permalink: hu_veritas_6x.html 
keywords: host utilities, veritas, infoscale, 6.x, netapp, ontap, san, lun, multipathing, iscsi 
summary: Hier finden Sie Anleitungen zur Konfiguration der ONTAP-SAN-Hosts für die Version der Veritas Infoscale 6 Serie 
---
= Konfigurieren Sie Veritas Infoscale 6 für FC, FCoE und iSCSI mit ONTAP -Speicher
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die Linux Host Utilities-Software bietet Verwaltungs- und Diagnosetools für Linux-Hosts, die mit ONTAP Speicher verbunden sind. Verwenden Sie die Linux Host Utilities mit Veritas Infoscale 6 für Oracle Linux (Red Hat Compatible Kernel based), Red Hat Enterprise Linux (RHEL) und SUSE Linux Enterprise Server-Hosts, um die Verwaltung von FC-, FCoE- und iSCSI-Protokolloperationen mit ONTAP -LUNs zu unterstützen.



== Schritt 1: Aktivieren Sie optional den SAN-Bootvorgang

Sie können Ihren Host so konfigurieren, dass er SAN-Booting verwendet, um die Bereitstellung zu vereinfachen und die Skalierbarkeit zu verbessern.

.Bevor Sie beginnen
* Überprüfen Sie mithilfe deslink:https://mysupport.netapp.com/matrix/#welcome["Interoperabilitäts-Matrix-Tool"^], ob Ihr Linux-Betriebssystem, Ihr Host Bus Adapter (HBA), die HBA-Firmware, das HBA-Boot-BIOS und die ONTAP-Version das Booten über das SAN unterstützen.
* Im Veritas Support Portal (Produktmatrix, Plattform-Lookup und HCL-Matrix) können Sie die Unterstützung der SAN-Boot-Konfiguration und bekannte Probleme überprüfen.


.Schritte
. link:https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["Erstellen Sie eine SAN-Boot-LUN und ordnen Sie sie dem Host zu"^].
. Aktivieren Sie das SAN-Booten im Server-BIOS für die Ports, denen die SAN-Boot-LUN zugeordnet ist.
+
Informationen zum Aktivieren des HBA-BIOS finden Sie in der anbieterspezifischen Dokumentation.

. Überprüfen Sie, ob die Konfiguration erfolgreich war, indem Sie den Host neu starten und überprüfen, ob das Betriebssystem ausgeführt wird.




== Schritt 2: Installieren Sie die Linux Host Utilities

NetApp empfiehlt dringend link:hu-luhu-release-notes.html["Installation der Linux-Host-Dienstprogramme"] zur Unterstützung des ONTAP LUN-Managements und zur Unterstützung des technischen Supports bei der Erfassung von Konfigurationsdaten.


NOTE: Durch die Installation der Linux Host Utilities werden keine Host-Timeout-Einstellungen auf Ihrem Linux-Host geändert.



== Schritt 3: Bestätigen Sie die Veritas Dynamic Multipathing-Konfiguration für Ihren Host.

Verwenden Sie Veritas Dynamic Multipathing (VxDMP) mit Veritas Infoscale 6 zur Verwaltung von ONTAP LUNs.

Um sicherzustellen, dass VxDMP für Ihren Host korrekt eingerichtet ist, müssen Sie die VxDMP-Konfiguration überprüfen und die Konfiguration der Array Support Library (ASL) und des Array Policy Module (APM) überprüfen. Die ASL- und APM-Pakete für NetApp -Speichersysteme werden während der Veritas-Softwareinstallation installiert.


NOTE: Für heterogene Multipath-Umgebungen, einschließlich Veritas Infoscale, Linux Native Device Mapper und LVM Volume Manager, konsultieren Sie bitte die Veritas-Produktadministrationsdokumentation bezüglich der Konfigurationseinstellungen.

.Bevor Sie beginnen
Stellen Sie sicher, dass Ihre Konfiguration die Systemanforderungen erfüllt. Siehe die link:https://mysupport.netapp.com/matrix/#welcome["Interoperabilitäts-Matrix-Tool"^] und die Veritas HCL Matrix.

.Schritte
. Überprüfen Sie, ob das ONTAP Zielarray an den VxDMP-Multipath angeschlossen ist:
+
[source, cli]
----
vxdmpadm
----
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
# vxdmpadm listenclosure
ENCLR_NAME   ENCLR_TYPE  ENCLR_SNO     STATUS      ARRAY_TYPE    LUN_COUNT    FIRMWARE
=====================================================================================
sfrac0       SFRAC       804Xw$PqE52h  CONNECTED   ALUA          43           9800
# vxdmpadm getdmpnode
NAME       STATE    ENCLR-TYPE  PATHS  ENBL  DSBL ENCLR-NAME
===================================================================
sfrac0_47  ENABLED  SFRAC       4      4     0    sfrac0
----
====
. Überprüfen Sie die Konfiguration der ASL- und APM-Pakete. NetApp empfiehlt die Verwendung der neuesten unterstützten Pakete, die im Veritas-Supportportal aufgeführt sind.
+
.Beispielkonfiguration für ASL und APM anzeigen
[%collapsible]
====
[listing]
----
# vxdmpadm list dmpnode dmpnodename=sfrac0_47 | grep asl
asl        = libvxnetapp.so
# vxddladm listversion |grep libvxnetapp.so
libvxnetapp.so                  vm-8.0.0-rev-1   8.0

# rpm -qa |grep VRTSaslapm
VRTSaslapm-x.x.x.0000-RHEL8.X86_64
vxddladm listsupport libname=libvxnetapp.so
ATTR_NAME   ATTR_VALUE
=========================================
LIBNAME     libvxnetapp.so
VID         NETAPP
PID         All
ARRAY_TYPE  ALUA, A/A
----
====
. Für eine optimale Systemkonfiguration im Falle eines Speicherausfalls stellen Sie bitte sicher, dass Sie über die folgenden Veritas VxDMP-Einstellungen verfügen:
+
[cols="2*"]
|===
| Parameter | Einstellung 


| dmp_lun_retry_Timeout | 60 


| dmp_PATH_Age | 120 


| dmp_Restore_Intervall | 60 
|===
. Stellen Sie die DMP-Regler auf Online:
+
[source, cli]
----
# vxdmpadm settune dmp_tunable=value
----
. Überprüfen Sie, ob die Tunables-Einstellungen korrekt sind:
+
[source, cli]
----
# vxdmpadm gettune
----
+
Das folgende Beispiel zeigt die effektiven VxDMP-Parameter auf einem SAN-Host.

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
# vxdmpadm gettune

Tunable                    Current Value    Default Value
dmp_cache_open                      on                on
dmp_daemon_count                    10                10
dmp_delayq_interval                 15                15
dmp_display_alua_states             on                on
dmp_fast_recovery                   on                on
dmp_health_time                     60                60
dmp_iostats_state              enabled           enabled
dmp_log_level                        1                 1
dmp_low_impact_probe                on                on
dmp_lun_retry_timeout               60                30
dmp_path_age                       120               300
dmp_pathswitch_blks_shift            9                 9
dmp_probe_idle_lun                  on                on
dmp_probe_threshold                  5                 5
dmp_restore_cycles                  10                10
dmp_restore_interval                60               300
dmp_restore_policy         check_disabled   check_disabled
dmp_restore_state              enabled           enabled
dmp_retry_count                      5                 5
dmp_scsi_timeout                    20                20
dmp_sfg_threshold                    1                 1
dmp_stat_interval                    1                 1
dmp_monitor_ownership               on                on
dmp_monitor_fabric                  on                on
dmp_native_support                 off               off
----
====
. Konfigurieren Sie die Protokoll-Timeout-Werte:
+
[role="tabbed-block"]
====
.FC/FCoE
--
Verwenden Sie die Standard-Timeout-Werte für FC und FCoE.

--
.iSCSI
--
Stellen Sie die `replacement_timeout` Parameterwert auf 120 setzen.

iSCSI `replacement_timeout` Der Parameter steuert, wie lange die iSCSI-Schicht warten soll, bis ein abgelaufener Pfad oder eine abgelaufene Sitzung wiederhergestellt ist, bevor Befehle darauf fehlschlagen. NetApp empfiehlt, den Wert wie folgt festzulegen: `replacement_timeout` auf 120 in der iSCSI-Konfigurationsdatei.

[source, cli]
----
# grep replacement_timeout /etc/iscsi/iscsid.conf
node.session.timeo.replacement_timeout = 120
----
--
====
. Legen Sie die Host-"udev rport"-Werte für Hosts der RHEL 8- und 9-Serie fest, um die Veritas Infoscale-Umgebung in Speicherausfallszenarien zu unterstützen.
+
Konfigurieren Sie die Werte für "udev rport", indem Sie die Datei erstellen. `/etc/udev/rules.d/40-rport.rules` mit folgendem Dateiinhalt:

+
[listing]
----
# cat /etc/udev/rules.d/40-rport.rules
KERNEL=="rport-*", SUBSYSTEM=="fc_remote_ports", ACTION=="add", RUN+=/bin/sh -c 'echo 20 > /sys/class/fc_remote_ports/%k/fast_io_fail_tmo;echo 864000 >/sys/class/fc_remote_ports/%k/dev_loss_tmo'"
----
+

NOTE: Alle weiteren Veritas-spezifischen Einstellungen finden Sie in der Standard-Produktdokumentation von Veritas Infoscale.

. Überprüfen Sie die Parametereinstellungen und den Pfadstatus für Ihre ONTAP LUNs:
+
In AFF, FAS oder ASA Konfigurationen sollte eine einzelne ONTAP LUN nicht mehr als vier Pfade benötigen. Bei einem Speicherausfall können mehr als vier Pfade Probleme verursachen.

+
Die folgenden Beispiele zeigen die korrekten Parametereinstellungen und den Pfadstatus für ONTAP -LUNs in einer ASA, AFF oder FAS Konfiguration.

+
[role="tabbed-block"]
====
.ASA-Konfiguration
--
Eine ASA Konfiguration optimiert alle Pfade zu einer bestimmten LUN und hält sie aktiv. Dies verbessert die Performance, da I/O-Operationen über alle Pfade gleichzeitig ausgeführt werden können.

.Beispiel anzeigen
[%collapsible]
=====
[listing]
----
# vxdmpadm getsubpaths dmpnodename-sfrac0_47
NAME  STATE[A]   PATH-TYPE[M]   CTLR-NAME   ENCLR-TYPE  ENCLR-NAME  ATTRS  PRIORITY
===================================================================================
sdas  ENABLED (A)    Active/Optimized c13   SFRAC       sfrac0     -      -
sdb   ENABLED(A) Active/Optimized     c14   SFRAC       sfrac0     -      -
sdcj  ENABLED(A)  Active/Optimized     c14   SFRAC       sfrac0     -      -
sdea  ENABLED (A)    Active/Optimized c14   SFRAC       sfrac0     -
----
=====
--
.AFF- oder FAS-Konfiguration
--
Eine AFF- oder FAS-Konfiguration sollte zwei Pfadgruppen mit höheren und niedrigeren Prioritäten aufweisen. Aktiv/optimierte Pfade mit höherer Priorität werden vom Controller bedient, wo sich das Aggregat befindet. Pfade mit niedriger Priorität sind aktiv, jedoch nicht optimiert, da sie von einem anderen Controller bedient werden. Nicht optimierte Pfade werden nur verwendet, wenn keine optimierten Pfade verfügbar sind.

Im folgenden Beispiel wird die Ausgabe für eine ONTAP-LUN mit zwei aktiv/optimiert-Pfaden und zwei aktiv/nicht-optimierten Pfaden angezeigt:

.Beispiel anzeigen
[%collapsible]
=====
[listing]
----
# vxdmpadm getsubpaths dmpnodename-sfrac0_47
NAME  STATE[A]   PATH-TYPE[M]   CTLR-NAME   ENCLR-TYPE  ENCLR-NAME  ATTRS  PRIORITY
===================================================================================
sdas  ENABLED     Active/Non-Optimized c13   SFRAC       sfrac0     -      -
sdb   ENABLED(A)  Active/Optimized     c14   SFRAC       sfrac0     -      -
sdcj  ENABLED(A)  Active/Optimized     c14   SFRAC       sfrac0     -      -
sdea  ENABLED     Active/Non-Optimized c14   SFRAC       sfrac0     -      -
----
=====
--
====




== Schritt 4: Bekannte Probleme

Es sind keine Probleme bekannt.



== Was kommt als Nächstes?

* link:hu-luhu-command-reference.html["Erfahren Sie mehr über die Verwendung des Linux Host Utilities-Tools"] .

