---
sidebar: sidebar 
permalink: hu_vsphere_8.html 
keywords: host utilities, veritas, infoscale, 8.x, netapp, ontap, vmware, vspehere 
summary: Sie können die ONTAP-SAN-Hosteinstellungen für die VMware vSphere 8.x-Version mit FC-, FCoE- und iSCSI-Protokollen konfigurieren. 
---
= Verwenden Sie VMware vSphere 8.x mit ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können die ONTAP-SAN-Hosteinstellungen für die VMware vSphere 8.x-Version mit FC-, FCoE- und iSCSI-Protokollen konfigurieren.



== Booten von Hypervisor-SAN

.Bevor Sie beginnen
Wenn Sie sich für das Booten über SAN entscheiden, muss es von Ihrer Konfiguration unterstützt werden. Sie können mit dem link:https://imt.netapp.com/matrix/#welcome["Interoperabilitäts-Matrix-Tool"^]überprüfen, ob Ihr Betriebssystem, HBA, die HBA-Firmware und das HBA-StartBIOS sowie die ONTAP-Version unterstützt werden.

.Schritte
. Ordnen Sie die SAN-Boot-LUN dem Host zu.
. Vergewissern Sie sich, dass mehrere Pfade verfügbar sind.
+

NOTE: Mehrere Pfade sind verfügbar, nachdem das Host-Betriebssystem auf den Pfaden ausgeführt wurde.

. Aktivieren Sie das SAN-Booten im Server-BIOS für die Ports, denen die SAN-Boot-LUN zugeordnet ist.
+
Informationen zum Aktivieren des HBA-BIOS finden Sie in der anbieterspezifischen Dokumentation.

. Starten Sie den Host neu, um zu überprüfen, ob der Startvorgang erfolgreich war.




== Multipathing

ESXi bietet ein erweiterbares Multipathing-Modul namens Native Multipathing Plug-in (NMP), das die Sub-Plugins, Storage Array Type Plugins (SATPs) und Path Selection Plugins (PSPs) verwaltet. Standardmäßig sind diese SATP-Regeln in ESXi verfügbar.

Für ONTAP-Speicher wird standardmäßig das „VMW_SATP_ALUA“-Plugin mit „VMW_PSP_RR“ als Pfadauswahlrichtlinie (PSP) verwendet. Du kannst den folgenden Befehl ausführen, um das PSP-System zu bestätigen:

[listing]
----
`esxcli storage nmp satp rule list -s VMW_SATP_ALUA`
----
Beispielausgabe:

[listing]
----
Name           Device  Vendor    Model         Driver  Transport  Options
---------------------------------------------------------------------------------
VMW_SATP_ALUA          LSI       INF-01-00                        reset_on_attempted_reserve  system
VMW_SATP_ALUA          NETAPP                                     reset_on_attempted_reserve  system

Rule Group  Claim Options  Default PSP  PSP Options     Description
------------------------------------------------------------------
tpgs_on        VMW_PSP_MRU                  NetApp E-Series arrays with ALUA support
tpgs_on        VMW_PSP_RR                   NetApp arrays with ALUA support
----


=== Konfigurationen ohne ASA

Für Konfigurationen ohne ASA sollten zwei Gruppen von Pfaden mit unterschiedlichen Prioritäten vorhanden sein. Die Pfade mit höheren Prioritäten sind aktiv/optimiert. Das heißt, sie werden vom Controller gewartet, wo sich das Aggregat befindet. Die Pfade mit niedrigeren Prioritäten sind aktiv, aber nicht optimiert, da sie von einem anderen Controller bedient werden. Die nicht optimierten Pfade werden nur verwendet, wenn optimierte Pfade nicht verfügbar sind.

.Beispiel
Das folgende Beispiel zeigt die richtige Ausgabe für eine ONTAP-LUN mit zwei aktiv/optimierten Pfaden und zwei aktiv/nicht optimierten Pfaden.

[listing]
----
# esxcli storage nmp device list -d naa.600a0980383148693724545244395855
----
Beispielausgabe:

[listing]
----
naa.600a0980383148693724545244395855
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a0980383148693724545244395855)
   Storage Array Type: VMW_SATP_ALUA
   Storage Array Type Device Config: {implicit_support=on; explicit_support=off; explicit_allow=on; alua_followover=on; action_OnRetryErrors=off; {TPG_id=1000,TPG_state=ANO}{TPG_id=1001,TPG_state=AO}}
   Path Selection Policy: VMW_PSP_RR
   Path Selection Policy Device Config: {policy=rr,iops=1000,bytes=10485760,useANO=0; lastPathIndex=1: NumIOsPending=0,numBytesPending=0}
   Path Selection Policy Device Custom Config:
   Working Paths: vmhba4:C0:T0:L11, vmhba3:C0:T0:L11
   Is USB: false
----
[listing]
----
# esxcli storage nmp path list -d naa.600a0980383148693724545244395855
----
Beispielausgabe:

[listing, subs="+quotes"]
----
fc.20000024ff7f4a51:21000024ff7f4a51-fc.2009d039ea3ab21f:2003d039ea3ab21f-naa.600a0980383148693724545244395855
   Runtime Name: vmhba4:C0:T0:L11
   Device: naa.600a0980383148693724545244395855
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a0980383148693724545244395855)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1001,*TPG_state=AO*,RTP_id=4,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.20000024ff7f4a50:21000024ff7f4a50-fc.2009d039ea3ab21f:2002d039ea3ab21f-naa.600a0980383148693724545244395855
   Runtime Name: vmhba3:C0:T0:L11
   Device: naa.600a0980383148693724545244395855
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a0980383148693724545244395855)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1001,*TPG_state=AO*,RTP_id=3,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.20000024ff7f4a51:21000024ff7f4a51-fc.2009d039ea3ab21f:2001d039ea3ab21f-naa.600a0980383148693724545244395855
   Runtime Name: vmhba4:C0:T3:L11
   Device: naa.600a0980383148693724545244395855
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a0980383148693724545244395855)
   Group State: active unoptimized
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1000,*TPG_state=ANO*,RTP_id=2,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.20000024ff7f4a50:21000024ff7f4a50-fc.2009d039ea3ab21f:2000d039ea3ab21f-naa.600a0980383148693724545244395855
   Runtime Name: vmhba3:C0:T3:L11
   Device: naa.600a0980383148693724545244395855
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a0980383148693724545244395855)
   Group State: active unoptimized
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1000,*TPG_state=ANO*,RTP_id=1,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.
----


=== Alle SAN-Array-Konfigurationen

Alle SAN-Array-(ASA-)Konfigurationen optimieren alle Pfade zu einer bestimmten LUN und halten sie aktiv. Dies verbessert die Performance, da I/O-Operationen über alle Pfade gleichzeitig ausgeführt werden können.

.Beispiel
Im folgenden Beispiel wird die richtige Ausgabe für eine ONTAP-LUN angezeigt.

[listing]
----
esxcli storage nmp device list -d naa.600a098038304759563f4e7837574453
----
Beispielausgabe:

[listing]
----
naa.600a098038314962485d543078486c7a
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038314962485d543078486c7a)
   Storage Array Type: VMW_SATP_ALUA
   Storage Array Type Device Config: {implicit_support=on; explicit_support=off; explicit_allow=on; alua_followover=on; action_OnRetryErrors=off; {TPG_id=1001,TPG_state=AO}{TPG_id=1000,TPG_state=AO}}
   Path Selection Policy: VMW_PSP_RR
   Path Selection Policy Device Config: {policy=rr,iops=1000,bytes=10485760,useANO=0; lastPathIndex=3: NumIOsPending=0,numBytesPending=0}
   Path Selection Policy Device Custom Config:
   Working Paths: vmhba4:C0:T0:L14, vmhba4:C0:T1:L14, vmhba3:C0:T0:L14, vmhba3:C0:T1:L14
   Is USB: false

----
[listing]
----
# esxcli storage nmp path list -d naa.600a098038314962485d543078486c7a
----
Beispielausgabe:

[listing, subs="+quotes"]
----
fc.200034800d756a75:210034800d756a75-fc.2018d039ea936319:2015d039ea936319-naa.600a098038314962485d543078486c7a
   Runtime Name: vmhba4:C0:T0:L14
   Device: naa.600a098038314962485d543078486c7a
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038314962485d543078486c7a)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1000,*TPG_state=AO*,RTP_id=2,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.200034800d756a75:210034800d756a75-fc.2018d039ea936319:2017d039ea936319-naa.600a098038314962485d543078486c7a
   Runtime Name: vmhba4:C0:T1:L14
   Device: naa.600a098038314962485d543078486c7a
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038314962485d543078486c7a)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1001,*TPG_state=AO*,RTP_id=4,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.200034800d756a74:210034800d756a74-fc.2018d039ea936319:2014d039ea936319-naa.600a098038314962485d543078486c7a
   Runtime Name: vmhba3:C0:T0:L14
   Device: naa.600a098038314962485d543078486c7a
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038314962485d543078486c7a)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1000,*TPG_state=AO*,RTP_id=1,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.200034800d756a74:210034800d756a74-fc.2018d039ea936319:2016d039ea936319-naa.600a098038314962485d543078486c7a
   Runtime Name: vmhba3:C0:T1:L14
   Device: naa.600a098038314962485d543078486c7a
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038314962485d543078486c7a)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1001,*TPG_state=AO*,RTP_id=3,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.
----


== VVol

Virtual Volumes (VVols) sind ein VMware Objekttyp, der einer Virtual Machine (VM)-Festplatte, ihren Snapshots und schnellen Klonen entspricht.

Die ONTAP Tools für VMware vSphere umfassen den VASA Provider für ONTAP, der den Integrationspunkt für VMware vCenter zur Nutzung von VVols-basiertem Storage bietet. Wenn Sie die ONTAP-Tools Open Virtualization Appliance (OVA) bereitstellen, wird sie automatisch beim vCenter-Server registriert und aktiviert den VASA Provider.

Wenn Sie einen VVols-Datastore über die vCenter-Benutzeroberfläche erstellen, werden FlexVols als Backup-Storage für den Datastore erstellt. Auf VVols in VVols-Datastores wird von ESXi-Hosts über einen Protokollendpunkt (PE) zugegriffen. In SAN-Umgebungen wird auf jedem FlexVol im Datastore eine 4-MB-LUN zur Verwendung als PE erstellt. Ein SAN PE ist eine administrative logische Einheit (Alu). VVols sind untergeordnete logische Einheiten (SLUs).

Bei der Verwendung von VVols gelten Standardanforderungen und Best Practices für SAN-Umgebungen, darunter (aber nicht beschränkt auf) die folgenden:

* Erstellen Sie mindestens eine SAN-LIF auf jedem Node pro SVM, die Sie verwenden möchten. Als Best Practice empfiehlt es sich, mindestens zwei pro Node zu erstellen, aber nicht mehr als nötig.
* Keine Single Points of Failure mehr Nutzen Sie mehrere VMkernel Netzwerkschnittstellen für verschiedene Subnetze, in denen bei Verwendung mehrerer virtueller Switches NIC-Teaming zum Einsatz kommt. Alternativ können Sie mehrere mit mehreren physischen Switches verbundene physische NICs nutzen, um Hochverfügbarkeit und einen höheren Durchsatz bereitzustellen.
* Konfigurieren Sie Zoning, VLANs oder beides nach Bedarf für die Host-Konnektivität.
* Vergewissern Sie sich, dass alle erforderlichen Initiatoren bei den Ziel-LIFs auf der gewünschten SVM angemeldet sind.



NOTE: Um den VASA Provider zu aktivieren, müssen Sie ONTAP Tools für VMware vSphere implementieren. Vasa Provider verwaltet alle iGroup-Einstellungen für Sie. Daher müssen iGroups in einer VVols-Umgebung nicht erstellt und gemanagt werden.

NetApp empfiehlt derzeit nicht, alle VVols-Einstellungen als Standard zu ändern.

Spezifische Versionen von ONTAP Tools finden Sie im. Weitere Informationen finden Sie im https://imt.netapp.com/matrix/#welcome["Interoperabilitäts-Matrix-Tool"^] alten VASA Provider für Ihre spezifischen Versionen von vSphere und ONTAP.

Detaillierte Informationen zur Bereitstellung und zum Management von VVols finden Sie in der Dokumentation zu ONTAP Tools für VMware vSphere, link:https://docs.netapp.com/us-en/netapp-solutions/hybrid-cloud/vsphere_ontap_ontap_for_vsphere.html["TR-4597"^], und link:https://www.netapp.com/pdf.html?item=/media/13555-tr4400pdf.pdf["TR-4400"^].



== Empfohlene Einstellungen



=== ATS-Verriegelung

ATS-Sperrung ist *obligatorisch* für VAAI-kompatiblen Speicher und aktualisierte VMFS5 und ist erforderlich für ordnungsgemäße Interoperabilität und optimale VMFS Shared Storage I/O-Performance mit ONTAP LUNs. Weitere Informationen zum Aktivieren der ATS-Sperrung finden Sie in der VMware-Dokumentation.

[cols="4*"]
|===
| Einstellungen | Standard | ONTAP empfohlen | Beschreibung 


| HardwareBeschleunigungsverriegelung | 1 | 1 | Ermöglicht die Verwendung von ATS-Verriegelung (Atomic Test and Set) 


| Festplatten-IOPS | 1000 | 1 | IOPS-Limit: Das Round Robin PSP-System erreicht standardmäßig ein IOPS-Limit von 1000. In diesem Standardfall wird ein neuer Pfad verwendet, nachdem 1000 I/O-Vorgänge ausgegeben wurden. 


| Disk/QFullSampleSize | 0 | 32 | Die Anzahl der „QUEUE FULL“- oder „BUSY“-Bedingungen, die es dauert, bevor ESXi beginnt, zu drosseln. 
|===

NOTE: Aktivieren `Space-alloc` Einstellung für alle LUNs, die VMware vSphere für zugeordnet sind `UNMAP` Zu arbeiten. Weitere Informationen finden Sie in der ONTAP-Dokumentation.



=== Timeouts für Gastbetriebssysteme

Sie können die virtuellen Maschinen manuell mit den empfohlenen Einstellungen für das Gastbetriebssystem konfigurieren. Nach den Tuning-Updates müssen Sie den Gast neu starten, damit die Updates wirksam werden.

*GOS Timeout Werte:*

[cols="2*"]
|===
| Gastbetriebssystem-Typ | Zeitüberschreitungen 


| Linux-Varianten | Zeitüberschreitung bei Festplatte = 60 


| Windows | Zeitüberschreitung bei Festplatte = 60 


| Solaris | Disk-Timeout = 60 Taced Retry = 300 Not Ready retry = 300 RESET-Retry = 30 max.drossel = 32 min.drossel = 8 
|===


=== Validieren der abstimmbaren vSphere-Lösung

Sie können den mit dem folgenden Befehl überprüfen `HardwareAcceleratedLocking` Einstellung.

`esxcli system settings  advanced list --option /VMFS3/HardwareAcceleratedLocking`

[listing, subs="+quotes"]
----
   Path: /VMFS3/HardwareAcceleratedLocking
   Type: integer
   Int Value: *1*
   Default Int Value: 1
   Min Value: 0
   Max Value: 1
   String Value:
   Default String Value:
   Valid Characters:
   Description: Enable hardware accelerated VMFS locking (requires compliant hardware). Please see http://kb.vmware.com/kb/2094604 before disabling this option.
----


=== Überprüfen Sie die Festplatten-IOPS-Einstellung

Sie können die IOPS-Einstellung mit dem folgenden Befehl überprüfen.

`esxcli storage nmp device list -d naa.600a098038304731783f506670553355`

[listing, subs="+quotes"]
----
naa.600a098038304731783f506670553355
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038304731783f506670553355)
   Storage Array Type: VMW_SATP_ALUA
   Storage Array Type Device Config: {implicit_support=on; explicit_support=off; explicit_allow=on; alua_followover=on; action_OnRetryErrors=off; {TPG_id=1000,TPG_state=ANO}{TPG_id=1001,TPG_state=AO}}
   Path Selection Policy: VMW_PSP_RR
   Path Selection Policy Device Config: {policy=rr,*iops=1*,bytes=10485760,useANO=0; lastPathIndex=0: NumIOsPending=0,numBytesPending=0}
   Path Selection Policy Device Custom Config:
   Working Paths: vmhba4:C0:T0:L82, vmhba3:C0:T0:L82
   Is USB: false
----


=== Überprüfen Sie die QFullSampleSize

Sie können den folgenden Befehl verwenden, um die QFullSampleSize zu überprüfen.

`esxcli system settings  advanced list --option /Disk/QFullSampleSize`

[listing, subs="+quotes"]
----
   Path: /Disk/QFullSampleSize
   Type: integer
   Int Value: *32*
   Default Int Value: 0
   Min Value: 0
   Max Value: 64
   String Value:
   Default String Value:
   Valid Characters:
   Description: Default I/O samples to monitor for detecting non-transient queue full condition. Should be nonzero to enable queue depth throttling. Device specific QFull options will take precedence over this value if set.
----


== Bekannte Probleme

Die Version VMware vSphere 8.x mit ONTAP weist folgende bekannte Probleme auf:

[cols="10,30,30"]
|===
| NetApp Bug ID | Titel | Beschreibung 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1543660["1543660"^] | I/O-Fehler tritt auf, wenn bei Linux VMs mit vNVMe Adaptern lange alle Pfade ausfallen (APD)  a| 
Linux-VMs, die vSphere 8.x und höher ausführen und virtuelle NVMe-Adapter (vNVME) verwenden, stoßen auf einen I/O-Fehler, da der vNVMe-Wiederholungsvorgang standardmäßig deaktiviert ist. Um eine Unterbrechung bei Linux VMs zu vermeiden, auf denen ältere Kernel während einer Alle Pfade unten (APD) ausgeführt werden, oder eine hohe I/O-Last zu vermeiden, hat VMware eine abstimmbare „VSCSIDisableNvmeRetry“ eingeführt, um den vNVMe-Wiederholungsvorgang zu deaktivieren.

|===
.Verwandte Informationen
* link:https://docs.netapp.com/us-en/netapp-solutions/virtualization/vsphere_ontap_ontap_for_vsphere.html["TR-4597-VMware vSphere with ONTAP"^]
* link:https://kb.vmware.com/s/article/2031038["Unterstützung von VMware vSphere 5.x, 6.x und 7.x mit NetApp MetroCluster (2031038)"^]
* link:https://kb.vmware.com/s/article/83370["NetApp ONTAP mit NetApp SnapMirror Active Sync mit VMware vSphere Metro Storage Cluster (vMSC)"^]

