---
sidebar: sidebar 
permalink: hu_vsphere_7.html 
keywords: host utilities, veritas, infoscale, 7.3. 7.3.1, netapp, ontap 
summary: Beschreibt die Verwendung von Veritas Infoscale 7.3 für Linux mit ONTAP 
---
= Verwenden Sie VMware vSphere 7.x mit ONTAP
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Sie können die Konfigurationseinstellungen des ONTAP-SAN-Hosts für die vSphere 7.x-Version mit FC-, FCoE- und iSCSI-Protokollen verwenden.



== Booten des Hypervisor-SAN

.Was Sie benötigen
Wenn Sie sich für das Booten über SAN entscheiden, muss es von Ihrer Konfiguration unterstützt werden. Sie können das verwenden https://mysupport.netapp.com/matrix/imt.jsp?components=65623;64703;&solution=1&isHWU&src=IMT["NetApp Interoperabilitäts-Matrix-Tool"^] Um zu überprüfen, ob Ihr Betriebssystem, HBA, die HBA-Firmware und das HBA-Boot-BIOS sowie die ONTAP-Version unterstützt werden.

.Schritte
. Ordnen Sie die SAN-Boot-LUN dem Host zu.
. Vergewissern Sie sich, dass mehrere Pfade verfügbar sind.
+

NOTE: Mehrere Pfade sind verfügbar, nachdem das Host-Betriebssystem auf den Pfaden ausgeführt wurde.

. Aktivieren Sie das SAN-Booten im Server-BIOS für die Ports, denen die SAN-Boot-LUN zugeordnet ist.
+
Informationen zum Aktivieren des HBA-BIOS finden Sie in der anbieterspezifischen Dokumentation.

. Starten Sie den Host neu, um zu überprüfen, ob der Startvorgang erfolgreich war.




== Multipathing

ESXi stellt ein erweiterbares Multipathing-Modul namens NMP (NMP) zur Verfügung, mit dem die Sub-Plug-ins Storage Array Type Plugins (SATPs) und PSPs (Path Selection Plugins) verwaltet werden. Diese SATP-Regeln sind standardmäßig in ESXi verfügbar.

Für NetApp ONTAP Storage wird das VMW_SATP_ALUA Plug-in standardmäßig mit VMW_PSP_RR als Pfadauswahl-Richtlinie (PSP) verwendet. Dies kann mit dem folgenden Befehl bestätigt werden.

*`esxcli storage nmp satp rule list -s VMW_SATP_ALUA`*

[listing]
----
Name           Device  Vendor    Model         Driver  Transport  Options
-------------  ------  --------  ------------  ------  ---------  --------------------------
VMW_SATP_ALUA          NETAPP                                     reset_on_attempted_reserve


Rule Group  Claim Options  Default PSP  PSP Options     Description
 ----------  -------------  -----------  --------------  -----------
system      tpgs_on        VMW_PSP_RR                   NetApp arrays with ALUA support
----


=== Konfigurationen ohne ASA

Für Konfigurationen ohne ASA sollten zwei Gruppen von Pfaden mit unterschiedlichen Prioritäten vorhanden sein. Die Pfade mit den höheren Prioritäten sind aktiv/optimiert, was bedeutet, dass sie vom Controller gewartet werden, wo sich das Aggregat befindet. Die Pfade mit den niedrigeren Prioritäten sind aktiv, werden aber nicht optimiert, da sie von einem anderen Controller bereitgestellt werden. Die nicht optimierten Pfade werden nur verwendet, wenn keine optimierten Pfade verfügbar sind.

.Beispiel
Im folgenden Beispiel wird die richtige Ausgabe für eine ONTAP-LUN mit zwei aktiv/optimierten Pfaden und zwei aktiv/nicht optimierten Pfaden angezeigt:

*`esxcli storage nmp device list -d naa.600a098038313530772b4d673979372f`*

[listing]
----
naa.600a098038313530772b4d673979372f
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038313530772b4d673979372f)
   Storage Array Type: VMW_SATP_ALUA
   Storage Array Type Device Config: {implicit_support=on; explicit_support=off; explicit_allow=on; alua_followover=on; action_OnRetryErrors=off; {TPG_id=1000,TPG_state=AO}{TPG_id=1001,TPG_state=ANO}}
   Path Selection Policy: VMW_PSP_RR
   Path Selection Policy Device Config: {policy=rr,iops=1,bytes=10485760,useANO=0; lastPathIndex=1: NumIOsPending=0,numBytesPending=0}
   Path Selection Policy Device Custom Config:
   Working Paths: vmhba3:C0:T3:L21, vmhba4:C0:T2:L21
   Is USB: false
----
*`esxcli storage nmp path list -d naa.600a098038313530772b4d673979372f`*

[listing]
----
fc.20000090fae0ec8e:10000090fae0ec8e-fc.201000a098dfe3d1:200b00a098dfe3d1-naa.600a098038313530772b4d673979372f
   Runtime Name: vmhba3:C0:T2:L21
   Device: naa.600a098038313530772b4d673979372f
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038313530772b4d673979372f)
   Group State: active unoptimized
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1001,TPG_state=ANO,RTP_id=29,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.20000090fae0ec8e:10000090fae0ec8e-fc.201000a098dfe3d1:200700a098dfe3d1-naa.600a098038313530772b4d673979372f
   Runtime Name: vmhba3:C0:T3:L21
   Device: naa.600a098038313530772b4d673979372f
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038313530772b4d673979372f)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1000,TPG_state=AO,RTP_id=25,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.20000090fae0ec8f:10000090fae0ec8f-fc.201000a098dfe3d1:200800a098dfe3d1-naa.600a098038313530772b4d673979372f
   Runtime Name: vmhba4:C0:T2:L21
   Device: naa.600a098038313530772b4d673979372f
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038313530772b4d673979372f)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1000,TPG_state=AO,RTP_id=26,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.20000090fae0ec8f:10000090fae0ec8f-fc.201000a098dfe3d1:200c00a098dfe3d1-naa.600a098038313530772b4d673979372f
   Runtime Name: vmhba4:C0:T3:L21
   Device: naa.600a098038313530772b4d673979372f
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038313530772b4d673979372f)
   Group State: active unoptimized
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1001,TPG_state=ANO,RTP_id=30,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.
----


=== Alle SAN-Array-Konfigurationen

In ASA Konfigurationen sind alle Pfade zu einer bestimmten LUN aktiv und optimiert. Dies verbessert die Performance, da I/O-Operationen über alle Pfade gleichzeitig ausgeführt werden können.

.Beispiel
Im folgenden Beispiel wird die richtige Ausgabe für eine ONTAP LUN angezeigt:

*`esxcli storage nmp device list -d naa.600a098038304759563f4e7837574453`*

[listing]
----
naa.600a098038304759563f4e7837574453
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038304759563f4e7837574453)
   Storage Array Type: VMW_SATP_ALUA
   Storage Array Type Device Config: {implicit_support=on; explicit_support=off; explicit_allow=on; alua_followover=on; action_OnRetryErrors=off; {TPG_id=1001,TPG_state=AO}{TPG_id=1000,TPG_state=AO}}
   Path Selection Policy: VMW_PSP_RR
   Path Selection Policy Device Config: {policy=rr,iops=1,bytes=10485760,useANO=0; lastPathIndex=2: NumIOsPending=0,numBytesPending=0}
   Path Selection Policy Device Custom Config:
   Working Paths: vmhba4:C0:T0:L9, vmhba3:C0:T1:L9, vmhba3:C0:T0:L9, vmhba4:C0:T1:L9
   Is USB: false
----
*`esxcli storage nmp device list -d naa.600a098038304759563f4e7837574453`*

[listing]
----
fc.20000024ff171d37:21000024ff171d37-fc.202300a098ea5e27:204a00a098ea5e27-naa.600a098038304759563f4e7837574453
   Runtime Name: vmhba4:C0:T0:L9
   Device: naa.600a098038304759563f4e7837574453
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038304759563f4e7837574453)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1000,TPG_state=AO,RTP_id=6,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.20000024ff171d36:21000024ff171d36-fc.202300a098ea5e27:201d00a098ea5e27-naa.600a098038304759563f4e7837574453
   Runtime Name: vmhba3:C0:T1:L9
   Device: naa.600a098038304759563f4e7837574453
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038304759563f4e7837574453)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1001,TPG_state=AO,RTP_id=3,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.20000024ff171d36:21000024ff171d36-fc.202300a098ea5e27:201b00a098ea5e27-naa.600a098038304759563f4e7837574453
   Runtime Name: vmhba3:C0:T0:L9
   Device: naa.600a098038304759563f4e7837574453
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038304759563f4e7837574453)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1000,TPG_state=AO,RTP_id=1,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.20000024ff171d37:21000024ff171d37-fc.202300a098ea5e27:201e00a098ea5e27-naa.600a098038304759563f4e7837574453
   Runtime Name: vmhba4:C0:T1:L9
   Device: naa.600a098038304759563f4e7837574453
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038304759563f4e7837574453)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1001,TPG_state=AO,RTP_id=4,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.
----


== VVol

Virtual Volumes (VVols) sind ein VMware Objekttyp, der einer VM-Festplatte (Virtual Machine) entspricht, mit Snapshots und schnellen Klonen.

Die ONTAP Tools für VMware vSphere umfassen den VASA Provider für ONTAP, der den Integrationspunkt für VMware vCenter zur Nutzung von VVols-basiertem Storage bietet. Bei der Implementierung der ONTAP Tools OVA wird sie automatisch beim vCenter Server registriert und aktiviert den VASA Provider.

Wenn Sie einen VVols Datastore über die vCenter Benutzeroberfläche erstellen, sind Sie damit in der Lage, FlexVols als Backup Storage für den Datastore zu erstellen. VVols in einem VVols-Datastore können über einen Protokollendpunkt (PE) von ESXi Hosts auf zugreifen. In SAN-Umgebungen wird auf jedem FlexVol im Datastore eine 4-MB-LUN zur Verwendung als PE erstellt. Ein SAN PE ist eine administrative logische Einheit (Alu). VVols sind subsidiäre logische Einheiten (SLUs).

Bei der Verwendung von VVols gelten Standardanforderungen und Best Practices für SAN-Umgebungen, darunter (aber nicht beschränkt auf) die folgenden:

. Erstellen Sie mindestens eine SAN-LIF auf jedem Node pro SVM, die Sie verwenden möchten. Als Best Practice empfiehlt es sich, mindestens zwei pro Node zu erstellen, aber nicht mehr als nötig.
. Keine Single Points of Failure mehr Nutzung mehrerer VMkernel Netzwerkschnittstellen für verschiedene Subnetze, in denen bei Verwendung mehrerer virtueller Switches NIC-Teaming zum Einsatz kommt Alternativ können Sie mehrere physische NICs nutzen, die mit mehreren physischen Switches verbunden sind, um Hochverfügbarkeit und einen höheren Durchsatz bereitzustellen.
. Konfiguration des Zoning und/oder VLANs entsprechend den Anforderungen der Host-Konnektivität
. Stellen Sie sicher, dass alle erforderlichen Initiatoren in den Ziel-LIFs auf der gewünschten SVM protokolliert werden.



NOTE: Um den VASA Provider zu aktivieren, müssen Sie ONTAP Tools für VMware vSphere implementieren. Vasa Provider managt alle igroup-Einstellungen für Sie. Es müssen also keine Initiatorgruppen in einer VVols Umgebung erstellt oder gemanagt werden.

NetApp empfiehlt derzeit nicht, alle VVols-Einstellungen vom Standard zu ändern.

Siehe https://mysupport.netapp.com/matrix/imt.jsp?components=65623;64703;&solution=1&isHWU&src=IMT["NetApp Interoperabilitäts-Matrix-Tool"^] Für bestimmte Versionen der ONTAP Tools oder Legacy VASA Provider für Ihre spezifischen Versionen von vSphere und ONTAP.

Weitere Informationen zum Bereitstellen und Verwalten von VVols finden Sie auch in der Dokumentation zu ONTAP-Tools für VMware vSphere link:https://docs.netapp.com/us-en/netapp-solutions/virtualization/vsphere_ontap_ontap_for_vsphere.html["TR-4597-VMware vSphere with ONTAP"^] Und link:https://www.netapp.com/pdf.html?item=/media/13555-tr4400pdf.pdf["TR-4400"^].



== Empfohlene Einstellungen



=== ATS-Verriegelung

ATS-Sperrung ist *obligatorisch* für VAAI-kompatiblen Speicher und ein Upgrade auf VMFS5. Außerdem ist für ordnungsgemäße Interoperabilität und optimale VMFS-Shared Storage-I/O-Performance mit ONTAP LUNs erforderlich. Weitere Informationen zum Aktivieren der ATS-Sperrung finden Sie in der VMware-Dokumentation.

[cols="4*"]
|===
| Einstellungen | Standard | ONTAP empfohlen | Beschreibung 


| HardwareBeschleunigungsverriegelung | 1 | 1 | Ermöglicht die Verwendung von ATS-Verriegelung (Atomic Test and Set) 


| Festplatten-IOPS | 1000 | 1 | IOPS-Limit: Das Round Robin PSP-System erreicht standardmäßig ein IOPS-Limit von 1000. In diesem Standardfall wird ein neuer Pfad verwendet, nachdem 1000 I/O-Vorgänge ausgegeben wurden. 


| Disk/QFullSampleSize | 0 | 32 | Die Anzahl der „QUEUE FULL“- oder „BUSY“-Bedingungen, die es dauert, bevor ESXi beginnt, zu drosseln. 
|===

NOTE: Aktivieren Sie die Space-Alloc-Einstellung für alle LUNs, die VMware vSphere zugeordnet sind, damit UNMAP funktioniert. Weitere Informationen finden Sie in der ONTAP-Dokumentation.



=== Timeouts für Gastbetriebssysteme

Sie können die virtuellen Maschinen manuell mit den empfohlenen Einstellungen für das Gastbetriebssystem konfigurieren. Nach den Tuning-Updates müssen Sie den Gast neu starten, damit die Updates wirksam werden.

*GOS Timeout Werte:*

[cols="2*"]
|===
| Gastbetriebssystem-Typ | Zeitüberschreitungen 


| Linux-Varianten | Zeitüberschreitung bei Festplatte = 60 


| Windows | Zeitüberschreitung bei Festplatte = 60 


| Solaris | Disk-Timeout = 60 Taced Retry = 300 Not Ready retry = 300 RESET-Retry = 30 max.drossel = 32 min.drossel = 8 
|===


=== Überprüfung der abstimmbaren vSphere-Lösung

Mit dem folgenden Befehl können Sie die Einstellung HardwareAcceleratedLocking überprüfen.

*`esxcli system settings  advanced list --option /VMFS3/HardwareAcceleratedLocking`*

[listing]
----
   Path: /VMFS3/HardwareAcceleratedLocking
   Type: integer
   Int Value: 1
   Default Int Value: 1
   Min Value: 0
   Max Value: 1
   String Value:
   Default String Value:
   Valid Characters:
   Description: Enable hardware accelerated VMFS locking (requires compliant hardware). Please see http://kb.vmware.com/kb/2094604 before disabling this option.
----


=== Überprüfen der Festplatten-IOPS-Einstellung

Überprüfen Sie die IOPS-Einstellung mit dem folgenden Befehl.

*`esxcli storage nmp device list -d naa.600a098038304731783f506670553355`*

[listing]
----
naa.600a098038304731783f506670553355
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038304731783f506670553355)
   Storage Array Type: VMW_SATP_ALUA
   Storage Array Type Device Config: {implicit_support=on; explicit_support=off; explicit_allow=on; alua_followover=on; action_OnRetryErrors=off; {TPG_id=1000,TPG_state=ANO}{TPG_id=1001,TPG_state=AO}}
   Path Selection Policy: VMW_PSP_RR
   Path Selection Policy Device Config: {policy=rr,iops=1,bytes=10485760,useANO=0; lastPathIndex=0: NumIOsPending=0,numBytesPending=0}
   Path Selection Policy Device Custom Config:
   Working Paths: vmhba4:C0:T0:L82, vmhba3:C0:T0:L82
   Is USB: false
----


=== Validieren der QFullSampleSize

Verwenden Sie den folgenden Befehl, um die QFullSampleSize zu überprüfen

*`esxcli system settings  advanced list --option /Disk/QFullSampleSize`*

[listing]
----
   Path: /Disk/QFullSampleSize
   Type: integer
   Int Value: 32
   Default Int Value: 0
   Min Value: 0
   Max Value: 64
   String Value:
   Default String Value:
   Valid Characters:
   Description: Default I/O samples to monitor for detecting non-transient queue full condition. Should be nonzero to enable queue depth throttling. Device specific QFull options will take precedence over this value if set.
----


== Bekannte Probleme

Es sind keine Probleme bekannt.

.Verwandte Informationen
* link:https://docs.netapp.com/us-en/netapp-solutions/virtualization/vsphere_ontap_ontap_for_vsphere.html["TR-4597-VMware vSphere with ONTAP"^]
* link:https://kb.vmware.com/s/article/2031038["Unterstützung von VMware vSphere 5.x, 6.x und 7.x mit NetApp MetroCluster (2031038)"^]
* link:https://kb.vmware.com/s/article/83370["NetApp ONTAP mit NetApp SnapMirror Business Continuity (SM-BC) mit VMware vSphere Metro Storage Cluster (vMSC)"^]

