---
sidebar: sidebar 
permalink: hu_veritas_6x.html 
keywords: host utilities, veritas, infoscale, 6.x, netapp, ontap, san, lun, multipathing, iscsi 
summary: Hier finden Sie Anleitungen zur Konfiguration der ONTAP-SAN-Hosts für die Version der Veritas Infoscale 6 Serie 
---
= Verwendung von Veritas Storage Foundation 6 für Linux mit NetApp ONTAP
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content




== Einführung

Dieses Dokument enthält Hinweise zur Konfiguration der ONTAP-SAN-Hosts für die Version der Veritas Storage Foundation 6 Serie für Red hat Enterprise Linux & Oracle Linux (RHCK) Plattformen mit FC-, FCoE- und iSCSI-Protokollen.



== Installieren der Linux Unified Host Utilities

Das NetApp Linux Unified Host Utilities-Softwarepaket ist auf der erhältlich link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab["NetApp Support Website"^] In einer 64-Bit-.rpm-Datei.

NetApp empfiehlt ausdrücklich die Installation der Linux Unified Host Utilities, dies ist jedoch nicht zwingend erforderlich. Die Dienstprogramme ändern keine Einstellungen auf Ihrem Linux-Host. Die Versorgungseinrichtungen verbessern das Management und unterstützen den NetApp Kunden-Support bei der Erfassung von Informationen zu Ihrer Konfiguration.

.Was Sie benötigen
Wenn Sie derzeit eine Version von Linux Unified Host Utilities installiert haben, sollten Sie diese aktualisieren oder entfernen und dann die folgenden Schritte ausführen, um die neueste Version zu installieren.

.Schritte
. Laden Sie das Softwarepaket für die 64-Bit-Version von Linux Unified Host Utilities von herunter https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab["NetApp Support Website"^] Auf Ihren Host.
. Installieren des Softwarepakets:
+
`rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_64`





== SAN Toolkit

Das Toolkit wird automatisch installiert, wenn Sie das NetApp Host Utilities-Paket installieren. Dieses Kit enthält die `sanlun` Dienstprogramm: Unterstützt Sie beim Management von LUNs und HBAs. Der `sanlun` Befehl gibt Informationen über die LUNs zurück, die Ihrem Host zugeordnet sind, Multipathing und Informationen zurück, die zum Erstellen von Initiatorgruppen erforderlich sind.

.Beispiel
In der folgenden Abbildung, die `sanlun show` Befehl gibt LUN-Informationen zurück.

[listing]
----
# sanlun show -p -v SFRAC:/vol/fen1/lun1

              ONTAP Path: SFRAC:/vol/fen1/lun1
                     LUN: 0
                LUN Size: 10g
                 Product: cDOT
                DMP NODE: sfrac0_47
      Multipath Provider: Veritas
----------  ------  ---------  ------  -------------------------------------
Veritas     host    vserver    host:
path        path    path     /dev/   chan:     vserver           major:
state       state   type     node    id:lun    LIF                   minor
----------  ------  ---------  ------  -------------------------------------
enabled     up      active/non-optimized sdea   14:0:1:0   lif_10    128:32
enabled (a) up      active/optimized     sdcj   14:0:0:0   lif_2      69:112
enabled (a) up      active/optimized     sdb    13:0:0:0   lif_1       8:16
enabled     up      active/non-optimized sdas   13:0:1:0   lif_9      66:192
----


== SAN wird gebootet

.Was Sie benötigen
Wenn Sie sich für das Booten über SAN entscheiden, muss es von Ihrer Konfiguration unterstützt werden. Sie können das verwenden https://mysupport.netapp.com/matrix/imt.jsp?components=65623;64703;&solution=1&isHWU&src=IMT["NetApp Interoperabilitäts-Matrix-Tool"^] Um zu überprüfen, ob Ihr Betriebssystem, HBA, die HBA-Firmware und das HBA-Boot-BIOS sowie die ONTAP-Version unterstützt werden.

Überprüfen Sie unter Veritas Support Portal (Produktmatrix, Platform Lookup, HCL Matrix) die Kompatibilität der SAN-Boot-Konfiguration und bekannte Einschränkungen.

.Schritte
. Ordnen Sie die SAN-Boot-LUN dem Host zu.
. Vergewissern Sie sich, dass mehrere Pfade verfügbar sind.
+

NOTE: Mehrere Pfade sind verfügbar, nachdem das Host-Betriebssystem auf den Pfaden ausgeführt wurde.

. Aktivieren Sie das SAN-Booten im Server-BIOS für die Ports, denen die SAN-Boot-LUN zugeordnet ist.
+
Informationen zum Aktivieren des HBA-BIOS finden Sie in der anbieterspezifischen Dokumentation.

. Starten Sie den Host neu, um zu überprüfen, ob der Startvorgang erfolgreich war.




== Multipathing

Sie müssen überprüfen, ob Ihre Konfiguration den Systemanforderungen entspricht. Weitere Informationen finden Sie im https://mysupport.netapp.com/matrix/imt.jsp?components=65623;64703;&solution=1&isHWU&src=IMT["NetApp Interoperabilitäts-Matrix-Tool"^] Und die Veritas HCL Matrix.

.Beispiel
In diesem Beispiel ist der `vxdmpadm` Der Befehl wird verwendet, um zu überprüfen, ob VxDMP Multipath das ONTAP-Ziel-Array angeschlossen hat.

[listing]
----
# vxdmpadm listenclosure
ENCLR_NAME   ENCLR_TYPE  ENCLR_SNO     STATUS      ARRAY_TYPE    LUN_COUNT    FIRMWARE
=====================================================================================
sfrac0       SFRAC       804Xw$PqE52h  CONNECTED   ALUA          43           9800
----
[listing]
----
# vxdmpadm getdmpnode
NAME       STATE    ENCLR-TYPE  PATHS  ENBL  DSBL ENCLR-NAME
===================================================================
sfrac0_47  ENABLED  SFRAC       4      4     0    sfrac0
----
Mit Veritas Dynamic Multipathing (VxDMP) müssen Sie Konfigurationsaufgaben durchführen, um NetApp LUNs als Veritas Multipath-Geräte beanspruchen zu können. Sie müssen über die Array Support Library (ASL) und die Array Policy Module (APM)-Pakete verfügen, die Veritas für NetApp Storage-Systeme bietet. Während die Veritas Software Installation die Standard-ASL APM-Pakete zusammen mit dem Produkt lädt, wird empfohlen, die neuesten unterstützten Pakete zu verwenden, die im Veritas Support-Portal aufgelistet sind.

.Beispiel
Das folgende Beispiel zeigt die Konfiguration der Veritas Support Library (ASL) und des Array Policy Module (APM).

[listing]
----
# vxdmpadm list dmpnode dmpnodename=sfrac0_47 | grep asl
asl        = libvxnetapp.so
----
[listing]
----
# vxddladm listversion |grep libvxnetapp.so
libvxnetapp.so              vm-7.4-rev-1    6.1

# rpm -qa |grep VRTSaslapm
VRTSaslapm-x.x.x.0000-RHEL8.X86_64
----
[listing]
----
vxddladm listsupport libname=libvxnetapp.so
ATTR_NAME   ATTR_VALUE
=========================================
LIBNAME     libvxnetapp.so
VID         NETAPP
PID         All
ARRAY_TYPE  ALUA, A/A
----


=== Nicht-ASA-Konfiguration

Für Konfigurationen ohne ASA sollten zwei Gruppen von Pfaden mit unterschiedlichen Prioritäten vorhanden sein. Die Pfade mit den höheren Prioritäten sind aktiv/optimiert, was bedeutet, dass sie vom Controller gewartet werden, wo sich das Aggregat befindet. Die Pfade mit den niedrigeren Prioritäten sind aktiv, werden aber nicht optimiert, da sie von einem anderen Controller bereitgestellt werden. Die nicht optimierten Pfade werden nur verwendet, wenn keine optimierten Pfade verfügbar sind.

.Beispiel
Im folgenden Beispiel wird die richtige Ausgabe für eine ONTAP-LUN mit zwei aktiv/optimierten Pfaden und zwei aktiv/nicht optimierten Pfaden angezeigt:

[listing]
----
# vxdmpadm getsubpaths dmpnodename-sfrac0_47
NAME  STATE[A]   PATH-TYPE[M]   CTLR-NAME   ENCLR-TYPE  ENCLR-NAME  ATTRS  PRIORITY
===================================================================================
sdas  ENABLED     Active/Non-Optimized c13   SFRAC       sfrac0     -      -
sdb   ENABLED(A)  Active/Optimized     c14   SFRAC       sfrac0     -      -
sdcj  ENABLED(A)  Active/Optimized     c14   SFRAC       sfrac0     -      -
sdea  ENABLED     Active/Non-Optimized c14   SFRAC       sfrac0     -      -
----

NOTE: Verwenden Sie keine unverhältnismäßig hohe Anzahl von Pfaden zu einer einzelnen LUN. Es sollten nicht mehr als vier Pfade erforderlich sein. Mehr als acht Pfade können bei Storage-Ausfällen zu Pfadproblemen führen.



=== Empfohlene Einstellungen



==== Einstellungen für Veritas Multipath

Die folgenden Veritas VxDMP Tunables werden von NetApp für die optimale Systemkonfiguration bei Storage Failover-Operationen empfohlen.

[cols="2*"]
|===
| Parameter | Einstellung 


| dmp_lun_retry_Timeout | 60 


| dmp_PATH_Age | 120 


| dmp_Restore_Intervall | 60 
|===
DMP-Tunables werden online mithilfe des gesetzt `vxdmpadm` Befehl wie folgt:

`# vxdmpadm settune dmp_tunable=value`

Die Werte dieser abstimmbaren Werte können mit Hilfe dynamisch überprüft werden `#vxdmpadm gettune`.

.Beispiel
Das folgende Beispiel zeigt die effektiven VxDMP-Tunables auf dem SAN-Host.

[listing]
----
# vxdmpadm gettune

Tunable                    Current Value    Default Value
dmp_cache_open                      on                on
dmp_daemon_count                    10                10
dmp_delayq_interval                 15                15
dmp_display_alua_states             on                on
dmp_fast_recovery                   on                on
dmp_health_time                     60                60
dmp_iostats_state              enabled           enabled
dmp_log_level                        1                 1
dmp_low_impact_probe                on                on
dmp_lun_retry_timeout               60                30
dmp_path_age                       120               300
dmp_pathswitch_blks_shift            9                 9
dmp_probe_idle_lun                  on                on
dmp_probe_threshold                  5                 5
dmp_restore_cycles                  10                10
dmp_restore_interval                60               300
dmp_restore_policy         check_disabled   check_disabled
dmp_restore_state              enabled           enabled
dmp_retry_count                      5                 5
dmp_scsi_timeout                    20                20
dmp_sfg_threshold                    1                 1
dmp_stat_interval                    1                 1
dmp_monitor_ownership               on                on
dmp_monitor_fabric                  on                on
dmp_native_support                 off               off
----


==== Einstellungen nach Protokoll

* Nur für FC/FCoE: Verwenden Sie die standardmäßigen Timeout-Werte.
* Nur für iSCSI: Legen Sie die fest `replacement_timeout` Parameterwert bis 120.
+
ISCSI `replacement_timeout` Der Parameter steuert, wie lange die iSCSI-Schicht auf einen Timeout-Pfad oder eine Sitzung warten sollte, um sich wiederherzustellen, bevor Befehle darauf ausfallen. Festlegen des Werts von `replacement_timeout` In der iSCSI-Konfigurationsdatei bis 120 wird empfohlen.



.Beispiel
[listing]
----
# grep replacement_timeout /etc/iscsi/iscsid.conf
node.session.timeo.replacement_timeout = 120
----


==== Einstellungen nach Betriebssystemplattformen

Für die Serien Red hat Enterprise Linux 7 und 8 müssen Sie konfigurieren `udev rport` Werte zur Unterstützung der Veritas Infoscale Umgebung in Storage-Failover-Szenarien. Erstellen Sie die Datei `/etc/udev/rules.d/40-rport.rules` Mit folgendem Dateiinhalt:

[listing]
----
# cat /etc/udev/rules.d/40-rport.rules
KERNEL=="rport-*", SUBSYSTEM=="fc_remote_ports", ACTION=="add", RUN+=/bin/sh -c 'echo 20 > /sys/class/fc_remote_ports/%k/fast_io_fail_tmo;echo 864000 >/sys/class/fc_remote_ports/%k/dev_loss_tmo'"
----

NOTE: Weitere Einstellungen für Veritas finden Sie in der Standarddokumentation zu Veritas Infoscale.



== Multipath-Koexistenz

Wenn Sie über eine heterogene Multipath-Umgebung wie Veritas Infoscale, Linux Native Device Mapper und LVM Volume Manager verfügen, finden Sie im Veritas Product Administration Guide die Konfigurationseinstellungen.



== Bekannte Probleme und Einschränkungen

Es gibt keine bekannten Probleme und Einschränkungen.
