---
sidebar: sidebar 
permalink: hu_wuhu_71.html 
keywords: windows, host, utilities, 7.1, hba, fibre, channel, SANtricity, netapp, san, host, e-series, platform 
summary: Windows Unified Host Utilities umfassen ein Installationsprogramm, das die erforderlichen Windows Registry- und HBA-Parameter festlegt, damit der Windows Host die Storage-Systemverhalten von NetApp ONTAP und E-Series Plattformen korrekt verarbeitet. 
---
= Installieren Sie Windows Unified Host Utilities 7.1
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Mit den Windows Unified Host Utilities (WUHU) können Sie einen Windows Hostcomputer an NetApp Speichersysteme anschließen.

Die Windows Unified Host Utilities unterstützen die folgenden Versionen von Windows:

* Windows 2022
* Windows 2019
* Windows 2016
* Windows 2012R2
* Windows 2012


Die Windows Unified Host Utilities umfassen ein Installationsprogramm, das die erforderlichen Windows Registry- und Host Bus Adapter (HBA)-Parameter festlegt, damit ein Windows Host die Storage-Systemverhalten von NetApp ONTAP und E-Series Plattformen korrekt verarbeiten kann.

Wenn Sie die Host Utilities-Software installieren, legt das Installationsprogramm die erforderlichen Parameter für die Windows Registrierung und den Host Bus Adapter (HBA) fest.

Die folgenden Programme und Dateien werden auf dem Windows-Hostcomputer installiert. Das Standardverzeichnis ist `C:\Program Files\NetApp\Windows Host Utilities`.

|===
| Programm | Zweck 


| `emulexhba.reg` | Fehlerbehebung: Dieses Programm wird nur ausgeführt, wenn vom technischen Support-Personal dazu aufgefordert wird. 


| `\NetAppQCLI\fcconfig.exe` | Wird vom Installationsprogramm verwendet, um HBA-Parameter einzustellen. 


| `\NetAppQCLI\fcconfig.ini` | Wird vom Installationsprogramm verwendet, um HBA-Parameter einzustellen. 


| `\NetAppQCLI\*.*` | Wird vom Installationsprogramm zum Festlegen der QLogic FC HBA-Parameter verwendet. 


| `san_version.exe` | Zeigt die Version der Host Utilities und FC HBAs an. 
|===
Die Host Utilities unterstützen verschiedene Windows Host-Konfigurationen, Protokolle und Multipathing-Optionen. Siehe https://mysupport.netapp.com/matrix/["NetApp Interoperabilitäts-Matrix-Tool"^] Hier finden Sie die aktuelle Liste der unterstützten Konfigurationen.



== Überprüfen Sie Ihre Host- und Speichersystemkonfigurationen

Bevor Sie die Host Utilities installieren, müssen Sie überprüfen, ob die Version der Host Utilities die Konfiguration des Host- und Speichersystems unterstützt, damit die Software ordnungsgemäß installiert wird.

.Schritte
. Überprüfen Sie die unterstützte Konfiguration im http://mysupport.netapp.com/matrix["NetApp Interoperabilitäts-Matrix-Tool"^].
. Prüfen Sie die für den jeweiligen Host erforderlichen Hotfixes auf der link:https://docs.netapp.com/us-en/ontap-sanhost/index.html["SAN-Host, Windows-Dokumentation"].
+

NOTE: Der link:https://docs.netapp.com/us-en/ontap-sanhost/hu_windows_2022.html["Verwenden von Windows Server 2022 mit ONTAP"] Das Dokument enthält Anweisungen zu link:https://docs.netapp.com/us-en/ontap-sanhost/hu_windows_2022.html#installing-windows-hotfixes["Windows Hotfixes werden installiert"] Für Windows Server 2022. In den Windows-Dokumenten in der Kategorie Hostkonfigurationen finden Sie die entsprechenden Hotfix-Informationen für frühere Versionen von Windows-Servern.

. Fügen Sie die iSCSI- oder FCP-Lizenz hinzu und starten Sie den Ziel-Service.
+

NOTE: FC- und iSCSI-Protokolle erfordern keine Lizenzen auf E-Series Storage-Systemen mit dem SANtricity Storage Manager.

. Überprüfen Sie Ihre Verkabelung
+
Siehe https://docs.netapp.com/us-en/ontap/san-config/index.html["Referenz zur SAN-Konfiguration"^] Dokumentation für Ihre Version von ONTAP oder https://docs.netapp.com/us-en/e-series/install-hw-cabling/index.html["Hardwareverkabelung der E-Series"^] Detaillierte Informationen zu Verkabelung und Konfiguration





== Konfigurieren Sie FC HBAs und Switches

Installieren und konfigurieren Sie einen oder mehrere unterstützte FC-Host-Bus-Adapter (HBAs) für FC-Verbindungen zu einem Speichersystem.

Das Windows Host Utilities-Installationsprogramm legt die erforderlichen FC HBA-Einstellungen fest.


NOTE: Ändern Sie die HBA-Einstellungen nicht manuell.

.Schritte
. Installieren Sie einen oder mehrere unterstützte FC-HBAs gemäß den Anweisungen des HBA-Anbieters.
. Beziehen Sie die unterstützten HBA-Treiber und Verwaltungsprogrammen ein, und installieren Sie diese gemäß den Anweisungen des HBA-Anbieters.
. Verbinden Sie die HBAs mit Ihren FC-Switches oder direkt mit dem Speichersystem.
. Erstellen Sie auf dem FC-Switch Zonen gemäß Ihrer FC-Switch-Dokumentation.
. Wenn ONTAP verwendet wird, Zonen Sie den Switch nach dem Worldwide Port Name (WWPN). Stellen Sie sicher, dass Sie den WWPN der LIFs und nicht die physischen Ports auf den Storage Controllern verwenden. Siehe https://docs.netapp.com/us-en/ontap/san-config/index.html["Referenz zur SAN-Konfiguration"^] Dokumentation für weitere Informationen.




== Installieren Sie die Host Utilities

Das Installationsprogramm installiert das Host Utilities-Paket und setzt die Windows-Registry- und HBA-Einstellungen.

Sie müssen angeben, ob Multipathing-Unterstützung enthält, wenn Sie das Windows Unified Host Utilities Softwarepaket installieren. Das Installationsprogramm fordert Sie auf, die folgende Auswahl zu treffen. Sie können eine ruhige (unbeaufsichtigte) Installation auch über eine Windows-Eingabeaufforderung ausführen.

.Multipathing-Unterstützung
* Wählen `MPIO` Wenn Sie mehr als einen Pfad vom Windows-Host oder der virtuellen Maschine zum Speichersystem haben.
* Wählen `no MPIO` Nur, wenn Sie einen einzelnen Pfad zum Storage-System verwenden.


Die MPIO-Auswahl ist für Windows XP und Windows Vista-Systeme nicht verfügbar. Multipath-I/O wird auf diesen Gast-Betriebssystemen nicht unterstützt. Für Hyper-V-Gäste werden im Gastbetriebssystem keine RAW-Festplatten (Pass-Through) angezeigt, wenn Sie Multipathing-Unterstützung wählen. Sie können entweder RAW-Festplatten verwenden oder MPIO verwenden, aber beide können nicht im Gastbetriebssystem verwendet werden.

Sie können die Host-Dienstprogramme interaktiv oder über die Befehlszeile installieren. Das neue Installationspaket für Host Utilities muss sich in einem Pfad befinden, der vom Windows Host zugänglich ist. Befolgen Sie die Anweisungen zum interaktiven Installieren der Host Utilities oder über die Windows Befehlszeile.

[role="tabbed-block"]
====
.Interaktiv installieren
--
.Schritte
Um das Host Utilities-Softwarepaket interaktiv zu installieren, müssen Sie das Installationsprogramm für Host Utilities ausführen und die Anweisungen befolgen.

.Schritte
. Laden Sie die ausführbare Datei vom herunter https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["NetApp Support Website"^].
. Wechseln Sie in das Verzeichnis, von dem Sie die ausführbare Datei heruntergeladen haben.
. Führen Sie die aus `netapp_windows_host_utilities_7.1_x64` Datei und folgen Sie den Anweisungen auf dem Bildschirm.
. Starten Sie den Windows-Host neu, wenn Sie dazu aufgefordert werden.


--
.Installation über eine Befehlszeile
--
Sie können eine ruhige (unbeaufsichtigte) Installation der Host Utilities durchführen, indem Sie die entsprechenden Befehle an einer Windows-Eingabeaufforderung eingeben. Nach Abschluss der Installation wird das System automatisch neu gestartet.

.Schritte
. Geben Sie an einer Windows-Eingabeaufforderung den folgenden Befehl ein:
+
`msiexec /i installer.msi /quiet MULTIPATHING= {0 | 1} [INSTALLDIR=inst_path]`

+
** `installer` Ist der Name des `.msi` Für Ihre CPU-Architektur
** MULTIPATHING gibt an, ob MPIO-Unterstützung installiert ist. Zulässige Werte sind „0“ für „Nein“, „1“ für „Ja“
** `inst_path` Ist der Pfad, in dem die Host Utilities-Dateien installiert werden. Der Standardpfad lautet `C:\Program Files\NetApp\Windows Host Utilities\`.





NOTE: Um die standardmäßigen Microsoft Installer-Optionen (MSI) für die Protokollierung und andere Funktionen anzuzeigen, geben Sie ein `msiexec /help` An einer Windows-Eingabeaufforderung. Mit dem Befehl`msiexec /i install.msi /quiet /l*V <install.log> LOGVERBOSE=1` werden Protokollinformationen angezeigt.

--
====