---
sidebar: sidebar 
permalink: hu_wuhu_72.html 
keywords: windows, 7.2, host utilities, SAN, windows 
summary: Die Windows Host Utilities umfassen ein Installationsprogramm, das die erforderlichen Windows Registrierungs- und HBA-Parameter so festlegt, dass der Windows Host die Verhaltensweisen von ONTAP und E-Series Plattformen des Storage-Systems korrekt verarbeitet. 
---
= Installieren Sie Windows Host Utilities 7.2 für ONTAP -Speicher
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Mithilfe der Windows Host Utilities können Sie einen Windows Host-Computer mit NetApp Storage-Systemen verbinden.

Die Windows Host Utilities unterstützen die folgenden Versionen von Windows:

* Windows 2025
* Windows 2022
* Windows 2019
* Windows 2016
* Windows 2012R2
* Windows 2012


Die Windows Host Utilities umfassen ein Installationsprogramm, das die erforderlichen Windows Registrierungs- und HBA-Parameter (Host Bus Adapter) festlegt, damit ein Windows Host die Storage-Systemverhalten der ONTAP und E-Series Plattformen korrekt verarbeiten kann.

Wenn Sie die Host Utilities-Software installieren, legt das Installationsprogramm die erforderlichen Windows Registry- und HBA-Parameter fest.

Die folgenden Programme und Dateien werden auf dem Windows-Hostcomputer installiert. Das Standardverzeichnis ist `C:\Program Files\NetApp\Windows Host Utilities`.

|===
| Programm | Zweck 


| `emulexhba.reg` | Fehlerbehebung: Dieses Programm wird nur ausgeführt, wenn vom technischen Support-Personal dazu aufgefordert wird. 


| `\NetAppQCLI\fcconfig.exe` | Wird vom Installationsprogramm zum Einstellen der HBA-Parameter verwendet. 


| `\NetAppQCLI\fcconfig.ini` | Wird vom Installationsprogramm zum Einstellen der HBA-Parameter verwendet. 


| `\NetAppQCLI\*.*` | Wird vom Installationsprogramm zum Festlegen der QLogic FC HBA-Parameter verwendet. 


| `san_version.exe` | Zeigt die Version der Host Utilities und FC HBAs an. 
|===
Die Host Utilities unterstützen verschiedene Windows Host-Konfigurationen, Protokolle und Multipathing-Optionen. Weitere Informationen finden Sie im https://mysupport.netapp.com/matrix/["Interoperabilitäts-Matrix-Tool"^].



== Schritt 1: Überprüfen Sie die Konfiguration Ihres Hosts und Speichersystems

Vergewissern Sie sich, dass die Host- und Speichersystem-Konfiguration unterstützt wird, bevor Sie Windows Host Utilities für die installieren<<supported-windows-versions-72,Unterstützte Windows-Version>>.

.Schritte
. Überprüfen Sie die unterstützte Konfiguration im http://mysupport.netapp.com/matrix["Interoperabilitäts-Matrix-Tool"^].
. Überprüfen Sie die für Ihre Windows Server-Hostversion erforderlichen Hotfixes imlink:https://docs.netapp.com/us-en/ontap-sanhost/index.html["SAN-Host, Windows-Dokumentation"] .
+
Zum Beispiel dielink:https://docs.netapp.com/us-en/ontap-sanhost/hu_windows_2022.html["Konfigurieren Sie Windows Server 2022 für ONTAP -Speicher"] Die Dokumentation enthält Anweisungen zum Installieren von Windows-Hotfixes für Windows Server 2022.

. link:https://docs.netapp.com/us-en/ontap/san-admin/verify-license-fc-iscsi-task.html["Fügen Sie die iSCSI- oder FCP-Lizenz hinzu"^] .
+

NOTE: Für die FC- und iSCSI-Protokolle sind auf Speichersystemen der E-Serie, die den SANtricity Storage Manager verwenden, keine Lizenzen erforderlich.

. Starten Sie den Zieldienst.
. Überprüfen Sie die Verkabelung.
+
Weitere Informationen finden Sie im https://docs.netapp.com/us-en/ontap/san-config/index.html["Referenz zur SAN-Konfiguration"^] für detaillierte Informationen zur Verkabelung und Konfiguration.





== Schritt 2: FC-HBAs und Switches konfigurieren

Installieren und konfigurieren Sie einen oder mehrere unterstützte FC-Hostbusadapter (HBAs) für FC-Verbindungen zum Speichersystem.

Das Windows Host Utilities-Installationsprogramm legt die erforderlichen FC HBA-Einstellungen fest.


CAUTION: Sie sollten nur zulassen, dass das Installationsprogramm von Windows Host Utilities die HBA-Parameter einstellt.  Dadurch wird sichergestellt, dass der Windows-Host das Speichersystemverhalten für ONTAP -Plattformen korrekt verarbeiten kann.

.Schritte
. Installieren Sie einen oder mehrere unterstützte FC-HBAs gemäß den Anweisungen des HBA-Anbieters.
. Beziehen Sie die unterstützten HBA-Treiber und Verwaltungsprogrammen ein, und installieren Sie diese gemäß den Anweisungen des HBA-Anbieters.
. https://docs.netapp.com/us-en/ontap/san-management/index.html["Verbinden Sie die HBAs mit Ihren FC-Switches oder direkt mit dem Speichersystem"^] .
. https://docs.netapp.com/us-en/ontap/san-config/fibre-channel-fcoe-zoning-concept.html["Erstellen Sie Zonen auf dem FC-Switch gemäß Ihrer FC-Switch-Dokumentation"^] .
. Bei ONTAP zonieren Sie den Switch nach dem WWPN.  Achten Sie darauf, die WWPN der logischen Schnittstellen (LIFs) und nicht die WWPN der physischen Ports auf den Speichercontrollern zu verwenden. Weitere Informationen finden Sie im  https://docs.netapp.com/us-en/ontap/san-config/index.html["Referenz zur SAN-Konfiguration"^] für weitere Informationen.




== Schritt 3: Installieren Sie die Windows-Host-Dienstprogramme

Das Installationsprogramm installiert das Windows Host Utilities-Paket und legt die Windows-Registrierung und die HBA-Einstellungen fest.

.Über diese Aufgabe
Optional können Sie Multipathing-Unterstützung einschließen, wenn Sie das Softwarepaket „Windows Host Utilities“ installieren.  Das Installationsprogramm fordert Sie zur Eingabe der folgenden Optionen auf:

* Wählen `MPIO` Wenn Sie mehr als einen Pfad vom Windows-Host oder der virtuellen Maschine zum Speichersystem haben.
* Wählen `no MPIO` nur, wenn Sie einen einzelnen Pfad zum Speichersystem verwenden.


Sie können die Multipathing-Unterstützung auch über eine Windows-Eingabeaufforderung auswählen.

Bei Hyper-V-Gästen werden Raw-Datenträger (Pass-Through) nicht im Gastbetriebssystem angezeigt, wenn Sie die Multipathing-Unterstützung wählen.  Sie können entweder Raw-Festplatten oder MPIO verwenden, aber nicht beides im Gastbetriebssystem.


CAUTION: Wenn Sie die MPIO-Software nicht installieren, sieht das Windows-Betriebssystem jeden Pfad möglicherweise als separate Festplatte. Dies kann zu Datenbeschädigungen führen.


NOTE: Windows XP oder Windows Vista, die auf einer virtuellen Hyper-V-Maschine ausgeführt werden, unterstützt MPIO nicht.

.Schritte
Sie können die Host-Dienstprogramme interaktiv oder über die Windows-Befehlszeile installieren.  Das neue Host Utilities-Installationspaket muss sich in einem Pfad befinden, auf den der Windows-Host zugreifen kann.

[role="tabbed-block"]
====
.Interaktiv installieren
--
Installieren Sie das Host Utilities-Softwarepaket interaktiv, indem Sie das Host Utilities-Installationsprogramm ausführen und den Anweisungen folgen.

. Laden Sie die ausführbare Datei vom herunter https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.2/downloads["NetApp Support Website"^].
. Wechseln Sie in das Verzeichnis, in dem Sie die ausführbare Datei heruntergeladen haben.
. Führen Sie die aus `netapp_windows_host_utilities_7.2_x64` Datei und folgen Sie den Anweisungen auf dem Bildschirm.
. Starten Sie den Windows-Host neu, wenn Sie dazu aufgefordert werden.


--
.Nicht-interaktiv installieren
--
Führen Sie eine nicht interaktive Installation der Host-Dienstprogramme mithilfe der Windows-Befehlszeile durch.  Das System wird nach Abschluss der Installation automatisch neu gestartet.

. Geben Sie den folgenden Befehl an der Windows-Eingabeaufforderung ein:
+
[source, cli]
----
msiexec /i installer.msi /quiet MULTIPATHING= {0 | 1} [INSTALLDIR=inst_path]
----
+
** `installer` Ist der Name des `.msi` Datei für Ihre CPU-Architektur.
** MULTIPATHING gibt an, ob MPIO-Unterstützung installiert ist. Die zulässigen Werte sind „0“ für „Nein“ und „1“ für „Ja“.
** `inst_path` Ist der Pfad, in dem die Host Utilities-Dateien installiert werden. Der Standardpfad lautet `C:\Program Files\NetApp\Windows Host Utilities\`.





NOTE: Um die standardmäßigen Microsoft Installer-Optionen (MSI) für die Protokollierung und andere Funktionen anzuzeigen, geben Sie ein `msiexec /help` An der Windows-Eingabeaufforderung. Beispiel: Der `msiexec /i install.msi /quiet /l*v <install.log> LOGVERBOSE=1` Befehl zeigt Protokollinformationen an.

--
====


== Was kommt als Nächstes?

link:hu-wuhu-configuration.html["Erfahren Sie mehr über die Konfiguration der Windows-Hostdienstprogramme für ONTAP -Speicher."]
