---
sidebar: sidebar 
permalink: hu_wuhu_repair_remove.html 
keywords: windows, host, utilities, 7.1, hba, fibre, channel, SANtricity, netapp, san, host, e-series, platform 
summary: Die Windows Host Utilities umfassen ein Installationsprogramm, das die erforderlichen Windows Registrierungs- und HBA-Parameter so festlegt, dass der Windows Host die Verhaltensweisen von ONTAP und E-Series Plattformen des Storage-Systems korrekt verarbeitet. 
---
= Reparieren und entfernen Sie die Windows Host Utilities für ONTAP -Speicher
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Verwenden Sie die Option *Reparieren* im Installationsprogramm von Host Utilities, um den Hostbusadapter (HBA) und die Windows-Registrierungseinstellungen zu aktualisieren.  Sie können die Host-Dienstprogramme auch vollständig entfernen, entweder interaktiv oder über die Windows-Befehlszeile.

[role="tabbed-block"]
====
.Interaktiv reparieren oder entfernen
--
Die Option *Repair* aktualisiert die Windows-Registrierung und FC-HBAs mit den erforderlichen Einstellungen. Sie können die Host Utilities auch vollständig entfernen.

.Schritte
. Öffnen Sie Windows * Programme und Funktionen * (Windows Server 2012 R2, Windows Server 2016, Windows Server 2019 und Windows 2022).
. Wählen Sie *NetApp Windows Hostdienstprogramme*.
. Wählen Sie *Ändern*.
. Wählen Sie je nach Bedarf * Repair* oder *Remove* aus.
. Befolgen Sie die Anweisungen auf dem Bildschirm.


--
.Nicht interaktiv reparieren oder entfernen
--
Die Option *Repair* aktualisiert die Windows-Registrierung und FC-HBAs mit den erforderlichen Einstellungen. Sie können auch die Host Utilities vollständig von einer Windows-Kommandozeile entfernen.

.Schritte
. Windows Host Utilities Reparieren:
+
[source, cli]
----
msiexec /f installer.msi [/quiet]
----
+
** `/f` Repariert die Installation.
** `installer.msi` Ist der Name des Windows Host Utilities-Installationsprogramms auf Ihrem System.
** `/quiet` Unterdrückt alle Rückmeldungen und startet das System automatisch neu, ohne dass beim Abschluss des Befehls eine Aufforderung erforderlich ist.




--
====