---
sidebar: sidebar 
permalink: hu_wuhu_72.html 
keywords: wuhu, 7.2, host utilities, SAN, windows, unified 
summary: Die Windows Unified Host Utilities umfassen ein Installationsprogramm, das die erforderlichen Windows Registrierungs- und HBA-Parameter so eingestellt, dass der Windows Host die Verhaltensweisen von Storage-Systemen der NetApp ONTAP und E-Series Plattformen korrekt verarbeitet. 
---
= Installieren Sie Windows Unified Host Utilities 7.2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Mit den Windows Unified Host Utilities (WUHU) können Sie einen Windows Hostcomputer an NetApp Speichersysteme anschließen.

Die Windows Unified Host Utilities unterstützen die folgenden Versionen von Windows:

* Windows 2022
* Windows 2019
* Windows 2016
* Windows 2012R2
* Windows 2012


Die Windows Unified Host Utilities umfassen ein Installationsprogramm, das die erforderlichen Windows Registry- und Host Bus Adapter (HBA)-Parameter festlegt, damit ein Windows Host die Storage-Systemverhalten von NetApp ONTAP und E-Series Plattformen korrekt verarbeiten kann.

Wenn Sie die Host Utilities-Software installieren, legt das Installationsprogramm die erforderlichen Windows Registry- und HBA-Parameter fest.

Die folgenden Programme und Dateien werden auf dem Windows-Hostcomputer installiert. Das Standardverzeichnis ist `C:\Program Files\NetApp\Windows Host Utilities`.

|===
| Programm | Zweck 


| `emulexhba.reg` | Fehlerbehebung: Dieses Programm wird nur ausgeführt, wenn vom technischen Support-Personal dazu aufgefordert wird. 


| `\NetAppQCLI\fcconfig.exe` | Wird vom Installationsprogramm zum Einstellen der HBA-Parameter verwendet. 


| `\NetAppQCLI\fcconfig.ini` | Wird vom Installationsprogramm zum Einstellen der HBA-Parameter verwendet. 


| `\NetAppQCLI\*.*` | Wird vom Installationsprogramm zum Festlegen der QLogic FC HBA-Parameter verwendet. 


| `san_version.exe` | Zeigt die Version der Host Utilities und FC HBAs an. 
|===
Die Host Utilities unterstützen verschiedene Windows Host-Konfigurationen, Protokolle und Multipathing-Optionen. Weitere Informationen finden Sie im https://mysupport.netapp.com/matrix/["NetApp Interoperabilitäts-Matrix-Tool"^].



== Überprüfen Sie die Konfiguration Ihres Host- und Storage-Systems

Bevor Sie die Host-Dienstprogramme installieren, müssen Sie überprüfen, ob die Host-Dienstprogramme-Version Ihre Host- und Speichersystem-Konfiguration unterstützt, damit die Software korrekt installiert wird.

.Schritte
. Überprüfen Sie die unterstützte Konfiguration im http://mysupport.netapp.com/matrix["NetApp Interoperabilitäts-Matrix-Tool"^].
. Prüfen Sie die für den jeweiligen Host erforderlichen Hotfixes im link:https://docs.netapp.com/us-en/ontap-sanhost/index.html["SAN-Host, Windows-Dokumentation"].
+

NOTE: Der link:https://docs.netapp.com/us-en/ontap-sanhost/hu_windows_2022.html["Verwenden von Windows Server 2022 mit ONTAP"] Das Dokument enthält Anweisungen zu link:https://docs.netapp.com/us-en/ontap-sanhost/hu_windows_2022.html#installing-windows-hotfixes["Windows Hotfixes werden installiert"] Für Windows Server 2022. In den Windows-Dokumenten in der Kategorie Hostkonfigurationen finden Sie die entsprechenden Hotfix-Informationen für frühere Versionen von Windows-Servern.

. Fügen Sie die iSCSI-, FCP- oder NVMe-of-Lizenz hinzu und starten Sie den Zielservice.
+

NOTE: FC- und iSCSI-Protokolle erfordern keine Lizenzen auf E-Series Storage-Systemen mit dem SANtricity Storage Manager.

. Überprüfen Sie die Verkabelung.
+
Siehe https://docs.netapp.com/us-en/ontap/san-config/index.html["Referenz zur SAN-Konfiguration"^] Dokumentation für Ihre Version von ONTAP oder https://docs.netapp.com/us-en/e-series/install-hw-cabling/index.html["Hardwareverkabelung der E-Series"^] Detaillierte Informationen zu Verkabelung und Konfiguration





== Konfigurieren Sie FC HBAs und Switches

Installieren und konfigurieren Sie einen oder mehrere unterstützte FC-Hostbusadapter (HBAs) für FC-Verbindungen zum Speichersystem.

Das Windows Host Utilities-Installationsprogramm legt die erforderlichen FC HBA-Einstellungen fest.


CAUTION: Ändern Sie die HBA-Einstellungen nicht manuell.

.Schritte
. Installieren Sie einen oder mehrere unterstützte FC-HBAs gemäß den Anweisungen des HBA-Anbieters.
. Beziehen Sie die unterstützten HBA-Treiber und Verwaltungsprogrammen ein, und installieren Sie diese gemäß den Anweisungen des HBA-Anbieters.
. Verbinden Sie die HBAs mit Ihren FC-Switches oder direkt mit dem Speichersystem.
. Erstellen Sie auf dem FC-Switch Zonen gemäß Ihrer FC-Switch-Dokumentation.
. Wenn ONTAP verwendet wird, Zonen Sie den Switch mit dem WWPN. Vergewissern Sie sich, dass Sie den WWPN der logischen Schnittstellen (LIFs) und nicht den WWPN der physischen Ports auf den Storage Controllern verwenden. Siehe https://docs.netapp.com/us-en/ontap/san-config/index.html["Referenz zur SAN-Konfiguration"^] Dokumentation für weitere Informationen.




== Installieren Sie die Host Utilities

Das Installationsprogramm installiert das Host-Dienstprogramme-Paket und legt die Windows-Registrierung und HBA-Einstellungen fest.

Sie müssen angeben, ob Multipathing-Unterstützung enthält, wenn Sie das Windows Unified Host Utilities Softwarepaket installieren. Das Installationsprogramm fordert Sie zur Eingabe der folgenden Optionen auf. Sie können eine ruhige (unbeaufsichtigte) Installation auch über eine Windows-Eingabeaufforderung ausführen.

.Multipathing-Unterstützung
* Wählen `MPIO` Wenn Sie mehr als einen Pfad vom Windows-Host oder der virtuellen Maschine zum Speichersystem haben.
* Wählen `no MPIO` Nur, wenn Sie einen einzelnen Pfad zum Storage-System verwenden.


Die MPIO-Auswahl ist für Windows XP und Windows Vista-Systeme nicht verfügbar. Multipath-I/O wird auf diesen Gast-Betriebssystemen nicht unterstützt. Für Hyper-V-Gäste werden im Gastbetriebssystem keine RAW-Festplatten (Pass-Through) angezeigt, wenn Sie Multipathing-Unterstützung wählen. Sie können entweder RAW-Festplatten verwenden oder MPIO verwenden, aber beide können nicht im Gastbetriebssystem verwendet werden.

Sie können die Host-Dienstprogramme interaktiv oder über die Befehlszeile installieren. Das neue Installationspaket für Host Utilities muss sich in einem Pfad befinden, der vom Windows Host zugänglich ist. Befolgen Sie die Anweisungen zum interaktiven Installieren der Host Utilities oder über die Windows Befehlszeile.

[role="tabbed-block"]
====
.Interaktiv installieren
--
Um das Host Utilities-Softwarepaket interaktiv zu installieren, müssen Sie das Host Utilities-Installationsprogramm ausführen und den Aufforderungen folgen.

.Schritte
. Laden Sie die ausführbare Datei vom herunter https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.2/downloads["NetApp Support Website"^].
. Wechseln Sie in das Verzeichnis, in dem Sie die ausführbare Datei heruntergeladen haben.
. Führen Sie die aus `netapp_windows_host_utilities_7.2_x64` Datei und folgen Sie den Anweisungen auf dem Bildschirm.
. Starten Sie den Windows-Host neu, wenn Sie dazu aufgefordert werden.


--
.Installation über eine Befehlszeile
--
Sie können eine (unbeaufsichtigte) Installation der Hostdienstprogramme durchführen, indem Sie die entsprechenden Befehle an der Windows-Eingabeaufforderung eingeben. Nach Abschluss der Installation wird das System automatisch neu gestartet.

.Schritte
. Geben Sie den folgenden Befehl an der Windows-Eingabeaufforderung ein:
+
`msiexec /i installer.msi /quiet MULTIPATHING= {0 | 1} [INSTALLDIR=inst_path]`

+
** `installer` Ist der Name des `.msi` Datei für Ihre CPU-Architektur.
** MULTIPATHING gibt an, ob MPIO-Unterstützung installiert ist. Die zulässigen Werte sind „0“ für „Nein“ und „1“ für „Ja“.
** `inst_path` Ist der Pfad, in dem die Host-Dienstprogramme-Dateien installiert sind. Der Standardpfad lautet `C:\Program Files\NetApp\Windows Host Utilities\`.





NOTE: Um die standardmäßigen Microsoft Installer-Optionen (MSI) für die Protokollierung und andere Funktionen anzuzeigen, geben Sie ein `msiexec /help` An der Windows-Eingabeaufforderung. Beispiel: Der `msiexec /i install.msi /quiet /l*v <install.log> LOGVERBOSE=1` Befehl zeigt Protokollinformationen an.

--
====