---
permalink: legal_notice.html 
sidebar: sidebar 
keywords: legal, notices, copyright, trademarks, patents 
summary: Rechtliche Hinweise ermöglichen den Zugriff auf Copyright-Erklärungen, Marken, Patente und mehr. 
---
= Rechtliche Hinweise
:allow-uri-read: 


Rechtliche Hinweise ermöglichen den Zugriff auf Copyright-Erklärungen, Marken, Patente und mehr.



== Urheberrecht

http://www.netapp.com/us/legal/copyright.aspx[]



== Marken

NetApp, das NETAPP Logo und die auf der NetApp Markenseite aufgeführten Marken sind Marken von NetApp Inc. Andere Firmen- und Produktnamen können Marken der jeweiligen Eigentümer sein.

http://www.netapp.com/us/legal/netapptmlist.aspx[]



== Patente

Eine aktuelle Liste der NetApp Patente finden Sie unter:

https://www.netapp.com/us/media/patents-page.pdf[]



== Datenschutzrichtlinie

https://www.netapp.com/us/legal/privacypolicy/index.aspx[]



== Open Source

Stellt Informationen über das Urheberrecht und die Lizenzen Dritter bereit, die in diesem Produkt verwendet werden.

* link:./media/Notices-AIX61-2023.pdf["Hinweis für AIX"^]
* link:./media/Linux_Unified_Host_Utilities.pdf["Hinweis für Linux"^]
* link:./media/Solaris_Host_Utilities-2017.09.12-01.25.35.pdf["Hinweis für Solaris"^]
* link:./media/Windows_Unified_Host_Utilities_(WUHU)Notice.pdf["Hinweis für Windows"^]

