---
permalink: legal-notices.html 
sidebar: sidebar 
keywords: legal, notices, copyright, trademarks, patents 
summary: Rechtliche Hinweise ermöglichen den Zugriff auf Copyright-Erklärungen, Marken, Patente und mehr. 
---
= Rechtliche Hinweise
:allow-uri-read: 


[role="lead"]
Rechtliche Hinweise ermöglichen den Zugriff auf Copyright-Erklärungen, Marken, Patente und mehr.

[role="lead"]
Rechtliche Hinweise ermöglichen den Zugriff auf Copyright-Erklärungen, Marken, Patente und mehr.



== Urheberrecht

link:https://www.netapp.com/company/legal/copyright/["https://www.netapp.com/company/legal/copyright/"^]



== Marken

NetApp, das NETAPP Logo und die auf der NetApp Markenseite aufgeführten Marken sind Marken von NetApp Inc. Andere Firmen- und Produktnamen können Marken der jeweiligen Eigentümer sein.

link:https://www.netapp.com/company/legal/trademarks/["https://www.netapp.com/company/legal/trademarks/"^]



== Patente

Eine aktuelle Liste der NetApp Patente finden Sie unter:

link:https://www.netapp.com/pdf.html?item=/media/11887-patentspage.pdf["https://www.netapp.com/pdf.html?item=/media/11887-patentspage.pdf"^]



== Datenschutzrichtlinie

link:https://www.netapp.com/company/legal/privacy-policy/["https://www.netapp.com/company/legal/privacy-policy/"^]



== Open Source

In den Benachrichtigungsdateien finden Sie Informationen zu Urheberrechten und Lizenzen von Drittanbietern, die in der NetApp Software verwendet werden.

Stellt Informationen über das Urheberrecht und die Lizenzen Dritter bereit, die in diesem Produkt verwendet werden.

* link:./media/Notices-AIX61-2023.pdf["Hinweis für AIX"^]
* link:./media/Linux_Unified_Host_Utilities.pdf["Hinweis für Linux"^]
* link:./media/Solaris_Host_Utilities-2017.09.12-01.25.35.pdf["Hinweis für Solaris"^]
* link:./media/Windows_Unified_Host_Utilities_(WUHU)Notice.pdf["Hinweis für Windows"^]

