---
sidebar: sidebar 
permalink: nvme-ubuntu-2204.html 
keywords: nvme, linux, rhel, red hat, enterprise 
summary: Konfigurieren des NVMe-of-Hosts für Ubuntu 22.04 mit ONTAP 
---
= Ubuntu 22.04 für NVMe-oF mit ONTAP-Speicher konfigurieren
:allow-uri-read: 


[role="lead"]
NVMe over Fabrics (NVMe-of), einschließlich NVMe over Fibre Channel (NVMe/FC) und andere Übertragungen, wird mit Ubuntu 22.04 mit Asymmetric Namespace Access (ANA) unterstützt. In NVMe-of Umgebungen entspricht ANA ALUA Multipathing in iSCSI- und FC-Umgebungen und wird mit in-Kernel NVMe Multipath implementiert.

Erfahren Sie, wie Sie NVMe over Fabrics (NVMe-oF)-Hosts für Ubuntu 22.04 konfigurieren. Weitere Informationen zu Support und Funktionen finden Sie unter link:nvme-ubuntu-supported-features.html["Ubuntu ONTAP Unterstützung und Funktionen"].

NVMe-oF mit Ubuntu 22.04 weist die folgenden bekannten Einschränkungen auf:

* Das Booten von SAN über das NVMe-oF-Protokoll wird derzeit für Ubuntu 22.04 mit ONTAP nicht unterstützt.


Weitere Details zu den unterstützten Konfigurationen finden Sie im link:https://support.netapp.com/matrix/["Interoperabilitäts-Matrix-Tool"^].



== Schritt 1: Installieren Sie Ubuntu und die NVMe-Software und überprüfen Sie Ihre Konfiguration

Um Ihren Host für NVMe-oF zu konfigurieren, müssen Sie die Host- und NVMe-Softwarepakete installieren, Multipathing aktivieren und Ihre Host-NQN-Konfiguration überprüfen.

. Installieren Sie Ubuntu 22.04 auf dem Server. Überprüfen Sie nach Abschluss der Installation, ob Sie den angegebenen Ubuntu 22.04-Kernel ausführen:
+
[source, cli]
----
# uname -r
----
+
Beispiel für eine Ubuntu-Kernelversion:

+
[listing]
----
5.15.0-101-generic
----
. Installieren Sie den `nvme-cli` Paket:
+
[source, cli]
----
# apt list | grep nvme
----
+
Das folgende Beispiel zeigt eine  `nvme-cli` Paketversion:

+
[listing]
----
nvme-cli/jammy-updates,now 1.16-3ubuntu0.1 amd64
----
. Überprüfen Sie auf dem Ubuntu 22.04-Host den hostnqn-String unter `/etc/nvme/hostnqn`:
+
[source, cli]
----
# cat /etc/nvme/hostnqn
----
+
Das folgende Beispiel zeigt eine  `hostnqn` Version:

+
[listing]
----
nqn.2014-08.org.nvmexpress:uuid:063a9fa0-438a-4737-b9b4-95a21c66d041
----
. Überprüfen Sie im ONTAP-System, ob die  `hostnqn` Zeichenkette von  `/etc/nvme/hostnqn` mit der  `hostnqn` Zeichenkette für das entsprechende Subsystem im ONTAP-Speichersystem übereinstimmt:
+
[source, cli]
----
::> vserver nvme subsystem host show -vserver vs_106_fc_nvme
----
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
Vserver     Subsystem          Host NQN
----------- --------------- ----------------------------------------------------------
vs_106_fc_nvme ub_106 nqn.2014-08.org.nvmexpress:uuid:c04702c8-e91e-4353-9995-ba4536214631
----
====
+

NOTE: Wenn die `hostnqn` Zeichenfolgen nicht übereinstimmen, verwenden Sie die `vserver modify` Befehl zum Aktualisieren der `hostnqn` Zeichenfolge auf Ihrem entsprechenden ONTAP -Speichersystem-Subsystem, um die Übereinstimmung mit `hostnqn` Zeichenfolge von `/etc/nvme/hostnqn` auf dem Host.





== Schritt 2: NVMe/FC und NVMe/TCP konfigurieren

Konfigurieren Sie NVMe/FC für Broadcom/Emulex- oder Marvell/Qlogic-Adapter oder konfigurieren Sie NVMe/TCP mithilfe manueller Erkennung und Verbindungsoperationen.

[role="tabbed-block"]
====
.Broadcom/Emulex
--
Konfigurieren Sie NVMe/FC für einen Broadcom/Emulex-Adapter.

. Stellen Sie sicher, dass Sie das unterstützte Adaptermodell verwenden:
+
.. Zeigen Sie die Modellnamen an:
+
[source, cli]
----
cat /sys/class/scsi_host/host*/modelname
----
+
Die folgende Ausgabe sollte angezeigt werden:

+
[listing]
----
LPe36002-M64
LPe36002-M64
----
.. Zeigen Sie die Modellbeschreibungen an:
+
[source, cli]
----
cat /sys/class/scsi_host/host*/modeldesc
----
+
Sie sollten eine Ausgabe sehen, die dem folgenden Beispiel ähnelt:

+
[listing]
----
Emulex LPe36002-M64 2-Port 64Gb Fibre Channel Adapter
Emulex LPe36002-M64 2-Port 64Gb Fibre Channel Adapter
----


. Vergewissern Sie sich, dass Sie das empfohlene Broadcom verwenden `lpfc` Firmware- und Inbox-Treiber.
+
.. Anzeige der Firmware-Version:
+
[source, cli]
----
cat /sys/class/scsi_host/host*/fwrev
----
+
Der Befehl gibt die Firmware-Versionen zurück:

+
[listing]
----
14.2.673.40, sli-4:6:d
14.2.673.40, sli-4:6:d
----
.. Zeigen Sie die Posteingangstreiberversion an:
+
[source, cli]
----
cat /sys/module/lpfc/version
----
+
Das folgende Beispiel zeigt eine Treiberversion:

+
[listing]
----
0: 14.0.0.4
----
+
Die aktuelle Liste der unterstützten Adaptertreiber- und Firmware-Versionen finden Sie im link:https://mysupport.netapp.com/matrix/["Interoperabilitäts-Matrix-Tool"^].



. Verifizieren Sie das `lpfc_enable_fc4_type` Ist auf festgelegt `3`:
+
[source, cli]
----
cat /sys/module/lpfc/parameters/lpfc_enable_fc4_type
----
. Vergewissern Sie sich, dass Sie Ihre Initiator-Ports anzeigen können:
+
[source, cli]
----
cat /sys/class/fc_host/host*/port_name
----
+
Sie sollten eine ähnliche Ausgabe sehen:

+
[listing]
----
0x100000109bf0447c
0x100000109bf0447b
----
. Überprüfen Sie, ob Ihre Initiator-Ports online sind:
+
[source, cli]
----
cat /sys/class/fc_host/host*/port_state
----
+
Die folgende Ausgabe sollte angezeigt werden:

+
[listing]
----
Online
Online
----
. Vergewissern Sie sich, dass die NVMe/FC-Initiator-Ports aktiviert sind und die Ziel-Ports sichtbar sind:
+
[source, cli]
----
cat /sys/class/scsi_host/host*/nvme_info
----
+
.Beispielausgabe anzeigen
[%collapsible]
=====
[listing, subs="+quotes"]
----
NVME Initiator Enabled
XRI Dist lpfc1 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc1 WWPN x100000109bf0447c WWNN x200000109bf0447c DID x022300 *ONLINE*
NVME RPORT       WWPN x200cd039eaa8138b WWNN x200ad039eaa8138b DID x021509 *TARGET DISCSRVC ONLINE*
NVME RPORT       WWPN x2010d039eaa8138b WWNN x200ad039eaa8138b DID x021108 *TARGET DISCSRVC ONLINE*

NVME Statistics
LS: Xmt 000000000e Cmpl 000000000e Abort 00000000
LS XMIT: Err 00000000  CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 0000000000005238 Issue 000000000000523a OutIO 0000000000000002
        abort 00000000 noxri 00000000 nondlp 00000000 qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 00000000 Err 00000000

NVME Initiator Enabled
XRI Dist lpfc0 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc0 WWPN x100000109bf0447b WWNN x200000109bf0447b DID x022600 *ONLINE*
NVME RPORT       WWPN x200bd039eaa8138b WWNN x200ad039eaa8138b DID x021409 *TARGET DISCSRVC ONLINE*
NVME RPORT       WWPN x200fd039eaa8138b WWNN x200ad039eaa8138b DID x021008 *TARGET DISCSRVC ONLINE*

NVME Statistics
LS: Xmt 000000000e Cmpl 000000000e Abort 00000000
LS XMIT: Err 00000000  CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 000000000000523c Issue 000000000000523e OutIO 0000000000000002
        abort 00000000 noxri 00000000 nondlp 00000000 qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 00000000 Err 00000000
----
=====


--
.Marvell/QLogic
--
Der native Inbox qla2xxx Treiber im Ubuntu 22.04 GA Kernel enthält die neuesten Upstream-Fixes. Diese Fehlerbehebungen sind für die Unterstützung von ONTAP unerlässlich.

Konfigurieren Sie NVMe/FC für einen Marvell/QLogic-Adapter.

. Vergewissern Sie sich, dass der unterstützte Adaptertreiber und die unterstützten Firmware-Versionen ausgeführt werden:
+
[source, cli]
----
# cat /sys/class/fc_host/host*/symbolic_name
----
+
Das folgende Beispiel zeigt Treiber- und Firmwareversionen:

+
[listing]
----
QLE2872 FW: v9.14.02 DVR: v10.02.06.200-k
QLE2872 FW: v9.14.02 DVR: v10.02.06.200-k
----
. Verifizieren Sie das `ql2xnvmeenable` Ist festgelegt. Dadurch kann der Marvell Adapter als NVMe/FC-Initiator verwendet werden:
+
[source, cli]
----
cat /sys/module/qla2xxx/parameters/ql2xnvmeenable
----
+
Die erwartete Ausgabe ist 1.



--
.NVMe/TCP
--
NVMe/TCP verfügt nicht über eine Auto-Connect-Funktion. Stattdessen können Sie die NVMe/TCP-Subsysteme und -Namespaces entdecken, indem Sie die NVMe/TCP `connect`- oder `connect-all`-Operationen manuell durchführen.

Wenn ein Pfad ausfällt und nicht innerhalb der standardmäßigen Timeout-Periode von 10 Minuten wiederhergestellt wird, kann NVMe/TCP die Verbindung nicht automatisch wiederherstellen. Um ein Timeout zu vermeiden, legen Sie die Wiederholungsperiode für Failover-Ereignisse auf mindestens 30 Minuten fest.

. Prüfen Sie, ob der Initiator-Port die Discovery-Log-Seiten-Daten über die unterstützten NVMe/TCP LIFs abrufen kann:
+
[source, cli]
----
nvme discover -t tcp -w host-traddr -a traddr
----
+
.Beispielausgabe anzeigen
[%collapsible]
=====
[listing, subs="+quotes"]
----
#nvme discover -t tcp -w 10.10.11.47-a 10.10.10.122
Discovery Log Number of Records 8, Generation counter 10
=====Discovery Log Entry 0======
trtype:  tcp
adrfam:  ipv4
subtype: *current discovery subsystem*
treq:    not specified
portid:  0
trsvcid: 8009
subnqn:  nqn.1992-08.com.netapp:sn.bbfb4ee8dfb611edbd07d039ea165590:discovery
traddr:  10.10.10.122
eflags:  *explicit discovery connections*, *duplicate discovery* information
sectype: none
=====Discovery Log Entry 1======
trtype:  tcp
adrfam:  ipv4
subtype: *current discovery subsystem*
treq:    not specified
portid:  1
trsvcid: 8009
subnqn:  nqn.1992 08.com.netapp:sn.bbfb4ee8dfb611edbd07d039ea165590:discovery
traddr:  10.10.10.124
eflags:  *explicit discovery connections*, *duplicate discovery* information
sectype: none
=====Discovery Log Entry 2======
trtype:  tcp
----
=====
. Vergewissern Sie sich, dass die anderen LIF-Kombinationen des NVMe/TCP-Initiators erfolgreich beim Abrufen von Protokollseitendaten der Bestandsaufnahme abgerufen werden können:
+
[source, cli]
----
nvme discover -t tcp -w host-traddr -a traddr
----
+
.Beispielausgabe anzeigen
[%collapsible]
=====
[listing, subs="+quotes"]
----
#nvme discover -t tcp -w 10.10.10.47 -a 10.10.10.122
#nvme discover -t tcp -w 10.10.10.47 -a 10.10.10.124
#nvme discover -t tcp -w 10.10.11.47 -a 10.10.11.122
#nvme discover -t tcp -w 10.10.11.47 -a 10.10.11.
----
=====
. Führen Sie den Befehl nvme connect-all über alle unterstützten NVMe/TCP Initiator-Ziel-LIFs über die Nodes hinweg aus und legen Sie das Zeitlimit für den Controller-Verlust für mindestens 30 Minuten oder 1800 Sekunden fest:
+
[source, cli]
----
nvme connect-all -t tcp -w host-traddr -a traddr -l 1800
----
+
.Beispielausgabe anzeigen
[%collapsible]
=====
[listing, subs="+quotes"]
----
#nvme	connect-all	-t	tcp	-w	10.10.10.47	-a	10.10.10.122 -l	1800
#nvme	connect-all	-t	tcp	-w	10.10.10.47	-a	10.10.10.124 -l	1800
#nvme	connect-all	-t	tcp	-w	10.10.11.47	-a	10.10.11.122 -l	1800
#nvme	connect-all	-t	tcp	-w	10.10.11.47	-a	10.10.11.124 -l	1800
----
=====


--
====


== Schritt 3: Optional: Aktivieren Sie 1 MB I/O für NVMe/FC.

ONTAP meldet in den Identify Controller-Daten eine maximale Datenübertragungsgröße (MDTS) von 8.  Dies bedeutet, dass die maximale E/A-Anforderungsgröße bis zu 1 MB betragen kann.  Um E/A-Anfragen der Größe 1 MB für einen Broadcom NVMe/FC-Host auszugeben, sollten Sie die `lpfc` Wert des `lpfc_sg_seg_cnt` Parameter vom Standardwert 64 auf 256.


NOTE: Diese Schritte gelten nicht für Qlogic NVMe/FC-Hosts.

.Schritte
. Setzen Sie den `lpfc_sg_seg_cnt` Parameter auf 256:
+
[source, cli]
----
cat /etc/modprobe.d/lpfc.conf
----
+
Sie sollten eine Ausgabe ähnlich dem folgenden Beispiel sehen:

+
[listing]
----
options lpfc lpfc_sg_seg_cnt=256
----
. Führen Sie den Befehl aus `dracut -f`, und starten Sie den Host neu.
. Stellen Sie sicher, dass der Wert für `lpfc_sg_seg_cnt` 256 lautet:
+
[source, cli]
----
cat /sys/module/lpfc/parameters/lpfc_sg_seg_cnt
----




== Schritt 4: Multipathing-Konfiguration überprüfen

Vergewissern Sie sich, dass der in-Kernel-Multipath-Status, der ANA-Status und die ONTAP-Namespaces für die NVMe-of-Konfiguration richtig sind.

.Schritte
. Vergewissern Sie sich, dass das in-Kernel NVMe Multipath aktiviert ist:
+
[source, cli]
----
# cat /sys/module/nvme_core/parameters/multipath
----
+
Die erwartete Ausgabe ist „Y“.

. Vergewissern Sie sich, dass die entsprechenden NVMe-of-Einstellungen (z. B. auf NetApp ONTAP-Controller gesetzt auf Modell und Load-Balancing-IOpolicy auf Round-Robin eingestellt) für die jeweiligen ONTAP-Namespaces den Host korrekt widerspiegeln:
+
[source, cli]
----
# cat /sys/class/nvme-subsystem/nvme-subsys*/model
----
+
Die folgende Ausgabe sollte angezeigt werden:

+
[listing]
----
NetApp ONTAP Controller
NetApp ONTAP Controller
----
+
.. Zeigen Sie die Richtlinie an:
+
[source, cli]
----
# cat /sys/class/nvme-subsystem/nvme-subsys*/iopolicy
----
+
Die folgende Ausgabe sollte angezeigt werden:

+
[listing]
----
round-robin
round-robin
----


. Überprüfen Sie, ob die Namespaces auf dem Host erstellt und richtig erkannt wurden:
+
[source, cli]
----
# nvme list
----
+
.Beispielausgabe anzeigen
[%collapsible]
====
[listing]
----
Node         SN                   Model
---------------------------------------------------------
/dev/nvme0n1 81CZ5BQuUNfGAAAAAAAB	NetApp ONTAP Controller


Namespace Usage    Format             FW             Rev
-----------------------------------------------------------
1                 21.47 GB / 21.47 GB	4 KiB + 0 B   FFFFFFFF
----
====
. Überprüfen Sie, ob der Controller-Status jedes Pfads aktiv ist und den korrekten ANA-Status aufweist:
+
[role="tabbed-block"]
====
.NVMe/FC
--
[source, cli]
----
# nvme list-subsys /dev/nvme0n1
----
.Beispielausgabe anzeigen
[%collapsible]
=====
[listing, subs="+quotes"]
----
nvme-subsys4 - NQN=nqn.1992-08.com.netapp:sn.8763d311b2ac11ed950ed039ea951c46:subsystem. ub_106 \
+- nvme1 *fc* traddr=nn-0x20a6d039ea954d17:pn-0x20a7d039ea954d17,host_traddr=nn-0x200000109b1b95ef:pn-0x100000109b1b95ef *live optimized*
+- nvme2 *fc* traddr=nn-0x20a6d039ea954d17:pn-0x20a8d039ea954d17,host_traddr=nn-0x200000109b1b95f0:pn-0x100000109b1b95f0 *live optimized*
+- nvme3 *fc* traddr=nn-0x20a6d039ea954d17:pn-0x20aad039ea954d17,host_traddr=nn-0x200000109b1b95f0:pn-0x100000109b1b95f0 *live non-optimized*
+- nvme5 *fc* traddr=nn-0x20a6d039ea954d17:pn-0x20a9d039ea954d17,host_traddr=nn-0x200000109b1b95ef:pn-0x100000109b1b95ef *live non-optimized*
----
=====
--
.NVMe/TCP
--
[source, cli]
----
# nvme list-subsys /dev/nvme1n1
----
.Beispielausgabe anzeigen
[%collapsible]
=====
[listing, subs="+quotes"]
----
nvme-subsys1 - NQN=nqn.1992- 08.com.netapp:sn. bbfb4ee8dfb611edbd07d039ea165590:subsystem.rhel_tcp_95
+- nvme1 *tcp* traddr=10.10.10.122,trsvcid=4420,host_traddr=10.10.10.47,src_addr=10.10.10.47 *live*
+- nvme2 *tcp* traddr=10.10.10.124,trsvcid=4420,host_traddr=10.10.10.47,src_addr=10.10.10.47 *live*
+- nvme3 *tcp* traddr=10.10.11.122,trsvcid=4420,host_traddr=10.10.11.47,src_addr=10.10.11.47 *live*
+- nvme4 *tcp* traddr=10.10.11.124,trsvcid=4420,host_traddr=10.10.11.47,src_addr=10.10.11.47 *live*
----
=====
--
====
. Vergewissern Sie sich, dass das NetApp Plug-in für jedes ONTAP Namespace-Gerät die richtigen Werte anzeigt:
+
[role="tabbed-block"]
====
.Spalte
--
[source, cli]
----
# nvme netapp ontapdevices -o column
----
.Beispielausgabe anzeigen
[%collapsible]
=====
[listing]
----
Device        Vserver   Namespace Path
----------------------- ------------------------------
/dev/nvme0n1 co_iscsi_tcp_ubuntu /vol/vol1/ns1



NSID       UUID                                   Size
------------------------------------------------------------
1          79c2c569-b7fa-42d5-b870-d9d6d7e5fa84	21.47GB
----
=====
--
.JSON
--
[source, cli]
----
# nvme netapp ontapdevices -o json
----
.Beispielausgabe anzeigen
[%collapsible]
=====
[listing]
----
{

"ONTAPdevices" : [
{

"Device" : "/dev/nvme0n1",
"Vserver" : "co_iscsi_tcp_ubuntu",
"Namespace_Path" : "/vol/nvmevol1/ns1",
"NSID" : 1,
"UUID" : "79c2c569-b7fa-42d5-b870-d9d6d7e5fa84",
"Size" : "21.47GB",
"LBA_Data_Size" : 4096,
"Namespace_Size" : 5242880
},

]
}

----
=====
--
====




== Schritt 5: Überprüfen der bekannten Probleme

Die NVMe-of Hostkonfiguration für Ubuntu 22.04 mit ONTAP-Release weist das folgende bekannte Problem auf:

[cols="20,20,60"]
|===
| NetApp Bug ID | Titel | Beschreibung 


| CONTAPEXT-2037 | Ubuntu 22.04 NVMe-of-Hosts erstellen doppelte Persistent Discovery Controller | Auf NVMe-of Hosts können Sie den Befehl „nvme discover -p“ verwenden, um Persistent Discovery Controller (PDCs) zu erstellen. Dieser Befehl sollte nur ein PDC für jede Kombination aus Initiator und Ziel erstellen. Wenn Sie Ubuntu 22.04 jedoch auf einem NVMe-of-Host ausführen, wird bei jeder Ausführung von „nvme discover -p“ ein doppelter PDC erstellt. Dies führt zu einer unnötigen Nutzung der Ressourcen auf dem Host und dem Ziel. 
|===