---
sidebar: sidebar 
permalink: nvme_sles15_sp1.html 
keywords: nvme, linux, suse, sles, 15, sp1, server, enterprise 
summary: Beschreibt die Konfiguration von NVMe/FC für SUSE Linux Enterprise Server 15 SP1 mit ONTAP 
---
= NVMe/FC-Hostkonfiguration für SUSE Linux Enterprise Server 15 SP1 mit ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können NVMe over Fibre Channel (NVMe/FC) auf Hosts konfigurieren, auf denen SUSE Linux Enterprise Server 15 SP1 und ONTAP als Ziel ausgeführt werden.

NVMe/FC wird auf ONTAP 9 6 oder höher für die folgenden Versionen von SUSE Linux Enterprise Server unterstützt:

* SUSE Linux Enterprise Server 15 SP1
+
Auf dem SUSE Linux Enterprise Server 15 SP1-Host kann sowohl NVMe/FC- als auch FCP-Datenverkehr über dieselben Fibre-Channel-Initiator-Adapter-Ports ausgeführt werden. Eine Liste der unterstützten FC-Adapter und Controller finden Sie im link:https://hwu.netapp.com/Home/Index["Hardware Universe"^] .

+
Die aktuelle Liste der unterstützten Konfigurationen und Versionen finden Sie unter link:https://mysupport.netapp.com/matrix/["NetApp Interoperabilitätsmatrix"^].

* Das nvme-cli-Paket enthält native NVMe/FC-Skripts für die automatische Verbindung. Sie können den nativen Inbox-lpfc-Treiber unter SUSE Linux Enterprise Server 15 SP1 verwenden.




== Bekannte Einschränkungen

Das Booten von SAN über das NVMe-of-Protokoll wird derzeit nicht unterstützt.



== Aktivieren Sie NVMe/FC unter SUSE Linux Enterprise Server 15 SP1

. Führen Sie ein Upgrade auf den empfohlenen SUSE Linux Enterprise Server 15 SP2 MU-Kernel durch
. Führen Sie ein Upgrade auf die empfohlene nvme-cli MU-Version durch.
+
Dieses nvme-cli-Paket enthält die nativen automatischen NVMe/FC-Verbindungsskripts, sodass Sie die von Broadcom bereitgestellten externen NVMe/FC-Skripts für die automatische Verbindung nicht auf dem SUSE Linux Enterprise Server 15 SP1-Host installieren müssen. Dieses Paket enthält außerdem die ONTAP udev-Regel für den Round Robin-Lastausgleich für NVMe Multipath und das NetApp Plug-in für ONTAP Geräte.

+
[listing]
----
# rpm -qa | grep nvme-cli
nvme-cli-1.8.1-6.9.1.x86_64
----
. Überprüfen Sie auf dem SUSE Linux Enterprise Server 15 SP1-Host die NQN-Hostzeichenfolge unter `/etc/nvme/hostnqn`, und vergewissern Sie sich, dass sie mit der NQN-Hostzeichenfolge für das entsprechende Subsystem im ONTAP-Array übereinstimmt. Beispiel:
+
[listing]
----
# cat /etc/nvme/hostnqn
nqn.2014-08.org.nvmexpress:uuid:75953f3b-77fe-4e03-bf3c-09d5a156fbcd
----
+
[listing]
----
*> vserver nvme subsystem host show -vserver vs_nvme_10
Vserver Subsystem Host NQN
------- --------- -------------------------------------- -----------
sles_117_nvme_ss_10_0
nqn.2014-08.org.nvmexpress:uuid:75953f3b-77fe-4e03-bf3c-09d5a156fbcd
----
. Starten Sie den Host neu.




== Konfigurieren Sie den Broadcom FC-Adapter für NVMe/FC

. Vergewissern Sie sich, dass Sie den unterstützten Adapter verwenden. Die aktuelle Liste der unterstützten Adapter finden Sie im link:https://mysupport.netapp.com/matrix/["NetApp Interoperabilitätsmatrix"^].
+
[listing]
----
# cat /sys/class/scsi_host/host*/modelname
LPe32002-M2
LPe32002-M2
----
+
[listing]
----
# cat /sys/class/scsi_host/host*/modeldesc
Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
----
. Stellen Sie sicher, dass Sie die empfohlene Broadcom lpfc-Firmware und native Inbox-Treiber-Versionen verwenden.
+
[listing]
----
# cat /sys/class/scsi_host/host*/fwrev
12.4.243.17, sil-4.2.c
12.4.243.17, sil-4.2.c
----
+
[listing]
----
# cat /sys/module/lpfc/version
0:12.6.0.0
----
. Stellen Sie sicher, dass lpfc_enable_fc4_type auf 3 gesetzt ist.
+
[listing]
----
# cat /sys/module/lpfc/parameters/lpfc_enable_fc4_type
3
----
. Vergewissern Sie sich, dass die Initiator-Ports ausgeführt werden.
+
[listing]
----
# cat /sys/class/fc_host/host*/port_name
0x10000090fae0ec61
0x10000090fae0ec62
----
+
[listing]
----
# cat /sys/class/fc_host/host*/port_state
Online
Online
----
. Vergewissern Sie sich, dass die NVMe/FC-Initiator-Ports aktiviert sind und die Ziel-LIFs ausgeführt werden können.
+
[listing]
----
# cat /sys/class/scsi_host/host*/nvme_info
NVME Initiator Enabled
XRI Dist lpfc0 Total 6144 NVME 2947 SCSI 2977 ELS 250
NVME LPORT lpfc0 WWPN x10000090fae0ec61 WWNN x20000090fae0ec61 DID x012000 ONLINE
NVME RPORT WWPN x202d00a098c80f09 WWNN x202c00a098c80f09 DID x010201 TARGET DISCSRVC ONLINE
NVME RPORT WWPN x203100a098c80f09 WWNN x202c00a098c80f09 DID x010601 TARGET DISCSRVC ONLINE
NVME Statistics
…
----




== NVMe/FC validieren

. Überprüfen Sie die folgenden NVMe/FC-Einstellungen.
+
[listing]
----
# cat /sys/module/nvme_core/parameters/multipath
Y
----
+
[listing]
----
# cat /sys/class/nvme-subsystem/nvme-subsys*/model
NetApp ONTAP Controller
NetApp ONTAP Controller
----
+
[listing]
----
# cat /sys/class/nvme-subsystem/nvme-subsys*/iopolicy
round-robin
round-robin
----
. Vergewissern Sie sich, dass die Namespaces erstellt wurden.
+
[listing]
----
# nvme list
Node SN Model Namespace Usage Format FW Rev
---------------- -------------------- -----------------------
/dev/nvme0n1 80BADBKnB/JvAAAAAAAC NetApp ONTAP Controller 1 53.69 GB / 53.69 GB 4 KiB + 0 B FFFFFFFF
----
. Überprüfen Sie den Status der ANA-Pfade.
+
[listing]
----
# nvme list-subsys/dev/nvme0n1
Nvme-subsysf0 – NQN=nqn.1992-08.com.netapp:sn.341541339b9511e8a9b500a098c80f09:subsystem.sles_117_nvme_ss_10_0
\
+- nvme0 fc traddr=nn-0x202c00a098c80f09:pn-0x202d00a098c80f09 host_traddr=nn-0x20000090fae0ec61:pn-0x10000090fae0ec61 live optimized
+- nvme1 fc traddr=nn-0x207300a098dfdd91:pn-0x207600a098dfdd91 host_traddr=nn-0x200000109b1c1204:pn-0x100000109b1c1204 live inaccessible
+- nvme2 fc traddr=nn-0x207300a098dfdd91:pn-0x207500a098dfdd91 host_traddr=nn-0x200000109b1c1205:pn-0x100000109b1c1205 live optimized
+- nvme3 fc traddr=nn-0x207300a098dfdd91:pn-0x207700a098dfdd91 host traddr=nn-0x200000109b1c1205:pn-0x100000109b1c1205 live inaccessible
----
. Überprüfen Sie das NetApp Plug-in für ONTAP Geräte.
+
[listing]
----
# nvme netapp ontapdevices -o column
Device   Vserver  Namespace Path             NSID   UUID   Size
-------  -------- -------------------------  ------ ----- -----
/dev/nvme0n1   vs_nvme_10       /vol/sles_117_vol_10_0/sles_117_ns_10_0    1        55baf453-f629-4a18-9364-b6aee3f50dad   53.69GB

# nvme netapp ontapdevices -o json
{
   "ONTAPdevices" : [
   {
        Device" : "/dev/nvme0n1",
        "Vserver" : "vs_nvme_10",
        "Namespace_Path" : "/vol/sles_117_vol_10_0/sles_117_ns_10_0",
         "NSID" : 1,
         "UUID" : "55baf453-f629-4a18-9364-b6aee3f50dad",
         "Size" : "53.69GB",
         "LBA_Data_Size" : 4096,
         "Namespace_Size" : 13107200
    }
]
----




== Bekannte Probleme

Es sind keine Probleme bekannt.



== Aktivieren Sie 1 MB I/O-Größe für Broadcom NVMe/FC

ONTAP meldet eine MDTS (MAX Data-Übertragungsgröße) von 8 in den Identifizieren von Controller-Daten. Das bedeutet, dass die maximale E/A-Anforderungsgröße bis zu 1 MB betragen kann. Um I/O-Anforderungen der Größe 1 MB für einen Broadcom-NVMe/FC-Host auszustellen, sollten Sie den Wert des `lpfc_sg_seg_cnt` Parameters ab dem Standardwert 64 auf 256 erhöhen `lpfc`.


NOTE: Diese Schritte gelten nicht für Qlogic NVMe/FC-Hosts.

.Schritte
. Setzen Sie den `lpfc_sg_seg_cnt` Parameter auf 256:
+
[listing]
----
cat /etc/modprobe.d/lpfc.conf
----
+
[listing]
----
options lpfc lpfc_sg_seg_cnt=256
----
. Führen Sie den Befehl aus `dracut -f`, und starten Sie den Host neu.
. Stellen Sie sicher, dass der erwartete Wert von `lpfc_sg_seg_cnt` 256 ist:
+
[listing]
----
cat /sys/module/lpfc/parameters/lpfc_sg_seg_cnt
----




== LPFC Verbose Logging

Legen Sie den lpfc-Treiber für NVMe/FC fest.

.Schritte
. Stellen Sie die ein `lpfc_log_verbose` Treibereinstellung auf einen der folgenden Werte, um NVMe/FC-Ereignisse zu protokollieren.
+
[listing]
----
#define LOG_NVME 0x00100000 /* NVME general events. */
#define LOG_NVME_DISC 0x00200000 /* NVME Discovery/Connect events. */
#define LOG_NVME_ABTS 0x00400000 /* NVME ABTS events. */
#define LOG_NVME_IOERR 0x00800000 /* NVME IO Error events. */
----
. Führen Sie nach dem Festlegen der Werte den aus `dracut-f` Führen Sie einen Befehl aus und starten Sie den Host neu.
. Überprüfen Sie die Einstellungen.
+
[listing]
----
# cat /etc/modprobe.d/lpfc.conf options lpfc lpfc_log_verbose=0xf00083

# cat /sys/module/lpfc/parameters/lpfc_log_verbose 15728771
----

