---
sidebar: sidebar 
permalink: nvme-aix.html 
keywords: nvme, linux, rhel, red hat, enterprise, aix, ontap 
summary: Konfigurieren des NVMe/FC-Hosts für AIX mit ONTAP 
---
= Konfigurieren Sie AIX mit NVMe-oF für ONTAP -Speicher
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die IBM AIX- und Virtual I/O Server (VIOS)/PowerVM-Hosts unterstützen das NVMe/FC-Protokoll mit Asymmetric Namespace Access (ANA).  ANA entspricht dem asymmetrischen Logical Unit Access (ALUA)-Multipathing in iSCSI- und FCP-Umgebungen.

Weitere Einzelheiten zu unterstützten Konfigurationen finden Sie imlink:https://mysupport.netapp.com/matrix/["Interoperabilitäts-Matrix-Tool (IMT)"^] .

.Über diese Aufgabe
Sie können die folgende Unterstützung und Funktionen mit der NVMe-oF-Hostkonfiguration für AIX-Hosts verwenden.  Sie sollten sich auch die bekannten Einschränkungen ansehen, bevor Sie mit dem Konfigurationsprozess beginnen.

* Support verfügbar:
+
** Ab ONTAP 9.13.1 wird NVMe/FC-Unterstützung für IBM AIX 7.2 TL5 SP6, AIX 7.3 TL1 SP2 und VIOS 3.1.4.21 mit SAN-Boot-Unterstützung für physische und virtuelle Stacks hinzugefügt.  Weitere Informationen zum Einrichten der SAN-Boot-Unterstützung finden Sie in der IBM-Dokumentation.
** NVMe/FC wird von power9- und Power10-IBM-Servern unterstützt.
** Ein separates PCM (Path Control Module), wie z. B. Host Utilities für AIX SCSI Multipath I/O (MPIO)-Unterstützung, ist für NVMe-Geräte nicht erforderlich.
** Der Virtualisierungssupport mit NetApp (VIOS/PowerVM) wird mit VIOS 3.1.4.21 eingeführt. Dieser wird _only_ über den NPIV (N_PortID Virtualization) Speichervirtualisierungsmodus unterstützt, der den Power10 IBM-Server verwendet.


* Bekannte Einschränkungen:
+
** Qlogic/Marvel 32G FC HBAs auf einem AIX-Host unterstützen NVMe/FC nicht.
** SAN-Boot wird für NVMe/FC-Geräte mit Power9 IBM-Server nicht unterstützt.




.Bevor Sie beginnen
* Überprüfen Sie, ob Sie über 32-GB-FC-Emulex-Adapter (EN1A, EN1B, EN1L, EN1M) oder 64-GB-FC-Adapter (EN1N, EN1P) mit Adapter-Firmware 12.4.257.30 und höher verfügen.
* Wenn Sie über eine MetroCluster-Konfiguration verfügen, empfiehlt NetApp, die AIX NVMe/FC-Standard-APD-Zeit (All Path Down) für die Unterstützung ungeplanter MetroCluster-Switchover-Ereignisse zu ändern, um zu vermeiden, dass das AIX-Betriebssystem eine kürzere I/O-Zeitüberschreitung erzwingt. Weitere Informationen und die empfohlenen Änderungen an den Standardeinstellungen finden Sie unter NetApp Bugs Online - link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1553249["1553249"^].
* Abhängig von Ihrer AIX-Version beträgt das Asymmetric Namespace Access Transition Timeout (ANATT) für das AIX-Host-Betriebssystem standardmäßig 30 Sekunden oder 60 Sekunden.  Wenn der ANATT-Standardwert für Ihren Host 30 Sekunden beträgt, müssen Sie einen IBM Interim Fix (ifix) von der IBM-Website installieren, der den ANATT auf 60 Sekunden festlegt, um sicherzustellen, dass alle ONTAP Workflows unterbrechungsfrei ablaufen.
+
[NOTE]
====
Für die NVMe/FC AIX-Unterstützung müssen Sie ein ifix auf der GA-Version des AIX-Betriebssystems installieren.  Das ifix ist für das VIOS/PowerVM-Betriebssystem nicht erforderlich.

Sie müssen die ifixes auf einer AIX-Version installieren, auf der zuvor keine ifixes installiert waren, die sich auf `devices.pciex.pciexclass.010802.rte` auf dem System.  Zuvor installierte Ifixes können mit der neuen Installation in Konflikt geraten.

====
+
[role="tabbed-block"]
====
.Stellen Sie ANATT auf 60 Sekunden ein
--
Der Standard-ANATT für die Releases AIX Level 72-TL5-SP6-2320 und AIX Level 73-TL1-SP2-2320 beträgt 30 Sekunden.  IBM stellt einen Ifix bereit, der ANATT auf 60 Sekunden setzt.  Das ifix ist über die IBM-Fall-ID TS018079082 verfügbar und Sie können es für die folgenden AIX-Versionen installieren:

** Für AIX-Level 72-TL5-SP6-2320 installieren Sie den `IJ46710s6a.230509.epkg.Z` Paket.
** Für AIX Level 73-TL1-SP2-2320 installieren Sie den `IJ46711s2a.230509.epkg.Z` Paket.


--
.Der Standard-ANATT beträgt 60 Sekunden
--
Der Standard-ANATT beträgt 60 Sekunden für die folgenden AIX-Versionen:

** AIX-Ebene 73-TL2-SP3-2446
** AIX-Ebene 73-TL2-SP2-2420
** AIX-Ebene 72-TL5-SP8-2420


--
.Optional können Sie ANATT auf 120 Sekunden einstellen
--
IBM stellt einen Ifix bereit, der ANATT auf 120 Sekunden festlegt.  Wenn Sie ANATT auf 120 Sekunden einstellen, verbessert dies die Leistung bei ONTAP -Speicher-Failover-Ereignissen.  Das ifix ist über die IBM-Fall-ID TS012877410 verfügbar und Sie können es für die folgenden AIX-Versionen installieren:

** Für AIX Level 73-TL3-SP0-2446 installieren Sie die `IJ53487s0a.250130.epkg.Z` Paket.
** Für AIX Level 72-TL5-SP9-2446 installieren Sie die `IJ53445s9a.250130.epkg.Z` Paket.


--
====
+
[NOTE]
====
Die Mindestversion der Server-Firmware für Power9-Server zur Unterstützung von NVMe/FC ist FW 950.

Die Mindestserver-Firmwareversion für Power10-Server zur NVMe/FC-Unterstützung ist FW 1010.

====
+
Weitere Informationen zur Verwaltung von Ifixen finden Sie unter link:http://www-01.ibm.com/support/docview.wss?uid=isg3T1012104["Verwalten von Interim Fixes auf AIX"^].





== Schritt 1: Bestätigen Sie die Multipath-Konfiguration für Ihren Host

Wenn Sie das AIX-Betriebssystem installieren, wird IBM MPIO, das für NVMe-Multipathing verwendet wird, standardmäßig aktiviert.

.Schritte
. Stellen Sie sicher, dass NVMe-Multipathing aktiviert ist:
+
[source, cli]
----
lsmpio -l hdisk1
----
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
name     path_id  status   path_status  parent  connection
hdisk1  8         Enabled  Sel,Opt       nvme12  fcnvme0, 9
hdisk1  9         Enabled  Sel,Non       nvme65  fcnvme1, 9
hdisk1  10        Enabled  Sel,Opt       nvme37  fcnvme1, 9
hdisk1  11        Enabled  Sel,Non       nvme60  fcnvme0, 9
----
====




== Schritt 2: NVMe/FC konfigurieren

Sie müssen NVMe/FC für Broadcom/Emulex-Adapter auf VIOS konfigurieren, da die NVMe/FC-Protokollunterstützung im Virtual Fibre Channel (vFC) auf VIOS deaktiviert ist.  Die NVMe/FC-Protokollunterstützung ist im physischen FC standardmäßig aktiviert.

.Schritte
. link:https://mysupport.netapp.com/matrix/["Stellen Sie sicher, dass Sie den unterstützten Adapter verwenden"^] .
. Liste der virtuellen Adapter abrufen:
+
[source, cli]
----
lsmap -all -npiv
----
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
Name          Physloc                            ClntID ClntName       ClntOS
------------- ---------------------------------- ------ -------------- -------
vfchost0      U9105.22A.785DB61-V2-C2                 4 s1022-iop-mcc- AIX
Status:LOGGED_IN
FC name:fcs4                    FC loc code:U78DA.ND0.WZS01UY-P0-C7-T0
Ports logged in:3
Flags:0xea<LOGGED_IN,STRIP_MERGE,SCSI_CLIENT,NVME_CLIENT>
VFC client name:fcs0            VFC client DRC:U9105.22A.785DB61-V4-C2
----
====
. Aktivieren Sie die Unterstützung für das NVMe/FC-Protokoll auf einem Adapter, indem Sie den ausführen `ioscli vfcctrl` Befehl auf dem VIOS:
+
[source, cli]
----
vfcctrl -enable -protocol nvme -vadapter vfchost0
----
+
.Beispielausgabe
[listing]
----
The "nvme" protocol for "vfchost0" is enabled.
----
. Stellen Sie sicher, dass die Unterstützung auf dem Adapter aktiviert wurde:
+
[source, cli]
----
lsattr -El vfchost0
----
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
alt_site_wwpn       WWPN to use - Only set after migration   False
current_wwpn  0     WWPN to use - Only set after migration   False
enable_nvme   yes   Enable or disable NVME protocol for NPIV True
label               User defined label                       True
limit_intr    false Limit NPIV Interrupt Sources             True
map_port      fcs4  Physical FC Port                         False
num_per_nvme  0     Number of NPIV NVME queues per range     True
num_per_range 0     Number of NPIV SCSI queues per range     True
----
====
. Aktivieren Sie das NVMe/FC-Protokoll für alle Adapter:
+
.. Ändern Sie das `dflt_enabl_nvme` Attributwert von `viosnpiv0` Pseudo-Gerät an `yes`.
.. Stellen Sie die ein `enable_nvme` Attributwert an `yes` Für alle VFC-Hostgeräte.
+
[source, cli]
----
chdev -l viosnpiv0 -a dflt_enabl_nvme=yes
----
+
[source, cli]
----
lsattr -El viosnpiv0
----
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
bufs_per_cmd    10  NPIV Number of local bufs per cmd                    True
dflt_enabl_nvme yes Default NVME Protocol setting for a new NPIV adapter True
num_local_cmds  5   NPIV Number of local cmds per channel                True
num_per_nvme    8   NPIV Number of NVME queues per range                 True
num_per_range   8   NPIV Number of SCSI queues per range                 True
secure_va_info  no  NPIV Secure Virtual Adapter Information              True
----
====


. Aktivieren Sie das NVMe/FC-Protokoll für ausgewählte Adapter, indem Sie die ändern `enable_nvme` Wert des VFC-Host-Device-Attributs auf `yes`.
. Verifizieren Sie das `FC-NVMe Protocol Device` Wurde auf dem Server erstellt:
+
[source, cli]
----
lsdev |grep fcnvme
----
+
.Beispielausgabe
[listing]
----
fcnvme0       Available 00-00-02    FC-NVMe Protocol Device
fcnvme1       Available 00-01-02    FC-NVMe Protocol Device
----
. Notieren Sie die Host-NQN vom Server:
+
[source, cli]
----
lsattr -El fcnvme0
----
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
attach     switch                                                               How this adapter is connected  False
autoconfig available                                                            Configuration State            True
host_nqn   nqn.2014-08.org.nvmexpress:uuid:64e039bd-27d2-421c-858d-8a378dec31e8 Host NQN (NVMe Qualified Name) True
----
====
+
[source, cli]
----
lsattr -El fcnvme1
----
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
attach     switch                                                               How this adapter is connected  False
autoconfig available                                                            Configuration State            True
host_nqn   nqn.2014-08.org.nvmexpress:uuid:64e039bd-27d2-421c-858d-8a378dec31e8 Host NQN (NVMe Qualified Name) True
----
====
. Überprüfen Sie die Host-NQN und stellen Sie sicher, dass sie mit der Host-NQN-Zeichenfolge für das entsprechende Subsystem auf dem ONTAP-Array übereinstimmt:
+
[source, cli]
----
vserver nvme subsystem host show -vserver vs_s922-55-lpar2
----
+
.Beispielausgabe
[listing]
----
Vserver         Subsystem                Host NQN
------- --------- ----------------------------------------------------------
vs_s922-55-lpar2 subsystem_s922-55-lpar2 nqn.2014-08.org.nvmexpress:uuid:64e039bd-27d2-421c-858d-8a378dec31e8
----
. Überprüfen Sie, ob die Initiator-Ports ausgeführt wurden und Sie die Ziel-LIFs sehen können.




== Schritt 3: NVMe/FC validieren

Überprüfen Sie, ob die ONTAP -Namespaces für die NVMe/FC-Konfiguration korrekt sind.

.Schritte
. Überprüfen Sie, ob die ONTAP -Namespaces auf dem Host korrekt wiedergegeben werden:
+
[source, cli]
----
lsdev -Cc disk |grep NVMe
----
+
.Beispielausgabe
[listing]
----
hdisk1  Available 00-00-02 NVMe 4K Disk
----
. Überprüfen Sie optional den Multipathing-Status:
+
[source, cli]
----
lsmpio -l hdisk1
----
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
name     path_id  status   path_status  parent  connection
hdisk1  8        Enabled  Sel,Opt      nvme12  fcnvme0, 9
hdisk1  9        Enabled  Sel,Non      nvme65  fcnvme1, 9
hdisk1  10       Enabled  Sel,Opt      nvme37  fcnvme1, 9
hdisk1  11       Enabled  Sel,Non      nvme60  fcnvme0, 9
----
====




== Schritt 4: Überprüfen der bekannten Probleme

Bei der NVMe/FC-Hostkonfiguration für AIX mit ONTAP Speicher sind die folgenden Probleme bekannt:

[cols="10,30,30"]
|===
| Burt-ID | Titel | Beschreibung 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1553249["1553249"^] | AIX NVMe/FC Standard-APD-Zeit, die zur Unterstützung von MCC-Ereignissen mit ungeplanten Umschaltungen geändert werden soll | Standardmäßig verwenden AIX-Betriebssysteme einen All Path Down (APD)-Timeout-Wert von 20 Sek. für NVMe/FC.  Allerdings können die von ONTAP MetroCluster initiierten Workflows für die automatische ungeplante Umschaltung (AUSO) und Tiebreaker eine etwas längere Zeit als das APD-Timeout-Fenster benötigen, was zu I/O-Fehlern führt. 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1546017["1546017"^] | AIX NVMe/FC ist mit ANATT 60 GB und nicht mit 120 GB ausgestattet, wie von ONTAP angekündigt | ONTAP gibt das ANA (Asymmetric Namespace Access)-Transition Timeout bei der Controller-Identifizierung mit 120 Sek. an. Derzeit liest AIX bei ifix das ANA-Übergangszeitlimit von Controller Identify, aber spannt es effektiv auf 60 Sek., wenn es über diesem Grenzwert liegt. 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1541386["1541386"^] | AIX NVMe/FC schlägt nach dem Ablauf von ANATT EIO vor | Wenn der ANA(Asymmetric Namespace Access)-Übergang bei jedem Storage-Failover (SFO)-Ereignis die ANA-Transition-Timeout-Obergrenze für einen bestimmten Pfad überschreitet, fällt der AIX-NVMe/FC-Host mit einem I/O-Fehler aus, obwohl alternative fehlerfreie Pfade für den Namespace verfügbar sind. 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1541380["1541380"^] | AIX NVMe/FC wartet, bis ANATT halb/vollständig abläuft, bevor I/O nach ANA AEN fortgesetzt wird | IBM AIX NVMe/FC unterstützt einige von ONTAP veröffentlichte AENs (Asynchronous Notifications) nicht. Diese suboptimale ANA-Handhabung führt während des SFO-Betriebs zu einer suboptimalen Leistung. 
|===


== Schritt 5: Fehlerbehebung

Bevor Sie NVMe/FC-Fehler beheben, überprüfen Sie, ob Sie eine Konfiguration ausführen, die mit demlink:https://mysupport.netapp.com/matrix/["IMT"^] Spezifikationen.  Wenn weiterhin Probleme auftreten, wenden Sie sich anlink:https://mysupport.netapp.com["NetApp Support"^] .
