---
sidebar: sidebar 
permalink: nvme_windows_2012r2.html 
keywords: nvme, windows, enterprise 
summary: NVMe/FC-Host-Konfiguration für Windows Server 2012 R2 mit ONTAP 
---
= NVMe/FC-Host-Konfiguration für Windows Server 2012 R2 mit ONTAP
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Sie können NVMe over Fibre Channel (NVMe/FC) auf Hosts konfigurieren, auf denen Windows Server 2012 R2 und ONTAP als Ziel ausgeführt werden.

NVMe/FC wird auf ONTAP 9.7 oder höher für Windows Server 2012 unterstützt.

Beachten Sie, dass der Broadcom Initiator sowohl NVMe/FC- als auch FCP-Datenverkehr über dieselben 32-Gbit-FC-Adapter-Ports verarbeiten kann. Verwenden Sie für FCP und FC/NVMe MSDSM als Microsoft Multipath I/O (MPIO) Option.

Siehe link:https://hwu.netapp.com/Home/Index["Hardware Universe"^] Für eine Liste der unterstützten FC-Adapter und Controller. Die aktuelle Liste der unterstützten Konfigurationen und Versionen finden Sie unter link:https://mysupport.netapp.com/matrix/["NetApp Interoperabilitätsmatrix"^].


NOTE: Sie können die in diesem Dokument angegebenen Konfigurationseinstellungen verwenden, um die mit verbundenen Cloud-Clients zu konfigurieren link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] Und link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["Amazon FSX für ONTAP"^].



== Bekannte Einschränkungen

Windows Failover Cluster (WFC) wird mit ONTAP NVMe/FC nicht unterstützt, da ONTAP derzeit keine persistenten Reservierungen mit NVMe/FC unterstützt.


NOTE: Der von Broadcom für Windows NVMe/FC gelieferte externe Treiber ist kein echter NVMe/FC-Treiber, sondern ein translationaler SCSI ⇄ NVMe-Treiber. Dieser translationale Overhead wirkt sich nicht unbedingt auf die Performance aus, negiert jedoch die Performance-Vorteile von NVMe/FC. Somit ist bei Windows-Servern die NVMe/FC- und FCP-Performance dieselbe, anders als bei anderen Betriebssystemen wie Linux, wo die NVMe/FC-Performance deutlich besser ist als die des FCP.



== Aktivieren Sie NVMe/FC auf einem Windows-Initiator-Host

Führen Sie diese Schritte aus, um FC/NVMe auf dem Windows-Initiator-Host zu aktivieren:

.Schritte
. Installieren Sie das OneCommand Manager-Dienstprogramm auf dem Windows-Host.
. Legen Sie an jedem der HBA-Initiator-Ports die folgenden HBA-Treiberparameter fest:
+
** EnableNVMe = 1
** NVMEMode = 0
** LimTransferSize=1


. Starten Sie den Host neu.




== Konfigurieren Sie den Broadcom FC-Adapter in Windows für NVMe/FC

Mit dem Broadcom Adapter für FC/NVMe in einer Windows-Umgebung a `+hostnqn+` Ist jedem Port des Host Bus Adapters (HBA) zugeordnet. Der `+hostnqn+` Ist wie folgt formatiert.

....
nqn.2017-01.com.broadcom:ecd:nvmf:fc:100000109b1b9765
nqn.2017-01.com.broadcom:ecd:nvmf:fc:100000109b1b9766
....


=== Aktivieren Sie MPIO für NVMe-Geräte auf dem Windows-Host

. Installieren link:link:https://docs.netapp.com/us-en/ontap-sanhost/hu_wuhu_71.html["Windows Host Utility Kit 7.1"] Treiber-Parameter einstellen, die für FC und NVMe gemeinsam sind.
. Öffnen Sie die MPIO-Eigenschaften.
. Fügen Sie auf der Registerkarte *Multi-Paths* die für NVMe angegebene Geräte-ID hinzu.
+
MPIO erkennt NVMe-Geräte, die im Festplattenmanagement sichtbar sind.

. Öffnen Sie * Disk Management* und gehen Sie zu *Disk Properties*.
. Klicken Sie auf der Registerkarte *MPIO* auf *Details*.
. Legen Sie die folgenden MSDSM-Einstellungen fest:
+
** PathVerifiedPeriod: *10*
** PathVerifyEnabled: *Enable*
** RetryCount: *6*
** Wiederholungsintervall: *1*
** PDORemovedPeriod: *130*


. Wählen Sie die MPIO-Richtlinie *Round Robin mit Untergruppe* aus.
. Ändern Sie die Registrierungswerte:
+
[listing]
----
HKLM\SYSTEM\CurrentControlSet\Services\mpio\Parameters\PathRecoveryInterval DWORD -> 30

HKLM\SYSTEM\CurrentControlSet\Services\mpio \Parameters\ UseCustomPathRecoveryInterval  DWORD-> 1
----
. Starten Sie den Host neu.
+
Die NVMe-Konfiguration ist jetzt auf dem Windows Host abgeschlossen.





== NVMe/FC validieren

. Überprüfen Sie, ob der Porttyp FC+NVMe ist.
+
Nachdem NVMe nun aktiviert ist, sollten Sie die Anzeige lesen `+Port Type+` Aufgelistet unter `+FC+NVMe+`, Wie folgt.

+
[listing]
----
PS C:\Program Files\Emulex\Util\OCManager> .\hbacmd listhba

Manageable HBA List

Port WWN       : 10:00:00:10:9b:1b:97:65
Node WWN       : 20:00:00:10:9b:1b:97:65
Fabric Name    : 10:00:c4:f5:7c:a5:32:e0
Flags          : 8000e300
Host Name      : INTEROP-57-159
Mfg            : Emulex Corporation
Serial No.     : FC71367217
Port Number    : 0
Mode           : Initiator
PCI Bus Number : 94
PCI Function   : 0
Port Type      : FC+NVMe
Model          : LPe32002-M2

Port WWN       : 10:00:00:10:9b:1b:97:66
Node WWN       : 20:00:00:10:9b:1b:97:66
Fabric Name    : 10:00:c4:f5:7c:a5:32:e0
Flags          : 8000e300
Host Name      : INTEROP-57-159
Mfg            : Emulex Corporation
Serial No.     : FC71367217
Port Number    : 1
Mode           : Initiator
PCI Bus Number : 94
PCI Function   : 1
Port Type      : FC+NVMe
Model          : LPe32002-M2
----
. Überprüfen Sie, ob NVMe/FC-Subsysteme erkannt wurden.
+
Der `+nvme-list+` Mit dem Befehl werden die erkannten NVMe/FC-Subsysteme aufgelistet.

+
[listing]
----
PS C:\Program Files\Emulex\Util\OCManager> .\hbacmd nvme-list 10:00:00:10:9b:1b:97:65

Discovered NVMe Subsystems for 10:00:00:10:9b:1b:97:65

NVMe Qualified Name     :  nqn.1992-08.com.netapp:sn.a3b74c32db2911eab229d039ea141105:subsystem.win_nvme_interop-57-159
Port WWN                :  20:09:d0:39:ea:14:11:04
Node WWN                :  20:05:d0:39:ea:14:11:04
Controller ID           :  0x0180
Model Number            :  NetApp ONTAP Controller
Serial Number           :  81CGZBPU5T/uAAAAAAAB
Firmware Version        :  FFFFFFFF
Total Capacity          :  Not Available
Unallocated Capacity    :  Not Available

NVMe Qualified Name     :  nqn.1992-08.com.netapp:sn.a3b74c32db2911eab229d039ea141105:subsystem.win_nvme_interop-57-159
Port WWN                :  20:06:d0:39:ea:14:11:04
Node WWN                :  20:05:d0:39:ea:14:11:04
Controller ID           :  0x0181
Model Number            :  NetApp ONTAP Controller
Serial Number           :  81CGZBPU5T/uAAAAAAAB
Firmware Version        :  FFFFFFFF
Total Capacity          :  Not Available
Unallocated Capacity    :  Not Available
Note: At present Namespace Management is not supported by NetApp Arrays.
----
+
[listing]
----
PS C:\Program Files\Emulex\Util\OCManager> .\hbacmd nvme-list 10:00:00:10:9b:1b:97:66

Discovered NVMe Subsystems for 10:00:00:10:9b:1b:97:66

NVMe Qualified Name     :  nqn.1992-08.com.netapp:sn.a3b74c32db2911eab229d039ea141105:subsystem.win_nvme_interop-57-159
Port WWN                :  20:07:d0:39:ea:14:11:04
Node WWN                :  20:05:d0:39:ea:14:11:04
Controller ID           :  0x0140
Model Number            :  NetApp ONTAP Controller
Serial Number           :  81CGZBPU5T/uAAAAAAAB
Firmware Version        :  FFFFFFFF
Total Capacity          :  Not Available
Unallocated Capacity    :  Not Available

NVMe Qualified Name     :  nqn.1992-08.com.netapp:sn.a3b74c32db2911eab229d039ea141105:subsystem.win_nvme_interop-57-159
Port WWN                :  20:08:d0:39:ea:14:11:04
Node WWN                :  20:05:d0:39:ea:14:11:04
Controller ID           :  0x0141
Model Number            :  NetApp ONTAP Controller
Serial Number           :  81CGZBPU5T/uAAAAAAAB
Firmware Version        :  FFFFFFFF
Total Capacity          :  Not Available
Unallocated Capacity    :  Not Available

Note: At present Namespace Management is not supported by NetApp Arrays.
----
. Überprüfen Sie, ob Namespaces erstellt wurden.
+
Der `+nvme-list-ns+` Der Befehl listet die Namespaces für ein angegebenes NVMe Ziel auf, das die mit dem Host verbundenen Namespaces aufführt.

+
[listing]
----
PS C:\Program Files\Emulex\Util\OCManager> .\HbaCmd.exe nvme-list-ns 10:00:00:10:9b:1b:97:66 20:08:d0:39:ea:14:11:04 nq
.1992-08.com.netapp:sn.a3b74c32db2911eab229d039ea141105:subsystem.win_nvme_interop-57-159 0


Active Namespaces (attached to controller 0x0141):

                                       SCSI           SCSI           SCSI
   NSID           DeviceName        Bus Number    Target Number     OS LUN
-----------  --------------------  ------------  ---------------   ---------
0x00000001   \\.\PHYSICALDRIVE9         0               1              0
0x00000002   \\.\PHYSICALDRIVE10        0               1              1
0x00000003   \\.\PHYSICALDRIVE11        0               1              2
0x00000004   \\.\PHYSICALDRIVE12        0               1              3
0x00000005   \\.\PHYSICALDRIVE13        0               1              4
0x00000006   \\.\PHYSICALDRIVE14        0               1              5
0x00000007   \\.\PHYSICALDRIVE15        0               1              6
0x00000008   \\.\PHYSICALDRIVE16        0               1              7

----

