---
sidebar: sidebar 
permalink: nvme_aix.html 
keywords: nvme, linux, rhel, red hat, enterprise, aix, ontap 
summary: Konfigurieren des NVMe/FC-Hosts für AIX mit ONTAP 
---
= NVMe/FC-Hostkonfiguration für AIX mit ONTAP
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Sie können NVMe over Fibre Channel (NVMe/FC) auf IBM AIX und VIOS/PowerVM Hosts aktivieren, die ONTAP Storage als Ziel verwenden. Weitere Informationen zu unterstützten Konfigurationen finden Sie im link:https://mysupport.netapp.com/matrix/["NetApp Interoperabilitäts-Matrix-Tool"^].

Für die NVMe/FC-Hostkonfiguration für einen AIX-Host mit ONTAP ist folgende Unterstützung verfügbar:

* Ab ONTAP 9.13.1 wird NVMe/FC-Unterstützung für IBM AIX 7.2 TL5 SP6, AIX 7.3 TL1 SP2 und VIOS 3.1.4.21 Versionen mit SAN-Boot-Unterstützung für physische und virtuelle Stacks hinzugefügt. Weitere Informationen zum Einrichten der SAN-Startunterstützung finden Sie in der IBM-Dokumentation.
* NVMe/FC wird von power9- und Power10-IBM-Servern unterstützt.
* Für NVMe Geräte ist kein separates PCM (Path Control Module) wie Host Utilities für AIX SCSI Multipath I/O (MPIO) Unterstützung erforderlich.
* Der Virtualisierungssupport mit NetApp (VIOS/PowerVM) wird mit VIOS 3.1.4.21 eingeführt. Dieser wird _only_ über den NPIV (N_PortID Virtualization) Speichervirtualisierungsmodus unterstützt, der den Power10 IBM-Server verwendet.


.Was Sie benötigen
* Überprüfen Sie, ob Sie über 32-GB-FC-Emulex-Adapter (EN1A, EN1B, EN1L, EN1M) oder 64-GB-FC-Adapter (EN1N, EN1P) mit Adapter-Firmware 12.4.257.30 und höher verfügen.
* Bei einer MetroCluster-Konfiguration empfiehlt NetApp, die AIX NVMe/FC Standard-APD-Zeit (All Path Down) zu ändern, um ungeplante MetroCluster Switchover-Ereignisse zu unterstützen, um zu vermeiden, dass das AIX Betriebssystem eine kürzere I/O-Zeitüberschreitung durchsetzt. Weitere Informationen und die empfohlenen Änderungen an den Standardeinstellungen finden Sie im öffentlichen Bericht 1553249.
* Standardmäßig beträgt der Asymmetric Namespace Access Transition Timeout (ANATT)-Wert für das AIX-Host-Betriebssystem 30 Sekunden. IBM bietet einen Interim Fix (ifix), der den ANATT-Wert auf 60 Sekunden kappen lässt. Sie müssen ein ifix von der IBM-Website installieren, um sicherzustellen, dass alle ONTAP-Workflows unterbrechungsfrei sind.
+

NOTE: Für die Unterstützung von NVMe/FC AIX müssen Sie ein ifix auf den GA-Versionen von AIX OS installieren. Dies ist für das VIOS/PowerVM-Betriebssystem nicht erforderlich.

+
die ifix-Details lauten wie folgt:

+
** Für AIX-Level 72-TL5-SP6-2320 installieren Sie den `IJ46710s6a.230509.epkg.Z` Paket.
** Für AIX Level 73-TL1-SP2-2320 installieren Sie den `IJ46711s2a.230509.epkg.Z` Paket.
+
Weitere Informationen zur Verwaltung von Ifixen finden Sie unter link:http://www-01.ibm.com/support/docview.wss?uid=isg3T1012104["Verwalten von Interim Fixes auf AIX"^].

+

NOTE: Sie müssen die ifixes auf einer AIX-Version installieren, für die keine zuvor installierten ifixes vorhanden sind `devices.pciex.pciexclass.010802.rte` Auf dem System. Wenn diese Ifixe vorhanden sind, werden sie mit der neuen Installation in Konflikt stehen.

+
In der folgenden Tabelle werden die HBAs dargestellt, die der AIX LPAR (AIX Logical Partition) oder dem physischen Stack zugewiesen sind:

+
[cols="10,10,10,10,10"]
|===
| Host-Betriebssystem | Power Arch | Power-FW-Version | Modus | Kommentare 


.2+| AIX 7.2 TL5 SP6 | Leistungs9 | FW 950 oder höher | Physischer Stack | ifix verfügbar über TS012877410. 


| Leistungs10 | FW 1010 oder höher | Physischer Stack | SAN-Booting wird unterstützt. ifix verfügbar über TS012877410. 


.2+| AIX 7.3 TL1 SP2 | Leistungs9 | FW 950 oder höher | Physischer Stack | ifix verfügbar über TS012877410. 


| Leistungs10 | FW 1010 oder höher | Physischer und virtueller Stack | ifix verfügbar über TS012877410. 
|===
+
In der folgenden Tabelle werden die dem VIOS mit NPIV-Unterstützung zugewiesenen HBAs im virtualisierten Modus dargestellt:

+
[cols="10,10,10,10,10"]
|===
| Host-Betriebssystem | Power Arch | Power-FW-Version | Modus | Kommentare 


| VIOS/PowerVM 3.1.4.21 | Leistungs10 | FW 1010 oder höher | Virtueller Stack | Der Support beginnt mit AIX 7.3 TL1 SP2 für VIOC 
|===






== Bekannte Einschränkungen

Die NVMe/FC-Hostkonfiguration für AIX mit ONTAP weist folgende bekannte Einschränkungen auf:

* QLogic/Marvel 32G FC HBAs auf einem AIX-Host unterstützt NVMe/FC nicht.
* SAN-Boot wird für NVMe/FC-Geräte mit power9 IBM-Server nicht unterstützt.




== Multipathing

IBM MPIO (Multi Path I/O), das für NVMe Multipathing verwendet wird, wird standardmäßig bei der Installation von AIX OS bereitgestellt.

Sie können mithilfe des überprüfen, ob NVMe-Multipathing für einen AIX-Host aktiviert ist `lsmpio` Befehl:

[listing]
----
#[root@aix_server /]: lsmpio -l hdisk1
----
*Beispielausgabe*

[listing]
----
name     path_id  status   path_status  parent  connection
hdisk1  8         Enabled  Sel,Opt       nvme12  fcnvme0, 9
hdisk1  9         Enabled  Sel,Non       nvme65  fcnvme1, 9
hdisk1  10        Enabled  Sel,Opt       nvme37  fcnvme1, 9
hdisk1  11        Enabled  Sel,Non       nvme60  fcnvme0, 9
----


== Konfiguration von NVMe/FC

Gehen Sie wie folgt vor, um NVMe/FC für Broadcom/Emulex-Adapter zu konfigurieren.

.Schritte
. Vergewissern Sie sich, dass Sie den unterstützten Adapter verwenden. Die aktuelle Liste der unterstützten Adapter finden Sie im link:https://mysupport.netapp.com/matrix/["NetApp Interoperabilitäts-Matrix-Tool"^].
. Standardmäßig ist die Unterstützung des NVMe/FC-Protokolls im physischen FC aktiviert. Die Unterstützung des NVMe/FC-Protokolls ist jedoch im virtuellen Fibre Channel (VFC) auf dem virtuellen I/O-Server (VIOS) deaktiviert.
+
Liste der virtuellen Adapter abrufen:

+
[listing]
----
$ lsmap -all -npiv
----
+
*Beispielausgabe*

+
[listing]
----
Name          Physloc                            ClntID ClntName       ClntOS
------------- ---------------------------------- ------ -------------- -------
vfchost0      U9105.22A.785DB61-V2-C2                 4 s1022-iop-mcc- AIX
Status:LOGGED_IN
FC name:fcs4                    FC loc code:U78DA.ND0.WZS01UY-P0-C7-T0
Ports logged in:3
Flags:0xea<LOGGED_IN,STRIP_MERGE,SCSI_CLIENT,NVME_CLIENT>
VFC client name:fcs0            VFC client DRC:U9105.22A.785DB61-V4-C2
----
. Aktivieren Sie die Unterstützung für das NVMe/FC-Protokoll auf einem Adapter, indem Sie den ausführen `ioscli vfcctrl` Befehl auf dem VIOS:
+
[listing]
----
$  vfcctrl -enable -protocol nvme -vadapter vfchost0
----
+
*Beispielausgabe*

+
[listing]
----
The "nvme" protocol for "vfchost0" is enabled.
----
. Stellen Sie sicher, dass die Unterstützung auf dem Adapter aktiviert wurde:
+
[listing]
----
# lsattr -El vfchost0
----
+
*Beispielausgabe*

+
[listing]
----
alt_site_wwpn       WWPN to use - Only set after migration   False
current_wwpn  0     WWPN to use - Only set after migration   False
enable_nvme   yes   Enable or disable NVME protocol for NPIV True
label               User defined label                       True
limit_intr    false Limit NPIV Interrupt Sources             True
map_port      fcs4  Physical FC Port                         False
num_per_nvme  0     Number of NPIV NVME queues per range     True
num_per_range 0     Number of NPIV SCSI queues per range     True
----
. NVMe/FC-Protokoll für alle aktuellen Adapter oder ausgewählte Adapter aktivieren:
+
.. Aktivieren Sie das NVMe/FC-Protokoll für alle Adapter:
+
... Ändern Sie das `dflt_enabl_nvme` Attributwert von `viosnpiv0` Pseudo-Gerät an `yes`.
... Stellen Sie die ein `enable_nvme` Attributwert an `yes` Für alle VFC-Hostgeräte.
+
[listing]
----
# chdev -l viosnpiv0 -a dflt_enabl_nvme=yes
----
+
[listing]
----
# lsattr -El viosnpiv0
----
+
*Beispielausgabe*

+
[listing]
----
bufs_per_cmd    10  NPIV Number of local bufs per cmd                    True
dflt_enabl_nvme yes Default NVME Protocol setting for a new NPIV adapter True
num_local_cmds  5   NPIV Number of local cmds per channel                True
num_per_nvme    8   NPIV Number of NVME queues per range                 True
num_per_range   8   NPIV Number of SCSI queues per range                 True
secure_va_info  no  NPIV Secure Virtual Adapter Information              True
----


.. Aktivieren Sie das NVMe/FC-Protokoll für ausgewählte Adapter, indem Sie die ändern `enable_nvme` Wert des VFC-Host-Device-Attributs auf `yes`.


. Verifizieren Sie das `FC-NVMe Protocol Device` Wurde auf dem Server erstellt:
+
[listing]
----
# [root@aix_server /]: lsdev |grep fcnvme
----
+
*Exahornausgabe*

+
[listing]
----
fcnvme0       Available 00-00-02    FC-NVMe Protocol Device
fcnvme1       Available 00-01-02    FC-NVMe Protocol Device
----
. Notieren Sie die Host-NQN vom Server:
+
[listing]
----
# [root@aix_server /]: lsattr -El fcnvme0
----
+
*Beispielausgabe*

+
[listing]
----
attach     switch                                                               How this adapter is connected  False
autoconfig available                                                            Configuration State            True
host_nqn   nqn.2014-08.org.nvmexpress:uuid:64e039bd-27d2-421c-858d-8a378dec31e8 Host NQN (NVMe Qualified Name) True
----
+
[listing]
----
[root@aix_server /]: lsattr -El fcnvme1
----
+
*Beispielausgabe*

+
[listing]
----
attach     switch                                                               How this adapter is connected  False
autoconfig available                                                            Configuration State            True
host_nqn   nqn.2014-08.org.nvmexpress:uuid:64e039bd-27d2-421c-858d-8a378dec31e8 Host NQN (NVMe Qualified Name) True
----
. Überprüfen Sie die Host-NQN und stellen Sie sicher, dass sie mit der Host-NQN-Zeichenfolge für das entsprechende Subsystem auf dem ONTAP-Array übereinstimmt:
+
[listing]
----
::> vserver nvme subsystem host show -vserver vs_s922-55-lpar2
----
+
*Beispielausgabe*

+
[listing]
----
Vserver         Subsystem                Host NQN
------- --------- ----------------------------------------------------------
vs_s922-55-lpar2 subsystem_s922-55-lpar2 nqn.2014-08.org.nvmexpress:uuid:64e039bd-27d2-421c-858d-8a378dec31e8
----
. Überprüfen Sie, ob die Initiator-Ports ausgeführt wurden und Sie die Ziel-LIFs sehen können.




== NVMe/FC validieren

Sie müssen überprüfen, ob sich die ONTAP-Namespaces korrekt auf dem Host widerspiegeln. Führen Sie dazu den folgenden Befehl aus:

[listing]
----
# [root@aix_server /]: lsdev -Cc disk |grep NVMe
----
*Beispielausgabe*

[listing]
----
hdisk1  Available 00-00-02 NVMe 4K Disk
----
Sie können den Multipathing-Status überprüfen:

[listing]
----
#[root@aix_server /]: lsmpio -l hdisk1
----
*Beispielausgabe*

[listing]
----
name     path_id  status   path_status  parent  connection
hdisk1  8        Enabled  Sel,Opt      nvme12  fcnvme0, 9
hdisk1  9        Enabled  Sel,Non      nvme65  fcnvme1, 9
hdisk1  10       Enabled  Sel,Opt      nvme37  fcnvme1, 9
hdisk1  11       Enabled  Sel,Non      nvme60  fcnvme0, 9
----


== Bekannte Probleme

Die NVMe/FC-Hostkonfiguration für AIX mit ONTAP weist folgende bekannte Probleme auf:

[cols="10,30,30"]
|===
| Burt-ID | Titel | Beschreibung 


| 1553249 | AIX NVMe/FC Standard-APD-Zeit, die zur Unterstützung von MCC-Ereignissen mit ungeplanten Umschaltungen geändert werden soll | Standardmäßig verwenden AIX-Betriebssysteme einen All Path Down (APD)-Timeout-Wert von 20 Sek. für NVMe/FC.  Allerdings können die von ONTAP MetroCluster initiierten Workflows für die automatische ungeplante Umschaltung (AUSO) und Tiebreaker eine etwas längere Zeit als das APD-Timeout-Fenster benötigen, was zu I/O-Fehlern führt. 


| 1546017 | AIX NVMe/FC ist mit ANATT 60 GB und nicht mit 120 GB ausgestattet, wie von ONTAP angekündigt | ONTAP gibt das ANA (Asymmetric Namespace Access)-Transition Timeout bei der Controller-Identifizierung mit 120 Sek. an. Derzeit liest AIX bei ifix das ANA-Übergangszeitlimit von Controller Identify, aber spannt es effektiv auf 60 Sek., wenn es über diesem Grenzwert liegt. 


| 1541386 | AIX NVMe/FC schlägt nach dem Ablauf von ANATT EIO vor | Wenn der ANA(Asymmetric Namespace Access)-Übergang bei jedem Storage-Failover (SFO)-Ereignis die ANA-Transition-Timeout-Obergrenze für einen bestimmten Pfad überschreitet, fällt der AIX-NVMe/FC-Host mit einem I/O-Fehler aus, obwohl alternative fehlerfreie Pfade für den Namespace verfügbar sind. 


| 1541380 | AIX NVMe/FC wartet, bis ANATT halb/vollständig abläuft, bevor I/O nach ANA AEN fortgesetzt wird | IBM AIX NVMe/FC unterstützt einige von ONTAP veröffentlichte AENs (Asynchronous Notifications) nicht. Diese suboptimale ANA-Handhabung führt während des SFO-Betriebs zu einer suboptimalen Leistung. 
|===


== Fehlerbehebung

Vergewissern Sie sich vor der Fehlerbehebung bei NVMe/FC-Fehlern, dass Sie eine Konfiguration ausführen, die den IMT-Spezifikationen entspricht.
Wenn weiterhin Probleme auftreten, wenden Sie sich an den technischen Support, um weitere Informationen zu erhalten.
