---
sidebar: sidebar 
permalink: nvme_windows_2019.html 
keywords: nvme, windows, enterprise 
summary: 'Sie können NVMe over Fibre Channel (NVMe/FC) auf Hosts konfigurieren, auf denen Windows Server 2019 für den Betrieb mit ONTAP-LUNs ausgeführt wird.' 
---
= NVMe/FC-Host-Konfiguration für Windows Server 2019 mit ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können NVMe over Fibre Channel (NVMe/FC) auf Hosts konfigurieren, auf denen Windows Server 2019 für den Betrieb mit ONTAP-LUNs ausgeführt wird.

.Über diese Aufgabe
Sie können die folgende Unterstützung für die NVMe/FC-Hostkonfiguration für Windows 2019 verwenden. Sie sollten auch die bekannten Einschränkungen überprüfen, bevor Sie mit dem Konfigurationsprozess beginnen.


NOTE: Mit den in diesem Verfahren angegebenen Konfigurationseinstellungen können Sie Cloud-Clients konfigurieren, die mit  und verbunden link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^]link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["Amazon FSX für ONTAP"^]sind.

* Support verfügbar:
+
Ab ONTAP 9.7 wird NVMe/FC für Windows Server 2019 unterstützt.

+
Eine Liste der unterstützten FC-Adapter und Controller finden Sie im link:https://hwu.netapp.com/Home/Index["Hardware Universe"^]. Die aktuelle Liste der unterstützten Konfigurationen und Versionen finden Sie im link:https://mysupport.netapp.com/matrix/["Interoperabilitäts-Matrix-Tool"^].

* Bekannte Einschränkungen:
+
Windows Failover Cluster wird mit NVMe/FC nicht unterstützt, da ONTAP derzeit persistente Reservierungen mit NVMe/FC nicht unterstützt.

+

NOTE: Broadcom liefert einen externen Treiber für Windows NVMe/FC, der ein translationaler SCSI ⇄ NVMe-Treiber und kein echter NVMe/FC-Treiber ist. Der translationale Overhead beeinträchtigt nicht unbedingt die Performance, doch er hebt die Performance-Vorteile von NVMe/FC auf. Daher ist die Performance von NVMe/FC und FCP auf Windows Servern im Gegensatz zu anderen Betriebssystemen wie Linux, bei denen die NVMe/FC-Performance deutlich besser ist als die von FCP.





== NVMe/FC aktivieren

Aktivieren Sie FC/NVMe auf dem Windows Initiator-Host.

.Schritte
. Installieren Sie das OneCommand Manager-Dienstprogramm auf dem Windows-Host.
. Legen Sie an jedem der HBA-Initiator-Ports die folgenden HBA-Treiberparameter fest:
+
** EnableNVMe = 1
** NVMEMode = 0


. Starten Sie den Host neu.




== Konfigurieren Sie den Broadcom FC-Adapter

Der Broadcom Initiator kann sowohl NVMe/FC- als auch FCP-Datenverkehr über dieselben 32-Gbit-FC-Adapter-Ports bedienen. Für FCP und FC/NVMe sollten Sie das Microsft Device-Specific Module (DSM) als Microsoft Multipath I/O (MPIO)-Option verwenden.

Ein `+hostnqn+` ist jedem HBA-Port (Host Bus Adapter) für den Broadcom-Adapter mit FC/NVMe in einer Windows-Umgebung zugeordnet. Das `+hostnqn+` ist wie im folgenden Beispiel gezeigt formatiert:

....
nqn.2017-01.com.broadcom:ecd:nvmf:fc:100000109b1b9765
nqn.2017-01.com.broadcom:ecd:nvmf:fc:100000109b1b9766
....


=== MPIO für NVMe-Geräte aktivieren

Sie müssen MPIO für NVMe-Geräte aktivieren, um die NVMe-Konfiguration auf dem Windows-Host abzuschließen.

.Schritte
. Installieren link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Windows Host Utility Kit 7.1"] Treiber-Parameter einstellen, die für FC und NVMe gemeinsam sind.
. Öffnen Sie die MPIO-Eigenschaften.
. Fügen Sie auf der Registerkarte *Multi-Paths* die für NVMe angegebene Geräte-ID hinzu.
+
MPIO erkennt NVMe-Geräte, die im Festplattenmanagement sichtbar sind.

. Öffnen Sie * Disk Management* und gehen Sie zu *Disk Properties*.
. Wählen Sie auf der Registerkarte *MPIO* die Option *Details*.
. Stellen Sie die folgenden Microsoft DSM-Einstellungen ein:
+
** PathVerifiedPeriod: *10*
** PathVerifyEnabled: *Enable*
** RetryCount: *6*
** Wiederholungsintervall: *1*
** PDORemovedPeriod: *130*


. Wählen Sie die MPIO-Richtlinie *Round Robin mit Untergruppe* aus.
. Ändern Sie die Registrierungswerte:
+
[listing]
----
HKLM\SYSTEM\CurrentControlSet\Services\mpio\Parameters\PathRecoveryInterval DWORD -> 30

HKLM\SYSTEM\CurrentControlSet\Services\mpio \Parameters\ UseCustomPathRecoveryInterval  DWORD-> 1
----
. Starten Sie den Host neu.




== NVMe/FC validieren

Vergewissern Sie sich, dass die NVMe-Subsysteme erkannt wurden und die ONTAP-Namespaces für die NVMe-of Konfiguration richtig sind.

.Schritte
. Überprüfen Sie, ob „Porttyp“ `+FC+NVMe+`:
+
`listhba`

+
.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
Port WWN       : 10:00:00:10:9b:1b:97:65
Node WWN       : 20:00:00:10:9b:1b:97:65
Fabric Name    : 10:00:c4:f5:7c:a5:32:e0
Flags          : 8000e300
Host Name      : INTEROP-57-159
Mfg            : Emulex Corporation
Serial No.     : FC71367217
Port Number    : 0
Mode           : Initiator
PCI Bus Number : 94
PCI Function   : 0
*Port Type*      : *FC+NVMe*
Model          : LPe32002-M2

Port WWN       : 10:00:00:10:9b:1b:97:66
Node WWN       : 20:00:00:10:9b:1b:97:66
Fabric Name    : 10:00:c4:f5:7c:a5:32:e0
Flags          : 8000e300
Host Name      : INTEROP-57-159
Mfg            : Emulex Corporation
Serial No.     : FC71367217
Port Number    : 1
Mode           : Initiator
PCI Bus Number : 94
PCI Function   : 1
Port Type      : FC+NVMe
Model          : LPe32002-M2
----
====
. Überprüfen Sie, ob die NVMe/FC-Subsysteme erkannt wurden:
+
** `+nvme-list+`
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
NVMe Qualified Name     :  nqn.1992-08.com.netapp:sn.a3b74c32db2911eab229d039ea141105:subsystem.win_nvme_interop-57-159
Port WWN                :  20:09:d0:39:ea:14:11:04
Node WWN                :  20:05:d0:39:ea:14:11:04
Controller ID           :  0x0180
Model Number            :  NetApp ONTAP Controller
Serial Number           :  81CGZBPU5T/uAAAAAAAB
Firmware Version        :  FFFFFFFF
Total Capacity          :  Not Available
Unallocated Capacity    :  Not Available

NVMe Qualified Name     :  nqn.1992-08.com.netapp:sn.a3b74c32db2911eab229d039ea141105:subsystem.win_nvme_interop-57-159
Port WWN                :  20:06:d0:39:ea:14:11:04
Node WWN                :  20:05:d0:39:ea:14:11:04
Controller ID           :  0x0181
Model Number            :  NetApp ONTAP Controller
Serial Number           :  81CGZBPU5T/uAAAAAAAB
Firmware Version        :  FFFFFFFF
Total Capacity          :  Not Available
Unallocated Capacity    :  Not Available
Note: At present Namespace Management is not supported by NetApp Arrays.
----
====
** `nvme-list`
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
NVMe Qualified Name     :  nqn.1992-08.com.netapp:sn.a3b74c32db2911eab229d039ea141105:subsystem.win_nvme_interop-57-159
Port WWN                :  20:07:d0:39:ea:14:11:04
Node WWN                :  20:05:d0:39:ea:14:11:04
Controller ID           :  0x0140
Model Number            :  NetApp ONTAP Controller
Serial Number           :  81CGZBPU5T/uAAAAAAAB
Firmware Version        :  FFFFFFFF
Total Capacity          :  Not Available
Unallocated Capacity    :  Not Available

NVMe Qualified Name     :  nqn.1992-08.com.netapp:sn.a3b74c32db2911eab229d039ea141105:subsystem.win_nvme_interop-57-159
Port WWN                :  20:08:d0:39:ea:14:11:04
Node WWN                :  20:05:d0:39:ea:14:11:04
Controller ID           :  0x0141
Model Number            :  NetApp ONTAP Controller
Serial Number           :  81CGZBPU5T/uAAAAAAAB
Firmware Version        :  FFFFFFFF
Total Capacity          :  Not Available
Unallocated Capacity    :  Not Available

Note: At present Namespace Management is not supported by NetApp Arrays.
----
====


. Überprüfen Sie, ob die Namespaces erstellt wurden:
+
`+nvme-list-ns+`

+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
Active Namespaces (attached to controller 0x0141):

                                       SCSI           SCSI           SCSI
   NSID           DeviceName        Bus Number    Target Number     OS LUN
-----------  --------------------  ------------  ---------------   ---------
0x00000001   \\.\PHYSICALDRIVE9         0               1              0
0x00000002   \\.\PHYSICALDRIVE10        0               1              1
0x00000003   \\.\PHYSICALDRIVE11        0               1              2
0x00000004   \\.\PHYSICALDRIVE12        0               1              3
0x00000005   \\.\PHYSICALDRIVE13        0               1              4
0x00000006   \\.\PHYSICALDRIVE14        0               1              5
0x00000007   \\.\PHYSICALDRIVE15        0               1              6
0x00000008   \\.\PHYSICALDRIVE16        0               1              7

----
====

