---
sidebar: sidebar 
permalink: nvme-proxmox-ve-8x.html 
keywords: nvme, proxmox, linux, red hat, enterprise 
summary: Konfiguration eines NVMe-oF-Hosts für Proxmox VE 8.x mit ONTAP Speicher 
---
= Proxmox VE 8.x für NVMe-oF mit ONTAP Speicher konfigurieren
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Der Proxmox VE 8.x Host unterstützt die NVMe over Fibre Channel (NVMe/FC) und NVMe over TCP (NVMe/TCP) Protokolle mit Asymmetric Namespace Access (ANA). ANA bietet Multipathing-Funktionalität, die dem asymmetrischen logischen Einheitenzugriff (ALUA) in iSCSI- und FCP-Umgebungen entspricht.

Erfahren Sie, wie Sie NVMe over Fabrics (NVMe-oF)-Hosts für Proxmox VE 8.x konfigurieren. Weitere Informationen zu Support und Funktionen finden Sie unter link:nvme-proxmox-supported-features.html["ONTAP Support und -Funktionen"^]Die

NVMe-oF mit Proxmox VE 8.x weist folgende bekannte Einschränkung auf:

* Die SAN-Bootkonfiguration für NVMe-FC wird nicht unterstützt.




== Schritt 1: Installieren Sie die Proxmox VE- und NVMe-Software und überprüfen Sie Ihre Konfiguration.

Um Ihren Host für NVMe-oF zu konfigurieren, müssen Sie die Host- und NVMe-Softwarepakete installieren, Multipathing aktivieren und Ihre Host-NQN-Konfiguration überprüfen.

.Schritte
. Installieren Sie Proxmox 8.x auf dem Server.  Nach Abschluss der Installation überprüfen Sie, ob Sie den angegebenen Proxmox 8.x-Kernel ausführen:
+
[source, cli]
----
uname -r
----
+
Das folgende Beispiel zeigt eine Proxmox-Kernelversion:

+
[listing]
----
6.8.12-10-pve
----
. Installieren Sie den `nvme-cli` Paket:
+
[source, cli]
----
apt list|grep nvme-cli
----
+
Das folgende Beispiel zeigt eine  `nvme-cli` Paketversion:

+
[listing]
----
nvme-cli/oldstable,now 2.4+really2.3-3 amd64
----
. Installieren Sie den `libnvme` Paket:
+
[source, cli]
----
apt list|grep libnvme
----
+
Das folgende Beispiel zeigt eine  `libnvme` Paketversion:

+
[listing]
----
libnvme1/oldstable,now 1.3-1+deb12u1 amd64
----
. Überprüfen Sie auf dem Host die Hostnqn-Zeichenfolge unter  `/etc/nvme/hostnqn` :
+
[source, cli]
----
cat /etc/nvme/hostnqn
----
+
Das folgende Beispiel zeigt eine `hostnqn` Wert:

+
[listing]
----
nqn.2014-08.org.nvmexpress:uuid:1536c9a6-f954-11ea-b24d-0a94efb46eaf
----
. Überprüfen Sie im ONTAP System, ob `hostnqn` Die Zeichenkette stimmt mit der `hostnqn` Zeichenkette für das entsprechende Subsystem im ONTAP Array:
+
[source, cli]
----
::>  vserver nvme subsystem host show -vserver proxmox_120_122
----
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
Vserver Subsystem Priority  Host NQN
------- --------- --------  ---------
proxmox_120_122
proxmox_120_122
                  regular   nqn.2014-08.org.nvmexpress:uuid:1536c9a6-f954-11ea-b24d-0a94efb46eaf
                  regular   nqn.2014-08.org.nvmexpress:uuid:991a7476-f9bf-11ea-8b73-0a94efb46c3b
proxmox_120_122_tcp
                  regular   nqn.2014-08.org.nvmexpress:uuid:1536c9a6-f954-11ea-b24d-0a94efb46eaf
                  regular  nqn.2014-08.org.nvmexpress:uuid:991a7476-f9bf-11ea-8b73-0a94efb46c3b
2 entries were displayed.
----
====
+

NOTE: Wenn die `hostnqn` Zeichenfolgen nicht übereinstimmen, verwenden Sie die `vserver modify` Befehl zum Aktualisieren der `hostnqn` Zeichenfolge auf Ihrem entsprechenden ONTAP -Speichersystem-Subsystem, um die Übereinstimmung mit `hostnqn` Zeichenfolge von `/etc/nvme/hostnqn` auf dem Host.





== Schritt 2: NVMe/FC und NVMe/TCP konfigurieren

Konfigurieren Sie NVMe/FC mit Broadcom/Emulex- oder Marvell/QLogic-Adaptern oder konfigurieren Sie NVMe/TCP mithilfe manueller Erkennungs- und Verbindungsvorgänge.

[role="tabbed-block"]
====
.NVMe/FC - Broadcom/Emulex
--
Konfigurieren Sie NVMe/FC für einen Broadcom/Emulex-Adapter.

. Stellen Sie sicher, dass Sie das unterstützte Adaptermodell verwenden:
+
.. Zeigen Sie die Modellnamen an:
+
[source, cli]
----
cat /sys/class/scsi_host/host*/modelname
----
+
Die folgende Ausgabe sollte angezeigt werden:

+
[listing]
----
LPe35002-M2
LPe35002-M2
----
.. Zeigen Sie die Modellbeschreibungen an:
+
[source, cli]
----
cat /sys/class/scsi_host/host*/modeldesc
----
+
Sie sollten eine Ausgabe ähnlich dem folgenden Beispiel sehen:

+
[listing]
----
Emulex LPe35002-M2 2-Port 32Gb Fibre Channel Adapter
Emulex LPe35002-M2 2-Port 32Gb Fibre Channel Adapter
----


. Vergewissern Sie sich, dass Sie das empfohlene Broadcom verwenden `lpfc` Firmware und Inbox-Treiber:
+
.. Anzeige der Firmware-Version:
+
[source, cli]
----
cat /sys/class/scsi_host/host*/fwrev
----
+
Der Befehl gibt die Firmware-Versionen zurück:

+
[listing]
----
14.0.505.12, sli-4:6:d
14.0.505.12, sli-4:6:d
----
.. Zeigen Sie die Posteingangstreiberversion an:
+
[source, cli]
----
cat /sys/module/lpfc/version
----
+
Das folgende Beispiel zeigt eine Treiberversion:

+
[listing]
----
0:14.2.0.17
----


+
Die aktuelle Liste der unterstützten Adaptertreiber- und Firmware-Versionen finden Sie im link:https://mysupport.netapp.com/matrix/["Interoperabilitäts-Matrix-Tool"^].

. Verifizieren Sie das `lpfc_enable_fc4_type` Ist auf festgelegt `3`:
+
[source, cli]
----
cat /sys/module/lpfc/parameters/lpfc_enable_fc4_type
----
. Vergewissern Sie sich, dass Sie Ihre Initiator-Ports anzeigen können:
+
[source, cli]
----
cat /sys/class/fc_host/host*/port_name
----
+
Sie sollten eine Ausgabe ähnlich der folgenden sehen:

+
[listing]
----
0x100000109b95467e
0x100000109b95467f
----
. Überprüfen Sie, ob Ihre Initiator-Ports online sind:
+
[source, cli]
----
cat /sys/class/fc_host/host*/port_state
----
+
Die folgende Ausgabe sollte angezeigt werden:

+
[listing]
----
Online
Online
----
. Vergewissern Sie sich, dass die NVMe/FC-Initiator-Ports aktiviert sind und die Ziel-Ports sichtbar sind:
+
[source, cli]
----
cat /sys/class/scsi_host/host*/nvme_info
----
+
.Beispiel anzeigen
[%collapsible]
=====
[listing, subs="+quotes"]
----
NVME Initiator Enabled
XRI Dist lpfc0 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc0 WWPN x10005ced8c531948 WWNN x20005ced8c531948 DID x082400
*ONLINE*
NVME RPORT WWPN x200ed039eac79573 WWNN x200dd039eac79573 DID x060902
*TARGET DISCSRVC ONLINE*
NVME RPORT WWPN x2001d039eac79573 WWNN x2000d039eac79573 DID x060904
*TARGET DISCSRVC ONLINE*
NVME Statistics LS: Xmt 0000000034 Cmpl 0000000034 Abort 00000000 LS XMIT: Err 00000000 CMPL: xb 00000000 Err 00000000 Total FCP Cmpl 0000000000142cfb Issue 0000000000142cfc OutIO 0000000000000001 abort 00000005 noxri 00000000 nondlp 00000000 qdepth 00000000 wqerr 00000000 err 00000000 FCP CMPL: xb 00000005 Err 00000005 NVME Initiator Enabled XRI Dist lpfc1 Total 6144 IO 5894 ELS 250 NVME LPORT lpfc1 WWPN x10005ced8c531949 WWNN x20005ced8c531949 DID x082500
*ONLINE*
NVME RPORT WWPN x2010d039eac79573 WWNN x200dd039eac79573 DID x062902
*TARGET DISCSRVC ONLINE*
NVME RPORT WWPN x2007d039eac79573 WWNN x2000d039eac79573 DID x062904
*TARGET DISCSRVC ONLINE*
NVME Statistics LS: Xmt 0000000034 Cmpl 0000000034 Abort 00000000 LS XMIT: Err 00000000 CMPL: xb 00000000 Err 00000000 Total FCP Cmpl 00000000000d39f1 Issue 00000000000d39f2 OutIO 0000000000000001 abort 00000005 noxri 00000000 nondlp 00000000 qdepth 00000000 wqerr 00000000 err 00000000 FCP CMPL: xb 00000005 Err 00000005
----
=====


--
.NVMe/FC - Marvell/QLogic
--
Konfigurieren Sie NVMe/FC für einen Marvell/QLogic-Adapter.

. Stellen Sie sicher, dass Sie die unterstützten Adaptertreiber- und Firmware-Versionen verwenden:
+
[source, cli]
----
cat /sys/class/fc_host/host*/symbolic_name
----
+
Das folgende Beispiel zeigt Treiber- und Firmwareversionen:

+
[listing]
----
QLE2872 FW:v9.15.00 DVR:v10.02.09.300-k
QLE2872 FW:v9.15.00 DVR:v10.02.09.300-k
----
. Verifizieren Sie das `ql2xnvmeenable` Ist festgelegt. Dadurch kann der Marvell Adapter als NVMe/FC-Initiator verwendet werden:
+
[source, cli]
----
cat /sys/module/qla2xxx/parameters/ql2xnvmeenable
----
+
Die erwartete Ausgabe ist 1.



--
.NVMe/TCP
--
Das NVMe/TCP-Protokoll unterstützt den automatischen Verbindungsvorgang nicht.  Stattdessen können Sie die NVMe/TCP-Subsysteme und Namespaces ermitteln, indem Sie den NVMe/TCP `connect` oder `connect-all` Vorgänge manuell ausführen.

. Überprüfen Sie, ob der Initiator-Port die Daten der Erkennungsprotokollseite über die unterstützten NVMe/TCP-LIFs abrufen kann:
+
[source, cli]
----
nvme discover -t tcp -w host-traddr -a traddr
----
+
.Beispiel anzeigen
[%collapsible]
=====
[listing, subs="+quotes"]
----
nvme discover -t tcp -w 192.168.2.22 -a 192.168.2.30

Discovery Log Number of Records 12, Generation counter 13
=====Discovery Log Entry 0======
trtype:  tcp
adrfam:  ipv4
subtype: *current discovery subsystem*
treq:    not specified
portid:  10
trsvcid: 8009
subnqn:  nqn.1992-08.com.netapp:sn.ae9f2d55a7ec11ef8751d039ea9e891c:discovery
traddr:  192.168.2.30
eflags:  *explicit discovery connections, duplicate discovery information*
sectype: none
=====Discovery Log Entry 1======
trtype:  tcp
adrfam:  ipv4
subtype: *current discovery subsystem*
treq:    not specified
portid:  9
trsvcid: 8009
subnqn:  nqn.1992-08.com.netapp:sn.ae9f2d55a7ec11ef8751d039ea9e891c:discovery
traddr:  192.168.1.30
eflags:  *explicit discovery connections, duplicate discovery information*
sectype: none
=====Discovery Log Entry 2======
trtype:  tcp
adrfam:  ipv4
subtype: *current discovery subsystem*
treq:    not specified
portid:  12
trsvcid: 8009
subnqn:  nqn.1992-08.com.netapp:sn.ae9f2d55a7ec11ef8751d039ea9e891c:discovery
traddr:  192.168.2.25
eflags:  *explicit discovery connections, duplicate discovery information*
sectype: none
=====Discovery Log Entry 3======
trtype:  tcp
adrfam:  ipv4
subtype: *current discovery subsystem*
treq:    not specified
portid:  11
trsvcid: 8009
subnqn:  nqn.1992-08.com.netapp:sn.ae9f2d55a7ec11ef8751d039ea9e891c:discovery
traddr:  192.168.1.25
eflags:  *explicit discovery connections, duplicate discovery information*
sectype: none
=====Discovery Log Entry 4======
trtype:  tcp
adrfam:  ipv4
subtype: *nvme subsystem*
treq:    not specified
portid:  10
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:sn.ae9f2d55a7ec11ef8751d039ea9e891c:subsystem.proxmox_120_122
traddr:  192.168.2.30
eflags:  none
sectype: none
=====Discovery Log Entry 5======
trtype:  tcp
adrfam:  ipv4
subtype: *nvme subsystem*
treq:    not specified
portid:  9
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:sn.ae9f2d55a7ec11ef8751d039ea9e891c:subsystem.proxmox_120_122
traddr:  192.168.1.30
eflags:  none
sectype: none
=====Discovery Log Entry 6======
trtype:  tcp
adrfam:  ipv4
subtype: *nvme subsystem*
treq:    not specified
portid:  12
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:sn.ae9f2d55a7ec11ef8751d039ea9e891c:subsystem.proxmox_120_122
traddr:  192.168.2.25
eflags:  none
sectype: none
=====Discovery Log Entry 7======
trtype:  tcp
adrfam:  ipv4
subtype: *nvme subsystem*
treq:    not specified
portid:  11
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:sn.ae9f2d55a7ec11ef8751d039ea9e891c:subsystem.proxmox_120_122
traddr:  192.168.1.25
eflags:  none
sectype: none
=====Discovery Log Entry 8======
trtype:  tcp
adrfam:  ipv4
subtype: *nvme subsystem*
treq:    not specified
portid:  10
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:sn.ae9f2d55a7ec11ef8751d039ea9e891c:subsystem.proxmox_120_122_tcp
traddr:  192.168.2.30
eflags:  none
sectype: none
=====Discovery Log Entry 9======
trtype:  tcp
adrfam:  ipv4
subtype: *nvme subsystem*
treq:    not specified
portid:  9
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:sn.ae9f2d55a7ec11ef8751d039ea9e891c:subsystem.proxmox_120_122_tcp
traddr:  192.168.1.30
eflags:  none
sectype: none
=====Discovery Log Entry 10======
trtype:  tcp
adrfam:  ipv4
subtype: *nvme subsystem*
treq:    not specified
portid:  12
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:sn.ae9f2d55a7ec11ef8751d039ea9e891c:subsystem.proxmox_120_122_tcp
traddr:  192.168.2.25
eflags:  none
sectype: none
=====Discovery Log Entry 11======
trtype:  tcp
adrfam:  ipv4
subtype: *nvme subsystem*
treq:    not specified
portid:  11
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:sn.ae9f2d55a7ec11ef8751d039ea9e891c:subsystem.proxmox_120_122_tcp
traddr:  192.168.1.25
eflags:  none
sectype: none
----
=====
. Überprüfen Sie, ob die anderen NVMe/TCP-Initiator-Ziel-LIF-Kombinationen erfolgreich Daten der Erkennungsprotokollseite abrufen können:
+
[source, cli]
----
nvme discover -t tcp -w host-traddr -a traddr
----
+
.Beispiel anzeigen
[%collapsible]
=====
[listing, subs="+quotes"]
----
nvme discover -t tcp -w 192.168.1.22 -a 192.168.1.30
nvme discover -t tcp -w 192.168.2.22 -a 192.168.2.30
nvme discover -t tcp -w 192.168.1.22 -a 192.168.1.25
nvme discover -t tcp -w 192.168.2.22 -a 192.168.2.25
----
=====
. Führen Sie die aus `nvme connect-all` Befehl über alle unterstützten NVMe/TCP Initiator-Ziel-LIFs der Nodes hinweg:
+
[source, cli]
----
nvme connect-all -t tcp -w host-traddr -a traddr
----
+
.Beispiel anzeigen
[%collapsible]
=====
[listing, subs="+quotes"]
----
nvme connect-all -t tcp -w 192.168.1.22 -a 192.168.1.30
nvme connect-all -t tcp -w 192.168.2.22 -a 192.168.2.30
nvme connect-all -t tcp -w 192.168.1.22 -a 192.168.1.25
nvme connect-all -t tcp -w 192.168.2.22 -a 192.168.2.25
----
=====


[NOTE]
====
Die Einstellung für NVMe/TCP `ctrl_loss_tmo timeout` ist automatisch auf „Aus“ eingestellt.  Infolge:

* Es gibt keine Begrenzung für die Anzahl der Wiederholungsversuche (unbegrenzte Wiederholung).
* Sie müssen kein bestimmtes  `ctrl_loss_tmo timeout` Dauer bei Verwendung des  `nvme connect` oder  `nvme connect-all` Befehle (Option -l ).
* Bei den NVMe/TCP-Controllern kommt es im Falle eines Pfadausfalls nicht zu Timeouts und die Verbindung bleibt unbegrenzt bestehen.


====
--
====


== Schritt 3: Optional: Aktivieren Sie 1 MB I/O für NVMe/FC.

ONTAP meldet in den Identify Controller-Daten eine maximale Datenübertragungsgröße (MDTS) von 8.  Dies bedeutet, dass die maximale E/A-Anforderungsgröße bis zu 1 MB betragen kann.  Um E/A-Anfragen der Größe 1 MB für einen Broadcom NVMe/FC-Host auszugeben, sollten Sie die `lpfc` Wert des `lpfc_sg_seg_cnt` Parameter vom Standardwert 64 auf 256.


NOTE: Diese Schritte gelten nicht für Qlogic NVMe/FC-Hosts.

.Schritte
. Setzen Sie den `lpfc_sg_seg_cnt` Parameter auf 256:
+
[source, cli]
----
cat /etc/modprobe.d/lpfc.conf
----
+
Sie sollten eine Ausgabe ähnlich dem folgenden Beispiel sehen:

+
[listing]
----
options lpfc lpfc_sg_seg_cnt=256
----
. Führe die `update-initramfs` Führen Sie den Befehl aus und starten Sie den Host neu.
. Stellen Sie sicher, dass der Wert für `lpfc_sg_seg_cnt` 256 lautet:
+
[source, cli]
----
cat /sys/module/lpfc/parameters/lpfc_sg_seg_cnt
----




== Schritt 4: NVMe-Bootdienste überprüfen

Mit Proxmox 8.x `nvmefc-boot-connections.service` Und `nvmf-autoconnect.service` Die im NVMe/FC enthaltenen Boot-Dienste `nvme-cli` Die Pakete werden beim Systemstart automatisch aktiviert.

Überprüfen Sie nach dem Booten, ob die  `nvmefc-boot-connections.service` Und  `nvmf-autoconnect.service` Boot-Dienste sind aktiviert.

.Schritte
. Vergewissern Sie sich, dass `nvmf-autoconnect.service` aktiviert ist:
+
[source, cli]
----
systemctl status nvmf-autoconnect.service
----
+
.Beispielausgabe anzeigen
[%collapsible]
====
[listing]
----
○ nvmf-autoconnect.service - Connect NVMe-oF subsystems automatically during boot
     Loaded: loaded (/lib/systemd/system/nvmf-autoconnect.service; enabled; preset: enabled)
     Active: inactive (dead) since Fri 2025-11-21 19:59:10 IST; 8s ago
    Process: 256613 ExecStartPre=/sbin/modprobe nvme-fabrics (code=exited, status=0/SUCCESS)
    Process: 256614 ExecStart=/usr/sbin/nvme connect-all (code=exited, status=0/SUCCESS)
   Main PID: 256614 (code=exited, status=0/SUCCESS)
        CPU: 18ms
Nov 21 19:59:07 SR665-14-122.lab.eng.btc.netapp.in systemd[1]: Starting nvmf-autoconnect.service - Connect NVMe-oF subsystems automatically during boot...
Nov 21 19:59:10 SR665-14-122.lab.eng.btc.netapp.in nvme[256614]: Failed to write to /dev/nvme-fabrics: Invalid argument
Nov 21 19:59:10 SR665-14-122.lab.eng.btc.netapp.in nvme[256614]: Failed to write to /dev/nvme-fabrics: Invalid argument
Nov 21 19:59:10 SR665-14-122.lab.eng.btc.netapp.in systemd[1]: nvmf-autoconnect.service: Deactivated successfully.
Nov 21 19:59:10 SR665-14-122.lab.eng.btc.netapp.in systemd[1]: Finished nvmf-autoconnect.service - Connect NVMe-oF subsystems automatically during boot.
----
====
. Vergewissern Sie sich, dass `nvmefc-boot-connections.service` aktiviert ist:
+
[source, cli]
----
systemctl status nvmefc-boot-connections.service
----
+
.Beispielausgabe anzeigen
[%collapsible]
====
[listing]
----
○ nvmefc-boot-connections.service - Auto-connect to subsystems on FC-NVME devices found during boot
    Loaded: loaded (/lib/systemd/system/nvmefc-boot-connections.service; enabled; preset: enabled)
     Active: inactive (dead) since Thu 2025-11-20 17:48:29 IST; 1 day 2h ago
    Process: 1381 ExecStart=/bin/sh -c echo add > /sys/class/fc/fc_udev_device/nvme_discovery (code=exited, status=0/SUCCESS)
   Main PID: 1381 (code=exited, status=0/SUCCESS)
        CPU: 3ms

Nov 20 17:48:29 SR665-14-122.lab.eng.btc.netapp.in systemd[1]: Starting nvmefc-boot-connections.service - Auto-connect to subsystems on FC-NVME devices found during boot..
Nov 20 17:48:29 SR665-14-122.lab.eng.btc.netapp.in systemd[1]: nvmefc-boot-connections.service: Deactivated successfully.
Nov 20 17:48:29 SR665-14-122.lab.eng.btc.netapp.in systemd[1]: Finished nvmefc-boot-connections.service - Auto-connect to subsystems on FC-NVME devices found during boot...
----
====




== Schritt 5: Überprüfen der Multipathing-Konfiguration

Vergewissern Sie sich, dass der in-Kernel-Multipath-Status, der ANA-Status und die ONTAP-Namespaces für die NVMe-of-Konfiguration richtig sind.

.Schritte
. Vergewissern Sie sich, dass das in-Kernel NVMe Multipath aktiviert ist:
+
[source, cli]
----
cat /sys/module/nvme_core/parameters/multipath
----
+
Die folgende Ausgabe sollte angezeigt werden:

+
[listing]
----
Y
----
. Überprüfen Sie, ob die entsprechenden NVMe-oF-Einstellungen (z. B. Modell auf NetApp ONTAP Controller und Load-Balancing-IOPolicy auf Round-Robin eingestellt) für die ONTAP Namespaces auf dem Host korrekt angezeigt werden:
+
.. Zeigen Sie die Teilsysteme:
+
[source, cli]
----
cat /sys/class/nvme-subsystem/nvme-subsys*/model
----
+
Die folgende Ausgabe sollte angezeigt werden:

+
[listing]
----
NetApp ONTAP Controller
NetApp ONTAP Controller
----
.. Zeigen Sie die Richtlinie an:
+
[source, cli]
----
cat /sys/class/nvme-subsystem/nvme-subsys*/iopolicy
----
+
Die folgende Ausgabe sollte angezeigt werden:

+
[listing]
----
round-robin
round-robin
----


. Überprüfen Sie, ob die Namespaces auf dem Host erstellt und richtig erkannt wurden:
+
[source, cli]
----
nvme list
----
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
Node                  Generic               SN                   Model                                    Namespace  Usage                      Format           FW Rev
--------------------- --------------------- -------------------- ---------------------------------------- ---------- -------------------------- ---------------- --------
/dev/nvme2n20         /dev/ng2n20           81K13BUDdygsAAAAAAAG NetApp ONTAP Controller                  10          5.56  GB /  91.27  GB      4 KiB +  0 B   9.18.1
----
====
. Überprüfen Sie, ob der Controller-Status jedes Pfads aktiv ist und den korrekten ANA-Status aufweist:
+
[role="tabbed-block"]
====
.NVMe/FC
--
[source, cli]
----
nvme list-subsys /dev/nvme2n20
----
.Beispiel anzeigen
[%collapsible]
=====
[listing, subs="+quotes"]
----
nvme-subsys2 - NQN= nqn.1992-08.com.netapp:sn.ae9f2d55a7ec11ef8751d039ea9e891c:subsystem.proxmox_120_122_tcp
\
+- nvme1 *fc* traddr=nn-0x200dd039eac79573:pn-0x2010d039eac79573,host_traddr=nn-0x20005ced8c531949:pn-0x10005ced8c531949 *live optimized*
+- nvme3 *fc* traddr=nn-0x200dd039eac79573:pn-0x200ed039eac79573,host_traddr=nn-0x20005ced8c531948:pn-0x10005ced8c531948 *live optimized*
+- nvme5 *fc* traddr=nn-0x200dd039eac79573:pn-0x200fd039eac79573,host_traddr=nn-0x20005ced8c531949:pn-0x10005ced8c531949 *live non-optimized*
+- nvme7 fc traddr=nn-0x200dd039eac79573:pn-0x2011d039eac79573,host_traddr=nn-0x20005ced8c531948:pn-0x10005ced8c531948 *live non-optimized*
----
=====
--
.NVMe/TCP
--
[source, cli]
----
nvme list-subsys /dev/nvme2n3
----
.Beispiel anzeigen
[%collapsible]
=====
[listing, subs="+quotes"]
----
nvme-subsys2 - NQN= qn.1992-08.com.netapp:sn.ae9f2d55a7ec11ef8751d039ea9e891c:subsystem.proxmox_120_122_tcp
\
+- nvme2 *tcp* traddr=192.168.1.30,trsvcid=4420,host_traddr=192.168.1.22,src_addr=192.168.1.22 *live optimized*
+- nvme4 *tcp* traddr=192.168.2.30,trsvcid=4420,host_traddr=192.168.2.22,src_addr=192.168.2.22 *live optimized*
+- nvme6 *tcp* traddr=192.168.1.25,trsvcid=4420,host_traddr=192.168.1.22,src_addr=192.168.1.22 *live non-optimized*
+- nvme8 *tcp* traddr=192.168.2.25,trsvcid=4420,host_traddr=192.168.2.22,src_addr=192.168.2.22 *live non-optimized*
----
=====
--
====
. Vergewissern Sie sich, dass das NetApp Plug-in für jedes ONTAP Namespace-Gerät die richtigen Werte anzeigt:
+
[role="tabbed-block"]
====
.Spalte
--
[source, cli]
----
nvme netapp ontapdevices -o column
----
.Beispiel anzeigen
[%collapsible]
=====
[listing, subs="+quotes"]
----

Device        Vserver               Namespace Path
------------- --------------------- ------------------------------
/dev/nvme2n11     proxmox_120_122 / /vol/vm120_tcp1/ns

NSID       UUID                            Size
---- ------------------------------------  --------
1          5aefea74-f0cf-4794-a7e9-e113c4659aca   37.58GB
----
=====
--
.JSON
--
[source, cli]
----
nvme netapp ontapdevices -o json
----
.Beispiel anzeigen
[%collapsible]
=====
[listing, subs="+quotes"]
----
{
      "Device":"/dev/nvme2n11",
      "Vserver":"proxmox_120_122",
      "Namespace_Path":"/vol/vm120_tcp1/ns",
      "NSID":1,
      "UUID":"5aefea74-f0cf-4794-a7e9-e113c4659aca",
       “Size”:”37.58GB”,
      "LBA_Data_Size":4096,
      "Namespace_Size":32212254720
    }
  ]
----
=====
--
====




== Schritt 6: Überprüfen Sie die bekannten Probleme

Es sind keine Probleme bekannt.
