---
sidebar: sidebar 
permalink: overview.html 
keywords: ontap, san, host, rhel, red, hat, linux, sles, suse, esxi, nvme, oracle, linux, windows, enterprise, fc, fcp, isci, aix, powervm, vios, centos, citrix, hp-ux, solaris, veritas, cvo, cloud, volume, ontap, clients, configuration, FSx, instance, netapp 
summary: Dieser Inhalt enthält eine vertriebsspezifische Anleitung zur Konfiguration von Cloud-Clients, die mit Cloud Volumes ONTAP und Amazon FSX für ONTAP- und SAN-Hosts verbunden sind, die mit lokalem ONTAP Storage verbunden sind. 
---
= ÜBERSICHT über DIE SAN-Host-Konfiguration
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


Dieser Content bietet Host- und versionsspezifische Best Practices zur schnellen Konfiguration von SAN-Hosts, die mit ONTAP Storage verbunden sind.

Ihre SAN-Hosts und ONTAP-Storage können sich entweder vor Ort, in der Cloud oder beides befinden.


NOTE: In einer Cloud-Umgebung werden Hosts normalerweise als Clients bezeichnet. Alle hostspezifischen Informationen in diesem Inhalt gelten auch für Cloud Clients.

So lässt sich beispielsweise lokaler ONTAP Storage konfigurieren, um eine Verbindung zu lokalen SAN-Hosts herzustellen oder eine Verbindung zu SAN-Cloud-Clients herzustellen. Sie könnten auch konfigurieren link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] Oder link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["Amazon FSX für ONTAP"^] Herstellen einer Verbindung zu lokalen SAN-Hosts oder zur Verbindung mit SAN-Cloud-Clients:

Die ordnungsgemäße Konfiguration ist für beste Performance und ein erfolgreiches Failover wichtig.

.Verwandte Informationen
* Der link:https://docs.netapp.com/us-en/ontap/san-config/index.html["ONTAP-SAN-Konfiguration"^] Für Ihre Version von ONTAP
* Der link:https://docs.netapp.com/us-en/ontap/san-management/index.html["ONTAP-SAN-Administration-Leitfaden"^] Für Ihre Version von ONTAP
* Der link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["Versionshinweise zu ONTAP"^] Für Ihre Version von ONTAP
* Der link:https://docs.netapp.com/us-en/e-series/index.html["E-Series Dokumentation"^] Um die Dokumentation zu SANtricity zu finden.

