---
sidebar: sidebar 
permalink: overview.html 
keywords: ontap, san, host, rhel, red, hat, linux, sles, suse, esxi, nvme, oracle, linux, windows, enterprise, fc, fcp, isci, aix, powervm, vios, centos, citrix, hp-ux, solaris, veritas, cvo, cloud, volume, ontap, clients, configuration, FSx, instance, netapp 
summary: Dieser Inhalt enthält eine vertriebsspezifische Anleitung zur Konfiguration von Cloud-Clients, die mit Cloud Volumes ONTAP und Amazon FSX für ONTAP- und SAN-Hosts verbunden sind, die mit lokalem ONTAP Storage verbunden sind. 
---
= Informieren Sie sich über SAN-Host-Konfigurationen
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie sollten SAN-Hosts für das Multipathing und bestimmte Parameter und Einstellungen konfigurieren, die für den korrekten Betrieb mit ONTAP-LUNs entscheidend sind. Die Host-Konfiguration variiert je nach Host-Betriebssystem und Protokoll. Die richtige Konfiguration ist für die beste Performance und ein erfolgreiches Failover von großer Bedeutung.

Sie sollten Ihre SAN-Hosts so konfigurieren, dass sie die NetApp-SAN-Host Utilities verwenden. SAN Host Utilities unterstützen Sie beim Management und Monitoring Ihrer LUNs und Host Bus Adapter (HBAs). Sie können beispielsweise mit den SAN Host Utilities eine Liste aller LUNs abrufen, die einem Host zugeordnet sind, oder eine Liste aller Attribute einer bestimmten LUN, die einem Host zugeordnet ist. Der NetApp Kunden-Support kann auch die SAN Host Utilities verwenden, um Informationen über Ihre Konfiguration zu sammeln, wenn Sie beim Problem Unterstützung benötigen.

NetApp empfiehlt die Verwendung der SAN Host Utilities-Software, wenn diese für Ihren SAN-Host verfügbar ist.

Wenn Ihre SAN-Konfiguration das Booten von SAN unterstützt, können Sie Ihren Host auch so konfigurieren, dass er SAN-Booting verwendet, um die Bereitstellung zu vereinfachen und die Skalierbarkeit zu verbessern. Mit SAN-Boot können Sie mehrere neue Server bereitstellen, indem Sie sie mit dem SAN verbinden und die entsprechenden Starteinstellungen konfigurieren. Dies spart Zeit, da das Betriebssystem nicht mehr einzeln auf jedem Server installiert werden muss.

Ihre SAN-Hosts und ONTAP-Storage können sich entweder vor Ort, in der Cloud oder beides befinden.


NOTE: In einer Cloud-Umgebung werden Hosts normalerweise als Clients bezeichnet. Alle hostspezifischen Informationen in diesem Inhalt gelten auch für Cloud Clients.

Sie können beispielsweise den lokalen ONTAP -Speicher so konfigurieren, dass er eine Verbindung zu lokalen SAN-Hosts oder SAN-Cloud-Clients herstellt.  Sie können auch Speicherdienste konfigurieren, die in einer Cloud-Umgebung ausgeführt werden, wie z. B.link:https://docs.netapp.com/us-en/cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] oderlink:https://docs.netapp.com/us-en/storage-management-fsx-ontap/index.html["Amazon FSX für NetApp ONTAP"^] um eine Verbindung zu lokalen SAN-Hosts oder SAN-Cloud-Clients herzustellen.

.Verwandte Informationen
* link:https://docs.netapp.com/us-en/ontap/san-config/index.html["ONTAP-SAN-Konfigurationsreferenz"^]
* link:https://docs.netapp.com/us-en/ontap/san-management/index.html["ONTAP SAN-Storage-Management"^]
* link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["ONTAP 9 – Versionshinweise"^]
* SANtricity-Dokumentation im link:https://docs.netapp.com/us-en/e-series/index.html["Dokumentation zu E-Series Systemen"^]

