---
settings:
  name: ONTAP SAN Host Utilities
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: de-de,us-en,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: ONTAP SAN-Hosts und Cloud-Clients
    url: "/index.html"
  - title: Informieren Sie sich über SAN-Host-Konfigurationen
    url: "/overview.html"
  - title: Installieren Sie SAN Host Utilities
    entries:
    - title: Weitere Informationen zu SAN Host Utilities
      url: "/hu_sanhost_index.html"
    - title: AIX Host Utilitys
      entries:
      - title: Versionshinweise
        url: "/hu-aix-release-notes.html"
      - title: Installieren der AIX-Host-Dienstprogramme
        entries:
        - title: Installieren Sie AIX Host Utilities 8.0
          url: "/hu-aix-80.html"
        - title: Installieren Sie AIX Host Utilities 7.0
          url: "/hu-aix-70.html"
        - title: Installieren Sie AIX Host Utilities 6.1
          url: "/hu_aix_61.html"
      - title: Erfahren Sie mehr über das AIX SAN Tollkit
        url: "/hu-aix-san-toolkit.html"
      - title: AIX Host Utilities-Befehlsreferenz
        url: "/hu-aix-command-reference.html"
    - title: HP-UX Host Utilities
      entries:
      - title: Versionshinweise
        url: "/hu-hpux-release-notes.html"
      - title: Installieren Sie HP-UX Host Utilities 6.0
        url: "/hu_hpux_60.html"
      - title: Erfahren Sie mehr über das SAN Toolkit
        url: "/hu-hpux-sanlun-toolkit.html"
      - title: Erfahren Sie mehr über die HP-UX-Befehlsreferenz
        url: "/hu_hpux_60_cmd.html"
    - title: Linux Host Utilities
      entries:
      - title: Versionshinweise
        url: "/hu-luhu-release-notes.html"
      - title: Installieren Sie Linux-Host-Dienstprogramme
        entries:
        - title: Installieren Sie Linux Host Utilities 8.0
          url: "/hu-luhu-80.html"
        - title: Installieren Sie Linux Host Utilities 7.1
          url: "/hu_luhu_71.html"
      - title: Erfahren Sie mehr über das Dienstprogramm Sanlun
        url: "/hu-luhu-sanlun-utility.html"
      - title: Linux Host Utilities-Befehlsreferenz
        url: "/hu-luhu-command-reference.html"
    - title: Solaris Host Utilitys
      entries:
      - title: Versionshinweise
        url: "/hu-solaris-release-notes.html"
      - title: Installieren Sie Solaris Host Utilities
        entries:
        - title: Installieren von Solaris Host Utilities 8.0
          url: "/hu-solaris-80.html"
        - title: Installieren von Solaris Host Utilities 6.2
          url: "/hu_solaris_62.html"
      - title: Erfahren Sie mehr über das SAN Toolkit
        url: "/hu-solaris-san-toolkit.html"
      - title: Erfahren Sie mehr über die Solaris-Befehlsreferenz
        url: "/hu-solaris-command-reference.html"
    - title: Windows Host Utilities
      entries:
      - title: Versionshinweise
        url: "/hu-wuhu-release-notes.html"
      - title: Installieren Sie die Windows-Host-Dienstprogramme
        entries:
        - title: Installieren Sie Windows Host Utilities 8.0
          url: "/hu-wuhu-80.html"
        - title: Installieren Sie Windows Host Utilities 7.2
          url: "/hu_wuhu_72.html"
        - title: Installieren Sie Windows Host Utilities 7.1
          url: "/hu_wuhu_71.html"
      - title: Konfigurieren Sie die Einstellungen für Windows Host Utilities
        url: "/hu_wuhu_hba_settings.html"
      - title: Aktualisieren Sie Windows Host Utilities
        url: "/hu_wuhu_upgrade.html"
      - title: Reparieren und entfernen Sie Windows Host Utilities
        url: "/hu_wuhu_repair_remove.html"
      - title: Fehlerbehebung
        url: "/hu_wuhu_troubleshoot.html"
  - title: Konfigurieren Sie Hosts mit FCP und iSCSI
    entries:
    - title: Überblick
      url: "/hu_fcp_scsi_index.html"
    - title: AIX und PowerVM/VIOS
      entries:
      - title: 7.3/4.x
        url: "/hu-aix-73.html"
      - title: 7.2/3.1
        url: "/hu_aix_72.html"
      - title: '7.1'
        url: "/hu_aix_71.html"
    - title: CentOS
      entries:
      - title: CentOS 8.x
        url: "/hu-centos-8x.html"
      - title: CentOS 7
        entries:
        - title: '7.9'
          url: "/hu_centos_79.html"
        - title: '7.8'
          url: "/hu_centos_78.html"
        - title: '7.7'
          url: "/hu_centos_77.html"
        - title: '7.6'
          url: "/hu_centos_76.html"
        - title: '7.5'
          url: "/hu_centos_75.html"
        - title: '7.4'
          url: "/hu_centos_74.html"
        - title: '7.3'
          url: "/hu_centos_73.html"
        - title: '7.2'
          url: "/hu_centos_72.html"
        - title: '7.1'
          url: "/hu_centos_71.html"
        - title: '7.0'
          url: "/hu_centos_70.html"
      - title: CentOS 6
        entries:
        - title: '6.10'
          url: "/hu_centos_610.html"
        - title: '6.9'
          url: "/hu_centos_69.html"
        - title: '6.8'
          url: "/hu_centos_68.html"
        - title: '6.7'
          url: "/hu_centos_67.html"
        - title: '6.6'
          url: "/hu_centos_66.html"
        - title: '6.5'
          url: "/hu_centos_65.html"
        - title: '6.4'
          url: "/hu_centos_64.html"
    - title: Citrix
      entries:
      - title: Xenserver 8.4
        url: "/hu_citrix_84.html"
      - title: Hypervisor 8.2
        url: "/hu_citrix_82.html"
    - title: ESXi
      entries:
      - title: VMware vSphere 8
        url: "/hu_vsphere_8.html"
      - title: VMware vSphere 7
        url: "/hu_vsphere_7.html"
      - title: VMware vSphere 6.5 und 6.7
        url: "/hu_vsphere_6.html"
    - title: HP-UX ERHÄLTLICH
      entries:
      - title: 11i v3
        url: "/hu_hpux_11iv3.html"
    - title: Oracle Linux
      pdf-filename: OL-FCP
      entries:
      - title: 9.x
        url: "/hu-ol-9x.html"
      - title: 8.x
        url: "/hu-ol-8x.html"
      - title: Oracle Linux 7
        pdf-filename: OL-7-FCP
        entries:
        - title: '7.9'
          url: "/hu_ol_79.html"
        - title: '7.8'
          url: "/hu_ol_78.html"
        - title: '7.7'
          url: "/hu_ol_77.html"
        - title: '7.6'
          url: "/hu_ol_76.html"
        - title: '7.5'
          url: "/hu_ol_75.html"
        - title: '7.4'
          url: "/hu_ol_74.html"
        - title: '7.3'
          url: "/hu_ol_73.html"
        - title: '7.2'
          url: "/hu_ol_72.html"
        - title: '7.1'
          url: "/hu_ol_71.html"
        - title: '7.0'
          url: "/hu_ol_70.html"
      - title: Oracle Linux 6
        pdf-filename: OL-6-FCP
        entries:
        - title: '6.10'
          url: "/hu_ol_610.html"
        - title: '6.9'
          url: "/hu_ol_69.html"
        - title: '6.8'
          url: "/hu_ol_68.html"
        - title: '6.7'
          url: "/hu_ol_67.html"
        - title: '6.6'
          url: "/hu_ol_66.html"
        - title: '6.5'
          url: "/hu_ol_65.html"
        - title: '6.4'
          url: "/hu_ol_64.html"
    - title: Proxmox
      entries:
      - title: VE 9.x
        url: "/hu-proxmox-ve-9x.html"
      - title: VE 8.x
        url: "/hu-proxmox-ve-8x.html"
    - title: RHEL
      entries:
      - title: 10.x
        url: "/hu-rhel-10x.html"
        pdf-filename: RHEL-10-FCP
      - title: 9.x
        url: "/hu-rhel-9x.html"
        pdf-filename: RHEL-9-FCP
      - title: 8.x
        pdf-filename: RHEL-8-FCP
        url: "/hu-rhel-8x.html"
      - title: RHEL 7
        pdf-filename: RHEL-7-FCP
        entries:
        - title: '7.9'
          url: "/hu_rhel_79.html"
        - title: '7.8'
          url: "/hu_rhel_78.html"
        - title: '7.7'
          url: "/hu_rhel_77.html"
        - title: '7.6'
          url: "/hu_rhel_76.html"
        - title: '7.5'
          url: "/hu_rhel_75.html"
        - title: '7.4'
          url: "/hu_rhel_74.html"
        - title: '7.3'
          url: "/hu_rhel_73.html"
        - title: '7.2'
          url: "/hu_rhel_72.html"
        - title: '7.1'
          url: "/hu_rhel_71.html"
        - title: '7.0'
          url: "/hu_rhel_70.html"
      - title: RHEL 6
        pdf-filename: RHEL-6-FCP
        entries:
        - title: '6.10'
          url: "/hu_rhel_610.html"
        - title: '6.9'
          url: "/hu_rhel_69.html"
        - title: '6.8'
          url: "/hu_rhel_68.html"
        - title: '6.7'
          url: "/hu_rhel_67.html"
        - title: '6.6'
          url: "/hu_rhel_66.html"
        - title: '6.5'
          url: "/hu_rhel_65.html"
        - title: '6.4'
          url: "/hu_rhel_64.html"
    - title: Rocky Linux
      entries:
      - title: 10.x
        pdf-filename: RL-10-FCP
        url: "/hu-rockylinux-10x.html"
      - title: 9.x
        pdf-filename: RL-9-FCP
        url: "/hu-rockylinux-9x.html"
      - title: 8.x
        pdf-filename: RL-8-FCP
        url: "/hu-rockylinux-8x.html"
    - title: Solaris
      entries:
      - title: '11.4'
        url: "/hu-solaris-114.html"
      - title: '11.3'
        url: "/hu_solaris_113.html"
    - title: SUSE Linux Enterprise Server
      entries:
      - title: SUSE Linux Enterprise Server 15
        pdf-filename: SLES-15-FCP
        url: "/hu-sles-15spx.html"
      - title: SUSE Linux Enterprise Server 12
        entries:
        - title: 12 SP5
          url: "/hu_sles_12SP5.html"
        - title: 12 SP4
          url: "/hu_sles_12SP4.html"
        - title: 12 SP3
          url: "/hu_sles_12SP3.html"
        - title: 12 SP2
          url: "/hu_sles_12SP2.html"
        - title: 12 SP1
          url: "/hu_sles_12SP1.html"
        - title: '12'
          url: "/hu_sles_12.html"
    - title: Ubuntu
      pdf-filename: Ubuntu-FCP
      entries:
      - title: '24,04'
        url: "/hu_ubuntu_2404.html"
      - title: '22.04'
        url: "/hu_ubuntu_2204.html"
      - title: '20.04'
        url: "/hu_ubuntu_2004.html"
    - title: Veritas
      entries:
      - title: Infoscale 9
        url: "/hu-veritas-9x.html"
      - title: Infoscale 8
        url: "/hu-veritas-8x.html"
      - title: Infoscale 7
        url: "/hu-veritas-7x.html"
      - title: Storage-Grundlage 6
        url: "/hu_veritas_6x.html"
    - title: Windows
      pdf-filename: Windows FCP
      entries:
      - title: '2025'
        url: "/hu-windows-2025.html"
      - title: '2022'
        url: "/hu_windows_2022.html"
      - title: '2019'
        url: "/hu_windows_2019.html"
      - title: '2016'
        url: "/hu_windows_2016.html"
      - title: 2012 R2
        url: "/hu_windows_2012r2.html"
  - title: Hosts mit NVMe-of konfigurieren
    entries:
    - title: Erfahren Sie mehr über die Konfiguration von NVMe-oF-Hosts
      url: "/hu-nvme-index.html"
    - title: AIX
      url: "/nvme-aix.html"
    - title: ESXi
      entries:
      - title: VMware vSphere 8
        url: "/nvme-esxi-8.html"
      - title: VMware vSphere 7
        url: "/nvme-esxi-7.html"
    - title: Oracle Linux
      pdf-filename: NVMeoF OL
      entries:
      - title: ONTAP Support und -Funktionen
        url: "/nvme-ol-supported-features.html"
      - title: 9.x
        url: "/nvme-ol-9x.html"
      - title: 8.x
        url: "/nvme-ol-8x.html"
      - title: 7.x
        url: "/nvme-ol-7x.html"
    - title: Proxmox
      pdf-filename: NVMeoF Proxmox
      entries:
      - title: ONTAP Support und -Funktionen
        url: "/nvme-proxmox-supported-features.html"
      - title: VE 9.x
        url: "/nvme-proxmox-ve-9x.html"
      - title: VE 8.x
        url: "/nvme-proxmox-ve-8x.html"
    - title: RHEL
      pdf-filename: NVMeoF RHEL
      entries:
      - title: ONTAP Support und -Funktionen
        url: "/nvme-rhel-supported-features.html"
      - title: 10.x
        url: "/nvme-rhel-10x.html"
      - title: 9.x
        url: "/nvme-rhel-9x.html"
      - title: 8.x
        url: "/nvme-rhel-8x.html"
    - title: Rocky Linux
      entries:
      - title: ONTAP Support und -Funktionen
        url: "/nvme-rockylinux-supported-features.html"
      - title: 10.x
        url: "/nvme-rockylinux-10x.html"
      - title: 9.x
        url: "/nvme-rockylinux-9x.html"
      - title: 8.x
        url: "/nvme-rockylinux-8x.html"
    - title: SUSE Linux Enterprise Server
      entries:
      - title: ONTAP Support und -Funktionen
        url: "/nvme-sles-supported-features.html"
      - title: 15 SPx
        url: "/nvme-sles15-spx.html"
    - title: Ubuntu
      entries:
      - title: '24,04'
        url: "/nvme-ubuntu-2404.html"
      - title: '22.04'
        url: "/nvme-ubuntu-2204.html"
    - title: Windows
      entries:
      - title: '2025'
        url: "/nvme-windows-2025.html"
      - title: '2022'
        url: "/nvme-windows-2022.html"
      - title: '2019'
        url: "/nvme-windows-2019.html"
      - title: '2016'
        url: "/nvme-windows-2016.html"
      - title: 2012 R2
        url: "/nvme-windows-2012r2.html"
    - title: Fehlerbehebung
      url: "/troubleshoot.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: ONTAP
  repo: ontap-family
