---
sidebar: sidebar 
permalink: troubleshoot.html 
keywords: host utilities, veritas, infoscale, 8.x, netapp, ontap, vmware, vspehere 
summary: Sie können die ONTAP-SAN-Hosteinstellungen für die VMware vSphere 8.x-Version mit FC-, FCoE- und iSCSI-Protokollen konfigurieren. 
---
= Fehlerbehebung bei NVMe-oF mit ONTAP -Speicher für Linux-Host-Dienstprogramme
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Fehlerbehebung bei NVMe-oF-Fehlern auf Oracle Linux-, RHEL-, Rocky Linux- und SUSE Linux Enterprise Server-Hosts mit ONTAP Speicher.

Bevor Sie mit der Fehlersuche beginnen, vergewissern Sie sich, dass Ihre Konfiguration den geltenden Richtlinien entspricht. https://mysupport.netapp.com/matrix/#welcome["Interoperabilitäts-Matrix-Tool"^] Spezifikationen und fahren Sie dann mit den nächsten Schritten fort, um etwaige Probleme auf der Host-Seite zu beheben.


NOTE: Die Anweisungen zur Fehlerbehebung gelten nicht für AIX-, ESXi-, Proxmox- und Windows-Hosts.



== Aktivieren Sie die ausführliche Protokollierung

Wenn Sie ein Problem mit Ihrer Konfiguration haben, kann die ausführliche Protokollierung wichtige Informationen für die Fehlerbehebung liefern.

.Schritte
Ausführliche Protokollierung für LPFC oder Qlogic (Qla2xxx) aktivieren.

[role="tabbed-block"]
====
.LPFC
--
Legen Sie den lpfc-Treiber für NVMe/FC fest.

. Stellen Sie die ein `lpfc_log_verbose` Treibereinstellung auf einen der folgenden Werte, um NVMe/FC-Ereignisse zu protokollieren.
+
[listing]
----
#define LOG_NVME 0x00100000 /* NVME general events. */
#define LOG_NVME_DISC 0x00200000 /* NVME Discovery/Connect events. */
#define LOG_NVME_ABTS 0x00400000 /* NVME ABTS events. */
#define LOG_NVME_IOERR 0x00800000 /* NVME IO Error events. */
----
. Führen Sie nach dem Festlegen der Werte den aus `dracut-f` Führen Sie einen Befehl aus und starten Sie den Host neu.
. Überprüfen Sie die Einstellungen:
+
[source, cli]
----
# cat /etc/modprobe.d/lpfc.conf options lpfc lpfc_log_verbose=0xf00083

# cat /sys/module/lpfc/parameters/lpfc_log_verbose 15728771
----


--
.Qla2xxx
--
Es gibt keine spezifische qla2xxx-Protokollierung für NVMe/FC, ähnlich wie bei `lpfc` Treiber. Stellen Sie stattdessen die allgemeine qla2xxx-Protokollierungsebene ein.

. Fügen Sie den hinzu `ql2xextended_error_logging=0x1e400000` Wert zum entsprechenden `modprobe qla2xxx conf` Datei:
. Ausführen des `dracut -f` Befehl und starten Sie dann den Host neu.
. Überprüfen Sie nach dem Neubooten, ob die ausführliche Protokollierung aktiviert wurde:
+
[source, cli]
----
# cat /etc/modprobe.d/qla2xxx.conf
----
+
Sie sollten eine Ausgabe ähnlich dem folgenden Beispiel sehen:

+
[listing]
----
options qla2xxx ql2xnvmeenable=1 ql2xextended_error_logging=0x1e400000
# cat /sys/module/qla2xxx/parameters/ql2xextended_error_logging
507510784
----


--
====


== Häufige "nvme-cli"-Fehler und deren Umgehungsmöglichkeiten

Die von angezeigten Fehler `nvme-cli` Während `nvme discover`, `nvme connect`, Oder `nvme connect-all` Die Vorgänge und die Problemumgehungen sind in der folgenden Tabelle aufgeführt:

[cols="20, 20, 50"]
|===
| Fehlermeldung | Wahrscheinliche Ursache | Behelfslösung 


| `Failed to write to /dev/nvme-fabrics: Invalid argument` | Falsche Syntax | Vergewissern Sie sich, dass Sie die richtige Syntax für das verwenden `nvme discover`, `nvme connect`, und `nvme connect-all` Befehle. 


| `Failed to write to /dev/nvme-fabrics: No such file or directory` | Dies kann beispielsweise durch mehrere Probleme ausgelöst werden. Wenn die NVMe Befehle falsch dargestellt werden, ist dies eine der häufigsten Ursachen.  a| 
* Überprüfen Sie, ob Sie die richtigen Argumente (z. B. richtig WWNN-Zeichenfolge, WWPN-Zeichenfolge und mehr) an die Befehle übergeben haben.
* Wenn die Argumente richtig sind, aber Sie sehen immer noch diesen Fehler, überprüfen Sie, ob die `/sys/class/scsi_host/host*/nvme_info` Die Befehlsausgabe ist richtig. Der NVMe-Initiator wird als angezeigt `Enabled`, Und die NVMe/FC-Ziel-LIFs werden unter den Abschnitten für Remote-Ports korrekt angezeigt. Beispiel:
+
[listing]
----

# cat /sys/class/scsi_host/host*/nvme_info
NVME Initiator Enabled
NVME LPORT lpfc0 WWPN x10000090fae0ec9d WWNN x20000090fae0ec9d DID x012000 ONLINE
NVME RPORT WWPN x200b00a098c80f09 WWNN x200a00a098c80f09 DID x010601 TARGET DISCSRVC ONLINE
NVME Statistics
LS: Xmt 0000000000000006 Cmpl 0000000000000006
FCP: Rd 0000000000000071 Wr 0000000000000005 IO 0000000000000031
Cmpl 00000000000000a6 Outstanding 0000000000000001
NVME Initiator Enabled
NVME LPORT lpfc1 WWPN x10000090fae0ec9e WWNN x20000090fae0ec9e DID x012400 ONLINE
NVME RPORT WWPN x200900a098c80f09 WWNN x200800a098c80f09 DID x010301 TARGET DISCSRVC ONLINE
NVME Statistics
LS: Xmt 0000000000000006 Cmpl 0000000000000006
FCP: Rd 0000000000000073 Wr 0000000000000005 IO 0000000000000031
Cmpl 00000000000000a8 Outstanding 0000000000000001
----
* Wenn in der `nvme_info` Befehlsausgabe nicht die Ziel-LIFs angezeigt werden, wie im obigen Beispiel gezeigt, überprüfen Sie die `/var/log/messages` Ausgaben des Befehls und auf verdächtige NVMe/FC-Ausfälle und `dmesg` melden oder korrigieren Sie sie.




| `No discovery log entries to fetch`  a| 
Im Allgemeinen beobachtet, wenn die `/etc/nvme/hostnqn` Es wurde keine Zeichenfolge in das entsprechende Subsystem auf dem NetApp Array hinzugefügt oder eine falsche Zeichenfolge `hostnqn` Der String wurde dem jeweiligen Subsystem hinzugefügt.
 a| 
Überprüfen Sie das genau `/etc/nvme/hostnqn` String wird dem entsprechenden Subsystem im NetApp Array hinzugefügt (überprüfen Sie mithilfe der `vserver nvme subsystem host show` Befehl).



| `Failed to write to /dev/nvme-fabrics: Operation already in progress`  a| 
Beobachtet, wenn bereits Controller-Zuordnungen oder angegebene Operation erstellt oder gerade erstellt werden. Dies könnte im Rahmen der oben installierten Skripts zur automatischen Verbindung geschehen.
 a| 
Keine. Versuchen Sie, die auszuführen `nvme discover` Befehl nach einiger Zeit wieder. Für `nvme connect` Und `connect-all`, Ausführen des `nvme list` Befehl zum Überprüfen, ob die Namespace-Geräte bereits erstellt und auf dem Host angezeigt werden.

|===


== Wann wenden Sie sich an den technischen Support

Falls weiterhin Probleme auftreten, sammeln Sie bitte die folgenden Dateien und Befehlsausgaben und kontaktieren Sie uns. link:mysupport.netapp.com["NetApp Support"^] zur weiteren Triage:

[source, cli]
----
cat /sys/class/scsi_host/host*/nvme_info
/var/log/messages
dmesg
nvme discover output as in:
nvme discover --transport=fc --traddr=nn-0x200a00a098c80f09:pn-0x200b00a098c80f09 --host-traddr=nn-0x20000090fae0ec9d:pn-0x10000090fae0ec9d
nvme list
nvme list-subsys /dev/nvmeXnY
----