= 
:allow-uri-read: 


. Wenn Ihre Speicherkonfiguration MetroCluster oder SnapMirror Active Sync umfasst, ändern Sie die Standardeinstellungen:
+
[role="tabbed-block"]
====
.MetroCluster
--
Standardmäßig erzwingt das AIX-Betriebssystem ein kürzeres E/A-Timeout, wenn keine Pfade zu einer LUN verfügbar sind.  Dies kann in Konfigurationen auftreten, die ein SAN-Fabric mit einem Switch umfassen, und in MetroCluster -Konfigurationen, bei denen es zu ungeplanten Failovers kommt.  Weitere Informationen und empfohlene Änderungen der Standardeinstellungen finden Sie im Knowledge Base-Artikellink:https://kb.netapp.com/on-prem/ontap/mc/MC-KBs/What_are_AIX_Host_support_considerations_in_a_MetroCluster_configuration["Welche Überlegungen gibt es hinsichtlich der AIX-Host-Unterstützung in einer MetroCluster -Konfiguration?"^] .

--
.SnapMirror aktive Synchronisierung
--
SnapMirror active sync wird für einen AIX-Host unterstützt. Das Unterstützungsverhalten variiert je nach ONTAP-Version:

** Ab ONTAP 9.19.1 wird SnapMirror Active Sync in der Active/Active-Konfiguration unterstützt, wodurch unterbrechungsfreie SnapMirror Active Sync-Vorgänge ermöglicht werden. Siehe den Knowledge Base Artikel link:https://kb.netapp.com/on-prem/ontap/DP/SnapMirror/SnapMirror-KBs/SnapMirror_active_sync_support_for_AIX%3A_behavior_by_ONTAP_release_and_migration_guidance["SnapMirror active sync-Unterstützung für AIX: Verhalten je nach ONTAP Release und Migrationshinweise"^].
** Für ONTAP 9.11.1 bis 9.18.1 wird SnapMirror Active Sync in der Aktiv/Standby-Konfiguration unterstützt. Siehe den Knowledge Base Artikel link:https://kb.netapp.com/on-prem/ontap/DP/SnapMirror/SnapMirror-KBs/How_to_configure_AIX_Host_for_SnapMirror_active_sync_in_ONTAP["So konfigurieren Sie einen AIX-Host für SnapMirror active sync in ONTAP 9.11.1 bis 9.18.1"^].


--
====

