= Schritt 1: Aktivieren Sie optional den SAN-Bootvorgang
:allow-uri-read: 




== Schritt 1: Aktivieren Sie optional den SAN-Bootvorgang

Sie können Ihren Host so konfigurieren, dass er SAN-Booting verwendet, um die Bereitstellung zu vereinfachen und die Skalierbarkeit zu verbessern.

.Bevor Sie beginnen
Überprüfen Sie mithilfe deslink:https://mysupport.netapp.com/matrix/#welcome["Interoperabilitäts-Matrix-Tool"^], ob Ihr Linux-Betriebssystem, Ihr Host Bus Adapter (HBA), die HBA-Firmware, das HBA-Boot-BIOS und die ONTAP-Version das Booten über das SAN unterstützen.

.Schritte
. Erstellen Sie eine SAN-Boot-LUN, und ordnen Sie sie dem Host zu.
+
Siehe https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["SAN-Storage bereitstellen"^].

. Aktivieren Sie das SAN-Booten im Server-BIOS für die Ports, denen die SAN-Boot-LUN zugeordnet ist.
+
Informationen zum Aktivieren des HBA-BIOS finden Sie in der anbieterspezifischen Dokumentation.

. Überprüfen Sie, ob die Konfiguration erfolgreich war, indem Sie den Host neu starten und überprüfen, ob das Betriebssystem ausgeführt wird.

