= 
:allow-uri-read: 


Wenn Ihr Host mit LUNs anderer Anbieter verbunden ist und einer der Multipath-Parameter überschrieben wurde, müssen diese korrigiert werden, indem entweder ein vorhandener Abschnitt geändert oder ein neuer Abschnitt in der  `multipath.conf` Datei hinzugefügt wird, der speziell für ONTAP LUNs gilt. Im unteren Bereich der Datei finden sich die Änderungen, die für Ihren Host relevant sind. Werden die Parameter nicht korrigiert, funktionieren die ONTAP LUNs möglicherweise nicht wie erwartet.

Überprüfen Sie Ihre `/etc/multipath.conf` Datei, insbesondere im Abschnitt Standardeinstellungen, auf Einstellungen, die die überschreiben könnten<<multipath-parameter-settings,Standardeinstellungen für Multipath-Parameter>>.


CAUTION: Die empfohlenen Parametereinstellungen für ONTAP LUNs sollten Sie nicht außer Kraft setzen. Diese Einstellungen sind für eine optimale Performance Ihrer Hostkonfiguration erforderlich. Weitere Informationen erhalten Sie vom NetApp-Support, vom Hersteller Ihres Betriebssystems oder von beiden.

Das folgende Beispiel zeigt, wie eine überhielte Standardeinstellung korrigiert wird. In diesem Beispiel definiert die `multipath.conf` Datei Werte für `path_checker` und `no_path_retry`, die nicht mit ONTAP-LUNs kompatibel sind. Sie können diese Parameter nicht entfernen, da ONTAP-Speicher-Arrays noch mit dem Host verbunden sind. Stattdessen korrigieren Sie die Werte für `path_checker` und `no_path_retry`, indem Sie der Datei, die speziell auf die ONTAP-LUNs zutrifft, eine Gerätestanze hinzufügen `multipath.conf`.

.Beispiel anzeigen
[%collapsible]
====
[listing, subs="+quotes"]
----
defaults {
   path_checker      *readsector0*
   no_path_retry     *fail*
}

devices {
   device {
      vendor          "NETAPP"
      product         "LUN"
      no_path_retry   *queue*
      path_checker    *tur*
   }
}
----
====