= 
:allow-uri-read: 


Um sicherzustellen, dass Multipathing für Ihren Host korrekt konfiguriert ist, überprüfen Sie, ob die `/etc/multipath.conf` Datei definiert ist und ob die von NetApp empfohlenen Einstellungen für Ihre ONTAP LUNs konfiguriert sind.

.Schritte
. Überprüfen Sie, ob die `/etc/multipath.conf` Datei beendet wird. Wenn die Datei nicht vorhanden ist, erstellen Sie eine leere, Null-Byte-Datei:
+
[source, cli]
----
touch /etc/multipath.conf
----
. Beim ersten Erstellen der `multipath.conf` Datei müssen Sie möglicherweise die Multipath-Services aktivieren und starten, um die empfohlenen Einstellungen zu laden:
+
[source, cli]
----
systemctl enable multipathd
----
+
[source, cli]
----
systemctl start multipathd
----
. Jedes Mal, wenn Sie den Host starten, lädt die leere `/etc/multipath.conf` Zero-Byte-Datei automatisch die von NetApp empfohlenen Multipath-Parameter als Standardeinstellungen. Sie sollten keine Änderungen an der Datei für Ihren Host vornehmen `/etc/multipath.conf` müssen, da das Betriebssystem mit den Multipath-Parametern kompiliert wird, die ONTAP-LUNs korrekt erkennen und verwalten.
+
In der folgenden Tabelle sind die nativen kompilierten Multipath-Parametereinstellungen für ONTAP LUNs unter Linux aufgeführt.

+
.Parametereinstellungen anzeigen
[%collapsible]
====
[cols="2"]
|===
| Parameter | Einstellung 


| Erkennen_Prio | ja 


| Dev_Loss_tmo | „Unendlich“ 


| Failback | Sofort 


| Fast_io_fail_tmo | 5 


| Funktionen | „2 pg_init_retries 50“ 


| Flush_on_Last_del | „ja“ 


| Hardware_Handler | „0“ 


| Kein_PATH_retry | Warteschlange 


| PATH_Checker | „nur“ 


| Path_Grouping_Policy | „Group_by_prio“ 


| Pfad_Auswahl | „Servicezeit 0“ 


| Polling_Interval | 5 


| prio | ONTAP 


| Produkt | LUN 


| Beibehalten_Attached_hw_Handler | ja 


| rr_weight | „Einheitlich“ 


| User_friendly_names | Nein 


| Anbieter | NETAPP 
|===
====
. Überprüfen Sie die Parametereinstellungen und den Pfadstatus für Ihre ONTAP LUNs:
+
[source, cli]
----
multipath -ll
----
+
Die standardmäßigen Multipath-Parameter unterstützen ASA-, AFF- und FAS-Konfigurationen. In diesen Konfigurationen sollte eine einzelne ONTAP-LUN nicht mehr als vier Pfade benötigen. Wenn mehr als vier Pfade vorhanden sind, kann dies bei einem Storage-Ausfall zu Problemen mit den Pfaden führen.

+
Die Ausgaben im folgenden Beispiel zeigen die korrekten Parametereinstellungen und den Pfadstatus für ONTAP LUNs in einer ASA-, AFF- oder FAS-Konfiguration.

+
[role="tabbed-block"]
====
.ASA-Konfiguration
--
Eine ASA Konfiguration optimiert alle Pfade zu einer bestimmten LUN und hält sie aktiv. Dies verbessert die Performance, da I/O-Operationen über alle Pfade gleichzeitig ausgeführt werden können.

.Beispiel anzeigen
[%collapsible]
=====
[listing]
----
multipath -ll
3600a098038303634722b4d59646c4436 dm-28 NETAPP,LUN C-Mode
size=10G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
  |- 11:0:7:6   sdbz 68:208  active ready running
  |- 11:0:11:6  sddn 71:80   active ready running
  |- 11:0:15:6  sdfb 129:208 active ready running
  |- 12:0:1:6   sdgp 132:80  active ready running
----
=====
--
.AFF- oder FAS-Konfiguration
--
Eine AFF- oder FAS-Konfiguration sollte zwei Pfadgruppen mit höheren und niedrigeren Prioritäten aufweisen. Aktiv/optimierte Pfade mit höherer Priorität werden vom Controller bedient, wo sich das Aggregat befindet. Pfade mit niedriger Priorität sind aktiv, jedoch nicht optimiert, da sie von einem anderen Controller bedient werden. Nicht optimierte Pfade werden nur verwendet, wenn keine optimierten Pfade verfügbar sind.

Im folgenden Beispiel wird die Ausgabe für eine ONTAP-LUN mit zwei aktiv/optimiert-Pfaden und zwei aktiv/nicht-optimierten Pfaden angezeigt:

.Beispiel anzeigen
[%collapsible]
=====
[listing]
----
multipath -ll
3600a0980383036347ffb4d59646c4436 dm-28 NETAPP,LUN C-Mode
size=10G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 16:0:6:35 sdwb  69:624  active ready running
| |- 16:0:5:35 sdun  66:752  active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 15:0:0:35 sdaj  66:48   active ready running
  |- 15:0:1:35 sdbx  68:176  active ready running
----
=====
--
====

