= 
:allow-uri-read: 


Das NetApp Linux-Hostdienstprogramme-Softwarepaket ist auf dem in einer 32-Bit- oder 64-Bit-.rpm-Datei verfügbar https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["NetApp Support Website"^].

NetApp empfiehlt ausdrücklich die Installation der Linux Host Utilities, dies ist jedoch nicht zwingend erforderlich. Die Dienstprogramme ändern keine Einstellungen auf Ihrem Linux-Host. Die Versorgungseinrichtungen verbessern das Management und unterstützen den NetApp Kunden-Support bei der Erfassung von Informationen zu Ihrer Konfiguration.

.Schritte
. Wenn Sie derzeit eine Version von Linux Host Utilities installiert haben, entfernen Sie diese mit dem folgenden Befehl:
+
`rpm -e netapp_linux_unified_host_utilities-7-1`

+
Wechseln Sie für frühere Versionen von Linux Host Utilities zu dem Verzeichnis, in dem die Host Utility Software installiert ist, und geben Sie den Befehl ein `uninstall`.

. Laden Sie das 32-Bit- oder 64-Bit-Linux Host Utilities-Softwarepaket vom auf Ihren Host herunterlink:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["NetApp Support Website"^].
. Rufen Sie das Verzeichnis auf, in dem Sie das Softwarepaket heruntergeladen haben, und installieren Sie es mit dem folgenden Befehl:
+
`rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_xx.rpm`

+
[listing]
----
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:netapp_linux_unified_host_utiliti################################# [100%]
----
. Überprüfen Sie die Installation:
+
`sanlun version`

+
[listing]
----
sanlun version 7.1.386.1644
----

