= 
:allow-uri-read: 


. Wenn Ihre Speicherkonfiguration MetroCluster, Oracle Solaris-Virtualisierung oder SnapMirror Active Sync umfasst, ändern Sie die Standardeinstellungen:
+
[role="tabbed-block"]
====
.MetroCluster
--
Standardmäßig schlägt die Ausführung der E/A-Vorgänge durch das Solaris-Betriebssystem nach *20 Sekunden* fehl, wenn alle Pfade zu einer LUN verloren gegangen sind.  Gesteuert wird dies durch die `fcp_offline_delay` Parameter.  Der Standardwert für `fcp_offline_delay` ist für Standard- ONTAP -Cluster geeignet.  In MetroCluster -Konfigurationen müssen Sie jedoch den Wert von `fcp_offline_delay` auf *120 s*, um sicherzustellen, dass es während des Betriebs, einschließlich ungeplanter Failovers, nicht zu einer vorzeitigen E/A-Abschaltung kommt.

Weitere Informationen und empfohlene Änderungen an den Standardeinstellungen für MetroCluster finden Sie im Knowledge Base-Artikel https://kb.netapp.com/onprem/ontap/metrocluster/Solaris_host_support_considerations_in_a_MetroCluster_configuration["Überlegungen zum Support von Solaris Hosts in einer MetroCluster-Konfiguration"^] .

--
.Virtualisierung mit Oracle Solaris
--
** Zu den Solaris-Virtualisierungsoptionen gehören Solaris Logical Domains (auch LDOMs oder Oracle VM Server für SPARC genannt), Solaris Dynamic Domains, Solaris Zones und Solaris Containers.  Diese Technologien werden auch als „Oracle Virtual Machines“ bezeichnet.
** Sie können mehrere Optionen zusammen verwenden, beispielsweise einen Solaris-Container innerhalb einer bestimmten logischen Solaris-Domäne.
** NetApp unterstützt die Verwendung von Solaris-Virtualisierungstechnologien, wobei die Gesamtkonfiguration von Oracle unterstützt wird und jede Partition mit direktem Zugriff auf LUNs auf derlink:https://imt.netapp.com/matrix/#welcome["IMT"] in einer unterstützten Konfiguration.  Dazu gehören Root-Container, LDOM-E/A-Domänen und LDOM, das NPIV für den Zugriff auf LUNs verwendet.
** Partitionen oder virtuelle Maschinen, die nur virtualisierte Speicherressourcen verwenden, wie z. B. `vdsk` , benötigen keine besonderen Qualifikationen, da sie keinen direkten Zugriff auf ONTAP LUNs haben.  Sie müssen lediglich überprüfen, ob die Partition oder virtuelle Maschine, die direkten Zugriff auf die zugrunde liegende LUN hat, wie z. B. eine LDOM-E/A-Domäne, auf derlink:https://imt.netapp.com/matrix/#welcome["IMT"^] .


.Schritte
Wenn LUNs als virtuelle Datenträgergeräte innerhalb eines LDOM verwendet werden, wird die Quelle der LUN durch die Virtualisierung maskiert und das LDOM erkennt die Blockgrößen nicht richtig.  So vermeiden Sie dieses Problem:

.. Patchen Sie das LDOM-Betriebssystem für _Oracle Bug 15824910_
.. Erstellen Sie ein `vdc.conf` Datei, die die Blockgröße der virtuellen Festplatte auf `4096` .  Weitere Informationen finden Sie im Oracle-Dokument: 2157669.1.
.. Überprüfen Sie die Patch-Installation, um sicherzustellen, dass die empfohlenen Einstellungen richtig konfiguriert wurden:
+
... Erstellen Sie einen Zpool:
+
[source, cli]
----
zpool create zpool_name disk_list
----
... Laufen `zdb -C` Gegen den zpool und überprüfen Sie, dass der Wert von *ashift* ist `12`.
+
Wenn der Wert von *ashift* nicht `12` , erneut ausführen `zdb -C11` und überprüfen Sie, ob der richtige Patch installiert wurde, und überprüfen Sie den Inhalt von `vdc.conf` .

+
Fahren Sie nicht fort, bis *ashift* einen Wert von anzeigt `12` .






NOTE: Für den Oracle-Fehler 15824910 sind Patches für mehrere Solaris-Versionen verfügbar.  Wenden Sie sich an Oracle, wenn Sie Hilfe bei der Ermittlung des besten Kernel-Patches benötigen.

--
.SnapMirror aktive Synchronisierung
--
Ab ONTAP 9.9.1 werden SnapMirror Active Sync-Einstellungskonfigurationen im Solaris-Host unterstützt.  Um sicherzustellen, dass die Solaris-Client-Anwendungen unterbrechungsfrei funktionieren, wenn in einer SnapMirror Active Sync-Umgebung ein ungeplanter Site-Failover-Switchover stattfindet, müssen Sie Folgendes konfigurieren: `scsi-vhci-failover-override` Einstellung auf dem Solaris-Host.  Diese Einstellung überschreibt das Failover-Modul `f_tpgs` um die Ausführung des Codepfads zu verhindern, der den Widerspruch erkennt.

.Schritte
.. Erstellen der Konfigurationsdatei `/etc/driver/drv/scsi_vhci.conf` mit einem Eintrag ähnlich dem folgenden Beispiel für den mit dem Host verbundenen NetApp -Speichertyp:
+
[listing]
----
scsi-vhci-failover-override =
"NETAPP  LUN","f_tpgs"
----
.. Überprüfen Sie, ob der Override-Parameter erfolgreich angewendet wurde:
+
[source, cli]
----
devprop
----
+
[source, cli]
----
mdb
----
+
.Beispiele anzeigen
[%collapsible]
=====
[listing]
----
root@host-A:~# devprop -v -n /scsi_vhci scsi-vhci-failover-override      scsi-vhci-failover-override=NETAPP  LUN + f_tpgs
root@host-A:~# echo "*scsi_vhci_dip::print -x struct dev_info devi_child | ::list struct dev_info devi_sibling| ::print struct dev_info devi_mdi_client| ::print mdi_client_t ct_vprivate| ::print struct scsi_vhci_lun svl_lun_wwn svl_fops_name"| mdb -k
----
[listing]
----
svl_lun_wwn = 0xa002a1c8960 "600a098038313477543f524539787938"
svl_fops_name = 0xa00298d69e0 "conf f_tpgs"
----
=====



NOTE: Nachher `scsi-vhci-failover-override` Wurde angewendet, `conf` Wird hinzugefügt zu `svl_fops_name`. Weitere Informationen und empfohlene Änderungen an den Standardeinstellungen finden Sie in dem Artikel der NetApp Wissensdatenbank https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapMirror/Solaris_Host_support_recommended_settings_in_SnapMirror_Business_Continuity_(SM-BC)_configuration["Von Solaris Host unterstützte empfohlene Einstellungen in der SnapMirror Active Sync Konfiguration"^].

--
====

