= 
:allow-uri-read: 


. Installieren Sie den `nvme-cli` Paket:
+
[source, cli]
----
rpm -qa|grep nvme-cli
----
+
Das folgende Beispiel zeigt eine  `nvme-cli` Paketversion:

+
[listing]
----
nvme-cli-2.11-5.el10.x86_64
----
. Installieren Sie den `libnvme` Paket:
+
[source, cli]
----
rpm -qa|grep libnvme
----
+
Das folgende Beispiel zeigt eine  `libnvme` Paketversion:

+
[listing]
----
libnvme-1.11.1-1.el10.x86_64
----
. Überprüfen Sie auf dem Host die Hostnqn-Zeichenfolge unter  `/etc/nvme/hostnqn` :
+
[source, cli]
----
cat /etc/nvme/hostnqn
----
+
Das folgende Beispiel zeigt eine  `hostnqn` Version:

+
[listing]
----
nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0056-5410-8048-b9c04f425633
----
. Überprüfen Sie das `hostnqn` Die Zeichenfolge entspricht der `hostnqn` String für das entsprechende Subsystem auf dem ONTAP-Array:
+
[source, cli]
----
::> vserver nvme subsystem host show -vserver vs_nvme_194_proxmox84
----
+
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
Vserver Subsystem Priority  Host NQN
------- --------- --------  ------------------------------------------------
vs_ nvme_194_proxmox84
        nvme4
                  regular   nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0056-5410-8048- c7c04f425633
        nvme_1
                  regular   nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0056-5410-8048- c7c04f425633
        nvme_2
                  regular   nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0056-5410-8048- c7c04f425633
        nvme_3
                  regular   nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0056-5410-8048- c7c04f425633
4 entries were displayed.
----
====
+

NOTE: Wenn die `hostnqn` Zeichenfolgen nicht übereinstimmen, verwenden Sie den Befehl, `vserver modify` um die Zeichenfolge auf dem entsprechenden ONTAP-Array-Subsystem zu aktualisieren `hostnqn`, damit sie mit der `hostnqn` Zeichenfolge `/etc/nvme/hostnqn` auf dem Host übereinstimmt.


