= 
:allow-uri-read: 


Sie können das Windows-Betriebssystem mit einem lokalen Boot oder einem SAN-Boot starten. NetApp empfiehlt die Verwendung eines SAN-Starts, wenn dies von Ihrer Konfiguration unterstützt wird.

[role="tabbed-block"]
====
.Lokaler Start
--
Führen Sie einen lokalen Start durch, indem Sie das Windows-Betriebssystem auf der lokalen Festplatte (SSD, SATA, RAID usw.) installieren.

--
.SAN Booting
--
Wenn Sie sich für den SAN-Bootvorgang entscheiden, muss dies von Ihrer Konfiguration unterstützt werden.


NOTE: Mit den in diesem Verfahren angegebenen Konfigurationseinstellungen können Sie Cloud-Clients konfigurieren, die mit  und verbunden link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^]link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["Amazon FSX für ONTAP"^]sind.

.Bevor Sie beginnen
Überprüfen Sie mithilfe des https://mysupport.netapp.com/matrix/#welcome["Interoperabilitäts-Matrix-Tool"^], ob Ihr Windows-Betriebssystem, Ihr Hostbusadapter (HBA), die HBA-Firmware, das HBA-StartBIOS und die ONTAP-Version das Booten über das SAN unterstützen.

.Schritte
. Ordnen Sie die SAN-Boot-LUN dem Host zu.
+
Siehe link:https://docs.netapp.com/us-en/ontap/san-management/index.html["SAN-Storage-Management"^].

. Vergewissern Sie sich, dass mehrere Pfade verfügbar sind.
+

NOTE: Mehrere Pfade sind nur verfügbar, nachdem das Host-Betriebssystem auf den Pfaden ausgeführt wurde.

. Aktivieren Sie das SAN-Booten im Server-BIOS für die Ports, denen die SAN-Boot-LUN zugeordnet ist.
+
Informationen zum Aktivieren des HBA-BIOS finden Sie in der anbieterspezifischen Dokumentation.

. Starten Sie den Host neu, um zu überprüfen, ob der Startvorgang erfolgreich war


--
====