= 
:allow-uri-read: 


Nach dem Ausführen `mbralign` Auf Festplatten zur Korrektur der MBR-Ausrichtung mit PowerShell Toolkit auf Linux Gast-Betriebssystemen mithilfe des GRUB-Boot-Loaders müssen Sie GRUB neu installieren, um sicherzustellen, dass das Gastbetriebssystem ordnungsgemäß gestartet wird.

.Über diese Aufgabe
Das Cmdlet zum PowerShell Toolkit ist in der VHD-Datei für die virtuelle Maschine abgeschlossen. Dieses Verfahren gilt nur für Linux-Gastbetriebssysteme, die die GRUB-Boot-Loader und verwenden `SystemRescueCd`.

.Schritte
. Mounten Sie das ISO-Image von Laufwerk 1 der Installations-CDs für die richtige Linux-Version für die virtuelle Maschine.
. Öffnen Sie die Konsole für die virtuelle Maschine in Hyper-V Manager.
. Wenn die VM auf dem GRUB-Bildschirm läuft und eingefroren ist, klicken Sie in den Anzeigebereich, um sicherzustellen, dass sie aktiv ist, und wählen Sie dann das Symbolleistensymbol *Strg-Alt-Delete*, um die VM neu zu starten. Wenn die VM nicht ausgeführt wird, starten Sie sie, und klicken Sie dann sofort in den Anzeigebereich, um sicherzustellen, dass sie aktiv ist.
. Sobald Sie den VMware BIOS Startbildschirm sehen, drücken Sie einmal die Taste *Esc*. Das Startmenü wird angezeigt.
. Wählen Sie im Startmenü die Option *CD-ROM* aus.
. Geben Sie auf dem Linux-Startbildschirm Folgendes ein: `linux rescue`
. Nehmen Sie die Standardeinstellungen für Anaconda (die blauen/roten Konfigurationsbildschirme). Networking ist optional.
. GRUB starten, indem Sie Folgendes eingeben: `grub`
. Wenn sich nur ein virtuelles Laufwerk in dieser VM befindet oder wenn mehrere Laufwerke vorhanden sind und das erste das Startlaufwerk ist, führen Sie die folgenden GRUB-Befehle aus:
+
[listing]
----
root (hd0,0)
setup (hd0)
quit
----
+
Wenn die VM mehrere virtuelle Laufwerke enthält und die Boot-Festplatte nicht die erste Festplatte ist, oder wenn Sie GRUB durch Booten von der falsch ausgerichteten Backup-VHD beheben, geben Sie zum Identifizieren der Boot-Festplatte den folgenden Befehl ein:

+
[listing]
----
find /boot/grub/stage1
----
+
Führen Sie dann die folgenden Befehle aus:

+
[listing]
----
root (boot_disk,0)
setup (boot_disk)
quit
----
+

NOTE: In `setup (boot_disk)` `boot_disk` ist ein Platzhalter für die tatsächliche Datenträgerkennung der Startfestplatte.



. Drücken Sie *Strg-D*, um sich abzumelden.
+
Die Linux-Rettung wird heruntergefahren und dann neu gestartet.


